### ISSUE TITLE
ECDSA performance

### ISSUE THREAD

**Issue by bellgrim** [randombit/botan#1019]
Following up an issue reported here: https://github.com/opendnssec/SoftHSMv2/issues/213

Did some performance tests of ECDSA and compared it with OpenSSL. There are some significant differences. I compiled Botan with no additional flags. Should I add any to get better performance or is the issue related to https://github.com/randombit/botan/issues/664#issuecomment-253211974 ?

Number of signatures per second using a single thread:

Algo|OpenSSL|Botan
----|----------|------
secp256r1 | 17472.3 | 213
secp384r1 | 4067.4 | 140
secp521r1 | 1951.9 | 98

Full output from the performance tests:
```
$ openssl version
OpenSSL 1.1.0e  16 Feb 2017

$ botan version
2.1.0

$ openssl speed ecdsap256 ecdsap384 ecdsap521
Doing 256 bit sign ecdsa's for 10s: 174898 256 bit ECDSA signs in 10.01s 
Doing 256 bit verify ecdsa's for 10s: 74683 256 bit ECDSA verify in 10.00s
Doing 384 bit sign ecdsa's for 10s: 40715 384 bit ECDSA signs in 10.01s 
Doing 384 bit verify ecdsa's for 10s: 9782 384 bit ECDSA verify in 10.01s
Doing 521 bit sign ecdsa's for 10s: 19539 521 bit ECDSA signs in 10.01s 
Doing 521 bit verify ecdsa's for 10s: 4798 521 bit ECDSA verify in 10.01s
                              sign    verify    sign/s verify/s
 256 bit ecdsa (nistp256)   0.0001s   0.0001s  17472.3   7468.3
 384 bit ecdsa (nistp384)   0.0002s   0.0010s   4067.4    977.2
 521 bit ecdsa (nistp521)   0.0005s   0.0021s   1951.9    479.3

$ botan speed --msec=10000 ECDSA
ECDSA-secp256r1 305 keygen/sec; 3.28 ms/op 7848939 cycles/op (1 op in 3 ms)
ECDSA-secp256r1 213 EMSA1(SHA-256) sign/sec; 4.68 ms/op 11228207 cycles/op (2140 ops in 10005 ms)
ECDSA-secp256r1 418 EMSA1(SHA-256) verify/sec; 2.39 ms/op 5742684 cycles/op (4186 ops in 10002 ms)
ECDSA-secp384r1 274 keygen/sec; 3.64 ms/op 8724862 cycles/op (1 op in 4 ms)
ECDSA-secp384r1 140 EMSA1(SHA-256) sign/sec; 7.13 ms/op 17126892 cycles/op (1403 ops in 10005 ms)
ECDSA-secp384r1 272 EMSA1(SHA-256) verify/sec; 3.67 ms/op 8815119 cycles/op (2726 ops in 10004 ms)
ECDSA-secp521r1 167 keygen/sec; 5.97 ms/op 14332073 cycles/op (1 op in 6 ms)
ECDSA-secp521r1 98 EMSA1(SHA-256) sign/sec; 10.13 ms/op 24335566 cycles/op (987 ops in 10003 ms)
ECDSA-secp521r1 186 EMSA1(SHA-256) verify/sec; 5.37 ms/op 12887819 cycles/op (1864 ops in 10003 ms)
```

**Comment by randombit** [comment]
This is not related to the issue referenced since the optimization I mentioned only applies to secp256k1 and not to 'standard' ECDSA curves like P-256.

I think the performance issue is much worse in 2.1 than prior releases, because of the changes in #893 and #880 which improved the side channel resistance but you can see in the charts in #880 that there was ~2.5 slowdown by moving to a larger blinding factor and the alternative scalar multiplication algorithm. I meant to go back and try to improve performance before the 2.1 release while keeping the good side channel properties, but did not have the time to address this.

You could likely get some of the performance back by (pre-build) editing the generated build.h and setting `BOTAN_POINTGFP_USE_SCALAR_BLINDING` to 0.

There is a lot that could be done here obviously, likely we'd never hit OpenSSL's level of performance since OpenSSL goes to fairly heroic/extreme measures, but getting within 50% of it is entirely reasonable, just a question of development time.

**Comment by randombit** [comment]
Going to try to look at this for 2.4 release - #1240

**Comment by randombit** [comment]
With #1457 merged you should see rather better numbers and we "only" 3-10x slower than OpenSSL. (Except for P-256, which OpenSSL has a lot of special code for, we are still 30x slower there.)

Still not really satisfactory obviously, and I hope to have time for further work on this in the future, but I'm going to close this issue as the question has been answered and we have some progress towards improvements now in master.

**Comment by randombit** [comment]
We're now down to OpenSSL only being 1.3x to 6x faster than Botan for ECDSA. If trends continue we'll be faster than OpenSSL in a couple of weeks.

**Comment by bellgrim** [comment]
Thank you for the update. This looks much better!

Algo|OpenSSL 1.1.1|Botan 2.5|Botan 2.1
----|----------|------|------
secp256r1 | 18563.6 | 2244 | 213
secp384r1 | 4374.7 | 1149 | 140
secp521r1 | 2022.2 | 844 | 98

**Comment by randombit** [comment]
Just to follow up here since this ticket still shows up in searches.

Comparing the performance of ECDSA between OpenSSL 3.5 and Botan 3.10 on an i7-6700k; tldr is that Botan is  significantly faster than OpenSSL for most elliptic curve algorithms.

ECDSA signature generations per second:

| Curve                | OpenSSL | Botan | Ratio |
|----------------------|--------------|------------|----------------------|
| secp224r1 | 22213      | 26782      | 1.2                |
| secp256r1 | 51912      | 23128      | .44                |
| secp384r1 | 4514       | 10021      | 2.2                |
| secp521r1 | 3636       | 5413       | 1.48                |
| brainpool256r1      | 2978       | 18417      | 6.18                |
| brainpool384r1      | 1241       | 7590       | 6.11               |
| brainpool512r1      | 870        | 4085       | 4.69                |

ECDSA signature verifications per second:

| Curve                | OpenSSL | Botan | Ratio |
|----------------------|----------------|--------------|----------------------|
| secp224r1 | 10435        | 17898        | 1.71                |
| secp256r1 | 17422        | 13793        | .79                |
| secp384r1 | 2005         | 5713         | 2.85                |
| secp521r1 | 1902         | 3284         | 1.72                |
| brainpool256r1      | 3092         | 10865        | 3.52                |
| brainpool384r1      | 1452         | 3967         | 2.73               |
| brainpool512r1      | 1050         | 1885         | 1.79                |

This advantage carries over into other elliptic curve algorithms like SM2

| Operation               | OpenSSL | Botan | Ratio |
|----------------------|----------------|--------------|----------------------|
| SM2 sign | 3176        | 36721        | 11.5                |
| SM2 verify | 3496        | 14671        | 4.19                |

This improvement came as a result from the new pcurves library (#3979 plus about 50 later PRs) that was first introduced in 3.5, and further refined and optimized between 3.6 and 3.8
