### ISSUE TITLE
Module dependency resolution fails

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1028]
As example, `./configure.py --disable-modules=prf_tls` disables `tls`, but then `tls_cbc` is left enabled, causing a build failure. 

Think something in #984 broke this.

**Comment by webmaster128** [comment]
On master I currently get

```
g++ -fstack-protector -m64 -pthread -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -O3 -momit-leaf-frame-pointer -Wall -Wextra -Wpedantic -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Ibuild/include -Ibuild/include/external -c ./src/lib/tls/sessions_sql/tls_session_manager_sql.cpp -o build/obj/lib/tls_sessions_sql_tls_session_manager_sql.o
In file included from ./src/lib/tls/sessions_sql/tls_session_manager_sql.cpp:8:0:
build/include/botan/tls_session_manager_sql.h:11:39: fatal error: botan/tls_session_manager.h: No such file or directory
compilation terminated.
```

for the configuration you posted. Looks like sessions_sql is missing a dependency on tls. This is the case for tls_cbc too.

**Comment by webmaster128** [comment]
Do we have implicit dependencies on modules in parent folder? I don't remember seeing any code handling this

**Comment by webmaster128** [comment]
I am currently bisecting this. Let's see ...

**Comment by webmaster128** [comment]
a4f9e50611 from #984 broke this. But the bug might be somewhere else and only becomes visible by this change, e.g. in ModuleInfo.dependencies(). Unfortunately I don't have the time to debug this this week

**Comment by randombit** [comment]
Yes all modules have implicit dependencies on their parent dir, that's in `ModuleInfo.dependencies` where the parent module (if existing) is added as an implicit dep. You can also see this with eg `--disable-modules=aead` which in 2.1 and prior disabled all AEAD modes but on master they still are included in the build but of course fail since aead.h is not there.

I think the problem is in

```
+                if new_loaded_mod:
 +                    self._maybe_dep.remove(new_loaded_mod)
 +                    self._to_load.add(new_loaded_mod)
 +                    # Added new_loaded_mod, now resolve its dependencies
 +                    self._resolve_dependencies(new_loaded_mod, level+1)
```

If `_resolve_dependencies` fails we don't boot the module, instead it's left enabled even though it has a missing dependency. I think this needs to return success or fail so we can backtrack.

**Comment by webmaster128** [comment]
yes, that is problematic. In order to fix this, one must ensure that you can try self._resolve_dependencies for every choice in `possible_mods = dependency_choices.intersection(self._maybe_dep)` and do not change any state if _resolve_dependencies fails. Otherwise we load modules that are unused later on.

I think this code must be rewritten in a purely functional way to allow a clean recursion that works the same way in every recursion level. To archive that, dependency resolution should only have 2 variables copied between the recursion steps: a pool of available mods and a set of used mods. If one recursive call fails, throw away it's local changes and try to continue. _not_using_because must not happen anymore because all requested modules will be loaded or we will fail entirely.

That would be a good chance to implement unittests.
