### ISSUE TITLE
RLWE Primitives

### ISSUE THREAD

**Issue by avnr** [randombit/botan#1048]
Any chance for exporting the RLWE primitives from Newhope? I guess it will require dissemination as a new type of public key. Would love to see it in FFI too.

**Comment by randombit** [comment]
Are you referring to NTT, INVNTT, Rec, HelpRec etc? Open to it, but would like to understand the use case better. Is the idea that someone could use these as building blocks to build related RLWE schemes like NewHope-Simple or BLISS?

I don't think it would require a new public key type since the primitives aren't directly usable for signing or key exchange, instead it would be some type representing the ring with n=1024 q=12289, and NewHope could then be implemented by calling operations on that type in the correct sequence.

**Comment by avnr** [comment]
The raw transformations are probably too low level for the API of a library such as Botan, I rather had in mind using them for key generation and encrypt/decrypt primitives. BLISS is a great example which IMHO we're soon going to see quite a lot.

**Comment by randombit** [comment]
Closing this since it is not clear there is anything actionable at this time. We will want to consider a set of RLWE primitives if/when further relevant algos are added.
