### ISSUE TITLE
Scheduling TLS work to virtual cores

### ISSUE THREAD

**Issue by fwsGonzo** [randombit/botan#1057]
We just got 64-bit on IncludeOS and now I'm trying to work out how to make TLS processing faster. Regular websockets can send something like 450k msgs/sec, while we can only process (single-core) 10k msgs/sec with TLS, and only SSE3.

We can probably enable AVX2 and AES, but then I can't do any work on my work computer :P

And here is the complicated question:
What do I need to do to be able to, say, do TLS processing through a lambda that executes on another virtual core, to achieve multi-processing (which we already have)?

Something like:
```
void tcp_on_read(data)
{
     SMP::sched(
     [sock = this, data] () {
         auto& tls_stream = PER_CPU(tls_manager).find_by_tcp_connection(sock);
         tls_stream.process(data);
      }
}
```
Very crude example!
I imagine that each virtual core would have a TLS server. Does this sound reasonable? So I would be load balancing against my virtual CPUs.

However, the only thread-safe systems in the OS is our interfaces and the heap, nothing else. Do you think (off the top of your head) that is a problem?

Bonus question if you feel up for it. I'm writing a master thesis on Live Updating Unikernels, which I have finished work on. What are the chances for a (future) way to serialize all TLS state? And is it realistic? One of the great advantages of live updating unikernels is the ability to produce non-deterministic images with no kernel syscall interface. Couple this with an update service on a daily schedule and each day the contents of memory changes randomly.

**Comment by randombit** [comment]
AVX2 doesn't matter much here, though AES will help a lot (depending on the mix of new sessions vs bulk data). Still 10k/s/core seems a little slow for bulk traffic, it is probably worth profiling this further. I've attached a quick test for bulk traffic performance but don't have time to dig into the profiling results much just yet.

[tls_bulk.cpp.txt](https://github.com/randombit/botan/files/1020148/tls_bulk.cpp.txt)

As to multithreading of the Servers this should work fine, there is no hidden shared
 state between the servers at all so as long as the Session_Manager, RNG, Callbacks and etc that you pass to the Server at initialization manage their locking correctly (or are per-cpu) all should be well. The code in `src/cli/tls_proxy.cpp` implements a multithreaded server using asio and might be worth a look. You will need a `TLS::Server` per socket (since this class also contains the record buffers etc unique to the connection) rather than per core but having a per-core socket->Server map seems like it would work fine to me. Let me know if you run into any problems with this.

As to serializing the entire TLS state, interesting question. This would not be so terribly hard (though also not easy) - basically it would just imply serializing the state in `TLS::Channel` (there are just a few odds-and-ends stored in TLS::Client and TLS::Server). We could reuse the wire-protocol serialization/deserialization code in order to store the handshake messages, the record buffers can just be saved as the bytestrings they are, and serializing the sequence numbers and cipher state (just the keys, basically) are trivial.

**Comment by fwsGonzo** [comment]
I just got 50k msgs/sec with 16 CPUs (on 8 core machine), so its a 5x improvement over single-threaded! The SMP messaging system is very primitive and the overhead is probably 30%. I made RNG per-cpu and everythng was as you said, straightforward.

Anyways, what configuration is needed (if any) when configuring Botan to enable AES?

**Comment by randombit** [comment]
@fwsGonzo All you need is ensuring `aes_ni` module is enabled at build. Then if cpuid instruction indicates support for the instructions, everything goes faster.

No strong opinions about the red zone, but missing it shouldn't cause any problems for Botan (there is for instance no asm that relies on it).

**Comment by fwsGonzo** [comment]
Thanks for the help, we are now load-balancing TLS to SMP-cores. A future project could be serializing TLS state so that we can live update services that have open TLS streams.
