### ISSUE TITLE
X509 path validation should warn if child cert exceeds issuing certs lifetime

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#1089]
I'm trying to figure out if the `keyCertSign` bit is mandatory for CA certificates. Botans `X509_Certificate::is_CA_cert()` also returns true if there are no constraints (check in `X509_Certificate::allowed_usage`). 

> The keyCertSign bit is asserted when the subject public key is used for verifying signatures on public key certificates.  If the keyCertSign bit is asserted, then the cA bit in the basic  constraints extension (Section 4.2.1.9) MUST also be asserted.

Is this check present in Botan?

> If the keyUsage extension is present, then the subject public key MUST NOT be used to verify signatures on certificates or CRLs unless the corresponding keyCertSign or cRLSign bit is set.

I think Botan does not distinguish between keyUsage extension empty and keyUsage extension not present.

**Comment by neusdan** [comment]
One more question. We discovered that the end certificate is considered valid, even if its start/end date is outside of the validity time of the CA. This seems a litte bit strange, but i couldn't find anything about that in the RFC.

**Comment by randombit** [comment]
I do not think we verify that the cA bit is set if keyCertSign is set, this check doesn't sound familiar to me. This would be good to have.

I think you are correct that Botan is not distinguishing between an empty and missing keyUsage extension. #884 might behave a little bit better in that regard, if I ever finish it. This doesn't seem like a big problem in practice though? (Let me know if I'm missing something here.)

Re validity ranges - I agree that behavior does seem counterintuitive in some ways, but arguably as long as the subject certificate was issued within the valid lifetime of the issuer cert, there is (AFAIK) no limitation on the subject expiration dates; a CA can validly issue a subject cert with a startTime of 1970 and expireTime of 2300, for all I know. Now, I'm not saying this behavior seems positive or useful so if it turns out there is a PKIX restriction about issue dates, then I'm all for applying it. In the same vein it might be good  to check out what OpenSSL and Java do here, since if PKIX is silent on the issue, but OpenSSL+Java both reject such certs I think we can consider them to be invalid in practice (since they will not be  usable/acceptable by most software) and safely can be rejected.

**Comment by randombit** [comment]
I added a check (at validation time) that if an end-entity certificate has keyCertSign set then it must have the CA bit set also.

Leaving open since there is still the question of validity ranges.

**Comment by neusdan** [comment]
Thanks for the work on the keyCertSign/CA bit checks.

Re validity ranges - i'm not sure if i recall correctly what this was about. 
Did some checks.

CA valid from 2017 - 2027
Cert1  valid from 2030 - 2035
Cert2 valid from 2020 - 2035

System time 2021:

```
openssl verify -CAfile ca.crt cert1.crt
cert.crt: CN = cert
error 9 at 0 depth lookup:certificate is not yet valid

openssl verify -CAfile ca.crt cert2.crt
cert.crt: OK
```

```
botan cert_verify cert1.crt ca.crt
Certificate did not validate - Certificate is not yet valid

botan cert_verify cert2.crt ca.crt
Certificate passes validation checks
```

System time 2030:

```
openssl verify -CAfile ca.crt cert1.crt
cert_3.crt: CN = ca
error 10 at 1 depth lookup:certificate has expired
OK

openssl verify -CAfile ca.crt cert2.crt
cert_3.crt: CN = ca
error 10 at 1 depth lookup:certificate has expired
OK
```

```
botan cert_verify cert1.crt ca.crt
Certificate did not validate - Certificate has expired

botan cert_verify cert2.crt ca.crt
Certificate did not validate - Certificate has expired
```

So everything okay here?!

**Comment by neusdan** [comment]
Found something about this from Microsoft (but seems like it is really old)

> Note: An expired CA certificate in the certification path reduces the quality of the path; it does not invalidate the path. In the Windows Server 2003 PKI, a certification path can be valid as long as the CA certificate was valid at the time the certificate was issued. For example, a third-party CA might issue a certificate with a lifetime that extends past the CA certificate's expiration date. After the CA's certificate expires, the certification path for the certificate is still valid and the certificate is trusted as long as all other validation criteria are met. In Windows 2000 however, CryptoAPI enforces time nesting rules by default where a child certificate must have a validity period shorter than the parent. Signatures, however, may be considered valid past the date of the certificate lifetime. Signature validation and processing is, however, outside the scope of this white paper.

> Note: Windows 2000 and Windows Server 2003 CAs never issue certificates with a lifetime that extends past the CA certificate's expiration date. The issued certificate will be configured to expire on or before the CA's certificate expiration date.

Source: https://technet.microsoft.com/en-us/library/cc700843.aspx?f=255&MSPPError=-2147217396

**Comment by randombit** [comment]
It looks like OpenSSL follows basically the same rule as MS mentions?

> openssl verify -CAfile ca.crt cert2.crt
cert2.crt: CN = ca
error 10 at 1 depth lookup:certificate has expired
OK

So (if I'm interpreting this output right) in the 2030 case, OpenSSL notes that the CA certificate has expired, but still declares the end certificate valid. That suggests we should change the path validation logic.

> Note: Windows 2000 and Windows Server 2003 CAs never issue certificates with a lifetime that extends past the CA certificate's expiration date.

That's a good idea, we should do this.

**Comment by randombit** [comment]
Now that we have the notion of warning statuses supporting this should be easy.

**Comment by FAlbertDev** [comment]
I'll take care of this issue.

**Comment by reneme** [comment]
I think with @FAlbertDev's PR merged, this is now resolved.
