### ISSUE TITLE
Define an official compiler support

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#111]
On the website it is stated that

> Versions 1.11.0 and later require a mostly-compliant C++11 compiler such as Clang 3.1 or GCC 4.7.

This is very vague and a user of Botan can at the moment not rely on Botan building with those compilers. Thus I think it is necessary to officially define a compiler support list.

This ones we know to be working:
- MSVC 2013 (AppVeyor, Kullo CI)
- Clang 3.4 (Travis)
- Clang 3.6 (Kullo CI)
- gcc 4.8 (Travis, Kullo CI)
- gcc 4.9 (manual builds)

Are there any compiler versions below gcc 4.8 and clang 3.4 we need to support? Is someone using Botan using an older compiler.

See also C++11 support [gcc 4.7](https://gcc.gnu.org/gcc-4.7/cxx0x_status.html) vs. [gcc 4.8](https://gcc.gnu.org/gcc-4.8/cxx0x_status.html).

**Comment by randombit** [comment]
Clang 3.1 and GCC 4.7 were just the earliest compiler versions that supported all of the C++11 features I considered must have (non-static data member initializers, lambdas, template typedef). I agree the statement needs to be more clear so users have a good sense of what they should expect to work.

On the one hand it would be great to drop gcc 4.7 support and be able to use features added later, like inheriting constructors. Additionally it would focus support efforts and ensure that what is being tested matches up with what we claim to support - it turns out trunk wouldn't even compile under GCC 4.7 due a couple of missing includes (just fixed), clearly I had not tested that configuration in a while.

I'm slightly concerned that adopting features that are incompatible with GCC 4.7 leaves users of older distros out of luck. but the latest RHEL and Debian stable have GCC 4.8 or higher already, so perhaps 4.7 doesn't matter anymore.

**Comment by webmaster128** [comment]
Ubuntu 12.04 which is supported until April 2017 has gcc 4.7 via universe. So it might be a bit too early to drop gcc 4.7 support.

**Comment by tiwoc** [comment]
I'm building Botan with gcc 5.1 without a problem. The docs should probably state the minimum compiler versions that are supported ("should work on...") and the versions and probably platforms that are used for automated tests ("continuously tested on...").

**Comment by webmaster128** [comment]
At the moment it seems like supporting GCC 4.7 for 1.11 releases is not costing us anything. But for the Botan 2.0 release we should drop it definitely in order to freeze compiler support as well for the lifetime of Botan 2.0

**Comment by randombit** [comment]
I don't know if freeze is exactly the right word - modifications as needed to support future versions of GCC/Clang/MSVC would make sense. But yes if Botan 2.0.0 supports compiler version X then we should continue to support it through all 2.0.x releases, as anything else would leave a distribution packaging both botan and that compiler version in a rough place if it support for it was dropped mid-stream.

**Comment by webmaster128** [comment]
I was thinking of *freezing minimum versions* per compiler.

**Comment by randombit** [comment]
OK, sounds like we are in agreement on that.

Dropping 4.7 support (at least in the official sense) before 2.0 probably makes sense. I'm not sure what the story is with Clang here; OS X support is still the primary driver there and I don't have a good sense of what OS X versions are still important to support or what Clangs they provide. For Windows supporting both MSVC 2013 and 2015 is probably the right choice.

**Comment by webmaster128** [comment]
Apple put a lot of afford into pushing old software out of the market during the last years. They release a major OS upgrade every year and don't commit in supporting the old ones for a fixed time frame. There are already security bugs (locally) in OS X 10.9 that Apple is not going to fix. So using OS X 10.8 can not be considered secure today and OS X 10.9 is questionable.

Given that, I'd support the toolchain that has OS X 10.8 as a minimal requirement: [XCode 5](https://en.wikipedia.org/wiki/Xcode#5.x_series) from 2013. In that [toolchain](https://en.wikipedia.org/wiki/Xcode#Toolchain_versions) we have `clang-500.2.75 (based on LLVM 3.3svn)`.

So I'd go for clang 3.3, which [claims](http://llvm.org/releases/3.3/tools/clang/docs/ReleaseNotes.html#id1) to have a *feature-complete implementation of C++11*.

**Comment by randombit** [comment]
In c4cc713 I created a doc listing supported compilers/platforms for Botan 2.
