### ISSUE TITLE
X.509/ASN.1 charset handling

### ISSUE THREAD

**Issue by dewyatt** [randombit/botan#1113]
As mentioned in the manual:

> Botan doesn’t currently support any of the Unicode variants used in ASN.1 (UTF-8, UCS-2, and UCS-4), any of which could be used for the fields in the DN. This could be problematic, particularly in Asia and other areas where non-ASCII characters are needed for most names. The UTF-8 and UCS-2 string types are accepted (in fact, UTF-8 is used when encoding much of the time), but if any of the characters included in the string are not in ISO 8859-1 (ie 0 ... 255), an exception will get thrown. Currently the ASN1_String type holds its data as ISO 8859-1 internally (regardless of local character set); this would have to be changed to hold UCS-2 or UCS-4 in order to support Unicode (also, many interfaces in the X.509 code would have to accept or return a std::wstring instead of a std::string).

As an example, trying to use asn1print or cert_info, etc, for the certificate [here](http://gostcrypto.com/tool-asn1.html) will cause an exception.

As a workaround I've generally been storing and outputting everything as UTF-8 and using `boost::locale` for conversions, something like the below:

```cpp
// used for getting the local encoding
std::locale loc(boost::locale::generator().generate(""));

//IA5String -> UTF-8 (should be no-op)
boost::locale::conv::between("abcd",
    "UTF-8",
    "646",
    boost::locale::conv::stop);

//UCS-2 to local encoding
boost::locale::conv::between("\x42\x30",
    std::use_facet<boost::locale::info>(loc).encoding(),
    "ucs-2",
    boost::locale::conv::stop);
```

There might be a nicer way, this is just some local hack I've been using.

**Comment by randombit** [comment]
Would be nice to improve this area. I think the manuals comment about using `wstring` is bogus (yes, I wrote that) and it would be better to instead translate everything to UTF-8 `std::string`s.

I think (but am not certain) that C++11 `std::locale` is insufficient for this task. We'll have to use either Boost, iconv (on Unix/Linux) or `MultiByteToWideChar` and co on Windows.

**Comment by reneme** [comment]
We encountered X.509 certificates with non-Latin1 unicode chars in the DN. Obviously they are not readable by Botan. Our workaround is not to use any such characters in the certificates of our application for now, but that's only a short term solution.

After briefly looking into the ASN.1 parser, I am having trouble to estimate what it takes to get UTF-8 support in there. If you could you give us a few pointers, we might be able to allot some resources into this. How do you estimate the amount of changes necessary for this?

**Comment by randombit** [comment]
@reneme Would be great to have this fixed and I don't think it would be terribly hard. The main changes would be in `asn1_str.h` and `asn1_str.cpp`. Basically right now Botan stores all ASN.1 strings (lossily) as Latin-1 `std::string`; all that's needed (AFAIK) is to change this to be UTF-8 instead.

`ASN1_String::iso_8859` should be deprecated, but can't be removed immediately. I suppose the best behavior in the short term would be to transcode the value into Latin-1 if possible, or otherwise throw an exception.

The ASN1 string uses some character set conversion routines in `utils/charset.cpp`. These are also called independently of ASN1_String in a few spots (such as decoding the `GeneralName` type).

Random hints:
 - Remove `choose_encoding` from `asn1_str.cpp` - instead just always encode new strings as UTF8
 - Similarly in `ASN1_String::encode_into`, always choose UTF8
 - For decoding, some charsets (like PRINTABLE_STRING, NUMERIC_STRING, IA5_STRING) are ASCII subsets so can be directly treated as if they were UTF8 without further examination. (I suppose it wouldn't hurt to verify that strings tagged with these types are within their defined character sets though.)
 - Since we are always encoding to UTF8, the character set encoding routines can be simplified. Basically all we'd need in that case is: convert Latin-1 to UTF-8, and convert BMP (16-bit Unicode subset) to UTF-8. Just ignore (and deprecate) the existing `Charset::transcode` function, and add two new functions for these specific operations; they should only be called from within `ASN1_String`. The existing `latin1_to_utf8` in `charset.cpp` might actually be correct and usable as-is, I'm not sure. For BMP->UTF8 we may need help from system libraries, but I'm not sure. The basic UTF8 transformation is simple but it seems like Unicode has plenty of strange corner cases and I don't know how many we need to handle.
- A few other places in the code read ASN1 strings but then directly converts it to a `std::string` (eg `GeneralName`). These should change to store `ASN1_String` objects instead. They are easily spotted by their use of `Charset::transcode`.

Let me know if you have any questions or need further direction.

**Comment by randombit** [comment]
Fixed!
