### ISSUE TITLE
PKCS #7 Support (July 2017)

### ISSUE THREAD

**Issue by Pwnsian** [randombit/botan#1115]
Hi,

I'd like to bring up https://github.com/randombit/botan/issues/30 to ask the same--after a few years, what is the status of PKCS #7? My use case is the same, which is signing a PDF.

Additionally, to implement the functionality if required, what is the general procedure to do so with the current asn.1 functionality? I see the discussion mentioned in https://lists.randombit.net/pipermail/botan-devel/2011-October/001489.html, does that still hold? Any more pointers with the new versions of Botan?

Thank you.

**Comment by randombit** [comment]
Hi @Pwnsian I apologize for letting this ticket fall through the cracks.

There has been no progress on supporting PKCS7 within Botan since then. It is worth supporting, but it has not been a priority for me and nobody else has submitted anything.

The ASN.1 code has not substantially changed since that post so everything should still apply.

I've added PKCS7 to the todo file so we remember this request, but tbh unless someone either submits code for it or contracts with me to add it, it is not likely to happen anytime soon.
