### ISSUE TITLE
Botan tls and node.js returns EOF immediately.

### ISSUE THREAD

**Issue by slicer4ever** [randombit/botan#1117]
Hey there, i'm unsure if i've configured things incorrectly for node.js, or if it's a problem with botan's initial handshake message, but any attempt to contact my site which is ran on the https module of node.js causes it to respond with the server closed socket immediately. 

I'm testing with the cli tls_client so i'm not sure what is going on to cause this problem. 

The site in question is here: https://neonlightgames.com  the site isn't much at the moment, but i'd like to discover the reason i can't seem to communicate with it.

**Comment by randombit** [comment]
The problem is almost certainly that Botan has RSA key transport disabled by default, and your site does not offer forward-secure ciphersuites (DH/ECDH).

You can test this using the command line util by

echo "key_exchange_methods = RSA" > rsa_policy.txt
./botan tls_client --policy=rsa_policy.txt neonlightgames.com

As to Node, from my read of the docs it seems ECDH is supposed to be supported out of the box so I'm not sure what the problem there might be.

**Comment by slicer4ever** [comment]
haha, wow thank you.  passing the policy file to it seems to have taken care of the issue.  Thanks for the help.
