### ISSUE TITLE
Fail Decrypt  BotanCLI TLS using Wireshark 

### ISSUE THREAD

**Issue by yutianzhe30** [randombit/botan#1152]
Hello ,this issue may not be so proper here but i want some support.
When i use Wireshark to decrypt a Openssl sample(by importing server private RSA key) [https://github.com/matthewarcus/ssl-demo](url) it works perfect. 
And i want to do the same thing with Botan CLI tools and selfsigned cert and key(RSA_2048bits).
server
`botan tls_server selfsignedCer.cer serverPrivate.pem --port=9999 `
client
`botan tls_client localhost --port=9999 `
after some time 
 i add also tried --policy=weakpolicy 
`key_exchange_methods=RSA`
`ciphers=AES-256`
resulting
`Alert:unrecognized name`
`Certificate validation status: Cannot establish trust`
 `Handshake complete ,TLS v1.2 using RSA_WITH_AES_256_CBC_SHA256`
`Session ID : (long hex there) `
I have also tried using the key example in open SSL one
resulting ´Certificate validation status: Certificate issuer not found´

I have compared the differences in these 2 situation, it seems I dont have a Session ticket.
Look into wireshark i found the server hello extension does not cotain 'session ticket' (while client hello does)may be you can tell me how to enable this
![image](https://user-images.githubusercontent.com/3817426/29314776-da8660d2-81bf-11e7-9ac3-8e2a49f53f63.png)
![botan](https://user-images.githubusercontent.com/3817426/29318345-e91d7314-81cf-11e7-8eec-c1282e40989c.png)
upper is the one i can not decrypt (no decrypted SSL data section)
![openssl](https://user-images.githubusercontent.com/3817426/29318346-e927e90c-81cf-11e7-8219-8bdf7d0822fc.png)
upper is the openssl one which i can decrypt(u can see the decrypted data section)

I know this is not a really related issue. But I hope i can get come insight here. Thank you for your time

**Comment by randombit** [comment]
@yutianzhe30 The TLS server command line util doesn't support session tickets at the moment. The library uses them by default *if* a secret key is configured for that purpose (to encrypt/authenticate the session ticket data). But the command line util doesn't support setting PSKs at the moment. This would be a pretty simple patch I think.

I don't understand something though - you seem to be saying that without the session ticket, wireshark cannot decrypt the session. But having a session ticket would not assist in that, because it is encrypted. And even if you gave wireshark the same encryption key as that used by the server to encrypt the ticket, that would not help because the ticket contents are stored in a Botan-specific format which wireshark doesn't know about.

**Comment by yutianzhe30** [comment]
@randombit thank you for your reply.  I think thats my mistake, I will try more later
