### ISSUE TITLE
X25519

### ISSUE THREAD

**Issue by rafalsk** [randombit/botan#1166]
1) is there a public facility which would allow to accomplish an X5519 handshake?
The manual could use a revamp. In the section regarding Key Agreements there is just one example with ECDH. More description and additional sentances could be added on how X25519  differs and how to use curve25519_donna if no further architectural design changes  (better integration) are on the way.
2) why does the manual  list  DLIES and ECIES under the Key Agreement protocols?

**Comment by randombit** [comment]
Re 1, yes exactly as described in the manual for ECDH using a `PK_Key_Agreement` object, except provide a `Curve25519_PrivateKey` instead (and you don't need to create a `EC_Group` object, of course, because the domain is implicit). There is a test case that demonstrates usage here https://github.com/randombit/botan/blob/master/src/tests/test_c25519.cpp#L52

Certainly it would be good to address X25519 directly in the manual.

Re 2, that certainly doesn't make much sense, since both are key encapsulation protocols. That section of the docs was originally written for a BSI project, maybe BSI classifies IES schemes as key agreement by virtue of their using DH/ECDH keys? @securitykernel any idea on this?

**Comment by rafalsk** [comment]
@randombit; so there is more integration than I've crudely allowed myself to say! I think I'm having warm feelings toward the library again.

**Comment by securitykernel** [comment]
Re 2, BSI only lists DH and ECDH as key agreement and DLIES and ECIES correctly as asymmetric encryption schemes, so probably just a bug in the manual.

**Comment by randombit** [comment]
Thanks I'll update the docs
