### ISSUE TITLE
Number Theory pow_mod is not working with a negative base.

### ISSUE THREAD

**Issue by bbylin** [randombit/botan#1168]
When using pow_mod with a negative base it this exception thrown
```
C++ exception with description "Invalid argument Power_Mod::set_base: arg must be > 0"
```
The documentation is only mention that the exponent and modulus needs to be positive.
```
/**
* Modular exponentation
* @param b an integer base
* @param x a positive exponent
* @param m a positive modulus
* @return (b^x) % m
*/
BigInt BOTAN_DLL power_mod(const BigInt& b,
                           const BigInt& x,
                           const BigInt& m);
```
For my calculations needs the pow_mod handle a negative base is that possible with the botan implementation?

**Comment by randombit** [comment]
It's not supported natively because it doesn't really come up too often in crypto, but it's easy to compute because for a negative base `b`, `b^e % m` is either the same as 
`|b| ^ e % m` (if e is even) or `m - (|b| ^ e % m)` if e is odd. That's easy to realize when you consider that `b^2` is always positive, so in the exponentiation either all of the -1s cancel out, or (if e is odd) then there is a single remaining negative factor which is accounted for by the final negation (modulo m).

It might be good to just support this in `power_mod` directly.

**Comment by chrfleqoitech** [comment]
It would be much appreciated if it could be included into` power_mod` directly. Is that something that would make it into the 2.3.0 release planned for early October?

**Comment by randombit** [comment]
@chrfleqoitech @bbylin This is easy to do yourself in a wrapper around `power_mod`, but it's also easy to support directly so added in #1179

Note this only works for the `power_mod` function and not the lower level exponentiator classes, but you probably wouldn't/shouldn't be using those directly anyway.

**Comment by chrfleqoitech** [comment]
@randombit Thanks a lot sir ;)
