### ISSUE TITLE
Why are we testing debug mode on Visual C++?

### ISSUE THREAD

**Issue by randombit** [randombit/botan#1172]
Paging @webmaster128 @neusdan as people interested in Windows support.

AppVeyor CI is taking 2.5 hours and over an hour of that is in the two Debug builds. These builds have no optimizations enabled (`--debug-mode` disables optimizations) so running the tests take up almost all of the runtime. Are the results from these tests buying us anything? I suppose it does test that we get the debug linking flags right but that's about it that I can see. Can we either remove them (or at least one of them), or else use `--with-debug-info` to add debug info without also disabling optimization?

**Comment by webmaster128** [comment]
Debug builds in Visual C++ enable a lot of stuff that is called sanitizers on other platforms. Being able to run debug builds on Windows was the primary motivation for hundreds of changes in the form &vector[0] -> vector.begin() since strong range and type checking is in place. I guess that was part of the motivation but I don't remember exactly anymore.

However, I don't have a strong opinion for keeping or removing any specific configuration. Maybe one debug build using the latest compiler is sufficient for utilizing all checks available.

**Comment by randombit** [comment]
Ah OK so debug mode includes the equivalent of GCC's debug iterators? That's worth keeping for sure - I had thought this was enabled via some other mechanism.

**Comment by webmaster128** [comment]
Iterator debugging and operator[] range checking are the main features I am aware of. Debug builds also use a different debug STL, which seems to add [a lot of stuff](https://docs.microsoft.com/de-de/visualstudio/debugger/crt-debugging-techniques), e.g. a [debugging version of malloc](https://docs.microsoft.com/de-de/visualstudio/debugger/debug-versions-of-heap-allocation-functions). I'm not at all familiar with all those features but I get the impression the additional runtime is spent well.
