### ISSUE TITLE
Failing test RSAES/EME-PKCS1-v1_5

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#123]
In coverage mode, I just got the following failing test:

```
RSAES/EME-PKCS1-v1_5 failed - decrypted bad data
06DE6646853E49A067C85492FCA580E49D286981CCFDC4E13B5642489CC19E803A69116BC2D75CD005B768F3FE7AA780BF7E5A2A3EA53085619946DB4B3E9DB7592A8D060CDF185B3AB2C1BD551587EA8AC3745FEF60D945387B27C2001CF7A9EAE9A086AA58B769A59CC4D09BCF2C100ED630EE44889F341C8DCCF52F003CF1 -> 89263E12BCD22ED44CF8CC6A85C42FD008977CEE69A8AED9BE846F7C42FF72589655D8891021131C8EC9224A683C3DB31650C05095F43713AF5510E0261D091897D8FCE29BE2C0B5693C93598F22
06DE6646853E49A067C85492FCA580E49D286981CCFDC4E13B5642489CC19E803A69116BC2D75CD005B768F3FE7AA780BF7E5A2A3EA53085619946DB4B3E9DB7592A8D060CDF185B3AB2C1BD551587EA8AC3745FEF60D945387B27C2001CF7A9EAE9A086AA58B769A59CC4D09BCF9E100ED630EE44889F341C8DCCF52F003CF1 -> 4772617669746174696F6E2063616E6E6F742062652068656C6420726573706F6E7369626C6520666F722070656F706C652066616C6C696E6720696E206C6F76652E20202D2D20416C626572742045696E737465696E
Ignoring PKCS #1 failure
```

I have no clue why, because I did not change any C++ file and tests have been running fine a couple of times before today. I just want to document this in order to observe it.

What was strange as well: make did not stop after running the tests, so return code must have been 0.

**Comment by randombit** [comment]
This is expected but probably confusing and potentially frightening to a user, so should be handled better. For each standard encrypt/decrypt test vector, the test suite also creates some number of randomly chosen invalid ciphertexts and attempts to decrypt them (this is in test_pubkey.cpp function validate_encryption). For OAEP this should never succeed but for PKCS #1 v1.5 this can and does occur occasionally due to the known weaknesses in that padding scheme. For every other scheme such an event will cause an test failure, but the function special cases PKCS #1 and logs the error but ignores it as a failure.

I don't want to skip PKCS #1 v1.5 entirely for this test since corrupted ciphertexts "normally" don't decrypt and having such errors be logged makes it clear that they are not happening during normal operation.

**Comment by webmaster128** [comment]
Thanks for the background information.

Since this failure does not cause the tests to fail, there must already be a special handling. I'd suppress all output for this as long as there is no verbose mode.

**Comment by randombit** [comment]
I think we now do the right thing in this situation.
