### ISSUE TITLE
Don't deprecate std::function API

### ISSUE THREAD

**Issue by Exaeta** [randombit/botan#1256]
For some reason you guys have bought into the object-oriented fetish.
Did nobody seem to pay attention to the fact that although copying std::function is slow, calling them isn't?
Having a separate class for callbacks seems a bit silly.

This recommended API looks like Java and makes me want to puke. :)

**Comment by randombit** [comment]
> although copying std::function is slow, calling them isn't? Having a separate class for callbacks seems a bit silly.

This change wasn't done for performance reasons. The problem with the std::function based API is that it is harder to extend or evolve it. For example when we add support for custom extension handling, that will add 1-3 additional functions. Of course most applications don't need custom extensions, so the default Callback virtuals will be no-ops. Ditto for debug logging, certificate transparency, etc. To support this in the std::function based constructor we'd have to add additional more std::function parameters. This either breaks the API, or forces creating dozens of different constructors taking all the various permutations of optional callbacks. (Instead, these additional features will just not be supported through the deprecated API, only via `Callbacks`)

Also from a code structure perspective (internally) I like having a Callbacks class so it's very clear when the stack is making a call back to the application layer - `callbacks().foo()` vs `some_thing_that_happens_to_be_a_std_function()`

I understand that the Callbacks approach does require a somewhat different application structure than the `std::function` API. But it is easy to emulate in the application, in the same way we already do it internally (see `Compat_Callbacks` in `tls_callbacks.h`, which is how the deprecated constructors are implemented).

Lastly, while deprecated, it is not being removed in Botan 2.x so feel free to define `BOTAN_NO_DEPRECATED_WARNINGS` and ignore it. It will be removed in Botan 3.x (which is not coming out for several years at least), at which point applications will have to switch. (It may be worthwhile to de-deprecate `Compat_Callbacks` and bless that as the way for applications that want to use a `std::function` based interface, rather than forcing each such application to reimplement the same functionality)

**Comment by Exaeta** [comment]
Ah okay. A std::function wrapper would definitely be more convenient though.

**Comment by Exaeta** [comment]
@rabdombit 

I'm not sure if I understand the API correctly, but would it be possible to modify the API to pass the callbacks as a reference to the functions instead of adding them as state to the TLS class? My understanding is that callbacks always execute in the same thread as the caller, is that correct? So having a reference to callbacks instead of a member variable would be more flexible.

**Comment by Exaeta** [comment]
@rabdombit

Would it be possible to adjust the API to use a callback as a function parameter instead of as object state? It would make the calls easier for the compiler to inline and also be more flexible.

**Comment by Exaeta** [comment]
@randombit

Would it be possible to adjust the API to use a callback as a function parameter instead of as object state? It would make the calls easier for the compiler to inline and also be more flexible.

**Comment by randombit** [comment]
@Exaeta a struct of function pointers plus a `void*` seems to me like just a very poor vtable.

Closing since I am pretty sure the std::function-based API is going to be removed (eventually). I will be sure we offer a good transition path though, which should be easy to do with something rather like the existing `Compat_Callbacks`.
