### ISSUE TITLE
Should we generate pkg-config file on Windows?

### ISSUE THREAD

**Issue by runapp** [randombit/botan#1268]
In fact pkg-config is also working on Windows. I have little knowledge about pkg-config before so finding a suitable pkg-config file do take me long.
Now I know that it will be rather simple to generate it manually. I'm not sure if it should be auto-gerated, or add something like --write-pkg-config-on-win32 to configure.py, or stay at current state?

**Comment by randombit** [comment]
Interesting I did not know pkg-config was available for Windows. I suppose given MinGW, Subsytem for Linux and other such projects it should not be a surprise.

It would be pretty easy to create such a file. Currently the code in `configure.py` has

```
    if options.os != 'windows':
        write_template(in_build_dir(PKG_CONFIG_FILENAME), in_build_data('botan.pc.in'))
```

It might be as simple as removing this conditional. I'm assuming pkg-config on Windows would mostly be used in relation to GCC/Clang rather than MSVC (correct me if wrong); the template has some GCCisms like use of -L and -I flags, but these are ok on Windows also.

If you (or someone) could post an example pkg-config that has the desired behavior on Windows, that would help a lot.

**Comment by randombit** [comment]
Or alternately remove the conditional in configure.py and try the resulting pkg-config file; if all we have to do is remove that exclusion then great.

**Comment by runapp** [comment]
Seems the default one written by configure.py is perfect.

**Comment by randombit** [comment]
Hm, there must be some difference in how we named libraries between systems. I'll check that out.

**Comment by ksanderon** [comment]
related to #1403

**Comment by randombit** [comment]
#1712 adds option `--with-pkg-config` and now we generate the pkg-config file with the correct lib name regardless of platform.
