### ISSUE TITLE
Is static linking without amalgamation supported

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#128]
At the moment static linking is only working using the `--via-amalgamation` flag. Now the question is: is this configuration supported or not.

E.g. configuration

```
./configure.py --disable-shared
make -j 2
./botan-test
```
leads to a bunch of errors and a SEGFAULT on Linux.

Now there are basically two options (I have no opinion which one to choose):

1. Support and fix static without amalgamation
2. Don't support static without amalgamation, document it and exit with an error at configure time

Any ideas? Pros? Cons?

**Comment by cdesjardins** [comment]
I personally like the idea of fixing the issue that causes static builds to fail. Although it would be a big API change, I think it makes more sense to actually use the linker as it was intended to be used, because it will catch stupid type-o errors and the like at compile time rather that at run time.

**Comment by webmaster128** [comment]
I think this is because linker throws away symbols that are not used. E.g. 
```
$ ./configure.py --disable-shared
$ make -j 2
$ strings build/obj/lib/block_aes.o | grep ZN5Botan7AES_256
.rela.text._ZN5Botan7AES_256D2Ev
.gcc_except_table._ZN5Botan7AES_256D2Ev
[...]
_ZN5Botan7AES_25612key_scheduleEPKhm
_ZN5Botan7AES_2565clearEv
$ strings libbotan-1.11.a | grep ZN5Botan7AES_256          
_ZN5Botan7AES_256D2Ev
_ZN5Botan7AES_256D1Ev
[...]
_ZN5Botan7AES_25612key_scheduleEPKhm
_ZN5Botan7AES_2565clearEv
$ strings botan-test | grep ZN5Botan7AES_256
[no result]
```

SHA-1 on the other hand is linked, since test `unit_x509.cpp` has a `X509_CA` which in `sign_request()` has a `Cert_Extension::Subject_Key_ID` which has a `SHA_160` variable.

When I now add 
```
Botan::AES_128 b;
```
to `test_ocb_long()`, all AES test run smoothly and I find the AES symbols in the test binary

```
$ strings botan-test | grep ZN5Botan7AES_256         
_ZN5Botan7AES_256C2Ev
_ZN5Botan7AES_256D2Ev
[...]
_ZN5Botan7AES_256C2Ev
_ZN5Botan7AES_256C1Ev
```

So the current design of having a string based symbol collection is just not how C++ works. I think that must be fixed and by allowing static linking, we can achieve a better design.

**Comment by randombit** [comment]
In general I believe keeping the source as simple as possible is essential. That's sometimes not very simple at all, but my view is that making the code easy to read, understand, and audit is an important criterion in its own right. The previous lookup code was much more complex, required a non-reentrant initialization process, and allocated quite a bit of memory creating prototype objects just to be able to call clone() on them if and when required. And having the engine lookup logic, which converted from a string to a call to new T(), and the constructor of T itself, separated in completely different areas of the code, made it easy to make mistakes and caused several bugs. So I was happy to see it go.

My thought had been to split the build into two distinct targets, static and shared. The static would be always built using the amalgamation while the shared could be built either way. A default build on most platforms would be shared only. In the short term this translates to option 2.

Very likely supporting static libraries without amalgamation could be supported without increasing the complexity that much. But the only downside I am aware of to building the static library this way is that you need quite a bit of memory to build it, and applications linking against it would be larger until stripped. But if an application is concerned about both binary size and having an external runtime dependency, it seems far better served by a minimized amalgamation which can be customized to their application's requirements and be as small as possible. So I don't see that there is much harm to it in practice.

Is there a use case I'm missing?

**Comment by cdesjardins** [comment]
I am still not sure why you need a string based look-up at all, what is wrong with just allocating the desired object, or using the factory pattern or builder pattern?

**Comment by tiwoc** [comment]
@randombit There's a second downside to compiling --via-amalgamation:
`INFO: Skipping, uses assembly and --disable-asm set - sha1_x86_64`

I don't know how much of a performance penalty this introduces compared to the C++ implementation of SHA1, though.

**Comment by tiwoc** [comment]
Here's a description of the linker behavior that is the reason for non-amalgamation builds to fail, as far as I understand the issue: [Linker leaving out globals from unused object files in static libs](https://gist.github.com/tiwoc/433cf884fcc3aeccbf37)

**Comment by randombit** [comment]
@tiwoc On old compilers (GCC 3.3, etc) the assembly would beat the C++ versions, but the asm is often the slower when the C++ is compiled by a modern compiler. Given that we now require such a compiler they all could probably be removed. Alternately it would be simple enough to add another amalgamation file containing just the asm, as is done for avx2 etc.

**Comment by randombit** [comment]
@cdesjardins Are you suggesting removing any API which take a string describing the algorithm and produces an implementation for it? I'd be very against that.

Also, if the requirement is that applications should allocate the objects they want directly rather than using a lookup - they could do that now, and static linking would work perfectly. So I must be missing your point here.

**Comment by cdesjardins** [comment]
Why are you against removing the string based interfaces? Based on your comments it appears that they don't do anything, if using them is totally optional then why have them? I find it strange that you recommend using the API in an undocumented way as a work around for a bug in the API.

**Comment by randombit** [comment]
They are optional, that doesn't mean using them isn't a good idea. The difference between  `new AES_128` and `get_block_cipher("AES-128")` is that with the first you get one specific AES implementation (and in the case of AES the worst possible one at that, not just the slowest but the one using lookup tables which exposes one to side-channels) and with the second you might depending on build and CPU type get an AES implemented using SSSE3, AES-NI, via OpenSSL or some other future provider not yet written.

And removing them would just push the problem to every caller. Everything from TLS to the `hash` command line tool requires the ability to request different algorithms based on externally-provided parameters, so removing the string lookup APIs would just mean each subsystem or application would have to maintain its own mapping scheme. I don't see the value in that.

And the kicker is that even if this change was made, as soon as we add such a mapping: `if(name == "Foo") return new Foo; if(name == "Bar") return new Bar;` in (say) TLS, then Foo.o and Bar.o are going to be pulled in by the static linker anyway due to the constructor calls. Which doesn't seem to be that different from just using the amalgamation.

I guess where I'm going here is that while I agree the current situation is ugly and that requiring the amalgamation with static libraries is a hack, I don't feel like anyone has articulated a specific scenario where it causes a problem that won't also occur with any other approach.

**Comment by webmaster128** [comment]
Thanks for pointing that out Jack. It was not clear to me before, that (a) symbols can be used instead of strings and (b) strings have the advantage you just mentioned.

I don't see a reason to not use amalgamation.

For me the most important point is to not scare potential Botan users away because the lib does not build as expected. To achieve this and at the same time preserve algorithm lookups, we can go for option 2 until someone comes up with an elegant way to tell the linker not to throw away stuff.

Using option 2, there is two ways to enforce amalgamation

* a: implicitly set `--via-amalgamation` when `--disable-shared` is set
* b: exit with error if `--disable-shared` is set without `--via-amalgamation`

I tend to (b) because users might need to know what is going on. On MSVC for example, user needs to set [/bigobj](https://msdn.microsoft.com/en-us/library/ms173499.aspx) when building `botan_all.cpp`.

**Comment by tiwoc** [comment]
> The difference between new AES_128 and get_block_cipher("AES-128") is that with the first you get one specific AES implementation (and in the case of AES the worst possible one at that, not just the slowest but the one using lookup tables which exposes one to side-channels) and with the second you might depending on build and CPU type get an AES implemented using SSSE3, AES-NI, via OpenSSL or some other future provider not yet written.

I didn't know about this mechanism. If it isn't documented yet, it definitely should be, because then using something like `new AES_128` has an impact on security.

**Comment by cdesjardins** [comment]
Sorry I am so late to reply, I have been hiking around Ireland for the past few days, but this is good to know, at the end of the day I still like the factory pattern better than this string based interface, but that by itself does not solve the problem of getting each module to register their interfaces at init time...
