### ISSUE TITLE
Integrate clang-tidy checks into CI

### ISSUE THREAD

**Issue by ruipacheco** [randombit/botan#1291]
I'm running clang-tidy on my project, by accident it parsed the generated files for botan and ended up generating a serious number of warnings. I didn't check them all for but a few jumped at me:

```
../src/external/botan_all.cpp:36551:29: error: the 'empty' method should be used to check for emptiness instead of 'size' [readability-container-size-empty,-warnings-as-errors]
      if(i < ocsp.size() && ocsp[i].size() > 0)
                            ^~~~~~~~~~~~~~~~~~~
                            !ocsp[i].empty()
```
or
```
../src/external/botan_all.cpp:36532:28: error: statement should be inside braces [google-readability-braces-around-statements,-warnings-as-errors]
   if(chain_status.empty())
                           ^
                            {
```
I believe the project would only benefit from clang-tidy being run automatically on it.

**Comment by randombit** [comment]
I've used it in the past on other projects, but no it is not run on Botan regularly. This would be a good one to add to CI.

**Comment by ruipacheco** [comment]
I’ve just caught a use after move in my own codebase.

**Comment by ruipacheco** [comment]
And don't forget about cppcheck and clang-format.

**Comment by ruipacheco** [comment]
I'm adding support for the family of Clang sanitisers to my project and [Undefined Behaviour](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) sanitiser makes my tests fail with this error:

```
../src/external/botan_all.cpp:20689:29: runtime error: unsigned integer overflow: 2562383102 + 1935764329 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20689:48: runtime error: unsigned integer overflow: 1721680384 + 3903086636 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20689:6: runtime error: unsigned integer overflow: 3285377520 + 1329799724 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20689:35: runtime error: unsigned integer overflow: 3378787463 + 1518500249 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20698:21: runtime error: unsigned integer overflow: 2207762906 + 2978349057 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20698:40: runtime error: unsigned integer overflow: 2750920060 + 3400511731 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20698:6: runtime error: unsigned integer overflow: 4070669099 + 1856464495 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20698:27: runtime error: unsigned integer overflow: 2526670014 + 1859775393 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20707:35: runtime error: unsigned integer overflow: 285569844 + 4106249329 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20707:54: runtime error: unsigned integer overflow: 2497811585 + 3985252276 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20707:41: runtime error: unsigned integer overflow: 2877091994 + 2400959708 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20707:6: runtime error: unsigned integer overflow: 1360352245 + 3782245646 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20716:21: runtime error: unsigned integer overflow: 3198673172 + 3527190041 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20716:27: runtime error: unsigned integer overflow: 2430895917 + 3395469782 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20716:6: runtime error: unsigned integer overflow: 1143117661 + 3447867875 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20716:40: runtime error: unsigned integer overflow: 3911237438 + 612761308 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20818:24: runtime error: unsigned integer overflow: 1732584193 + 4160454636 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20819:24: runtime error: unsigned integer overflow: 4023233417 + 1206415599 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20820:24: runtime error: unsigned integer overflow: 2562383102 + 2046771076 cannot be represented in type 'unsigned int'
../src/external/botan_all.cpp:20822:24: runtime error: unsigned integer overflow: 3285377520 + 3616435319 cannot be represented in type 'unsigned int'
```

**Comment by randombit** [comment]
We already run with Clang ASan+UBSan (including at very large scale as part of OSS-Fuzz). But unsigned integer overflow is well defined, which is why plain `-fsanitize=undefined` does not include unsigned integer overflow checks and it must be requested specifically with `-fsanitize=unsigned-integer-overflow`. Outside of crypto unsigned overflow is typically unintentional (which is why UBSan offers to detect it, even though it's not undefined), but we rely on it heavily.

It should be no problem to compile botan with `-fsanitize=undefined` but we certainly can't support `-fsanitize=unsigned-integer-overflow`. It *should* be possible to compile code calling Botan with `-fsanitize=unsigned-integer-overflow` but its not something we test so I could believe there are problems (eg where an unsigned overflow occurs in an inlined function in a public header). If you run into such a situation open an issue and we'll probably be able to fix it, since we definitely don't want to stop library users from using such tools even if we cannot use them internally.

**Comment by ruipacheco** [comment]
This won't stop me from running my tests, I just thought it was a good idea to mention.

**Comment by noloader** [comment]
@randombit,

Regarding:

> It should be possible to compile code calling Botan with `-fsanitize=unsigned-integer-overflow` but its not something we test so I could believe there are problems ...

GCC has `no_sanitize` attributes that are supposed to allow you to whitelist functions in source code. Also see [6.31.1 Common Function Attributes](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html) in the GCC manual.

The problem is, I have not been able to get them to work properly under GCC. Clang may behave a little better than GCC.

It is also worth mentioning I was trying to suppress an unaligned SSE load that Intel said was OK. GCC was firing on it; while Clang did not produce a finding.

In the end I think your choice to ignore unsigned wrap is probably the best one. I would not spend too much time on it since it is so prevalent.

**Comment by randombit** [comment]
We have tooling to run `clang-tidy` and generally maintain it to be warning free, but it is unfortunately way too slow to run in CI. Closing as no further progress can be made here.
