### ISSUE TITLE
Inclusion of other ciphers

### ISSUE THREAD

**Issue by DonaldTsang** [randombit/botan#1294]
Is it possible to add other ciphers into the library?  
These ciphers have educational purposes and is part of legacy code.
1. RC2, RC5, TEA, XXTEA and IDEA-NXT (important for toying around with ciphers)
2. RC6 and MARS (the AES candidates)
These ciphers as part of the CRYPTREC Project.
3. CIPHERUNICORN-A, CLEFIA, Hierocrypt-3, SC2000 (128-bit CRYPTREC)
4. CIPHERUNICORN-E, Hierocrypt-L1, MISTY1: (64-bit CRYPTREC)
5. MUGI, Enocoro-128v2, MULTI-S01 (stream CRYPTREC)

**Comment by randombit** [comment]
MISTY1 is already included (though deprecated). RC2, RC5, RC6, TEA, and MARS all were previously included, but removed because they had no apparent use cases (1c0bc3cc6bcbd6). See also #167 for discussion.

I am not against adding new ciphers in principle. The main criteria is that there is some reason that a developer would actually want to use them. For example in the last year ARIA and SM4 have been added, as they are important in certain industry contexts. And SHACAL2 was added, because while relatively unusual it is one of the very few 256-bit block ciphers available. In contrast I'm not sure any of the CRYPTREC recommendations (outside of Camellia) have ever been widely adopted, even within Japanese industry (feel free to correct if I'm wrong about that).

**Comment by DonaldTsang** [comment]
Could you consider putting those in the back burner?
RC5 and TEA are very educational ciphers on par with RC4.

**Comment by neusdan** [comment]
You should have a look at the goals of Botan:

https://github.com/randombit/botan/blob/master/doc/manual/goals.rst

Educational purposes are a non-goal.

**Comment by DonaldTsang** [comment]
1. Has anyone create a crypto library for rare ciphers (i.e. "backburners")?
    a. Has this been done before in the past by others in other projects?
    b. Can botan allow an official "Community/Hobby Fork" for such purposes?
2. Is there a C/C++ based educational crypto library that could:
    a. Have a python API/wrapper for ease of use
    b. cover RC2, RC4, RC5, TEA and XTEA 
    c. Possibly cover AES, Serpent, Twofish and Camellia

**Comment by randombit** [comment]
I would not be comfortable with endorsing such a fork because it might lead to an expectation that it was supported or signed off by me. At which point, the code might as well just be in the library proper to minimize my work. (Obviously Botan is open source, you are free to fork it, and I'd be happy to answer any questions about integrating new ciphers into your fork or etc. I just am not willing to do anything that might confuse users as to what is vs is not supported by me, because that just leads to more work for me - which is no fun.)

Re (2) I'm not aware of anything that meets all your qualifications. Closest would be mcrypt (which is abandoned and has known security flaws, but does cover a lot of algos and there is a Python wrapper) and Crypto++ (which has the algos you mention, and is actively developed, but afaik has no general Python wrapper). Oh and you might want to check out the D language fork of Botan (https://code.dlang.org/packages/botan) as the fork predates the removal of MARS, RC6 etc.

TBH though a C or C++ implementation of ciphers seems completely the wrong way to go for "educational use". Since for such uses performance, testing, side channels, etc are not an issue, but clarity of implementation is very important, it would be better to just implement them directly in Python using eg Sage http://www.sagemath.org/

In any case since it seems there is nothing here that we want to take up, I am closing this issue.
