### ISSUE TITLE
How to get fingerprint/keyid of a public key

### ISSUE THREAD

**Issue by Ratzupaltuff2** [randombit/botan#1356]
I find fingerprints useful to lookup keys from e.g. database. But current implementation (2.3.0) of Public_Key/Private_Key only provides a fingerprint() method for the Private_Key (hash on private key bits)

My use case is to verify a signature with the matching public key. I would like to attach the fingerprint/keyid information (or part of it) along with the signature in order to look up the the matching public key from a database for verification. Unfortunately the Public_Key interface does not provide a fingerprint() method and the Private_Key won't be available at the verification client, of course.
Are there any reasons why this method is not available for both key types. 

Also isn't it a bit risky to expose the private key bits to the security level of an arbitrary hash function (as this can be requested by the API)? Does private_key_bits() yield encrypted or plain key value?

**Comment by randombit** [comment]
> Are there any reasons why this method is not available for both key types.

No, I think this was just because fingerprint was initially only needed for the private keys (as part of the certificate store code), and it was not implemented for public keys as an oversight. Makes sense to have this though. I will need to check if there is any particular convention for public key fingerprints (eg as used in HPKP).

If you just need an index for a database lookup it's easy to implement this, just call `public_key_bits` on the key and hash the result.

> Also isn't it a bit risky to expose the private key bits to the security level of an arbitrary hash function

I don't see any particular issue here. It would allow you to confirm a guess of the private key, but the public key works just as well for that purpose. I don't see how either a collision attack or a preimage attack on the hash could be used to derive any meaningful information about the private key.

> Does private_key_bits() yield encrypted or plain key value?

This is the plain text of the private key, encoded for PKCS8 format.

**Comment by randombit** [comment]
Now there is a `Public_Key::fingerprint_public` that just fingerprints the public value.
