### ISSUE TITLE
Performance issue of FFI botan_cipher_update for AEAD-EAX

### ISSUE THREAD

**Issue by ni4** [randombit/botan#1377]
FFI interface process chunks of input data, using the `const size_t ud = cipher.update_granularity();`. For EAX it equals to 1, so data is processed in 1 byte chunks, which would be quite slow.

**Comment by randombit** [comment]
Thanks for the report. For 2.4.0 I'll change this to 128 which is the same approached used in SIV.

Really the fix is to distinguish two different values which are both currently tied together: the minimum update grain size (minimum value needed for correct behavior), and the optimum update size (best value for performance).

**Comment by ni4** [comment]
Thanks, @randombit 
Also decryption didn't work because of `BOTAN_ASSERT(cipher.update_granularity() > cipher.minimum_final_size(), "logic error");` in `botan_cipher_update`

**Comment by randombit** [comment]
Thanks for mentioning, I'll add an EAX test to ffi to confirm this is fixed.
