### ISSUE TITLE
Keyed-hashing support for blake2

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#1397]
I tried to implement the blake2b self test from [RFC 7693](https://tools.ietf.org/html/rfc7693#appendix-E) but found that keyed hashing is not supported in Botan.

Are there any plans to implement keyed hashing for blake2 or the hash interface in general?

**Comment by randombit** [comment]
I think it would be better to expose a hash that supports keying as a MAC, instead of tacking on keying operations to the hash function interface.

But it's hard to see a good way to implement this without duplicating a lot of code. The best I can come up with is implement `BLAKE2b_MAC` and move most of the hash logic (eg the compression function) there. Then implement the hash function in terms of the MAC, just always setting the key to empty. `MessageAuthenticationCode::start_msg` also adds a place to support the BLAKE salting mode.
