### ISSUE TITLE
rst2man changes to cli.rst interfere with sphinx

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#1398]
Both the HTML version and the PDF version of the users manual list the CLI handbook page with title "botan" instead of "Command Line Interface (CLI) and also print the annotations added for rst2man in a4b39d62ff.

**Comment by randombit** [comment]
Yeah it's unfortunate - Sphinx can't generate man pages, and `rst2man` requires the title and annotations in order to do the right thing.

Maybe what to do is, if rst2man is enabled, copy cli.rst to `build`, edit it with the `rst2man` annotations, and then run `rst2man` on that instead of the copy in `doc`.

**Comment by randombit** [comment]
Fixed now

**Comment by securitykernel** [comment]
Cool, thanks!
