### ISSUE TITLE
2.4.0: Windows, some findings regarding configure.py

### ISSUE THREAD

**Issue by ksanderon** [randombit/botan#1403]
Hi I wasn't here for a lot of time, however today I needed to use botan in work and unfortunetely found some issues/inconvenience/inconsistency in `configure.py` on our beloved, retarded OS(Windows).

* Why when used option `--minimized-build` windows `dependency libraries(windows libs)` are not used in makefile, even if base modules require these? These libraries are not used even when lot of modules are added using `--enable-modules`. (I used it because I need only very small subset of botan).
  * workaround: use `--ldflags` to inject these libraries manualy.
* Why when msvc is set in `x86` mode, `x86_64` is detected, so build fails because check in `build.h`?
  * workaround: manualy set `--cpu`
* Why on all platforms(checked mac os x + linux) botan static library is something like `libbotan-2.a` but on windows it is `botan.lib` instead `botan-2.lib`?
* Why there is explicit added `\MD`(and no option to choose different runtime) to cc path instead of cc params?
  * workaround: manualy set `--cc-bin=cl` and then aditionally required runtime in `--cxxflags` (I'm not sure there)
* It could be a lot easier to use botan `configure.py` if it will put all input paths escaped into makefile - otherwise using it in some kind of script is drama or even manually in case of windows and path with for example space character because there is needed to escape path many nasted times - for configure.py itself and additionally for nmake + one more time to cover whole option, so 3 times.

Probably tommorow there will be little bit more about botan cross compilation as I will try to use it on game consoles and other odd devices, where everything is huge pain because of strange SDKs and compilers 😵 

If I will have at least one free afternoon I will try to fix these + create PR but you know how it is with free afternoons 😉

**Comment by randombit** [comment]
> Why when used option --minimized-build windows dependency libraries(windows libs) are are not used in makefile, even if base modules require these? 

That seems like a bug. Don't know why that would happen. I'll check it out tonight.

> Why when msvc is set in x86 mode, x86_64 is detected, so build fails because check in build.h?

configure.py is just detecting the native platform here. I think we could add something much as is done for compiler version detection to examine the compiler's arch specific macros. That would also make things nicer for cross-compile builds.

> Why on all platforms(checked mac os x + linux) botan static library is something like libbotan-2.a but on windows it is botan.lib instead botan-2.lib?

I have no idea why exactly we do this. The actual mechanism that's causing it is at https://github.com/randombit/botan/blob/master/src/build-data/os/windows.txt#L9 but this setting is just reflecting something from earlier releases. Which may have just been a bug in the nmake code, originally.

> Why there is explicit added \MD(and no option to choose different runtime) to cc path instead of cc params?

It would be nice to be able to select the runtime directly. I think there is even an open bug about this. That it is missing is mostly because I don't really care about Windows (sad but true) and nobody else has submitted a patch.

> It could be a lot easier to use botan configure.py if it will put all input paths escaped into makefile

Yeah we don't handle that well at all. I will fix this. Is `nmake` and `cl` ok with '\\' for escaping spaces? In 2.4.0 we finally got the makefile template for Unix make and nmake converged on a single file and I'm hoping to keep it that way.

**Comment by randombit** [comment]
Looked at this

> Why when used option --minimized-build windows dependency libraries(windows libs) are not used in makefile, even if base modules require these? These libraries are not used even when lot of modules are added using --enable-modules. (I used it because I need only very small subset of botan).

OK so now I understand the problem. We only link in user32 if the Tooltip entropy source is enabled, and we link advapi32 only for the system RNG (CryptGenRandom). But we are using various other Windows APIs in `utils`. However as far as I can tell all of these APIs (VirtualLock, QueryPerfCounter, etc) are exposed by `kernel32.lib` which is implicitly linked (? not too clear if this is correct but anyway in no situation do we explicitly link to it.)

Can you provide the specific symbols that are missing, when you do not add the extra needed libs via `--ldflags`? Probably the problem is just that `utils` needs to depend on `advapi32` due to some function call we're using that requires it but I'd like to better understand the problem rather than blindly hacking at it (where possible ;P)

**Comment by ksanderon** [comment]
Yep, on monday I will heve access to windows machine, so will check which symbols are missing. Regarding nmake and cl I'm not sure about that whet they support and what now - I usually use ninja or gnu make on windows ;)

**Comment by ksanderon** [comment]
I'v found that python path is not escaped + documentation is executed in default make target even if explicite said in ./configure.py that documentation is not needed.

@randombit : paths can be stored like `"C://some dir/some other/"`(including `"`) instead of `C:\\some dir\some other\` (i'v not checked what if path contain `"`(and if it can be escaped) but this is super corner case I suppose).

**Comment by noloader** [comment]
> configure.py is just detecting the native platform here. I think we could add something much as is done for compiler version detection to examine the compiler's arch specific macros. That would also make things nicer for cross-compile builds.

In case it helps, here is a script that detects the machine through the environment: [nmake file](https://github.com/weidai11/cryptopp/blob/master/cryptest.nmake#L73). The caveat is, it needs to execute in a [Developer Command Prompt](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs).

**Comment by randombit** [comment]
Open bug on selecting runtime is #210

**Comment by ksanderon** [comment]
@noloader : to be honest, lot of things somehow work. But nmake not smell tasty, rather like next hack which will add 10 new hidden bugs instead one well known. 

I see, that currently significent amount of botan issues is related to build system and bugs in hand crafted solutions in this area. Maybe it's worth to reconsider again to smoothly switch to cmake during next releases? If there will be such plan I gladely will serve with my experiance and add 5 lines there.

**Comment by randombit** [comment]
@ksanderon Skeptical. Especially doing module dependency resolution through CMake seems highly not fun. Anyway I have no plans on spending time on CMake support in the near term. If someone wants to post a PR I'll certainly consider it. But tbh I'd much rather maintain 3k lines of Python than 3k lines of CMake. If it turns out CMake can do everything configure.py can in half the line count, then ok I'm sold.

(Worth mentioning I have no problems with CMake in general. Assuming I ever start another non-trivial C++ project again I would probably use it. And maintaining a handrolled build system is certainly not cheap in developer time. But it's not clear that CMake can do what we need it to do, here, without a lot of work.)

One intermediate step which might be useful is to split out relevant parts of configure.py (eg module dependency resolution, amalgamation generation, ...) into modules which can either be imported into configure.py or else shelled out to for CMake.

**Comment by randombit** [comment]
I think everything discussed in here has been resolved now.
