### ISSUE TITLE
Compatible DSA signatures with openssl

### ISSUE THREAD

**Issue by wmnnd** [randombit/botan#1409]
Hi there,

I am wondering whether it’s possible to sign/verify files with DSA keys using Botan that is compatible to OpenSSL.
Unfortunately, documentation on the exact algorithms used for signing is very sparse (both for OpenSSL and Botan), so I’m not even sure where to look for more information on this.

Right now, if you try to create a DSA signature with Botan, OpenSSL won’t verify it and vice versa:
```
echo "Generating DSA Keys ..."
openssl gendsa <(openssl dsaparam 4096) -out dsa.priv.pem
openssl pkcs8 -topk8 -in dsa.priv.pem -nocrypt -out dsa.priv.pkcs8.pem
openssl dsa -in dsa.priv.pem -pubout -out dsa.pub.pem

echo "##Verifying OpenSSL-OpenSSL DSA Signature"
openssl dgst -signature <(base64 -d sig.dsa.openssl) -sha1 -verify dsa.pub.pem file.txt
echo "##Verifying Botan-OpenSSL DSA Signature"
openssl dgst -signature <(base64 -d sig.dsa.botan) -sha1 -verify dsa.pub.pem file.txt
echo "##Verifying OpenSSL-Botan DSA Signature"
botan verify --hash=SHA-1 dsa.pub.pem file.txt sig.dsa.openssl
echo "##Verifying Botan-Botan DSA Signature"
botan verify --hash=SHA-1 dsa.pub.pem file.txt sig.dsa.botan
```

Is there something I’m missing or is EMSA1 (which seems to be used by Botan) incompatible with OpenSSL? Can Botan not verify DSA signatures created with OpenSSL?

I tried this with Botan `2.5.0 (git:3099e920495c8e881387363de8e1b0bf7d1d5292)` (from master) and OpenSSL `1.0.2g`.

**Comment by randombit** [comment]
Thanks for the report and repro.

The problem is that while the underlying DSA implementations are compatible, there are two different common ways to serialize DSA signatures. (This also applies to ECDSA.) And in the respective command line utils, OpenSSL uses one, and Botan uses the other.

There is, strictly speaking, no incompatibility, in that it is easy to convert from one format to another without any secret knowledge. However of course they don't verify, so that's not so helpful.

I've added an option to the command line utils (``--der-format``) which selects to generate (or for verifying, to expect) the DER formatting, which is what OpenSSL is using. After that I was able to sign+verify in both directions without problems.
