### ISSUE TITLE
random_safe_prime() is slow when using DL_Group::Strong

### ISSUE THREAD

**Issue by bellgrim** [randombit/botan#1411]
I am having issues with creating a DL_Group for DH. When tracing the code, it looks like it cannot find a random_safe_prime. It gets stuck on an infinite loop (I aborted after some minutes): https://github.com/randombit/botan/blob/master/src/lib/math/numbertheory/make_prm.cpp#L121

The DL_Group is created similar to this:

```
Botan::RandomNumberGenerator* rng = new Botan::AutoSeeded_RNG();
Botan::DL_Group* group = new Botan::DL_Group(*rng, Botan::DL_Group::Strong, 1024);
```

I do not have this issue on all of my machines, only Ubuntu 14.04 (64-bit). Do you have any hints on how I can debug this?

**Comment by randombit** [comment]
Second 1024-bit generator finished after exactly 4 minutes.

**Comment by bellgrim** [comment]
It did return a value, but after 11 minutes.

```
$ time botan gen_dl_group --type=strong --pbits=1024
...
real	11m8.379s
user	11m0.733s
sys	0m7.156s
```

Shall run my code again and see how long it takes.

**Comment by bellgrim** [comment]
My code returned a result after 12 minutes. So it is not an infinite loop, just that it takes a long time.

**Comment by randombit** [comment]
That's too slow. We're doing something wrong here.

**Comment by randombit** [comment]
The paper https://eprint.iacr.org/2003/186.pdf was helpful.

First, we should generate q to be == 2 mod 3, otherwise 2*q+1 will be a multiple of 3 and never prime.

Secondly, using a larger sieve seems to be helpful.

Also, there is no reason to do a very strong prime test on q until we have verified that p is prime. As it is we go to great length making sure q is prime, then throw it away because p is obviously not prime. So we should switch to a 2-stage verification of q, first a fast check, then check 2*q+1, then if p proves to be prime go back and do a stronger check of q.

With those changes, generating a 1024-bit safe prime is taking 10-40 seconds.

PR coming soon.

**Comment by randombit** [comment]
Should be fixed by #1413, now seeing 1024-bit strong DH params in 1 - 20 seconds. Would be great if you can confirm, especially with your VM.

**Comment by bellgrim** [comment]
Thanks for the fix. This was a real improvement!

```
$ time botan gen_dl_group --type=strong --pbits=1024
....
real	0m3.777s
user	0m3.753s
sys	0m0.013s

$ time botan gen_dl_group --type=strong --pbits=1024
...
real	0m2.280s
user	0m2.267s
sys	0m0.009s

$ time botan gen_dl_group --type=strong --pbits=1024
...
real	0m8.406s
user	0m8.383s
sys	0m0.017s

$ time botan gen_dl_group --type=strong --pbits=1024
...
real	0m15.914s
user	0m15.854s
sys	0m0.054s
```

**Comment by randombit** [comment]
Thanks for the confirmation. Travis is having some load issues right now, but as soon as they get themselves sorted out I'll merge.

**Comment by randombit** [comment]
Fixed now thanks for the report.
