### ISSUE TITLE
Two questions regarding a custom build

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1416]
Premises:

I need to generate a custom build of Botan, aimed at X509 certificate manipulation. I want to **load**, **inspect** and **validate** existing certificates, as well as **generate** and **save** new ones. Of utmost importnace is the ability to support both **RSA** and **ECC** keys.

After fiddling with **configure.py** for a while I reached this combination of flags:

C:\Git\botan>configure.py --cc=msvc --os=windows **--minimized-build --enable-modules=x509,ecdsa,rsa** --amalgamation --single-amalgamation-file --prefix="C:\Botan"

INFO: Skipping (incompatible OS): darwin_secrandom dev_random fd_unix getentropy proc_walk

INFO: Skipping (incompatible compiler): aes_armv8 pmull sha1_armv8 sha1_x86 sha2_32_armv8 sha2_32_x86 shacal2_x86

INFO: Skipping (not requested): adler32 aead aes aes_ni aes_ssse3 aont aria auto_rng bcrypt blake2 blowfish camellia cascade cast cbc_mac ccm cecpq1 certstor_sql certstor_sqlite3 cfb chacha chacha20poly1305 chacha_rng chacha_sse2 clmul clmul_ssse3 cmac codec_filt comb4p compression crc24 crc32 cryptobox ctr curve25519 des dh dl_algo dl_group dlies dsa dyn_load eax ecdh ecgdsa ecies eckcdsa ed25519 elgamal eme_oaep eme_pkcs1 eme_raw emsa_pkcs1 emsa_raw emsa_x931 ffi filters fpe_fe1 gcm gmac gost_28147 gost_3410 gost_3411 hash_id hkdf hmac_drbg hotp http_util idea idea_sse2 iso9796 kasumi kdf1 kdf1_iso18033 kdf2 keccak lion locking_allocator mce mceies md4 md5 misty1 newhope nist_keywrap noekeon noekeon_simd ocb ofb par_hash passhash9 pbkdf1 pgp_s2k pkcs11 poly1305 poly_dbl prf_tls prf_x942 psk_db rc4 rdrand rdrand_rng rdseed rfc3394 rfc6979 rmd160 salsa20 seed serpent serpent_simd sessions_sql sessions_sqlite3 sha1_sse2 sha2_64 sha3 shacal2 shacal2_simd shake shake_cipher simd siphash siv skein sm2 sm3 sm4 socket sp800_108 sp800_56a sp800_56c srp6 stateful_rng streebog system_rng threefish threefish_avx2 tiger tls tls_cbc tss twofish whirlpool win32_stats x919_mac xmss xtea xts

INFO: Skipping (requires external dependency): bearssl boost bzip2 lzma openssl sqlite3 tpm zlib

INFO: Loading modules: **asn1 base base64 bigint block cbc cpuid ec_gfp ec_group ecc_key ecdsa emsa1 emsa_pssr entropy hash hex hmac kdf keypair mac mdx_hash mgf1 mode_pad modes mp numbertheory pbes2 pbkdf pbkdf2 pem pk_pad pubkey rng rsa sha1 sha2_32 stream utils x509**

The questions:

1. Given the list of modules above, is there anything I am missing in order to fulfill my purpose?
2. Given the list of modules above, is there anything else I could further strip out? I suspect that modules such as **block** and **cbc** could be stripped out, among others.

Any input would be greatly appreciated.

Thank you.

PS: congratulations to the authors for this excellent library.

**Comment by randombit** [comment]
1. For RSA you will almost certainly want to also enable `emsa_pkcs1` since in practice almost all X.509 RSA certificates are signed with that format. You might want to also enable SHA-384/SHA-512 (`sha2_64`) since those are sometimes used in ECDSA certificates.

2. Unfortunately it's not possible to further disable beyond what is being configured above. A lot of what is being pulled in (cbc, block, pbkdf2 etc) is because the public key code depends on `pbes2`, which is the encryption scheme used to encrypt private keys. PBES2 in turn pulls in PBKDF2, CBC, etc. If you are going to encrypt private keys, PBES2 is required. However, if you are not it is kind of a bunch of dead weight. It turns out to be easy to make PBES2 optional, and just disable encryption/decryption of private keys in that case. (#1417)

**Comment by DevSidious** [comment]
Sounds like `pbes2` is something I want to keep. Flags for `configure.py` now become:

`--cc=msvc --os=windows --minimized-build --enable-modules=x509,ecdsa,rsa,emsa_pkcs1,sha2_64`

Resulting in:

`INFO: Loading modules: asn1 base base64 bigint block cbc cpuid ec_gfp ec_group ecc_key ecdsa emsa1 emsa_pkcs1 emsa_pssr entropy hash hash_id hex hmac kdf keypair mac mdx_hash mgf1 mode_pad modes mp numbertheory pbes2 pbkdf pbkdf2 pem pk_pad pubkey rng rsa sha1 sha2_32 sha2_64 stream utils x509`

Excellent!  Big thank you @randombit .

**Comment by randombit** [comment]
OK, if you want to use PBES2 you should probably also enable at least one cipher (AES being the best choice for interop).

**Comment by DevSidious** [comment]
And if I build for x86_64 I should probably also enable `aes_ni` and `aes_ssse3`, correct ?

**Comment by randombit** [comment]
Yes. These days you can probably get away with skipping the SSSE3 code since AES-NI is pretty common but having the SSSE3 code around won't hurt unless you really need to shrink binaries to the minimum.

**Comment by randombit** [comment]
A downside of the build being very configurable is that it's basically impossible to test every possible configuration. There is a script that tests the result of disabling any single module, but testing all permutations is not really possible and so sometimes bugs are missed.

In this case, the problem was that if `emsa_pkcs1` was enabled, but a hash function that was being used for one of the tests was disabled (in this case, MD5) a crash would ensue. Should be fixed now, thanks for mentioning

**Comment by DevSidious** [comment]
`botan-test `successfully completes its tests now. Tested on both Windows and Linux, with

`configure.py --cc=msvc --os=windows --minimized-build --enable-modules=x509,ecdsa,rsa,emsa_pkcs1,sha2_64,aes,aes_ni,aes_ssse3`

and

`./configure.py --cpu=x86_64 --os=linux --minimized-build --enable-modules=x509,ecdsa,rsa,emsa_pkcs1,sha2_64,aes,aes_ni,aes_ssse3`

On Windows, `botan-test.exe` completes with `Tests complete ran 83582 tests in 21.58 sec 32 tests failed` while on Linux `botan-test` outputs `Tests complete ran 83584 tests in 17.62 sec 32 tests failed`. **83582** tests on Windows versus **83584** tests on Linux. Is this normal?

**Comment by randombit** [comment]
There are a few time related tests (checking handling of dates post-2038) that are skipped if `time_t` is 32-bit, so if your Windows build is 32-bit that might be why.

**Comment by neusdan** [comment]
Did you see that 32 tests failed?

**Comment by randombit** [comment]
I did. That's the recently added BSI tests, a couple are checking that an MD5-signed cert doesn't verify. Which it doesn't except now instead of validation failing because it is an untrusted hash it fails because its an unknown hash.

Wasn't sure of the right fix, maybe just disable the first couple of tests if MD5 is not in the bulid? Alternately, accept either error as ok.

**Comment by DevSidious** [comment]
Both builds are 64-Bit. I will investigate further and open a new thread, because I don't want to confuse things and diverge too far from the subject.

Thank you for the help. You can close this if you wish.

**Comment by randombit** [comment]
Indeed we're pretty far off the original topic now.
