### ISSUE TITLE
Question: configure.py --with-boost

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1419]
`./configure.py --help`

```
--with-boost                    use boost
```

What are the implications of configuring Botan with Boost? Any advantages/disadvantages/implications of using `--with-boost` configuration option?

**Comment by randombit** [comment]
Don't do it :)

It enables using Boost.filesystem for a couple of operations, but on either Windows or Unix we already have an implementation using the native APIs so there is no real benefit. It also enables using Boost.Asio but that is only used in the command line for a couple of TLS network utils (`tls_proxy` and `tls_http_server`). So in return for a Boost runtime dependency you get a couple of nifty but not essential TLS command line utils.

Previously it also enabled using Boost.date_time for some calendar conversions that otherwise relied on non-portable OS interfaces (this was important for Android among others), but that was removed in 2.4.0 with #1336. And in the old C++98 version it enabled Boost's shared_ptr and a few other things.

I should update the build documentation on this point.

**Comment by randombit** [comment]
Think above answers your question but feel free to reopen if anything is unclear.

**Comment by DevSidious** [comment]
Thank you. :)
