### ISSUE TITLE
CMake (Windows) incorect paths & etc.

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1424]
`configure.py --cpu=x86 --os=windows --cc=msvc --minimized-build --with-cmake`

`cmake CMakeLists.txt`

```
-- Configuring done
CMake Error at CMakeLists.txt:159 (add_library):
  Cannot find source file:

    C:/Git/botan/C:/Git/botan/src/lib/base/scan_name.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at CMakeLists.txt:172 (add_executable):
  Cannot find source file:

    C:/Git/botan/C:/Git/botan/src/cli/asn1.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at CMakeLists.txt:176 (add_executable):
  Cannot find source file:

    C:/Git/botan/C:/Git/botan/src/tests/main.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: botan
CMake Error: CMake can not determine linker language for target: botan_shared
CMake Error: CMake can not determine linker language for target: botan_cli
CMake Error: CMake can not determine linker language for target: botan_tests
-- Generating done
-- Build files have been written to: C:/Git/botan
```

**Comment by randombit** [comment]
CMake build does work for me (on Linux). But I don't have any Windows machine, looks like some problem with how we are generating paths. I don't use the cmake support and it fwiw is really only intended for developers (for using it with IDE integration for those who like such things). Not sure what to suggest besides building via `make` instead.

If you want to try poking at it, the CMake template is in `src/build-data/cmake.in`.

If you can attach the `CMakeLists.txt` plus `build/build_config.json` I might be able to figure out what we're doing wrong but no promises.

**Comment by DevSidious** [comment]
It works for me on Linux too. Here are the files requested: [files](https://my.pcloud.com/publink/show?code=kZxwmH7Z2f8fNUtBy9ki1GGp7o2HbmaGDRPV)

**Comment by DevSidious** [comment]
```
set(BOTAN_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/C:/Git/botan/src/lib/base/scan_name.cpp"
```

results in:

`C:/Git/botan/C:/Git/botan/src/lib/base/scan_name.cpp`

**Comment by randombit** [comment]
I'm not really sure what is happening. It seems like `os.normpath` behaves differently on Windows vs Unix, and returns an absolute path instead of a relative path. Or at least that's my interpretation of things.

Can you try #1425 and see if that helps? CMake build still works fine for me on Linux with that and (I think) it will help the problem you are seeing.

**Comment by ksanderon** [comment]
Regarding using botan with cmake, please have look at: https://gitlab.com/rilis/hell/gates/botan . Maybe you will find it usefull. This repository contain only usable for cmake wrapper around botan native build system with exposed most, if not all possible botan options in cmake way. It works for mac os, linux, windows, ps4, xbox, android, ios and other odd systems which I used to work with.

It support build and install tree, so you can use it with find_package or add_subdirectory.

CMake file in this repo work this way:
* download botan source archive from [official github releases of botan](https://github.com/randombit/botan/releases) (only because of speed reasons, because there could be used botan repo instead but it's quiet big in comparison to release snapshot) using ExternalProject
* check checksum, 
* extract sources in build tree,
* optionally patch makefile template if needed (issues are open for these in botan) 
* convert cmake parameters into form acceptable for configure.py
* execute configure.py, 
* execute generated make, 
* install botan in directory provided in CMAKE_INSTALL_PREFIX, 
* add "fake" cmake targets with defined dependencies using previously generated by make libraries, installed headers etc.
* create hell-botanConfig.cmake in correct one location to be useful for find_package

Currently there is added only 2.4.0 version, but there will be added new one in feature when they will come or older one on users request. 

**Now little bit advert** 😈  

*This is part of bigger project named [hell](https://gitlab.com/rilis/hell/hell), which is essentially decentralized git and cmake oriented dependency manager with semantic versioning for C++ which I'm developing.*

*Because it is not so well known and I cannot expect support for it in many bigger/respected projects there is something like [hell-gates](https://gitlab.com/rilis/hell/gates) which is set of proxy repositories for libraries which do not use cmake or even git but many users might want to use these common libraries in their projects like boost, botan or openssl (or at least I and my friends needed these in some point). So there are created cmake wrappers for these libraries, using their native build systems, which you can also use even if you don't like idea of hell itself. Additionally hell is part of [rilis](https://gitlab.com/rilis) crossplatform and rapid development libraries and tools "family", but this is different story.*

**Comment by DevSidious** [comment]
@randombit, #1425 seems to be it.

`cmake CMakeLists.txt`

```
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.12.25834.0
-- The CXX compiler identification is MSVC 19.12.25834.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Git/botan
```

**Comment by DevSidious** [comment]
@ksanderon thanks for sharing. Your project seems to be really useful. I'll have a look at it.
