### ISSUE TITLE
Shared cross-compile build fails

### ISSUE THREAD

**Issue by aido93** [randombit/botan#1427]
$ ./configure.py --os=mingw --with-openssl --with-zlib --cc-bin=../mxe/usr/bin/x86_64-w64-mingw32.shared-g++ --with-external-includedir=../mxe/usr/x86_64-w64-mingw32.shared/include --without-os-features=threads --with-external-libdir=../mxe/usr/x86_64-w64-mingw32.shared/lib --prefix=../libbotan/

$ make -j7

$ wine botan-test.exe
err:module:import_dll Library LIBEAY32.dll (which is needed by L"Z:\\home\\builder\\botan\\botan-test.exe") not found
err:module:import_dll Library zlib1.dll (which is needed by L"Z:\\home\\builder\\botan\\botan-test.exe") not found
err:module:import_dll Library libgcc_s_seh-1.dll (which is needed by L"Z:\\home\\builder\\botan\\botan-test.exe") not found
err:module:import_dll Library libssp-0.dll (which is needed by L"Z:\\home\\builder\\botan\\botan-test.exe") not found
err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\builder\\botan\\botan-test.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\builder\\botan\\botan-test.exe" failed, status c0000135

**Comment by randombit** [comment]
Sorry about not getting back to you on this.

I'm not really sure what the issue is. I can replicate it. But I'm not sure if we are doing something wrong (and if so, what) or if this is something about MinGW.

**Comment by DevSidious** [comment]
@aido93

I apologize if this is asymptotic to your goals, but you would save a lot of headaches if you just compile with the native compiler of the target platform. In the case of **msvc** you will also get performance benefits. Please ignore any blog or forum thread from N years ago saying otherwise, it's simply not true.

For example LibreSSL is built with **msvc** on windows while OpenSSL is built with mingw (or cygwin, don't remember exactly which one). LibreSSL is orders of magnitude faster than OpenSSL on Windows because of that. 

On Linux both LibreSSL and OpenSSL are built with gcc, OpenSSL outperforming LibreSSL. 

For what is worth.

**Comment by aido93** [comment]
I don't care about performance. I see that libbotan **works** correctly on the target platform even if I cross-compile it with mingw. But I see on the main page of this project that it is recommended to run tests:

`$ ./botan-test
# lots of output...`

Also once I succeeded to run them and all tests are OK even with wine in linux. It means that either it needs to edit documentation or just add to env-variables correct paths to libraries. It was not a headache. But when I did it I forget about this problem...

**Comment by aido93** [comment]
> or if this is something about MinGW.

Rather wine.

**Comment by DevSidious** [comment]
> I don't care about performance.

That's scary bro. : )))

**Comment by randombit** [comment]
Closing this as stale, please open a new issue if some problem remains unresolved.
