### ISSUE TITLE
How to add Subject Alt Names to CSRs? (Missing documentation?)

### ISSUE THREAD

**Issue by albocc** [randombit/botan#1428]
I am trying to create a CSR in Botan with additional SANs and I didn't find any documentation on this in the Botan manual. After looking at the code of the function that creates the CSR, I came up with the following but the resulting CSR doesn't contain any SANs at all:

    Botan::X509_Cert_Options csr_options("example.com/de");

    csr_options.extensions.add(new Botan::Cert_Extension::Subject_Alternative_Name(
            Botan::AlternativeName("","","example.org")));

    Botan::PKCS10_Request csr = Botan::X509::create_cert_req(csr_options, private_key,
            "SHA-256", Botan::system_rng());

What is the correct way to add SANs to a CSR and can you add that to the Botan manual?

**Comment by randombit** [comment]
For setting DNS address in SAN use `csr_options.dns = "example.org"` (I just checked and this works fine).

What you did certainly seems like it would work, right? I did not understand the problem either. Turns out, in `create_cert_req`  (and same problem affects generating self signed certs) the SAN information is loaded from the `dns`, `uri`, `email`, `xmpp` fields of `X509_Cert_Options` and then we create a new SAN extension and stomp on the extension you created. It would be better, in the case that the user explicitly set an extension, to never replace it.

Also this definitely should be better documented, just glanced over this section of the docs and quickly noticed several omissions and small errors.

**Comment by albocc** [comment]
Thanks for the fast reply!

I tried what you suggested and it seems to work great for one SAN. But how can I add an additional SAN, meaning more than one in total? Is that even possible with the current version?

**Comment by randombit** [comment]
You're right it's not currently possible to create a certificate request with multiple SANs of a single type.

Frustratingly we can decode certificates or CSRs containing multiple DNS names just fine, and the underlying code even supports encoding multiple DNS names. Its just the interface provided for creating the requests that is missing this.

I'll post a PR in a bit.

**Comment by randombit** [comment]
I believe #1429 addresses this on the code side, I still need to update the docs though.

**Comment by randombit** [comment]
Still need docs

**Comment by albocc** [comment]
Happy to see this fixed and already merged, that was fast!

**Comment by randombit** [comment]
@albocc Thanks very much for the report, it is sometimes easy on the developer side to miss omissions like this, so user feedback is very useful. If you notice other areas where the API is confusing or seems to be missing something definitely don't hesitate to open up issues.

I've updated the docs a bit now, so I think this can be closed.

**Comment by albocc** [comment]
Thank _you_ for your fast replies and the quick fix! I really appreciate the work you do and I am happy to see this resolved. :+1:
