### ISSUE TITLE
Current master fails tests

### ISSUE THREAD

**Issue by mouse07410** [randombit/botan#1431]
MacOS High Sierra 10.13.3, Xcode-9.2, current master:
```
. . . . .
TLS v1.2 AES-256/GCM client certs ran 18 tests in 1.14 msec 2 FAILED
Failure 1: TLS v1.2 AES-256/GCM client certs got client certs produced unexpected result '0' expected '2'
Failure 2: TLS v1.2 AES-256/GCM client certs client got CA list unexpected result 0 < 2
Note 1: TLS v1.2 AES-256/GCM client certs Session established TLS v1.2 RSA_WITH_CAMELLIA_256_CBC_SHA256 5A6D1F1EE75B74241FD0CD88953CA8009742FDCE59801C0B5F60E41A4109B4EA
Note 2: TLS v1.2 AES-256/GCM client certs Session established TLS v1.2 RSA_WITH_CAMELLIA_256_CBC_SHA256 5A6D1F1EE75B74241FD0CD88953CA8009742FDCE59801C0B5F60E41A4109B4EA
. . . . .
Tests complete ran 2675957 tests in 115.93 sec 2 tests failed
```

**Comment by randombit** [comment]
See it in Travis also, but so far not able to replicate locally.

Does this test fail consistently for you?

**Comment by randombit** [comment]
OK so there is one hint, every time it fails the reported session established ciphersuite does not match what it should be (AES-256/GCM), here `RSA_WITH_CAMELLIA_256_CBC`, in Travis seeing also `ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 `. It's almost like we are resuming an old session instead of creating a new session with client auth.

**Comment by randombit** [comment]
Ah fuck there it is, have to have sqlite3 enabled.

**Comment by randombit** [comment]
Should be fixed now.

**Comment by mouse07410** [comment]
Fix confirmed, thanks!
