### ISSUE TITLE
Questions relating to NEON SIMD and Botan performance on ARM CPUs

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1440]
When Botan's `configure.py` detects NEON CPU features,  `BOTAN_TARGET_SUPPORTS_NEON` is defined.

My ARM build machines have CPUs supporting NEON. However, I can not hold the same presumption when it comes to the machines my code will run on. My code will be distributed as a binary and it does not (and shall not) require to be built from source. 

The easy way out would be to configure Botan with `--disable-neon` and be done with it. However, NEON looks terribly well on paper, therefore the following questions present themselves: 

1. Does Botan really take advantage of NEON SIMD ? Looking through the code I haven't noticed anything special Botan does to take advantage of NEON features. The compiler **should** apply optimizations automatically, but I'm suspicious as how much performance would that squeeze.
2. Is there any data or experience available helping one ascertain the performance penalty (if any) on NEON enabled ARM CPUs induced by configuring Botan with `--disable-neon` ?

**Comment by randombit** [comment]
The main use of NEON right now is wrapped in the SIMD type (https://github.com/randombit/botan/blob/master/src/lib/utils/simd/simd_32.h) which is used for a few algos (Serpent, Noekeon, SHACAL2). It's also used in the code for calling the ARMv8 crypto extensions, but that is only for AArch64. So right now the performance impact is pretty minimal. No double we'll use it more in the future (for example for ChaCha, AES, GCM, ...) but right now most of the CPU specific optimizations are x86 simply because that's what I tend to be working with.

All uses of NEON are gated with runtime checks, either getauxval on Linux/Android, or machine-name matching on iOS. So you should be able to enable NEON in your build and everything will work. But, with your configuration I don't think NEON is used at all anyway, so you could just disable it completely and then not worry about it.

**Comment by DevSidious** [comment]
@randombit 
Your comment certainly clarified things greatly. Thank you.
