### ISSUE TITLE
Amalgamation does not amalgamate pkcs11.h , pkcs11f.h and pkcs11t.h

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1447]
`configure.py --disable-shared-library --amalgamation --single-amalgamation-file` produces at build time (ouside of Botan's source dir):

`botan_all.h(20100): fatal error C1083: Cannot open include file: 'pkcs11.h': No such file or directory`

`botan_all.h` line **20100**:

`#include "pkcs11.h"`

`pkcs11.h` in turn requires `pkcs11f.h` and `pkcs11t.h`

Is this by design?

**Comment by randombit** [comment]
I'm honestly not sure if this is intended behavior or not. @neusdan ?

It's caused because these headers are considered external (they are vendor headers that we include in the source). a56f569a202 introduced the external header notion and made changes to support amalgamation with pkcs11 but maybe something has regressed. I'm not really sure what the intended handling is nor do I recall the reasoning wrt the external header distinction.

**Comment by neusdan** [comment]
> and made changes to support amalgamation with pkcs11 but maybe something has regressed

I don't think this is a regression. The amalgamation build of botan itself still works because `build\include\external` is set as a include path. But if you use `botan_all.h` outside of the Botan build itself, yes then it does only work if the PKCS#11 headers are available.

I'm not a Amalgamation build user and not sure if we want to include the PKCS#11 headers there or not. Shipping the headers has the disadvantage that it can conflict if someone uses their own or an other version of the PKCS#11 headers. On the other side we have the advantage that we ship the version of the headers which was used during development of the PKCS#11 module and which is tested.

**Comment by DevSidious** [comment]
@neusdan 
> But if you use botan_all.h outside of the Botan build itself

That is in fact the case for the scenario described in the opening. I have Botan amalgamation files included in my own project.
