### ISSUE TITLE
[FEATURE] PKCS12/PFX support

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1449]
Support **PKCS12**. That is to say, add functionality to support loading of certificates and private keys from **PKCS12** formatted data and dumping of certificates and private keys to **PKCS12** formatted data.

**I am willing to financially support the development effort.**

What say ye? Anyone interested?

**Comment by randombit** [comment]
I have heard @securitykernel and company have some interest in supporting PKCS12 but I don't know what their timeline is. I emailed him pointing to here, but he likely will not see my mail before Monday. If a patch is not coming from them in the near future, I do take on funded dev projects so that's an option.

My opinions on PKCS12 are mostly unprintable, but it is commonly used so probably worth supporting given botan's general goals.

**Comment by DevSidious** [comment]
Thanks @randombit . Works for me. How would you define **the near future** ? :)

**Comment by randombit** [comment]
OK so turns out R&S has deferred working on PKCS12 support. So if this is something you really want, the options would be to fund the development or of course do it yourself. If you are interested in having me do it, drop me an email (`jack@randombit.net`) and we can work out the specifics.

**Comment by DevSidious** [comment]
Thanks. I'll get back at you ASAP.
