### ISSUE TITLE
Strange ECDSA certificate behavior

### ISSUE THREAD

**Issue by xentec** [randombit/botan#1480]
I have written a small [program][1] using Botan 2.4 which generates a CA and signed certificates for my website. Having nginx running with default TLS settings I've encountered ciphersuite mismatch error from Chromium, Firefox and nginx:
```
SSL_do_handshake() failed (SSL: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher) while SSL handshaking [...]
```
Expected error was `untrusted certificate`, which actually only `curl` is able to give after somehow finding a ciphersuite. Here is a test domain with said problem https://test.gated.space.

Speculating that I failed to sign the certificates, I've used the `botan` CLI tool to create and send a CSR to Let's Encrypt as follows:
```
botan keygen --algo=ECDSA --params=secp256r1 > key.pem
botan gen_pkcs10 key.pem test.gated.space --country=DE --emsa=EMSA1 > csr.pem
dehydrated -d test.gated.space -s csr.pem 
```
(btw: gen_pkcs10 is unable to select the right EMSA for ECDSA with SHA-256)
However Let's Encrypt was unable to parse my CSR
```
 + Requesting challenge for test.gated.space...
 + Responding to challenge for test.gated.space...
 + Challenge is valid!
 + Requesting certificate...
  + ERROR: An error occurred while sending post-request to https://acme-v01.api.letsencrypt.org/acme/new-cert (Status 400)

Details:
{
  "type": "urn:acme:error:malformed",
  "detail": "Error parsing certificate request: x509: failed to unmarshal elliptic curve point",
  "status": 400
}
```
which brings me to believe there is a strange error somewhere ECDSA module.
Botan was compiled with standard modules and without external providers.

[1]: https://gist.github.com/xentec/f709ecf2582dd0f7288ea9be45d3b533

**Comment by randombit** [comment]
The "failed to unmarshal elliptic curve point" seems to be coming from Golang's standard library. This makes sense since Lets Encrypt's CA server (Boulder) is written in Go. I just checked and Go does not support compressed ECC keys, which is what Botan uses by default. That's unfortunate. We'll probably need to add some options so it is possible to create a key, cert, pkcs10 request etc using uncompressed. Or just give up and switch to uncompressed by default :/ Looks like there was at least one attempt to add point compression, but was abandoned https://go-review.googlesource.com/c/go/+/1883

Thanks for mentioning the problem with ECDSA + gen_pkcs10. Looks like that got introduced when RSA-PSS support was added.

I'm not sure what is going on with the no shared cipher. I haven't used ECDSA certs in nginx before, maybe something with default settings is wrong for that. Does the same configuration work if you, say, generate an ECDSA key/cert using OpenSSL?

**Comment by xentec** [comment]
>Does the same configuration work if you, say, generate an ECDSA key/cert using OpenSSL?
Yes, you can see it here now: https://test.gated.space. The expected 'CERT_AUTHORITY_INVALID' error is shown.

**Comment by randombit** [comment]
OK that's interesting.

OpenSSL understand compressed points fine. But possible there is something else in nginx that does not like them. In which case it would perhaps decide it had no keys at all available to use, refuse to negotiate any ECDSA ciphersuites, and then find it had no ciphersuites left, then the handshake error.

Can you try this: edit src/lib/pubkey/ecc_key/ecc_key.cpp around line 71 there is

```
std::vector<uint8_t> EC_PublicKey::public_key_bits() const                                                                                                                                     
   {                                                                                                                                                                                           
   return unlock(EC2OSP(public_point(), PointGFp::COMPRESSED));                                                                                                                                
   }
```

Change `COMPRESSED` to `UNCOMPRESSED`. Recompile, and regenerate your key/cert.

**Comment by xentec** [comment]
This indeed did fix it.

**Comment by randombit** [comment]
OK interesting for you to hit not one but two different software systems where compressed EC keys cause problems. Sorry about that. This is probably a good sign we should switch to uncompressed by default.

**Comment by randombit** [comment]
With #1483 the issues you were having should be resolved. ECC public keys are encoded as uncompressed by default. Thank you very much for the report!
