### ISSUE TITLE
Should I reuse an RNG or can I create new ones?

### ISSUE THREAD

**Issue by theom** [randombit/botan#1500]
Hi

A quick question on proper RNG usage:

Let's say I have a class that uses Botan and I create several thousand instances of it. Is it less secure for my class to create its own instance of an RNG (e.g. AutoSeeded_RNG) compared to having a central RNG instance that I pass to each class instance?

Thanks,
JP

**Comment by randombit** [comment]
The security should be identical (though with some caveats).

The userspace RNGs are designed so that even if an attacker saw many gigabytes of the output and/or was able to provide seeding material for the RNG, they would remain secure (in the sense that output the attacker had not seen could still not be guessed any easier than a brute force) as long as some amount of good seeding material was used at some point. So sharing the RNG should be fine.

The biggest danger to sharing is that the RNG objects are *not serialized* so if you were using the same object across multiple threads it must be locked (eg using `Serialized_RNG`). However in that case it is much better to have an RNG per thread/class since otherwise the shared RNG object acts as an unnecessary contention point.

However this answer assumes that there are no bugs in the RNG implementations and that the implemented RNG design (HMAC_DRBG) is as secure as we currently believe them to be. If you want to be conservative (eg this system is protecting money, PII, healthy/safety) I'd still go for an RNG per instance, simply since it is one less thing to go wrong.

However creating an 1000s of RNGs could get (somewhat) expensive because of reseeding. Basically every AutoSeeded_RNG will be periodically reseeding and polling /dev/random, etc.  If this becomes an issue one thing you can do is set up a hierarchy of RNG instances, eg (untested code):

```
Entropy_Sources sources({"system_rng", "rdseed", "rdrand", "system_stats"});
AutoSeeded_RNG master_rng(sources);

AutoSeeded_RNG sub_rng1(master_rng);
AutoSeeded_RNG sub_rng2(master_rng);
```

Here the master_rng will reseed automatically from the system sources, and the sub RNGs will reseed from the master RNG.

Sorry for the somewhat complicated answer to a simple question. I'll try to improve the docs to explain these issues better.

**Comment by theom** [comment]
Thanks for the detailed answer - the more information the better.

Good point about having to serialize the access if the RNG is shared between multiple threads.  In my case I am using one thread for all the instances so no danger there. I was more concerned about the quality of the random numbers if I was constantly creating new RNG instances. Good to know that it's ok to do that.

The RNG hierarchy is also an interesting solution to solve the seeding overhead but my goal is to not having to pass along an RNG all the time when creating new instances. I don't think the hierarchy solves that since I still have to pass along the sub RNGs.

What I'm actually doing is wrapping the TLS server and client classes with a socket class and I guess I'll have to weigh in the reseeding cost with respect to how long each connection stays up. Is reseeding based on time, how many numbers the RNG has returned or something else?

**Comment by randombit** [comment]
Automatic reseeding is currently based on the number of bytes output. You can configure the exact value with the `reseed_interval` param to `AutoSeeded_RNG`, if `0` then automatic reseeding is disabled. It will of course still seed the first time, or if requested by the application using `rng.reseed()` but not otherwise. Reseeding if more than some time interval has passed since the last reseed operation is not implemented, though we may add this in the future.

For modern TLS ciphersuites such as GCM or ChaCha20, the RNG is not used after the handshake completes. However if you are negotiating a CBC ciphersuite, a new random IV is generated for each TLS record sent. So the best thing to do for TLS might be this - create an AutoSeeded_RNG per session with `reseed_interval` of zero (disabling automatic reseeds). This avoids reseeding potentially multiple times during the handshake process. Then after the handshake completes, perform an explicit reseed, which prevents someone who discovers a (extremely unlikely) attack on HMAC_DRBG from backtracking to the RNG state that was used during the handshake.

I guess I should mention you can also just use `system_rng()` everywhere and not worry about it too much.

**Comment by theom** [comment]
I'm not using the CBC ciphers so it's good to know that I can disable the reseeding of the RNGs the TLS connections are using.

I didn't know about `system_rng()` which is a nice alternative. Thanks.
