### ISSUE TITLE
Subject_Key_ID vs Authority_Key_ID constructors

### ISSUE THREAD

**Issue by DevSidious** [randombit/botan#1539]
Based on my understanding, the _Subject Key Identifier_ is a **SHA-1** hash of a given certificate's **public key**. The _Authority Key Identifier_ is a **SHA-1** hash, of the signer's **public key**.

**Subject_Key_ID**, requires a hashing function name:

`Subject_Key_ID(const std::vector<uint8_t>& public_key, const std::string& hash_fn);`

**Authority_Key_ID** doesn't require a hashing function name:

`explicit Authority_Key_ID(const std::vector<uint8_t>& k) : m_key_id(k) {}`

Question:

Why the extra parameter (hash_fn) for **Subject_Key_ID** ?

**Comment by randombit** [comment]
The SKID can be an arbitrary value / of arbitrary length. The SHA-1 of the key is the typical usage but this is just a common convention.

Basically `Subject_Key_ID` consumes the public key and hashes it with the specified function. The result is taken as the SKID. The AKID must always take the same value as the SKID in the issuing certificate (otherwise it doesn't work) whereas when `Subject_Key_ID` constructor is called it is because we are creating a new SKID and we can choose any value we like. (For example we could generate SKIDs completely at random.) Instead we hash the public key with the same hash function which is being used to sign the certificate.

**Comment by DevSidious** [comment]
Makes sense now. Thank you @randombit.
