### ISSUE TITLE
Policy does not allow any available cipher suite, if policy says “allowed_key_exchange_methods=RSA”

### ISSUE THREAD

**Issue by louiz** [randombit/botan#1558]
If we use a TLS policy that only allows RSA for the allowed_key_echange_methods, then creating a TLS::Client will fail with `Exception("Policy does not allow any available cipher suite")`` being thrown.

Can be reproduced with 
```
echo "key_exchange_methods = RSA" > weak_rsa.txt
botan tls_client irc.ppirc.net --port=6697 --policy=weak_rsa.txt
```
See #1038 for more context.

- Shouldn’t that be a Botan::TLS::TLS_Exception instead of Botan::Exception?
- This used to work (I think it happens only with botan >= 2.5, or maybe 2.6), what changed? I guess it’s a bug since the documentation still states that “RSA” is a valid value for this option, and I don’t see any changelog entry that talks about it being removed.
- We can’t connect to irc.ppirc.net anymore, at all. Because without that policy the negociation fails too (see #1038).

**Comment by randombit** [comment]
To enable RSA encryption based ciphersuites you also need to specify

`signature_methods = IMPLICIT`

(or `signature_methods = ECDSA RSA IMPLICIT` to additionally allow standard RSA/ECDSA signature ciphersuites).

IMPLICIT here meaning "the authentication is implicitly done by the key exchange". This was added to distinguish negotiating a truly anonymous ciphersuite (DH/ECDH) vs a ciphersuite that authenticates but does so via the key exchange rather than a signature.

This should have been better documented, sorry. This was introduced in #1285 so 2.5.0 onwards requires the change.

**Comment by louiz** [comment]
Thank you very much, I'll use that.
