### ISSUE TITLE
Which version that support windows XP ??

### ISSUE THREAD

**Issue by luis506** [randombit/botan#1577]
Gentlemens, 
which versions support windows XP , and  how to build it using MSVC ?

**Comment by randombit** [comment]
XP is not tested by us since it is EOLed by Microsoft. It may work. (I am at least not aware of any specific things that would prevent it from working.) I'd suggest first trying latest release (2.6), if that doesn't work try the last 1.10 release.

Re compilation, https://botan.randombit.net/manual/building.html should explain everything.

For 2.x we require at least MSVC 2013.

**Comment by randombit** [comment]
Feel free to open an issue if you run into any build problems.
