### ISSUE TITLE
dllexport on MS Windows

### ISSUE THREAD

**Issue by TempusFugitful** [randombit/botan#1613]
Hello,

I have been trying to get the botan.dll to play with the same AES decryption program found here: 

https://botan.randombit.net/manual/block_cipher.html

I followed the instructions to run configure.py and nmake for Windows (a Windows 10 environment).

The botan.dll build successfully. Then I import the DLL into my VS sample program (again, a simple copy/paste of the program found above, except changing the headers to the "botan_all.h". Visual studio builds the program successfully. However, when I attempt to execute the program, I get the error "The application was unable to start correctly."

I used dumpbin to try to determine if the problem was missing dependencies (things that botan.dll itself depends upon). I also checked my environment variables to make sure that both the VS program and the botan build environment were using the same msvc compiler and linker.

I am able to utilize the static library (botan_all.obj) successfully. So I have a path forward with this API. However, I am puzzled as to why I can't get the DLL to work in VS2017. Looking through "botan_all.h" I couldn't find any __declspec(dllexport) attributes. BOTAN_DLL macro is defined as __declspec(dllimport). Shouldn't a dllexport attribute be necessary for consuming exes?

Sincerely,
Mario

**Comment by randombit** [comment]
> However, when I attempt to execute the program, I get the error "The application was unable to start correctly."

Are you sure the DLL and your application were built with the same runtime? Because Botan exposes an API that uses STL types, the same runtime used by the library must be also used by all calling applications. Often it seems a mismatch manifests with a crash.

The default runtime for the library is `/MD`, you can set it to some other value with `--msvc-runtime` ala `--msvc-runtime=MT`.

> Looking through "botan_all.h" I couldn't find any __declspec(dllexport) attributes. BOTAN_DLL macro is defined as __declspec(dllimport). Shouldn't a dllexport attribute be necessary for consuming exes?

This is because when the library is build, the makefile sets flag `/DBOTAN_DLL=__declspec(dllexport)`which overrides the macro set in the header. So when the library code is compiled, it is set for dllexport, but then when consuming applications read the header it is set as dllimport.

**Comment by TempusFugitful** [comment]
In the Visual Studio project properties, I have the Runtime Library option set to Multi-threaded DLL (/MD).  It is in Release mode x86.

Here is the command I use for configuring:

python configure.py --minimized-build --enable-modules=aes --amalgamation --single-amalgamation-file --cpu=x86_32 --cc=msvc

The botan-test.exe always works fine, so I know that it is building okay. I agree that it very much looks like a runtime mismatch. But when I execute "cl" in the VS2017 command prompt, it shows the same version that VS does when I type it into the console there.

Perhaps I still haven't located some sort of environment variable mixup.

**Comment by TempusFugitful** [comment]
I was able to resolve this issue. It was a problem with my PATH variable.

**Comment by randombit** [comment]
Glad to hear. Closing this issue.
