### ISSUE TITLE
cannot convert 'const char*' to 'LPCWSTR {aka const wchar_t*}' for argument '1' to 'void* FindFirstFileW(LPCWSTR, LPWIN32_FIND_DATAW)'

### ISSUE THREAD

**Issue by doctor-yes** [randombit/botan#1615]
Hi, I got this error: cannot convert 'const char*' to 'LPCWSTR {aka const wchar_t*}' for argument '1' to 'void* FindFirstFileW(LPCWSTR, LPWIN32_FIND_DATAW)'
       HANDLE dir = ::FindFirstFile((cur_path + "/*").c_str(), &find_data);
                                                                         ^
from the code below in \src\lib\utils\filesystem.cpp line 123:

std::vector<std::string> impl_win32(const std::string& dir_path)
   {
   std::vector<std::string> out;
   std::deque<std::string> dir_list;
   dir_list.push_back(dir_path);

   while(!dir_list.empty())
      {
      const std::string cur_path = dir_list[0];
      dir_list.pop_front();

      WIN32_FIND_DATA find_data;
      HANDLE dir = ::FindFirstFile((cur_path + "/*").c_str(), &find_data);

      if(dir != INVALID_HANDLE_VALUE)
         {
         do
            {
            const std::string filename = find_data.cFileName;
            if(filename == "." || filename == "..")
               continue;
            const std::string full_path = cur_path + "/" + filename;

            if(find_data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
               {
               dir_list.push_back(full_path);
               }
            else
               {
               out.push_back(full_path);
               }
            }
         while(::FindNextFile(dir, &find_data));
         }

      ::FindClose(dir);
      }

   return out;
}

Am I missing something? Thanks a lot.

**Comment by randombit** [comment]
Maybe this should be `FindFirstFileA`?

**Comment by doctor-yes** [comment]
After changing 
  WIN32_FIND_DATA find_data;  -->  WIN32_FIND_DATAA find_data; 
  HANDLE dir = ::FindFirstFile((cur_path + "/*").c_str(), &find_data); --> HANDLE dir = ::FindFirstFileA((cur_path + "/*").c_str(), &find_data);
  while(::FindNextFile(dir, &find_data));  -->  while(::FindNextFileA(dir, &find_data));

the code compiles ok. Thanks for the help. Maybe this can be handled in the original code so user don't need to make these changes in future versions...

**Comment by randombit** [comment]
Thanks for confirming the fix. I'll address this for upcoming 2.7.0 release

**Comment by neusdan** [comment]
I think this is not the right fix. The user should decide by defining UNICODE if the Unicode or ANSI versions of the Windows API should be used.

**Comment by randombit** [comment]
I agree with you in the broad sense, but in this specific situation it doesn't seem to make much sense. The signature being implemented is `std::vector<std::string> get_files_recursive(const std::string& dir)`, so to use Unicode API we'd have to accept UTF-8 in `std::string`, convert to UTF-16, call Unicode API, convert results back to UTF-8 to put into vector of `std::string` ... and then the results are useless because Windows apparently doesn't accept UTF-8 in system calls taking `char*`. (?!?) So doesn't really get us anywhere.

Most uses of this function are in the tests to read data files (which all use plain ASCII filenames), only use in the library is a convenience method to `Certificate_Store_In_Memory` to load all certs in a directory. But if (AIUI) Windows doesn't accept UTF-8 in `fopen` and company, presumably `ifstream` also doesn't. So even if we have the Unicode name (or translatable equivalent) it does us no good, because our code for opening the file and reading the contents will not work.

**Comment by neusdan** [comment]
I understand that for the tests it's not really useful but for the certificate store I'm pretty sure it is. Especially for certificates which at least in our usecases have often as filename the name of a person containing umlauts and so on.

On Windows there is _wfopen for example but that's not portable. Maybe we can use something like boost filessystem our std filesystem instead of writing the handling our own.

**Comment by randombit** [comment]
> Especially for certificates which at least in our usecases have often as filename the name of a person containing umlauts and so on.

Fair, but supporting this case is actually a much larger issue than just this one function. For example all of the constructors or other functions taking a pathname do so via a `std::string`; none of these functions can accept a UTF-8 path on Windows.

Some options, though none of them particularly appealing

 - For Windows Unicode builds only, add equivalent `std::wstring` overloads. Adds a lot of noise, very likely to rot or be missed when adding new functions.
 - Change `std::string` arguments representing a pathname to some typedef (FsPath or whatever) which for Windows Unicode builds is `std::wstring` instead of `std::string`. Downside, breaks client applications that expected to use `std::string` and probably brings in some fun ABI issues. [However, changing these args to a FsPath typedef of `std::string` does help document intent and will make it easier to find such uses for converting to C++17 filesystem lib down the road, just think having it sometimes be `wstring` is asking for problems.]
 - Write a DataSource_Stream variant (or maybe just a constructor overload?) that uses the Windows APIs to read files with Unicode names. Since most? functions within the library taking a pathname alternately accept a `DataSource&` that works without having to change many places in the library. Applications would need to explicitly know to use this special data source to get Unicode support (but, that's also the case for anything requiring the application to use `wstring`).
 - Adopt C++17 filesystem, hope that this resolves the problem (I have no idea if it actually does). It at least gives us a proper path type. Unfortunately not really an option until 3.x. And we can't add a hard dependency on Boost.

Most palatable to me in short term would be the `DataSource` variant because it isolates the system specific issues in one location.

I think I am going to merge #1616 as-is since the current status with -DUNICODE is it just doesn't build, which doesn't do anyone any favors. Actually properly supporting Unicode filenames on Windows is another issue, which should certainly be resolved, but which I do not have the time or interest to look at right now.

**Comment by doctor-yes** [comment]
Just want to add that UNICODE was defined when I got that error. I tried to define it again right before the function but still got the error, and there is a warning saying that UNICODE is redefined...
