### ISSUE TITLE
FPE question - In what base should the number be passed for encryption and what base is it returning?

### ISSUE THREAD

**Issue by erotavlas** [randombit/botan#165]
I just want to verify what base the encryption is working in for the Format Preserving Encryption module.  I'm guessing that it is taking an integer of base 10 and returning an encrypted number of base 10.  In which case if my initial number is in another base, I must convert first to base 10 before encrypting? Is this correct?

**Comment by randombit** [comment]
Sorry about the long wait here. The base does not matter. FPE encrypts to and from integers mod N where N is the maximum value you want to encrypt. So for example if you are encrypting US Social Security Numbers (format 123-45-6789) you would choose N=1000000000 because the max possible SSN would be 999-99-9999 

You would not want to encrypt each digit independently, because then you've just created a simple substitution code.
