### ISSUE TITLE
Should any algorithms be removed prior to 2.0?

### ISSUE THREAD

**Issue by randombit** [randombit/botan#167]
Some of the algorithms in botan are obscure, obsolete, or outright broken and we should consider removing them (as has been done in past releases for various also-ran algorithms of the 90s like SHARK and HAVAL). Doing so prior to the 2.0 release would be the logical choice.

The maintenance burden of having these algorithms available is not high (really, almost zero), but it creates additional confusion for the user about what they might want to use, and by the very fact it is implemented and available at all leaves it possible for an application to potentially be tricked into using an insecure algorithm. Botan may be a kitchen sink, but it ideally would be a highly focused kitchen sink containing only the best available crypto primitives for any purpose.

Looking things over, the short list for removal would be Nyberg-Rueppel signatures, MARS, RC2, RC5, RC6. HAS-160, TEA, XTEA, SAFER, Lion, MD2, MD4, CBC-MAC, and X9.19-MAC. MD5 would be on the list too, but is still just too commonly used, and I'm on the fence about TEA/XTEA since they are somewhat common also and not (AFAIK) broken.

Are there good reasons to keep any of these algorithms? For example are there protocols or formats that would be useful to support which make use of any of them? And are there additional algorithms that we should consider for removal?

**Comment by mouse07410** [comment]
I say NO - we do not remove anything unless there is a good reason to. I see no “additional confusion for the user” at all.


On Jul 3, 2015, at 13:52 , Jack Lloyd <notifications@github.com<mailto:notifications@github.com>> wrote:


Some of the algorithms in botan are obscure, obsolete, or outright broken and we should consider removing them (as has been done in past releases for various also-ran algorithms of the 90s like SHARK and HAVAL). Doing so prior to the 2.0 release would be the logical choice.

The maintenance burden of having these algorithms available is not high (really, almost zero), but it creates additional confusion for the user about what they might want to use, and by the very fact it is implemented and available at all leaves it possible for an application to potentially be tricked into using an insecure algorithm. Botan may be a kitchen sink, but it ideally would be a highly focused kitchen sink containing only the best available crypto primitives for any purpose.

Looking things over, the short list for removal would be Nyberg-Rueppel signatures, MARS, RC2, RC5, RC6. HAS-160, TEA, XTEA, SAFER, Lion, MD2, MD4, CBC-MAC, and X9.19-MAC. MD5 would be on the list too, but is still just too commonly used, and I'm on the fence about TEA/XTEA since they are somewhat common also and not (AFAIK) broken.

Are there good reasons to keep any of these algorithms? For example are there protocols or formats that would be useful to support which make use of any of them? And are there additional algorithms that we should consider for removal?

—
Reply to this email directly or view it on GitHub<https://github.com/randombit/botan/issues/167>.

--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by cordney** [comment]
I'd vote for removing these algorithms. Removing obsolete and insecure algorithms is a common practice and should be practiced even more in the post-snowden era. If I'll go for a crypto library these days I'll choose one that is not unnecessarily bloated with algorithms that are seldomly used and/or do not meet current standards of what is considered to be secure. IMHO this is a great chance for botan to take a huge step forward.

@mouse07410 I would turn the argument around and say: We do not keep these unless there is a good reason to. Can you give a reason?

**Comment by mouse07410** [comment]
Removing insecure algorithms is a common practice. But this is the first time I see a reference to "obsolete" ones. I'd argue that there is no such thing. I hope you don't claim to know exactly how much each algorithm is used, by who, and for what purpose? Nor, I hope you'd try to say that this library should only address the needs of the "majority", so if for whatever reasons (that are mine alone and not for you to judge) I choose to use an algorithm A, I shouldn't be allowed that freedom because ten times more people settled on using B?

I say that as long as the algorithm is EITHER secure OR widely used, it should stay in the library. For the insecure ones that stay in the library because it is impractical yet to remove them (and I hope there aren't many of them), a warning should be present.

@Rene, what's a good reason to keep algorithms other that state-standardized? The majority of users (businesses and militaries) can use only what their states "blessed". All the other crypto users combined would number as distant second... Keep AES in and remove all the other current block ciphers - they only serve to confuse users. Maybe add Grasshopper and Kalyna if they prove to be secure. :-)

Sent from my iPad

On Jul 3, 2015, at 17:57, René Korthaus <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd vote for removing these algorithms. Removing obsolete and insecure algorithms is a common practice and should be practiced even more in the post-snowden era. If I'll go for a crypto library these days I'll choose one that is not unnecessarily bloated with algorithms that are seldomly used and/or do not meet current standards of what is considered to be secure. IMHO this is a great chance for botan to take a huge step forward.

@mouse07410<https://github.com/mouse07410> I would turn the argument around and say: We do not keep these unless there is a good reason to. Can you give a reason?

**Comment by webmaster128** [comment]
Botan is not a cryptography museum.

Since code is constantly evolving in terms of code style and scenarios how it is build, a piece of code is touched again and again and again over the years, so keeping any line of code is costy. A great example was making the library ready for the use of debug STLs #125 or making the library compile with only some modules enabled #148. Thus there is value in removing code.

I also argue against leaving an algorithm in the library just because it is secure. There might be algorithms that are as secure as AES but slower, more memory consuming, less researched. So as long as an algorithm has no advantage over the ones commonly used, drop it. If the advantage plays out in rare edge cases, that would be a reason to keep it. E.g. if an algorithm is much slower but consumes less memory, that might be useful for some users. A good set of criteria are [the ones used in the AES competition](http://csrc.nist.gov/publications/nistbul/itl97-02.txt):

* security (i.e., the effort required to cryptanalyze),
* computational efficiency,
* memory requirements,
* hardware and software suitability,
* simplicity,
* flexibility, and
* licensing requirements

or [Status Report on the First Round of the SHA-3 Cryptographic Hash Algorithm Competition – 2.2 Evaluation Criteria](http://csrc.nist.gov/groups/ST/hash/sha-3/Round1/documents/sha3_NISTIR7620.pdf).

I'd keep MD5 because it has been so popular that it will be used for decades in legacy applications and scenarios where security is not important (e.g. Gravatar URLs, download checksums). The rest of the algorithms I never heard of.

**Comment by mouse07410** [comment]
How do you define "commonly used"? E.g. is BLAKE2 "commonly used"?

Sent from my iPad

On Jul 6, 2015, at 03:58, Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:


Botan is not a cryptography museum.

Since code is constantly evolving in terms of code style and scenarios how it is build, a piece of code is touched again and again and again over the years, so keeping any line of code is costy. A great example was making the library ready for the use of debug STLs #125<https://github.com/randombit/botan/issues/125> or making the library compile with only some modules enabled #148<https://github.com/randombit/botan/pull/148>. Thus there is value in removing code.

I also argue against leaving an algorithm in the library just because it is secure. There might be algorithms that are as secure as AES but slower, more memory consuming, less researched. So as long as an algorithm has no advantage over the ones commonly used, drop it. If the advantage plays out in rare edge cases, that would be a reason to keep it. E.g. if an algorithm is much slower but consumes less memory, that might be useful for some users. A good set of criteria are the ones used in the AES competition<http://csrc.nist.gov/publications/nistbul/itl97-02.txt>:

  *   security (i.e., the effort required to cryptanalyze),
  *   computational efficiency,
  *   memory requirements,
  *   hardware and software suitability,
  *   simplicity,
  *   flexibility, and
  *   licensing requirements

or Status Report on the First Round of the SHA-3 Cryptographic Hash Algorithm Competition – 2.2 Evaluation Criteria<http://csrc.nist.gov/groups/ST/hash/sha-3/Round1/documents/sha3_NISTIR7620.pdf>.

I'd keep MD5 because it has been so popular that it will be used for decades in legacy applications and scenarios where security is not important (e.g. Gravatar URLs, download checksums). The rest of the algorithms I never heard of.

**Comment by randombit** [comment]
@mouse07410 I think the distinction is "is commonly used now" (AES, SHA-2, etc) or "might be commonly used in the future" (BLAKE2) vs "never commonly used now, and unlikely to be in the future"  even though having no security issues (for example Lion, MARS, RC6)

**Comment by mouse07410** [comment]
I see your point. I’m sure you appreciate how shaky the “might be commonly used” guesses/assumptions are.

It seems to me that there is neither pressure nor need to prune the algorithm tree now. In fact, there’d probably be a benefit of adding more (e.g. new Russian standard “Grasshopper” and new Ukrainian standard “Kalyna”)… Not to mention adding protocols such as HMQV and FHMQV...


On Aug 27, 2015, at 10:13 , Jack Lloyd <notifications@github.com<mailto:notifications@github.com>> wrote:

@mouse07410<https://github.com/mouse07410> I think the distinction is "is commonly used now" (AES, SHA-2, etc) or "might be commonly used in the future" (BLAKE2) vs "never commonly used now, and unlikely to be in the future" even though having no security issues (for example Lion, MARS, RC6)

—
Reply to this email directly or view it on GitHub<https://github.com/randombit/botan/issues/167#issuecomment-135447040>.

--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by randombit** [comment]
Closing, all done for 2.0 with this
