### ISSUE TITLE
Add support for Curve25519 via botan_privkey_load_ecdh()

### ISSUE THREAD

**Issue by tobiasbrunner** [randombit/botan#1680]
Would it be possible to add support for Curve25519 via `botan_privkey_load_ecdh()`?

The name `curve25519` is already supported via `botan_privkey_create_ecdh()`, however, we have existing test vectors that load a specific private key, which currently fails.

**Comment by randombit** [comment]
This is a little strange because that function takes a multi precision integer as the secret value, while x25519 secret is normally treated as a bytestring (which is IIRC the little-endian encoding of the secret scalar). But since `create_ecdh` already supports it this way probably best to be as consistent as possible.

Can you post a link to your test data?

**Comment by tobiasbrunner** [comment]
Yeah, I noticed the different types (`BigInt` vs. `secure_vector<uint8_t>`), which is why I didn't start working on a PR. The test vector we have is from [RFC 8031](https://tools.ietf.org/html/rfc8031) (https://github.com/strongswan/strongswan/blob/master/src/libstrongswan/plugins/test_vectors/test_vectors/curve25519.c).

**Comment by randombit** [comment]
Just a fyi, the test given doesn't seem to appear in RFC 8031 as best I can tell. It does however appear in RFC 8037 "CFRG Elliptic Curve Diffie-Hellman (ECDH) and Signatures in JSON Object Signing and Encryption (JOSE)"

Would it be possible within strongSwan to, instead of using `botan_privkey_load_ecdh`, make use of a (currently unwritten) `botan_privkey_load_x25519` which consumes an array of 32 bytes? We already have similar functions for Ed25519 keys. That would in any event be more consistent with standard usage of x25519, so even if we also extend `botan_privkey_load_ecdh` there should be an x25519 specific function also.

**Comment by randombit** [comment]
#1681 adds support for `botan_privkey_load_x25519` and co. Let me know if you think there is still a need for an integer based function.

**Comment by tobiasbrunner** [comment]
> Just a fyi, the test given doesn't seem to appear in RFC 8031 as best I can tell. It does however appear in RFC 8037 "CFRG Elliptic Curve Diffie-Hellman (ECDH) and Signatures in JSON Object Signing and Encryption (JOSE)"

Interesting, I saw the comment in our file and the test vector in Appendix A of RFC 8031, I didn't compare the actual values. I guess that gives us a second test vector :)

> Would it be possible within strongSwan to, instead of using botan_privkey_load_ecdh, make use of a (currently unwritten) botan_privkey_load_x25519 which consumes an array of 32 bytes?

Yes, absolutely. Thanks for adding the functions.
