### ISSUE TITLE
Decoding exception message unclear

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#1714]
In 56468f8a389350516de67005c8e780c4f7743aab, the `Decoding_Error(const std::string& name)` ctor was changed such that it calls the base class `Invalid_Argument` ctor only with `name`. Previously, it prepended `Decoding error:` before `name`. Was this intended? I accidentally tried to decrypt the wrong file using AES-CBC and the exception message I got was just "AES-128/CBC/PKCS7", which looks a bit weird.

**Comment by randombit** [comment]
The change was intentional, to avoid duplicated text in situations where decoding error is repeatedly caught then annotated with further information, compare eg

"Invalid argument Decoding error: CERTIFICATE decoding failed: Invalid argument Decoding error: Unknown X.509 cert version 5"
vs
"CERTIFICATE decoding failed with Unknown X.509 cert version 5"

(I think there were even cases where "Invalid argument Decoding error" got repeated 3 times)

But I agree the exception message here is not helpful. I just grepped over all throws of `Decoding_Error` and `Invalid_Argument` and this one (invalid CBC padding) was the only one that seems like a problem.
