### ISSUE TITLE
problem building on Centos 7/i686

### ISSUE THREAD

**Issue by ronchristie52** [randombit/botan#1718]
I'm trying to do two builds on a 32 bit machine and running into some issues. 
I'm using gcc 4.9.4, CentOS 7
With version 2.8.0, after doing a ./configure.py with no options specified, make errors out with hundreds of lines similar to:

     /tmp/cclwQzrt.s Assembler messages:
     /tmp/cclqQzrt.s:33: Error: suffix or operands invalid for 'vpunpckldq'

With version 1.10.17, after doing a ./configure.py with no options specified, make executes several dozen commands, but then errors out with the following:

    src/hash/gost_3411/gost_3411.cpp: In member function ‘void Botan::GOST_34_11::compress_n(const byte*, size_t)’:
    src/hash/gost_3411/gost_3411.cpp:94:19: error: ‘uint64_t’ does not name a type
             const uint64_t UVk = U[k] ^ V[k];
                   ^
    src/hash/gost_3411/gost_3411.cpp:96:41: error: ‘UVk’ was not declared in this scope
                key[4*l+k] = get_byte(l, UVk);
                                         ^
    make: *** [build/lib/hash_gost_3411.o] Error 1

Any suggestions?

**Comment by randombit** [comment]
For 1.10, I'd suggest avoiding it as it is completely EOL at the end of this year. The issue you are running into there is fixed in git but not part of a release (https://github.com/randombit/botan/commit/a67e20f2053683095ed1bcd57220dd6ee8fd82c6)

For 2.8, it looks like the binutils in CentOS 7 does not support AVX2. It appears RH ships a newer binutils as part of the "Red Hat Developer Toolset" but I could not find any information on if that version supports AVX2. Installing that may fix it. The simpler fix is to use configure flag `--disable-avx2` to avoid all use of these instructions.

**Comment by ronchristie52** [comment]
FWIW, I updated gcc to the 8.2.0 stream and rebuilt 1.10 and it worked okay. I've still got an issue with 2.8.0 though. Using the 8.2.0 compiler it gets a lot further but then borks on:

    /tmp/ccnZ33Jq.s:55: Error: no such instruction: 'sha256rnds2 %xmmo, %xmm1, %xmm5'

There are several of these lines, with what I assume are the register numbers changing more or less randomly.
Cheers,
R.

**Comment by ronchristie52** [comment]
I should have mentioned that the source file it errors on is block_shaca12_x86.cpp.

**Comment by randombit** [comment]
Try flag `--disable-sha`, which despite the name does not disable the SHA hash itself but rather just use of the Intel SHA instructions, which are causing the issue here - likely because they are fairly new and not supported by the binutils.

**Comment by ronchristie52** [comment]
Hi Jack,
Still no joy, I'm afraid. With the two disable flags set, I get:

    /tmp/ccqSGcEj.s: Assembler messages:
    /tmp/ccqSGcEj.s:117: Error: no such instruction: `rorx $11,%esi,%edx'
    /tmp/ccqSGcEj.s:118: Error: no such instruction: `rorx $6,%esi,%eax'
    /tmp/ccqSGcEj.s:120: Error: no such instruction: `rorx $25,%esi,%edx'
    /tmp/ccqSGcEj.s:133: Error: no such instruction: `rorx $13,%ecx,%esi'
    /tmp/ccqSGcEj.s:134: Error: no such instruction: `rorx $2,%ecx,%eax'
    /tmp/ccqSGcEj.s:136: Error: no such instruction: `rorx $22,%ecx,%esi'
    /tmp/ccqSGcEj.s:146: Error: no such instruction: `rorx $19,%edi,%eax'

Source file is sha_32_bmi2.cpp. This is on an older machine. I'm not entirely sure about what the CPU model is, other than it's a i686.
Cheers,
R.

**Comment by randombit** [comment]
Oh dear. There is no flag to disable use of BMI2 (though I will add this shortly), but you can use ``--disable-modules=sha2_32_bmi2`` which is the only user of these instructions.

Apologies for the hassle here, our CI only tests on Ubuntu and I mostly run Arch so right now 
CentOS/RHEL is not being checked at all.

Maybe we can add something that tests if binutils supports the instructions before enabling them, but I'm not sure how that would work. (Already ``configure.py`` checks that the compiler accepts them, but that has not been the problem here.)

Depending on how things go you may also need ``--disable-module=rdseed`` and/or ``--disable-module=rdrand_rng``

**Comment by ronchristie52** [comment]
Hi Jack,
Still no joy, but it may be due to my reluctance to embrace the latest and greatest versions of the underlying OS - and in this case glibc.
The latest error message is:

 "src/lib/utils/os_utils.cpp:32:12 fatal error: sys/auxv.h: no such file or directory

I should note that I'm running CentOS 6.10, which puts me somewhat behind the curve. LDD reports version 2.12 which implies that my glibc is the same version and is much too old to have the getauxval functionality.
CentOS doesn't seem to support in place upgrades and there's a lot of stuff on that machine I'd just as soon not lose or break. I'm wondering whether just upgrading glibc to a newer version of glibc (either the latest - 2.28 or an earlier version, say 2.23) might work and not break too much else.
 
I know that this isn't your problem particularly, but do you have any experience with upgrading only glibc on a system and did it break things irretrievably?
Cheers,
Ron

**Comment by randombit** [comment]
> LDD reports version 2.12 which implies that my glibc is the same version and is much too old to have the getauxval functionality.

Ouch I had forgotten just how ~~obsolete~~ stable RHEL is.

> I know that this isn't your problem particularly, but do you have any experience with upgrading only glibc on a system and did it break things irretrievably?

I have done this in the past and things worked but you may run into problems because I would suspect newer glibcs are going to require a later kernel version than whatever CentOS 6 ships with.

But, no need for that on Botan's account - just use `--without-os-feature=getauxval`. On x86 this does not break much anything. (For ARM and PowerPC we need getauxval to detect optional CPU features like NEON, so missing `getauxval` there would be painful).

**Comment by ronchristie52** [comment]
SUCCESS!
Thanks for all your help. Perhaps now that IBM is acquiring Red Hat we will see a little more rapid updating of RHEL/CentOS. On the other hand...
