### ISSUE TITLE
How to use Botan and Arduino

### ISSUE THREAD

**Issue by 1fabunicorn** [randombit/botan#1727]
Hello! I am trying to use your wonderful looking C++ lib with Arduino. Are there any guides for this, or do you have any instruction on how to. 

Right now I have the compiled botan lib in the libraries folder, but it won't work because of the directory structure (There is no .h file in the base)

Any tips?

**Comment by randombit** [comment]
Hi - this isn't something I've tried nor have I heard of anyone doing so. So there may be some problems or limitations, though I'd be happy to help and make any necessary improvements upstream. 

First thing to note right from the start, if your board is AVR that is almost certainly not going to work well, Botan is not really suited for or targeting 8-bit CPUs. A board using Cortex-M3 should be fine though you will likely want to create a stripped version of the library to save on flash space. (Major flags for this are `--minimized-build` which disables basically everything, plus `--enable-modules=the,things,you,need` to add back what you are going to use. The full list of modules is printed by `configure.py` when it runs) You'll probably also want `--optimize-for-size`.

I'm not sure what you mean wrt "There is no .h file in the base". But to get the headers in one place, one thing to try would be adding an additional configure.py flag `--link-method=copy` (this causes the headers to be actually copied into the build dir, instead of creating symlinks into the source tree) and then copying `build/include/botan` to wherever you need it. (Or, at least with GNU coreutils, you can just use `cp` with `-L` flag, which copies the data instead of the symlink.)

**Comment by 1fabunicorn** [comment]
Hello again! I used your suggestion of `--link-method=copy`, yes your interpreted me correct haha. 

I then used atom to replace all the occurrences of `botan/xyz.h` to just `xyz.h`. There is probaly some fancy regex, which I did try using `sed -i 's/botan//g' $(find ~/Arduino/libraries/botan -type f)` but it kept the `/` in front, so I quit that approach. 

Now, I am getting this error when compiling an example you gave using the arduino IDE. I understand the problem, just don't understand how to fix it. 

```
In file included from /home/nova/Arduino/libraries/botan/types.h:13:0,
                 from /home/nova/Arduino/libraries/botan/secmem.h:11,
                 from /home/nova/Arduino/libraries/botan/pk_keys.h:11,
                 from /home/nova/Arduino/libraries/botan/pkcs8.h:11,
                 from /home/nova/Documents/hackathon/exampleBotan/exampleBotan.ino:1:
/home/nova/Arduino/libraries/botan/build.h:438:6: error: #error "Trying to compile Botan configured as x86_64 with non-x86_64 compiler."
     #error "Trying to compile Botan configured as x86_64 with non-x86_64 compiler."
      ^
In file included from /home/nova/Arduino/libraries/botan/secmem.h:11:0,
                 from /home/nova/Arduino/libraries/botan/pk_keys.h:11,
                 from /home/nova/Arduino/libraries/botan/pkcs8.h:11,
                 from /home/nova/Documents/hackathon/exampleBotan/exampleBotan.ino:1:
/home/nova/Arduino/libraries/botan/types.h:15:42: fatal error: cstddef: No such file or directory
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
'''

The problem is that the arduino does not have a x86_64 bit hardware. Do you know how to fix that, to get the exact hardware specs?

**Comment by randombit** [comment]
> I actually found this repo from some kind stranger on reddit, who does use with embedded micro controllers, so apparently it is possible.

Interesting!

> Any idea what arduino hardware is, or how to make your for it?

Depending on the hardware it will either be AVR or ARM (per Wikipedia there are also some 32-bit x86 Arduino boards but those seem to be very uncommon). Most are AVR but faster/higher end boards are ARM. For ARM you just need to add flag `--cpu=arm32`.

For AVR, well it is not supported by the build natively, as this hasn't come up. This

`$ echo "endian little" > src/build-data/arch/avr.txt`

will create a minimal configuration for AVR after which `--cpu=avr` will work. (But, I am really not sure if there is any AVR board which has enough RAM/ROM for Botan to make sense to use.)

Oh, it occurs to me that it's very unlikely Arduino supports threads or a filesystem. So probably it also needs an OS target of its own, which is quite minimal in this case:

` $ touch src/build-data/os/arduino.txt`

Now `--os=arduino` will work.

> fatal error: cstddef: No such file or directory

This seems bad. https://forum.arduino.cc/index.php?topic=487294.0 suggests that Arduino doesn't support the standard library at all, which is going to be a big problem - use of `vector` and `string` are very pervasive and it would be next to impossible to remove them. 
The discussion links to https://github.com/vancegroup/stlport-avr/tree/STLport-master-arduino-installed which seems to be a C++11 compatible port of STLport, which may do the trick? But, all the open issues for that repo are from people having problems getting it to actually work on Arduino, which does not seem promising.

**Comment by 1fabunicorn** [comment]
Thank you again for taking the time to go over that. If you had a crypto address I would tip you for your service! 

Maybe it will be a project when I get further into my studies. 

Again, thanks!
