### ISSUE TITLE
Building Madness 

### ISSUE THREAD

**Issue by pip010** [randombit/botan#1740]
OK, so after weeks of fighting with Botan trying to build properly I still have hard times making this library build fine under windows using MSVC:

Here is my command for building:
python configure.py --cpu=AMD64 --cc=msvc --msvc-runtime=MDd --os=windows --debug-mode --with-debug-info --minimized-build --enable-modules=rsa,emsa_pssr,ec_group,x509,rng,auto_rng,entropy,hmac,hmac_drbg,win32_stats

However after successful build I see:
LINK : warning LNK4044: unrecognized option '/MDd'; ignored
LINK : warning LNK4044: unrecognized option '/bigobj'; ignored

Now /bigobj I have no idea what it is (and maybe is indeed not valid) however MDd flag is valid and IMPORTANT!

RUNTIME ERROR (Only in DEBUG) :
Any use of Botan::DataSource_Memoryor/and Botan::DataSource_Stream will result in std::bad_alloc on std::vector destructors

Not 100% sure about my diagnostic but what is happening is mix of C++ runtimes and as result I have heap allocated on one thread/runtime but deleted on another.

If I pass MDd as : --ldflags=MDd
then it fails miserably trying to build a target MDd.obj :((((

p.s. if you guys look at current open issues like 80% are build related, hint hint !

**Comment by randombit** [comment]
> Now /bigobj I have no idea what it is (and maybe is indeed not valid) however MDd flag is valid and IMPORTANT!

Right now we are using `link` to link binaries, which does not understand these options, but it still gets passed `$(ABI_FLAGS)` which it ignores. Perhaps that part of the makefile should be fixed. But, in any case, this warning is only happening due to linking the test suite and CLI.  When you build as above, does the test suite pass? If so that suggests the link flag is ok.

> Not 100% sure about my diagnostic but what is happening is mix of C++ runtimes and as result I have heap allocated on one thread/runtime but deleted on another.

That does seem right. I wish if MS was going to continue with this insane multiple runtime system, they would at least not make the objects link compatible.

BTW #1739 seems to be using debug builds and it works. It may be useful to try the option they were using `--library-suffix=d` to create distinct release vs debug library names.

> If I pass MDd as : --ldflags=MDd

I think you would want `--ldflags=/MDd` (this option just passes through its argument to the linker/compiler command line, it does no interpretation). But, same flag should have already been introduced by `--msvc-runtime=MDd`, or `--debug-mode` for that matter.

**Comment by mikeloomisgg** [comment]
> RUNTIME ERROR (Only in DEBUG) :

To me that suggests maybe you are building a project with a release runtime and then trying to link to the debug runtime you compiled Botan with. Your executable and any 3rd party libraries all need to be using the same debug/release dynamic/static runtimes.
