### ISSUE TITLE
Error with std::aligned_storage in MSVC 15.9.3 in aes.cpp

### ISSUE THREAD

**Issue by ma30002000** [randombit/botan#1787]
When compiling aes.cpp class AES_TE with MSVC 15.9.3 I get the following error

c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\type_traits(1271,1): error C2338:  You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior.

The problem seems to be  std::aligned_storage<256*sizeof(uint32_t), 64>::type data;
I suppose we would want _ENABLE_EXTENDED_ALIGNED_STORAGE?

**Comment by randombit** [comment]
This has already been fixed in 2.8 with https://github.com/randombit/botan/pull/1624 for an earlier version you'll just need to define the macro yourself, either by editing aes.cpp and defining it there, or adding it via CXXFLAGS at build time, or editing `src/build-data/cc/msvc.txt` and adding it to `lang_flags` definition.
