### ISSUE TITLE
HKDF function throws 'Botan::Invalid_Argument'

### ISSUE THREAD

**Issue by ronaldmickey** [randombit/botan#1823]
The exeception is as follows:
    Unhandled exception at 0x00007FFFDA61A388 in test.exe: Microsoft C++ exception: Botan::Invalid_Argument at memory location 0x000000130ECFF758.

And here is my code:

    std::string hex_kdf(std::string &in, std::string &salt, const std::string &KDF)
    {
	    std::unique_ptr<Botan::KDF> kdf(Botan::HKDF::create(KDF));

	    std::vector<uint8_t> text = Botan::hex_decode(in); /*VS2017 marks the exception here.*/

	    std::vector<uint8_t> slt = Botan::hex_decode(salt);

           std::vector<uint8_t> info = Botan::hex_decode("01020304050607080900");

	    return Botan::hex_encode(kdf->derive_key(64, text, slt, info));
    }

and here is the bit calling this function:

    std::cout << hex_kdf("DEADBEEF", "BADC0FEE", "HKDF(HMAC(SHA-256))") << std::endl;

I might be writing this bit wrong, might be forgetting some setup, and/or be related to my previous issue.

But, I'm not getting a nullptr this time.

It's most likely a pebcak.

Also is the `algo_spec` names like  "HKDF(HMAC(SHA-256))"?

I've been working on a bit of a "playground" of sorts, in an effort to learn the library here: https://github.com/ronaldmickey/botan_playground/

**Comment by randombit** [comment]
This code worked fine for me, except that GCC errored because you are passing `in` and `salt` by mutable reference `std::string&` but initializing them from constant strings. If VC accepts this code it might be resulting in `in` being junk (and specifically, not valid hex) which would cause `hex_decode` to fail.

I notice you initialized the KDF with `Botan::HKDF::create(KDF)`. That works because `create` is a static member of `KDF` which is a base class of `HKDF`, but if you know you are always using `HKDF` it might be simpler to initialize it directly

`Botan::HKDF hkdf(Botan::MessageAuthenticationCode::create_or_throw("HMAC(SHA-256)")`

**Comment by randombit** [comment]
@ronaldmickey This worked for me and I suspect the problem is due to passing the strings by reference but initializing by constants. If changing the arguments to be `const&` doesn't resolve the issue feel free to reopen and I'll take another look.
