### ISSUE TITLE
WIP: Roughtime client (https://roughtime.googlesource.com/roughtime/)

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#1825]
I plan to start working this week in roughtime client.

If anyone is already on it please let me know to avoid duplication.

Thanks!

**Comment by randombit** [comment]
Excellent, looking forward to this. Nobody has mentioned working on Roughtime so it is all yours.

**Comment by nunojpg** [comment]
I have currently a implementation out of tree, except for merkle tree since I still have to get validation data.

I will be moving it in tree soon. I see Botan has a HTTP implementation, but no UDP. Maybe I underestimated the work to get a cross platform UDP library working. Is there any other features pending which would require UDP? Maybe I should take a look at those also to try to get a list of requirements.

**Comment by randombit** [comment]
> Is there any other features pending which would require UDP? Maybe I should take a look at those also to try to get a list of requirements.

Nothing immediately pending, though we'll want UDP for things like QUIC and it could also be used for DTLS client. Requirements for all should be pretty basic though, UDP is low on features - a connected UDP socket should do it in most cases.

I do think there should be a distinction in the code between Roughtime the protocol vs Roughtime-over-UDP, in the same way TLS is decoupled from the transport layer. That would allow an application to run Roughtime over some other transport if needed (TCP or SCTP or whatever), and makes things easier to test since you can just pass byte buffers in and out.

**Comment by nunojpg** [comment]
Continues on pull request #1842.
