### ISSUE TITLE
configure.py with --debug-mode and --cxxflags=

### ISSUE THREAD

**Issue by Bjoe** [randombit/botan#1826]
I'm not sure if it is the correct behavior for to build botan with `--debug-mode` when `--cxxflags=` are set.
The current behavior is, if I set both parameter, `--cxxflags=` "wins" ;-), means `-g` is not set. I see only the build flags from `--cxxflags=`. Is this correct behavior?
I expected to **add** additional build flags, as with any other project (at least CMake based projects). Ok, the `--help` documentation say: `--cxxflags=FLAG    set compiler flags` ... maybe a hint would be nice like: --cxxflags= overules all other flags/debug mode. Take me some hours to find the problem why debug build is not working in my [hunter pkg](https://github.com/Bjoe/hunter/blob/4ad9daa705fc1b8951b41bec44f9ffeba1ffe857/cmake/projects/botan/schemes/url_sha1_botan.cmake.in#L205).

The next question is, how I can **add** additional build flags? At the moment [I use as workaround](https://github.com/Bjoe/hunter/blob/4ad9daa705fc1b8951b41bec44f9ffeba1ffe857/cmake/projects/botan/schemes/url_sha1_botan.cmake.in#L204) `--cc-abi-flags=`

Some host details:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
dpkg package:
Package: python2.7-minimal
Architecture: amd64
Version: 2.7.15~rc1-1ubuntu0.1

**Comment by reneme** [comment]
In fact, I was surprised by this build system behaviour just yesterday as well. Botan's runtime performance of a build generated [via `conan`](https://github.com/bincrafters/conan-botan) was much slower than usual. It turned out that the package maintainer (@SSE4) had the same expectation of `--cxxflags`'s behaviour and used it to add `-fPIC`. He ended up overruling the compiler-specific default flags (i.e. `-O3`) and ended up with a non-optimized build.

**Comment by randombit** [comment]
We can't change the current behavior of `--cxxflags` or `CXXFLAGS` since many builds (like Gentoo, Arch, Debian, etc) want to be able to control all of the build flags and make use of the current behavior. I have changed the help snippet for `--cxxflags` to "override all compiler flags" to make it more clear what it does, added a `--extra-cxxflags` which has the behavior you wanted from `--cxxflags`, and added documentation of all of the build flags to the handbook.

Thanks for bringing up this issue.
