### ISSUE TITLE
Ed25519 CLI sign/verify

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#1828]
CLI sign and verify forward to PK_Verifier and PK_Signer the EMSA parameter always in the format:

emsa(hash)

This is not compatible with Ed25519 which expects Identity, Pure or just a Hash.

Would appreciate some comments of the best approach to make it compatible.

**Comment by randombit** [comment]
Oh, yuck. Thanks for mentioning.

Think the fix is have `algo_default_emsa` (in `cli/pubkey.cpp`) return "" for Ed25519. Then break up this:

```
         const std::string sig_padding =
            get_arg_or("emsa", algo_default_emsa(key->algo_name())) + "(" + get_arg("hash") + ")"
 ```

to something like (totally untested):

```
const std::string emsa = get_arg_or("emsa", algo_default_emsa(key->algo_name()));
const std::string hash = get_arg("hash");
std::string sig_padding;
if(emsa.empty())
  sig_padding = hash;
else
  sig_padding = emsa + "(" + hash + ")";
```

Then with --emsa empty/unset (the default), the user can use --hash=Pure or --hash=SHA-384 or etc with Ed25519.

There might be some cleaner way, but this should work.

(Actually, the cleaner fix is that algo_default_emsa function is only called in that file twice. Replace it with `choose_sig_padding(emsa, hash)` with logic above incl what is currently in `algo_default_emsa`, then replace the initializations of `sig_padding` with `choose_sig_padding(get_arg("emsa"), get_arg("hash"))` At least then we don't have to duplicate the logic twice.
