### ISSUE TITLE
Use error_code

### ISSUE THREAD

**Issue by vinniefalco** [randombit/botan#1841]
I'm shocked that Botan uses exceptions always.. SHOCKED I tell you. The integration with Networking TS (and the currently shipping flavors Boost.Asio and Asio) will be much smoother with `error_code`. And given an `error_code` you can always `throw` it as a `system_error` from an additional set interfaces if the user really wants exceptions, as is the custom in std::filesystem, boost::system, boost::asio, standalone asio, boost::beast, et. al.:
https://github.com/boostorg/beast/blob/28f5921bd613d5076d640d094926a684731799c3/include/boost/beast/http/impl/read.ipp#L230

**Comment by crazydef** [comment]
This is the one thing which is causing me to pause too.  Exceptions are a no go for me, which is unfortunate because Botan up until now was looking like a good fit for my needs.

Given Botan's love of callbacks it would make far more sense to replace all exceptions with suitable callbacks that the calling application can then deal with in its own way.  Or at least give us the option of doing this.

**Comment by randombit** [comment]
Nonetheless we use exceptions and adapting everything to use error codes is probably not viable.

Best path to achieving this would probably be to expand the C89 API to cover everything and then provide a new C++ API on top of it.
