### ISSUE TITLE
Tests should not be part of coverage

### ISSUE THREAD

**Issue by vinniefalco** [randombit/botan#1845]
Coverage reports should include only implementation that users can access. On a positive note, by excluding the tests and unrelated code, Botan coverage will see a considerable increase :)

**Comment by randombit** [comment]
Including tests (+fuzzers) in coverage is very intentional, as seeing that a test is not being run can be indicative of a configuration issue. This has saved me several times. It also allows seeing which parts of the test framework itself are not being exercised during a normal run, which can guide adding tests (of the test framework, see `test_tests.cpp`) to ensure it works correctly. Coverage report is primarily for the developers and made public to end users as an fyi.

(Also, it is easy to see the library-only coverage from the all-source coverage report, but that doesn't work in the other direction.)

**Comment by vinniefalco** [comment]
If that is the use-case, then the the report can be run twice, one for the library proper and the other for the tests, by adjusting the file inputs. 

> Coverage report is primarily for the developers

I urge you to reconsider this position. Users or companies considering Botan can be reassured by accurate coverage reports. It does the library a disservice to under-report the coverage, as is happening in this case.

Ensuring coverage of tests is indeed useful for developers, but it is better addressed with a separate report.
