### ISSUE TITLE
Can we drop X509_Time(time_str)?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#185]
While `X509_Time::X509_Time(const std::string& t_spec, ASN1_Tag t)` parses an input time string according to the strict asn1 `UNIVERSAL 23` or `UNIVERSAL 24` rules, the constructor without a given tag is some kind of a guessing constructor that seems to take every input and tries to make something out of it.

While parsing a strictly defined time string is already hard, parsing an undefined time input is impossible.

Given that X509_Time is used for certificate validation times, this might even be a security problem.

I'd keep the following constructors:

```
X509_Time();
X509_Time(const std::chrono::system_clock::time_point& time);
X509_Time(const std::string&, ASN1_Tag);
```

This just requires explicitly setting `ASN1_Tag::UTC_TIME` or `ASN1_Tag::GENERALIZED_TIME` in some places.

**Comment by randombit** [comment]
+1

**Comment by webmaster128** [comment]
Great, thanks for the quick feedback. I'll work that out in order to get my new tests green :)

**Comment by webmaster128** [comment]
I made the change locally and when I now run the following test, I get an error:

```
./botan-test nist_x509                            
Invalid UTCTime string: '1998/01/01 12:01:00 UTC'
NIST X.509 path validation 1 tests 1 FAILs
===============
Tests 1 FAILs
```

I don't know where that input date comes from (`1998/01/01 12:01:00 UTC`). Is there a need to parse dates in that format for UTCTime?

**Comment by webmaster128** [comment]
@randombit I think I need you input here - just a hint how to proceed, otherwise I am stuck here.

**Comment by randombit** [comment]
I don't know of any reason this format would need to be parsed during the path validation tests, nor can I find that string in any of the NIST test data with `grep`.

Narrow down which test is the problem by reducing the scope the `try` block in the function `test_nist_x509` to inside the loop over the tests, rather than having the single try/catch block containing the entire set of certification path validation tests. That way an uncaught exception will just abort that one test rather than all of them. Once you know the test(s) that is causing the problem look at the test data for the path validation tests (in `src/tests/data/nist_x509`) using an ASN.1 printer (`openssl asn1parse` or `botan asn1`) and figure out what is different about that tests data.

It may be easier to just `catch throw` in gdb and check the backtrace when this exception is thrown.
