### ISSUE TITLE
botan-test fails on System z

### ISSUE THREAD

**Issue by bkircher** [randombit/botan#1875]
git revision 3a459487df5de4cb411efdda0010e617d6903284

Skein-512 fails on s390x:

```
./botan-test
Testing Botan 2.10.0 (release, dated 20190330, revision git:3a459487df5de4cb411efdda0010e617d6903284, distribution Fedora)
Starting tests drbg_seed:1590FF76EFA37FB0

<snip>

Note 1: Skein-512(224) Test # 1 Skein-512(224)  failed [Key=1541AE9FC3EBE24EB758CCB1FD60C2C31A9EBFE65B220086E7819E25]
Note 2: Skein-512(224) Test # 2 Skein-512(224)  failed [Key=23F031A6A4378039B66A5A178BAD217EAEC094B7FCBA663A47DDCF33]
Note 3: Skein-512(224) Test # 3 Skein-512(224)  failed [Key=B9CAAA9DDAF14985F6A3322C8F0BD182BDFB2DC3CABDFF56F14940B1]

<snip>

Skein-512(256) ran 2547 tests in 8.90 msec 1523 FAILED
Failure 1: Skein-512(256) producer 'base' unexpected result for hashing
Produced: 005320BF43B82BC6B6A64D7E747057141637BC4ECAD1582436DAA5A7DBC17B51
Expected: 39CCC4554A8B31853B9DE7A1FE638A24CCE6B35A55F2431009E18780335D2621
XOR Diff: 399FE4EA09331A438D3BAADF8A13DD30DAD10F149F231B343F3B2227E89C5D70
Failure 2: Skein-512(256) producer 'base' unexpected result for hashing (clone)
Produced: C48A6A8F509A3ECF9DFD0FAEA49DCBE0ABACF16C57404F8EB2EB6FF557B8138E
Expected: 39CCC4554A8B31853B9DE7A1FE638A24CCE6B35A55F2431009E18780335D2621
XOR Diff: FD46AEDA1A110F4AA660E80F5AFE41C4674A423602B20C9EBB0AE87564E535AF
Failure 3: Skein-512(256) producer 'base' unexpected result for hashing after clear
Produced: 369137750FD2F3E994F4D05B9FCA8B255034186BEF7C545FF11CE1731F6C74DD
Expected: 39CCC4554A8B31853B9DE7A1FE638A24CCE6B35A55F2431009E18780335D2621
XOR Diff: 0F5DF3204559C26CAF6937FA61A901019CD2AB31BA8E174FF8FD66F32C3152FC

<snip>
Tests complete ran 2709463 tests in 108.96 sec 6168 tests failed
BUILDSTDERR: error: Bad exit status from /var/tmp/rpm-tmp.bmzKE1 (%check)
```

Complete build and test output attached.

[s390x-build.txt](https://github.com/randombit/botan/files/3026637/s390x-build.txt)

**Comment by randombit** [comment]
This looks to be a pre-release of GCC 9. I suspect the issue is a compiler bug, especially as Debian builds/tests fine for S390x using GCC 8.2 (https://buildd.debian.org/status/fetch.php?pkg=botan&arch=s390x&ver=2.9.0-2&stamp=1547416407&raw=0) and no changes have been made to the relevant code in last several releases.

Is it possible to rebuild currently packaged (presumably passing) version using the new compiler? If fails that clearly demonstrates it as a compiler issue.

**Comment by bkircher** [comment]
> This looks to be a pre-release of GCC 9

Yes.

> Is it possible to rebuild currently packaged (presumably passing) version using the new compiler?

You seem to be right. Same tests are failing when trying to complete a package build for Botan 2.9.0 (one that succeeded before) on that build environment.

[s390x-build-2.9.0.txt](https://github.com/randombit/botan/files/3051700/s390x-build-2.9.0.txt)

**Comment by sharkcz** [comment]
The problem is that the config_str array (https://github.com/randombit/botan/blob/master/src/lib/hash/skein/skein_512.cpp#L77) isn't zerod after last specified zero (position 7) and it contains some garbage from the stack.

**Comment by randombit** [comment]
@sharkcz This seems very wrong to me. In C++ initializing an array with fewer initializers than the size of the array causes all remaining values to be set to zero. For example see https://en.cppreference.com/w/cpp/language/aggregate_initialization ("If the number of initializer clauses is less than the number of members or initializer list is completely empty, the remaining members are value-initialized.") or https://stackoverflow.com/questions/38892455/initializing-an-array-of-zeroes

Since there is debugger output showing that it in fact is not zeroed I can hardly contest it's not happening, but I certainly still think it is a bug in GCC 9 on S390x.

This could be fixed within Skein by explicitly initializing all of the values. But I am not going to do that until there is some firm confirmation from GCC upstream that this behavior is intended, since there are at least a dozen other areas of the code which use exactly the same idiom.

**Comment by sharkcz** [comment]
It has been confirmed as a gcc9 bug - https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90025

**Comment by bkircher** [comment]
Cool, many thanks for digging @sharkcz !
