### ISSUE TITLE
Usage Question: Generate a self signed certificate

### ISSUE THREAD

**Issue by abrousseau001** [randombit/botan#1887]
I am writing a simple c++ class to test botan for generating x509 self-signed certs to act as our licensing scheme to avoid misuse of our product. I have provided sample code below to my issue.
     
```
Botan::AutoSeeded_RNG` rng;
Botan::RSA_PrivateKey rsa_priv_key(rng, 4096);

//Options for the new cert being generated
//1. common_name/country/organization/organizational_unit
//2. Time in seconds that the certificate is good for (defaulted at one year)
Botan::X509_Cert_Options options("Test License/US/MyCompany/SomeDivision");

options.email = "acbrousseau@gmail.com";
options.serial_number = "come up with something to generate serials";

std::cout << "It worked.";

//Create the certificate for the license
Botan::X509_Certificate self_signed_cert = Botan::X509::create_self_signed_cert(options, rsa_priv_key, "SHA-256", `rng);
```

Each time Botan tries to create X509_Cert_Options I get an error about accessing the memory location. See below:
Exception thrown at 0x00007FF8E5F3FAC0 (botan.dll) in BotanTest.exe: 0xC0000005: Access violation reading location 0x000000B73DF00000.

Looking at the tests I see this is indeed the correct way to populate options. I compiled botan using MSVC 19.2 (VS 2019) and Python 3.7. Any assistance would be most appreciated.

**Comment by randombit** [comment]
Your code works for me (on Linux with GCC).

Sometimes people run into crashes with MSVC because they mix runtimes (debug vs non-debug, eg library is debug but app is release mode, or the reverse). The first time a STL object crosses the DLL boundary things get ugly, here initializing the `X509_Cert_Options` is the first time that happens.

One way to check on this would be to try calling `hex_decode` on a string, eg
```
std::string h = "F00F";
auto vec = Botan::hex_decode(h);
```
If that also crashes, that definitely points to a runtime mixup.

If its not that, I'm not really sure what the problem could be. The constructor is quite simple and just does some basic string operations and gets the current time. A backtrace would probably help.

BTW to avoid mixing up runtimes some people use `configure.py`'s `--library-suffix` option to add a `d` to their debug build libraries.

**Comment by abrousseau001** [comment]
Thanks for the quick response. That makes sense and I will get back with you in the next couple of days. I have been trying to add this library as a third party dependency using Conan so it integrates a bit better with CMake.
