### ISSUE TITLE
Online doxygen documentation

### ISSUE THREAD

**Issue by zaqwsx1277** [randombit/botan#1909]
Unfortunately online Crypto Library API Reference for ver. 2.10 is absent. 
https://botan.randombit.net/doxygen/
Please, restore this service.

**Comment by randombit** [comment]
I do not understand. The documentation you link to is for 2.10. If you meant the old (now end of life and unsupported) 1.10 branch, that is still available at https://botan.randombit.net/doxygen-1.10.

If you want the Doxygen for some other version of 2.x, you would need to generate it yourself from that version.

**Comment by zaqwsx1277** [comment]
Many thanks, but for previous version 2.09 doc was available with out problems.

**Comment by randombit** [comment]
The website always uses the manual/doxygen for the most recent version only. Since the documentation is improved over time and source compatibility is maintained, there is no reason to not just use the most recent version, and having multiple versions is confusing and makes it hard to link to.

However, on inspection of the website I see the Doxygen output is corrupted. This appears to be a problem with Doxygen 1.8.14, I think it may be same issue as https://github.com/doxygen/doxygen/issues/6856

**Comment by randombit** [comment]
Doxygen build on the site has been fixed by backing down to Doxygen 1.8.13. However as mentioned we only host the one version (latest release), and if you want something different you should build it locally from that version.
