### ISSUE TITLE
Problem with Signature verification for DSA_PublicKey

### ISSUE THREAD

**Issue by zaqwsx1277** [randombit/botan#1912]
I'm try verification Signature for DSA_PublicKey, but after atempt create_verification_op, my soft is crashed with message:

terminate called after throwing an instance of 'Botan::Decoding_Error' 
what():  Invalid argument Decoding error: Bad SCAN name '': Empty name    

    Botan::BigInt pENC ("0xC16CBAD34D475EC5396695D694BC8BC47E598E23B5A9D7C5CEC82D65B6827D44E95378484730C0BFF1F4CB56F47C6E51054BE89200F30D43DC4FEF9624D4665B") ;
    Botan::BigInt qENC ("0xB7B810B58C0934F642878F360B96D7CC26B53E4D") ;
    Botan::BigInt gENC ("0x4C53C726BDBFBBA6549D7E731939C6C93A869A27C5DB17BA3CAC589D7B3E003FA735F290CFD07A3EF10F35155F1A2EF70335AF7B6A5211A1103518FBA44E9718") ;
    Botan::BigInt yENC ("0x15F8A50211C234BBDF19B3CD25D14413F03DCF386FFC7357BCEE59E4EBFDB64167265E5F068247D4B50B3B867A85FB4D6E018329A993C36CFD9ABFB6ED6D29E0") ;
    Botan::DL_Group dlgroupENC (pENC, qENC, gENC);
    Botan::DSA_PublicKey dsaENC (dlgroupENC, yENC) ;

    std::unique_ptr<Botan::PK_Ops::Verification> ver_op = dsaENC.create_verification_op ("", "") ;

Is this operation possible for DSA algorithm?

**Comment by randombit** [comment]
`create_verification_op` and `PK_Ops::` are internal use and just exposed for ABI reasons. Use `PK_Verifier`.

The error here is confusing and should be improved, but the problem is you are expected to specify the hash function you are using in the first parameter, eg "EMSA1(SHA-256)". Or if you are providing a pre-digested data instead of a message use "Raw".
