### ISSUE TITLE
Windows builds should have _WIN32_WINNT defined

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#2028]
I am back from quite a long journey finding why my code did not compile on Windows with Amalgamation.

The underlying problem can be seen on CI, for example:

https://ci.appveyor.com/project/randombit/botan/builds/25935871/job/5iaaydgheapappat

> Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
> - add -D_WIN32_WINNT=0x0501 to the compiler command line; or
> - add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
> Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).

What actually happens is that depending if boost or windows.h is first included, then _WIN32_WINNT gets either defined to 0x0501 or 0x0A00 respectively. (for this build image windows version).

While this can probably cause unexpected behaviour all over, the most difficult to understand issues come with amalgamation.

The fix for this needs to be decided by a Windows Ninja...

**Comment by randombit** [comment]
Possible values documented in https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=vs-2019

Botan explicitly does not support Windows XP, because it is not supported anymore by the original vendor. Windows 7 and Server 2008 remains supported until January next year. So we probably want 0x0600 for Server 2008. After January 14, 2020 with both Windows 7 and Server 2008 EOL, we can probably switch to 0x0602 for WIndows 8.

But Windows expert I am not, maybe there are some bad effects from doing this that I am unaware of. One consideration is that Windows 7 still has 30+% market share so EOL or not, downstream developers are going to be unhappy if one of their dependencies means their application can't run on 1/3 of potential users's machines. So, maybe for a while we are capped to at most 0x0601 for Windows 7. Windows XP, Vista and older seem to be rare enough (~3% total users) that we can ignore them.

So I guess that would be my proposal:
 - Change to 0x0600 now
 - Change to 0x0601 in January - Windows Server 2008 is EOL then, and so is Windows 7, but Win7 seems common enough that we maybe are stuck with supporting it for a while anyway, and the cost of compat doesn't seem high here since we aren't trying to use cutting edge APIs on Windows.

@neusdan @webmaster128 any comments?

I'll post to the mailing list to see if anyone has input.

**Comment by randombit** [comment]
https://lists.randombit.net/pipermail/botan-devel/2019-July/002284.html

**Comment by randombit** [comment]
@nunojpg Can you try updating to 0x0600 in your Roughtime PR to verify that is sufficient to resolve the build issue you are having?

**Comment by nunojpg** [comment]
0x0600 is enough.

**Comment by nunojpg** [comment]
My point is that 0x0600 should be forced on CI, to make sure code compiles on a older version, but configure.py should by default use the one from current windows. (the one defined by windows.h).

**Comment by randombit** [comment]
Is there any problem with always building as 0x0600? (Assuming we don't need access to more recent API additions). Since it seems like it would be common for someone to be building eg on WIndows 10 but then distributing a binary that they would expect to work on 8/7/whatever.

**Comment by nunojpg** [comment]
I don't know if the generated code will always be the same, or if in some cases that will force worst performant code to be used.

But I really have no idea...

**Comment by neusdan** [comment]
I agree with your proposal. 0x0600 now and 0x0601 in January and I would set these values always independent of the build machine.

**Comment by randombit** [comment]
Only comment on mailing list was someone specifically requesting not dropping support for Windows 7 (which we are not going to do anytime soon, given the marketshare). So I merged #2036 which sets to 0x0600. @nunojpg can you rebase Roughtime against latest master and verify all is good?

**Comment by nunojpg** [comment]
@randombit yes, all good for me also.
