### ISSUE TITLE
Encrypt small data

### ISSUE THREAD

**Issue by Wambou** [randombit/botan#2067]
Hi,

After reading articles, I cannot find a simple answer to my problem, so I will try it here.

My problem is that I need to encrypt 14 bytes only, that must not expand.
Furthermore, I cannot provide IV because I won't be able to send it when I want to decrypt the data.

I based my work on someone else that presented a solution using "AES algorithm", without saying which mode to use. So I tried using AES-128/CBC, finding out that I don't have enough data to encrypt.
After reading about the different modes, I found that not providing IV for some of them, or using the same one, leaks info on the first block.
But since the first block is 16 bytes at least, I am stucked with almost not encrypted data...

So my question is, what would be the best solution in my case ?
If I can have some kind of authentication in the process would be a bonus but because of the size constrain I know it will be difficult.

Thank you in advance for your help.
(It's a bit urgent so I will continue my readings and searches but who knows, maybe the holy grail will show up here.)

**Comment by randombit** [comment]
This is not an easy problem to solve in a satisfactory way. Especially, authentication is basically impossible due to the need to not expand - there is no redundancy that can be checked. And traditional cipher modes are no good for this - without a nonce most of them become insecure if more than one message is sent under the same key.

If you can expand even slightly, format your messages as 16 bytes, with 2 bytes of MAC (say generated by truncating the output of SipHash-2-4 or HMAC) then encrypt the 16 byte block in AES ECB. A 2 byte MAC would generally be considered very weak, but it is stronger than no MAC at all... If you can expand to 14+16 bytes, use AES in SIV mode without a nonce - which is fully secure and gives authenticity.

If you really can't expand at all, the best approach I am aware of is using format preserving encryption to basically create a 14 byte block cipher. [You could also use another arbitrary-length block cipher construction, but most of these are oriented towards very long rather than very short blocks.]. Then you encrypt the entire message in ECB mode. On decryption you can check any redundancy in the message (say that a particular bit is not set or ...) which acts as a (very weak) authenticity check. One variant of FPE is available in Botan in fpe_fe1.h

There are a lot of problems that FPE doesn't fix though. Without a nonce, your system will be vulnerable to replay attacks. Without strong authentication, someone can send you randomized garbage and without some probability you'll accept it as a legitimate message. Look very hard at your requirements and see if there is any way you can go beyond 14 byte messages. Another option that might work for you - both plaintext and ciphertext remains 14 bytes (eg using FPE) but then every 10th (or whatever) message, you send a 14 byte message which is a MAC of the previous 10 messages, and the receiver doesn't actually act on any of the messages until it receives the MAC block, if the MAC is invalid it discards them. This is still vulnerable to replays though; if you are able to maintain a message counter on both sides, the MAC could include the counters as well as the payloads.

HTH. If you find anything in researching that can solve this better than what I suggest please leave references here as I would be curious to read them.

**Comment by Wambou** [comment]
Thanks for the answer.

Maybe I need to give extra information on my problem but I hoped to avoid disclosing too much information. (The following text will willfully avoid certain words to avoid easy searches, sorry for the extra deciphering process...)

One system will generate data that need to be encrypted as C. C is transmitted to someone else, so that it can be entered in another system by hand. Because of the manual action, at most 14 bytes can be encoded to avoid having to type a long text that makes no sense to the user.
The second system will decode C and check the content applying certain rules. C targets a specific system and will not be accepted by a third one, due to the rules mentioned above.

Authenticity and integrity are bonuses, if I can find something more secure than nothing, why not. I might reuse the idea to have a single byte MAC, I was thinking about it after my readings, but more in an Encrypt-then-Mac scheme.
Since the generating system will not be accessible to many, and the other systems will only receive the encrypted data, replay attack is, in a way, a wanted behavior. If I provide the same input, I want the same ciphered data generated, same applies to the deciphering part.

I will look into FPE and if I find something interesting elsewhere, I will post here.

Thank you again for your help.

**Comment by randombit** [comment]
Thanks for background. I am guessing any particular user will only type a `C` once, or perhaps a few times if the system needs to be reinitialized over time.

It sounds like the receiving system will have a pretty good idea of what `C` should look like, in order to apply to content checks. Say the plaintext in `C` can be split up in some way into `C_known` and `C_unknown`, where `C_known` is something the receiving system *already knows*, and `C_unknown` is some possibly empty data that it doesn't know, that is new information that is being provided by the generating system. It must be the case that `C_known` is non-empty, because if it is empty that implies `C` is unknown to the receiver and there is no meaningful content check (AIUI). So, have the sending system send `C_unknown` concatenated with a short MAC (say a truncated HMAC) covering both `C_known` and `C_unknown`. If len(`C_known`) > len(HMAC) then you see a space savings. Since (AIUI) you are already provisioning each system with a unique secret key, prior to initialization, you could just bake in `C_known` at the same time.

Given the context is sounds like you might be able to go as small as a 48 bit MAC without any real reduction in security. A user typing values will never break a 48 bit MAC in reasonable time, and if they edit the code to `nop` out the checks, or reverse engineer the code to recover the shared secret between the two systems, then it doesn't matter how long the MAC is.

A thought: Does the user really need to *type* the value using a keyboard? Are they transcribing from paper, or over an airgap? Or could they say, paste in something they are sent via email or on a webpage? In which case you don't want it to be too large, but base58check of 98 bytes is 140 chars, which is plenty of room for eg an ECDSA signature plus a message. Which would avoid needing to provision each system with a unique pre-shared secret key, instead just bake the generating system's public key into the receiving system binary.

**Comment by mouse07410** [comment]
Note that you can truncate the auth tag aka synthetic IV in SIV. One can calculate whether the reduced guarantees such a change causes, are still acceptable.

It would still require extending the result by a few bytes, though not necessarily by the entire 16 bytes.

**Comment by randombit** [comment]
@mouse07410 reference for this? I don't see anything about it in RFC 5297.

**Comment by mouse07410** [comment]
> reference for this?

:-)
My work, and of my colleagues. Not published yet (in the process).

But it should be obvious that (a) you can do that, and (b) it would worsen the security bounds by a degree relayed to the number of bits you removed.

**Comment by Wambou** [comment]
Thanks for the answers, it's really insightful.

As of today, it will be typed by hand. Maybe in the future we will provide like QR codes but for now, all by hand...

The data can be split into `C_known` and `C_unknown` and I thought about using the known part in some way yo cipher the unknown one. The HMAC idea seems to answer that in some way, adding integrity in the process. I can remove the `C_known` part and fit the truncated HMAC instead, still keeping my final 14 bytes.

For the truncated SIV, which I would like to read about, I have 14 bytes of data but inside it, I have some free bytes for future use. I might be able to give 1 or 2 away. So I will have 12 payload bytes and can give the last 2 bytes for something else, keeping my final 14 bytes.

Looking into SIV, I found this [Stanford MOOC about cryptography](https://www.coursera.org/lecture/crypto/deterministic-encryption-siv-and-wide-prp-hM7f2), around 9:46, where for small data, less than 16 bytes, a simple PRP is enough. Integrity can be added using `N` trailing 0 so that `1/2^N` is negligible (15:51). But there is still the problem that I cannot expand data. I will look into FPE for that.

Quick question about truncated HMAC, is it better to use lower bits or higher bits ?

**Comment by randombit** [comment]
> Quick question about truncated HMAC, is it better to use lower bits or higher bits ?

No difference. Usual convention is to take the higher bits.

**Comment by Wambou** [comment]
I have a pretty good idea of how I want to proceed now, but I do not succeed in encrypting just a small amount of data.

I wanted to use one of the Block_Cipher's primitives but I do not find out how...
Could you guide me in the documentation how I can do that ? I need like 112 bits block cipher.

Thank you in advance for your help.

**Comment by Wambou** [comment]
Hi all,

I finally succeed doing what I needed.
AES/CTR does not expand block size, so that I can cipher data smaller than block size.

Thank you for your help, it was insightful and helped me add some authentication in my scheme.

Regards.
