### ISSUE TITLE
Feature Request: Output Visual Studio project files

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#207]
It would be nice if the build system could output Visual Studio project files.

**Comment by webmaster128** [comment]
Feel free to implement ;)

**Comment by cordney** [comment]
To me, this seems like another pro for using a standard build system that is able to generate common IDE project files, like CMake. I'd also like to have Xcode project files when developing on OS X. The same goes for Eclipse, Netbeans and CLion. The last two have CMake-support right built-in. For the others, CMake is able to generate Eclipse, Visual Studio and Xcode project files easily.
Having an easy-to-use IDE integration would make contributions much much easier (imagine a life with auto completion and integrated debugging possibilities, just to name a few).

**Comment by cdesjardins** [comment]
@cordney Concur, cmake would also solve the problem regarding make dependencies.

**Comment by webmaster128** [comment]
+1 This would reduce the cross-platform maintenance afford a lot for Botan. Given the (nice) module system of Botan, I think we'd still need `./configure.py` to generate cmake project files, which should keep the flexibility high

**Comment by mouse07410** [comment]
In my experience, as long as you're staying within the constraints of the cmake configuration that the author put in, it works like charm. Once something falls out of sync with that paradise view - things go to hell in a basket very rapidly, leaving practically no recourse for somebody who is not a cmake expert.

I am strongly against making Botan dependent on cmake. Make a fork if you must, and make its build depend on whatever you please. Leave the mainstream Botan as is build-wise. It is already complicated enough.

P.S. If memory serves, you were unhappy to split the installation command in two: "install" and "install-docs", citing extra complexity that would confuse users. You say throwing them into the sewer of cmake won't confuse them?! I can't claim to understand your logic.

Sent from my iPad

On Jul 19, 2015, at 06:10, Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:


+1 This would reduce the cross-platform maintenance afford a lot for Botan. Given the (nice) module system of Botan, I think we'd still need ./configure.py to generate cmake project files, which should keep the flexibility high

**Comment by mouse07410** [comment]
One more comment: with the current config, it produces a relatively simple Makefile that can be manually adjusted, which currently is quite easy. There are many reasons to tune the build that your current config just cannot automate, and I'm willing to bet that cmake won't improve that either. This is from experience based on other projects where cmake experts built configurations, and we had to enhance the code and deploy it to environments that those "experts" claimed to support but apparently didn't understand as well as the primary release base.

There are simpler ways to kill this project than forcing its config to generate Xcode project via cmake.

Jack, I hope you are listening.

Sent from my iPad

On Jul 19, 2015, at 06:10, Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:


+1 This would reduce the cross-platform maintenance afford a lot for Botan. Given the (nice) module system of Botan, I think we'd still need ./configure.py to generate cmake project files, which should keep the flexibility high

**Comment by cordney** [comment]
First of all: Nobody of us wants to kill this project. We are all here to improve Botan as good as we can.

As to your remark regarding CMake - in my experience, this is with all build systems, including the current one. We used SCons and Qt previously, and now use CMake internally for all our C++ projects and we are quite happy with it.

I'd rather not want to create a fork "just" to use another build system. This seems like an odd idea.

**Comment by webmaster128** [comment]
I think we can close the original issue with "not before CMAKE". The rest of this is about cmake then.

There are some things that are kind of personal which I want to answer first

> If memory serves, you were unhappy to split the installation command in two: "install" and "install-docs", citing extra complexity that would confuse users.

Not because it confuses users. Because I myself don't want to maintain additional complexity in my spare time to avoid build system breaks that cause frustration. It turns out (surprise surprise) that development power is limited and I don't see a lot of people here taking care of non-gnu-linux targets where everything works like in a paradise.

> You say throwing them into the sewer of cmake won't confuse them?! I can't claim to understand your logic.

Here you are mixing up two things: 1. reducing complexity (i.e. number of possible build configurations) and 2. introducing a tool to handle the existing complexity better.

> with the current config, it produces a relatively simple Makefile that can be manually adjusted, which currently is quite easy.

That is a good point and I am absolutely with you on that point. I am not a cmake guru. I hate cmake syntax and I hate that it is nearly impossible to find the right output Makefile that will actually build the code.

But life is about tradeoffs. And if there are good reasons to introduce a tool, there will be downsides as well. Let's be scientific about that, collect the arguments, weigh them and decide after that.

As long as I can think you did not come up with an argument against cmake other than that you are afraid of technology you're not familiar with. If you have experience with projects migrating to cmake, let us know what exactly the problems have been.

I don't know what platforms you're targeting because you did not share with us yet. I only know that I already put hundreds of hours into the Botan build system to ensure that Botan builds on Windows, Botan works on Android, Botan can be used in an application with a debug STL, out-of-tree builds work as they should, Botan can be used in a debugger, Botan can be used in a profiler, Botan can be build on multiple cores on Windows. This is stuff I care about. And a lot of this stuff comes for free with cmake or another modern build system. We're re-inventing the wheel using python scripts at so many places, which is burning down developer-time like hell and I don't know if it's worth it.

For our use at Kullo it does not make a difference. We copy the amalgamation into our build system and we're fine. I just care for stable modern software development here.

**Comment by cdesjardins** [comment]
@webmaster128 
> We're re-inventing the wheel using python scripts at so many places, which is burning down developer-time like hell and I don't know if it's worth it.

+10

**Comment by mouse07410** [comment]
On Jul 19, 2015, at 15:46 , Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:

There are some things that are kind of personal which I want to answer first

If memory serves, you were unhappy to split the installation command in two: "install" and "install-docs", citing extra complexity that would confuse users.

Not because it confuses users. Because I myself don't want to maintain additional complexity in my spare time to avoid build system breaks that cause frustration. It turns out (surprise surprise) that development power is limited and I don't see a lot of people here taking care of non-gnu-linux targets where everything works like in a paradise.

OK, your point is taken. But if you expect that moving to cmake is going to reduce the maintenance efforts you’d need to invest - I don’t think we’re on the same page.

My platforms are mostly Mac and Linux. I care that it runs with no hitches whatsoever on those.

You say throwing them into the sewer of cmake won't confuse them?! I can't claim to understand your logic.

Here you are mixing up two things: 1. reducing complexity (i.e. number of possible build configurations) and 2. introducing a tool to handle the existing complexity better.

Not really. I don’t think I’m mixing these two - because I have (fairly fresh) experience of how introduction of cmake to a fairly straightforward C++-based project turned its multi-platform deployment into a nightmare.


with the current config, it produces a relatively simple Makefile that can be manually adjusted, which currently is quite easy.

That is a good point and I am absolutely with you on that point. I am not a cmake guru. I hate cmake syntax and I hate that it is nearly impossible to find the right output Makefile that will actually build the code.

In the make-based projects I worked with - there was no Makefile one can speak of. What passed under the name of makefile not only had very little (of useful stuff) to edit - it was hardly readable.

But life is about tradeoffs. And if there are good reasons to introduce a tool, there will be downsides as well. Let's be scientific about that, collect the arguments, weigh them and decide after that.

Right now building Botan on my Macs I have to hand-edit the python-generated Makefile, because of the (slightly) non-standard names and locations of the libraries. E.g., Macports-installed boost is in /opt/local/lib/libboost-mt.dylib, etc. Botany insists it’s  libboost.dylib. But this Makefile edit is trivial - add “-L/opt/local/lib” and append “-mt”.

With cmake it would be next to impossible (based on those several - less than ten - projects that I had to get running in Mac OS X and on Linux CentOS and Ubuntu), which means that if Botan were to move to cmake, I’d probably be unable to install it on (at least) half of my platforms, and would have to abandon the project (and at the time when it finally became quite usable for both C++ and Python callers).


As long as I can think you did not come up with an argument against cmake other than that you are afraid of technology you're not familiar with. If you have experience with projects migrating to cmake, let us know what exactly the problems have been.

My experience is that when several projects were moved to cmake, they stopped being portable across Linux and Mac - its inability to find libraries and components, and our inability to edit the available config files to point it at those components.

I cannot go into details of what those projects were - but it should suffice that those are from my direct first-hand experience.

I don’t doubt that if I was an expect in cmake (or if any of my team-mates was), we’d have been able to solve it. But we weren’t, and we did not have time to master cmake to that point (there were enough of challenges with the primary mission). And a lot was at stake getting those projects running, it was a real pain, and we didn’t come out of this as cmake-lovers (understandably so, I hope).

I don't know what platforms you're targeting because you did not share with us yet.

That I can easily do. Mac OS X Yosemite and Mavericks, some special (but probably irrelevant in this context) config changes that I’m not at liberty to delve into, and a lot of extra packages installed via Macports (such as python2 and python3). Occasional Windows, but if you break that platform, I and my projects won’t suffer. If you make Mac unusable - we’d suffer a lot.


I only know that I already put hundreds of hours into the Botan build system to ensure that Botan builds on Windows, Botan works on Android, Botan can be used in an application with a debug STL, out-of-tree builds work as they should, Botan can be used in a debugger, Botan can be used in a profiler, Botan can be build on multiple cores on Windows. This is stuff I care about. And a lot of this stuff comes for free with cmake or another modern build system.

Here I think I disagree, based on my negative experience (see above).

Are you saying that you already have a working cmake configuration that allows you all of the above, or that you expect cmake to be able to handle this based on its documented capabilities and claims of others?


... I just care for stable modern software development here.

Well so do I. :-)

Except that for me Windows doesn’t really matter (don’t mind if it works, don’t care if it doesn’t), but Mac OS X is crucial. (So is Linux, but I don’t think anybody would let that platform to break, no matter what.)
--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by mouse07410** [comment]
On Jul 19, 2015, at 15:12 , René Korthaus <notifications@github.com<mailto:notifications@github.com>> wrote:
First of all: Nobody of us wants to kill this project. We are all here to improve Botan as good as we can.

OK, granted.

As to your remark regarding CMake - in my experience, this is with all build systems, including the current one. We used SCons and Qt previously, and now use CMake internally for all our C++ projects and we are quite happy with it.

I agree - but with the current system it is easy to manually correct its shortcomings and get the running/working build quickly and easily.

In my experience with CMake this was not the case, and it costed me and my team dearly. Though on one platform (CentOS) for (and on) which the specified CMake config was done for the projects I ranted about in my previous email - it worked quite well. My problem was that I needed those configs to run on CentOS and on Mac OS X. And it just didn’t, no matter what. And there was no makefile or something to manually beat into shape with vi. No editable configuration file (CMakeLists.txt doesn’t count because it didn’t contain anything useful from the above problem’s point of view).

I'd rather not want to create a fork "just" to use another build system. This seems like an odd idea.

Right now after every python configure.py …flags… I manually adjust the generated Makefile. it takes me less that a minute, and the build works flawlessly (for the 1.11.* subversions, probably from 1.11.7 or so). With CMake I’m very likely to lose that ability, and I don’t trust whoever would write CMake config, to do it well enough so it runs on Mac OS X smoothly and doesn’t need a final adjustment like the current build does.

Because of that I want to have assurance that there would be a branch - preferably the mainstream one - that builds with reasonable manual adjustments on Mac OS X. That’s why I suggest that CMake is pushed to a separate branch - while I agree it is an odd idea in general.
--
Uri Blumenthal
uri@mit.edu<mailto:uri@mit.edu>

**Comment by cdesjardins** [comment]
I will just add a note that I have had great success with cmake and cross platform development, I converted a project about 2 years ago that had cross compiled code, host side code, and linux device driver code in it (in other words it had a lot of different parts with different requirements), and the host side code included libraries, and programs that needed to compile and run on windows, mac, linux. All of it was managed with a single cmake build system, and it was my first time using cmake.

Prior to cmake it was a pain in the neck to keep running, any build type change would always break some platform. Then I switched to cmake, and indeed getting it to work on a new platform required some tweaking, but once it was tweaked, it worked well, and continued to work well even when components were moved around, renamed, or other changes were made that would impact the build. (FYI: the project in question was firmware and host side code for the high speed readout of an x-ray camera developed at CERN)

So getting it to work everywhere is not 100% free, but it is totally possible, and once it works it is easy to maintain (despite you claims to the contrary). Then as a bonus you have all the other benefits of cmake: project file generation for almost every dev env, good dependency generation, and a robust cross platform build system.

Now, I use cmake whenever I can.

**Comment by mouse07410** [comment]
Chris,

That's precisely the point. Once somebody gets it [cmake config] for a given platform to work, it's no-brainier to maintain - we're in a perfect agreement here. But from *my* experience, it can be a royal bitch to get it to work in the first place (one of the projects I've whined about failed because the deadlines were too tight for us to break through the cmake maze as we were fighting other fires and resolving other issues with this and other projects). And I'm afraid that it could take rather long time before somebody with both enough expertise and enough of platform similarity comes to fix it for Mac OS X etc.

If are you saying that you can do it, I'd be a happy user of your successful result. But if you're saying that from your experience it "should be" easy to do - then my experience taught me otherwise, in a very painful way.

P.S. The failed project involved building things from c++test package. Cmake was finding it and building everything perfectly on CentOS, but for the life of it we couldn't cajole cmake to detect the corresponding package files on OS X. Silly, but a true story from real life. The clock ran out before we found the "magic word". In other projects we just bolted on our own bash+make build - ugly as a mule, but at least it built what we needed, and before the deadline (and nothing else mattered).

Sent from my iPad

On Jul 20, 2015, at 02:21, Chris Desjardins <notifications@github.com<mailto:notifications@github.com>> wrote:


I will just add a note that I have had great success with cmake and cross platform development, I converted a project about 2 years ago that had cross compiled code, host side code, and linux device driver code in it (in other words it had a lot of different parts with different requirements), and the host side code included libraries, and programs that needed to compile and run on windows, mac, linux. All of it was managed with a single cmake build system, and it was my first time using cmake.

Prior to cmake it was a pain in the neck to keep running, any build type change would always break some platform. Then I switched to cmake, and indeed getting it to work on a new platform required some tweaking, but once it was tweaked, it worked well, and continued to work well even when components were moved around, renamed, or other changes were made that would impact the build. (FYI: the project in question was firmware and host side code for the high speed readout of an x-ray camera developed at CERN)

So getting it to work everywhere is not 100% free, but it is totally possible, and once it works it is easy to maintain (despite you claims to the contrary). Then as a bonus you have all the other benefits of cmake: project file generation for almost every dev env, good dependency generation, and a robust cross platform build system.

Now, I use cmake whenever I can.

**Comment by webmaster128** [comment]
@mouse07410 I understand your concerns (really!) and I will ensure that CMake will not replace the current configure script until it is stable and works for every user who is active in this community. Moving to CMake might take half a year, or a year, or two. But the day will come when we get it right and CMake improve productivity and project interoperability.

At Kullo we build Botan in 4 different platforms today and a 5th is coming: Linux, OS X 10.9+, Windows, Android (and iOS). So I am pretty sure I have a good cross-platform overview.

Let's give it a try, see how far we get, what it can do and what limitations there might be.

ps.: Could you please use Github directly when you're responding to longer discussions including quotes? Nobody wants to do the work to separate your text from the text you are quoting. Thanks!

**Comment by arjunasatria** [comment]
+1

**Comment by kismis** [comment]
+1

**Comment by webmaster128** [comment]
@arjunasatria @kismis Could you please elaborate on why you need VS project files? What exactly are you planing to do with it? Why does the current build system not solve your problem?

There is some cmake action going on but it is very limited right now and only usable for developing and debugging Botan.

**Comment by ksanderon** [comment]
Sorry for being necromancer here. See: #967 - this is only draft but anyway might be useful for someone working on qt-creator, vs, clion or others.

**Comment by webmaster128** [comment]
Is this issue done with the bakefile generator?

**Comment by neusdan** [comment]
For now. It seems Bakefile is no longer actively maintained. So we probably need a replacement. Maybe we can use the CMake generator?

**Comment by ksanderon** [comment]
I'm not sure how looks current situation of cmake generator, however when I'v created it, there was only intention to support some Clion and QtCreator features ;) Anyway generated cmake was good enough to build correctly botan on mac os x, on debian linux on x86_64 and arch linux on arm. 

Support for msvc should not be too hard. 

I think that there is only one major issue eg. missing install tree implementation - I can add it because anyway need it to create [hell package](https://gitlab.com/rili/hell) of botan ;)
