### ISSUE TITLE
Make it possible to disable cli from the build

### ISSUE THREAD

**Issue by randombit** [randombit/botan#2086]
See #2085 from background

**Comment by randombit** [comment]
Maybe generalize it to `--build-targets=` which can accept options `static`, `shared`, `cli`, and `tests`. I believe there is an open issue about how disable-shared, disable-static is confusing especially for Windows targets.

**Comment by reneme** [comment]
> I believe there is an open issue about how disable-shared, disable-static is confusing 

I guess you mean [this one](https://github.com/randombit/botan/issues/2040)?

**Comment by reneme** [comment]
There are already switches like `--build-fuzzers` and `--build-bogo-shim`. In order to keep the default behaviour stable (i.e. the CLI and tests are built), we would need to add "negative" switches like `--no-build-cli` and `--no-build-tests`. That feels inconsistent.

I suggest to go with (something like) `--build-extra-targets=` (accepting a list of `cli`, `tests`, `fuzzers`, `bogo`) that defaults to `cli,tests` and strive to deprecate the above mentioned switches?

I would argue to keep `static` and `shared` out of this in a first step, to keep it simple.

**Comment by randombit** [comment]
Done with #2098
