### ISSUE TITLE
Why is shared lib disabled on MinGW?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#211]
I am configuring Botan on MinGW using  `./configure.py --os=mingw`, where I get

> INFO: Disabling shared lib on mingw

Why is that?

The problem is that in this case the force amalgamation error (b71615cca8b928a5) is not triggered and a static lib without amalgamation is built, which causes segfaults in the tests.

**Comment by randombit** [comment]
It is because of `build_shared no` being set in the osinfo files for MinGW (and also Cygwin). This value is based off of user reports from many years ago and are probably no longer valid; likely a DLL can be built just fine these days. In that case the whole logic for build_shared can be removed as those are the only ones in the build that have it set anymore.

However this points to a build issue: when building a shared library, you also get a static library which actually happens to not work at all. This is a separate issue which I'll open.

**Comment by webmaster128** [comment]
Building a shared lib on MinGW is not trival because of a confusing mix of Unix tools and Windows technology. I'll leave it to someone else to make that happen. In the meanwhile #275 takes care the the user builds a static amalgamation on those platforms.
