### ISSUE TITLE
libFuzzer latest version not compatible wth Botan configure

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#2132]
-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer.
Please either migrate to a compiler that supports -fsanitize=fuzzer
or use an older version of libFuzzer

**Comment by randombit** [comment]
Which version of Clang/libFuzzer is this? Still works for me fine with Clang 8 and I don't see anything about it in the Clang/LLVM 9 release notes (though their release notes are often not too good...)

Anyway it appears -fsanitize=fuzzer is supported since Clang 5 so will just switch over to the new flags, thanks for reporting.

**Comment by nunojpg** [comment]
This was with clang6 and latest libFuzzer
