### ISSUE TITLE
[Question] Choices of algorithms

### ISSUE THREAD

**Issue by CingKong** [randombit/botan#2145]
Just wanna know among all those algorithms supported by botan for now, which is **considered practically**:

the **most secure public key encryption** algorithm;
the **most secure symmetric encryption** algorithm;
the **most secure signature** algorithm;

i personally dont have any knowledge about cryptography (all i know right now is basics learned from the web). and i wanna employ strong cryptography in my next project.

I do **expect (greatly) increased performance cost** when choosing more secure algorithms and greater key lengths. and **currently have no thoughts on defending against quantum computation power**.

i did do lots of Google myself before asking here, but almost all related articles i found didnt do comparison between algorithms or are seriously outdated.

**Comment by CingKong** [comment]
btw is it true that RSA is the only algorithm that support both encryption and signature?

**Comment by randombit** [comment]
This is actually a hard question to answer definitively, because there are different tradeoffs that different algorithms make. There are some that are certainly *not* the most secure, eg, older finite-field based schemes like DSA or ElGamal. But is SM2 more or less secure than ECDSA? It is difficult to say for certain. But here would be my recommendation. These may not be in some certain sense the strongest but they are certainly all very strong, to the point that cryptography will not be your weak point, and they are widely implemented and understood

* Signature: ECDSA with P-521 curve and SHA-512. Or RSA 4096 bit key using PSSR(SHA-512) padding.
* Public key encryption: RSA, 4096 bit key, OAEP(SHA-512)
* Symmetric: AES-256 in SIV mode.

RSA with 3072 bit keys is also perfectly fine in a long term security sense (absent a truly astounding advance in factoring, a 3K RSA key will not be broken until a large QC has been built, large enough that previous iterations of the same machines would have already broken all elliptic curve cryptography in use) and is about twice as fast as 4K.

And yes RSA is the only implemented algorithm with supports both encryption and signature with the same key. Generally it is recommended to never use the same key for 2 purposes though due to risk that a weakness in one mode might allow attacking the other. This for instance is a practical concern if one uses RSA encryption with the terrible, obsolete PKCS v1.5 padding scheme - an oracle attack on the encryption makes it possible to also forge signatures.

**Comment by CingKong** [comment]
had a hard time trying to understand AEAD modes...
In the docs it says "AEAD modes provide message encryption, message authentication, and the ability to authenticate additional data that is not included in the ciphertext"

message authentication seems handled by the cipher? but what about this 'authenticate additional data"?

if im to send the IV and encrypted data together over the network or other mediums, do AEAD modes
still provide extra benefit, compared to normal cipher modes?

**Comment by randombit** [comment]
> do AEAD modes still provide extra benefit, compared to normal cipher modes?

**Yes**: AEAD provides authenticity as well as encryption. This is critical as using just a traditional cipher mode such as CBC provides confidentiality but it does not provide any way of verifying the message has not been tampered with. And, ironically, that lack of authenticity check can allow in some circumstances attacks which break the confidentiality as well. Now, CBC (or CTR, etc) is fine *if* combined with a good authentication code such as HMAC, and in just the right way [there are pitfalls here, sometimes even made by experienced designers, for example the TLS 1.0 CBC+HMAC combination had serious flaws.] The advantage of an AEAD is all of the design work in providing these properties has been done, and analyzed carefully.

An additional advantage of SIV, which caused me to recommend it, is that most AEADs fail somewhat catastrophically if the IV is ever reused two encrypt two different messages under the same key. In contrast SIV still retains excellent security in that case. In fact SIV is even secure if used without a nonce at all (though it is recommended to still use one).

Authenticating additional data is an "extra" that AEAD modes provide (AEAD == "Authenticated Encryption with Associated Data"). Basically it is data which is included in the authentication tag but which is not encrypted. For example if your message has some header data which must not be encrypted, you can included it as associated data which ensures it is still verified as authentic and was not tampered with.

BTW thank you for raising these questions. They are completely reasonable to have and point to areas where we can improve the documentation.

**Comment by CingKong** [comment]
to be honest, i dont quite understand what you are trying to explain to me, due to my bad english and the lack of cryptography knowledge xD

im actually thinking of designing an encrypted messenger for practice purpose, and for now i think im gonna go with "one RSA key for both encryption(OAEP(SHA-512)) and signature(PSSR(SHA-512)) purposes" so every user will have exactly one public key fingerprint, its easier to manage; and AES-256/SIV for symmetric encryption.

thanks for the advice and explanations.

**Comment by CingKong** [comment]
oh one more question, when quantum computer comes, will there be difference between 3k bits and 4k bits of RSA keys?

**Comment by CingKong** [comment]
speaking of documentation, personally i think lists of available algorithms will be perfect.

becuz i did just spend some time on figuring out what algorithms does Botan actually support. and in this file [pk_pad/padding.cpp](https://github.com/randombit/botan/blob/abdcd9f87c07308f89aa4ac449460823286fbf74/src/lib/pk_pad/padding.cpp#L29), it does look like Botan doesnt support PSSR padding for me :v

**Comment by CingKong** [comment]
I think im actually go with ECDSA and ECIES instead.
