### ISSUE TITLE
Remove SHA1 assembler implementation

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#216]
After a couple of benchmarks I think we can drop the assembler implementation of SHA1 because the base implementation was always faster on both 32 and 64 bit systems of different age:

## GCC

g++ 4.9 (64 bit) Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz

```
SHA-160 [sse2] 414.31 [base] 318.68 [x86-64] 229.25
```

GCC 4.9 AMD Phenom(tm) II X6 1055T Processor × 6

```
SHA-160 [sse2] 422.79 [base] 362.17 [x86-64] 298.40
```

g++ 4.8 (32bit) Pentium(R) Dual-Core CPU E5400 @ 2.70GHz

```
SHA-160 [sse2] 326.81 [base] 238.34 [x86-32] 228.83
```

g++ 4.8 (64bit) AMD Athlon(tm) 64 X2 Dual Core Processor 5600+

```
SHA-160 [base] 298.18 [sse2] 286.89 [x86-64] 261.87
```

## Clang

Clang 3.6 AMD Phenom(tm) II X6 1055T Processor × 6

```
SHA-160 [sse2] 413.41 [base] 313.90 [x86-64] 294.66
```

**Comment by etcimon** [comment]
This isn't the first time I see GCC/clang optimizing crypto better than hand-written assembly algorithms. Did you run this on other algorithms too?

**Comment by webmaster128** [comment]
Not yet but there are not a lot of assember implementations:

```
$ find . -name "*.S"
./src/lib/hash/sha1_x86_64/sha1_x86_64_imp.S
./src/lib/hash/md5_x86_32/md5_x86_32_imp.S
./src/lib/hash/sha1_x86_32/sha1_x86_32_imp.S
./src/lib/hash/md4_x86_32/md4_x86_32_imp.S
./src/lib/block/serpent_x86_32/serp_x86_32_imp.S
```

Feel free to benachmark the orthers. I used

```
./configure.py && make -j $(nproc) && ./botan speed SHA-160
```

**Comment by etcimon** [comment]
They've probably all been defeated by the compilers in that case. I've been puzzled by this 2 other times before, out of 2.

**Comment by etcimon** [comment]
In my tests, SSE2 and SSSE3 assembly was also slower than GCC/LLVM, for siphash from here:
https://github.com/floodyberry/siphash

**Comment by webmaster128** [comment]
Same goes for MD4, MD5 and Serpent is even

```
./botan speed MD4 && ./botan speed MD5 && ./botan speed Serpent
MD4 [base] 551.49 [x86-32] 535.79
MD5 [base] 397.05 [x86-32] 381.28
Serpent [simd32] 138.06 [x86-32] 51.20 [base] 48.27
```

So I think they must all die in favour of maintainability.

**Comment by etcimon** [comment]
It would hold true for removal of any hand-written assembly as a whole

**Comment by randombit** [comment]
All of these asm versions were excellent wins in the GCC 2.95 to 3.3 timeframe but are certainly not worth it anymore. Fortunately being able to remove all of them allows  removing the machinery for handling .S files entirely; while I expect SIMD intrinsics and inline asm will continue to see use, writing an entire file in asm is kind of a pain (especially portability wise) and is hardly worth it with modern compilers. I do think with sufficiently fanatical devotion to understanding the microarchitecture you can still see pretty big wins with asm, but in terms of maintenance the results are not worth the cost. I'm inclined these days to call other providers instead when performance is key and take advantage of the work that goes into OpenSSL and the OS crypto drivers, rather than duplicating that effort.

The inline asm used for the low level BigInt code is still quite a bit faster (20-50%) than what GCC produces for the generic C equivalents
