### ISSUE TITLE
Trusting given self-issued cert w/o knowing root CA

### ISSUE THREAD

**Issue by ben-dl** [randombit/botan#2167]
Hey,

I happen to need to connect to a TLS server which presents a self-issued (not self-signed) certificate which I am unable to get the root CA cert for.

Is it possible to trust this particular certificate using Botan? Adding it to the cert stores won't work (I assume this would only work for self-signed certs?):
```Certificate validation failure: Certificate issuer not found```

Or if not feasible, is it possible to go the nuclear option and disable certificate verification altogether (I should mention that I don't really care about the datas security, it's just that the server uses TLS)?
Or is there maybe an option in between that I've missed so far / googled the wrong question?

Any help would be really appreciated as I am new to TLS and x509, and don't hesitate to close this if I'm asking a _really_ stupid question :)

Thanks

**Comment by randombit** [comment]
Interesting situation.

There is no way to actually verify the certificate, because the key that generated the signature which would be used to verify it is unknown, because it is in the missing root cert. If you can convince the server admin to publish their root cert that would be good. But if not what you can do though is override `TLS_Callbacks::tls_verify_cert_chain` and basically do

```
    {
    if(cert_chain.size() == 1 && cert_chain[0].fingerprint() == "..." && hostname == "...")
       return;
    return TLS_Callbacks::tls_verify_cert_chain( ... args);
   }
```

ie for this one specific host, accept this one certain certificate as valid even if it would otherwise have failed the validity check.

**Comment by randombit** [comment]
If above is unclear or if you are having further issues feel free to reopen
