### ISSUE TITLE
Push minimal Python version to 2.7

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#217]
At some points in docs and scripts it is stated that Botan (especially `./configure.py`) is compatible with Python 2.6.

Nobody is testing this and even on Travis we cannot install Python 2.6, because it is [not available in Ubuntu 12.04](https://wiki.ubuntu.com/PrecisePangolin/ReleaseNotes/UbuntuDesktop#PrecisePangolin.2BAC8-ReleaseNotes.2BAC8-CommonInfrastructure.Python_Toolchain). Given that Python 2.7 and 3.x are default in Linux from early 2012, I think we should push the minimum version to 2.7, which we are able to test.

That would allow us to move from [optparse](https://docs.python.org/2/library/optparse.html) to [argparse](https://docs.python.org/2/library/argparse.html) for example.

Is anyone using Python 2.6 for any reason?

**Comment by mouse07410** [comment]
Nobody is testing this and even on Travis we cannot install Python 2.6, because it is not available in Ubuntu 12.04<https://wiki.ubuntu.com/PrecisePangolin/ReleaseNotes/UbuntuDesktop#PrecisePangolin.2BAC8-ReleaseNotes.2BAC8-CommonInfrastructure.Python_Toolchain>.


Well, it is the default (and I think the only officially available version) on CentOS. :-(


But regardless:


Given that Python 2.7 and 3.x are default in Linux from early 2012, I think we should push the minimum version to 2.7, which we are able to test.

That would allow us to move from optparse<https://docs.python.org/2/library/optparse.html> to argparse<https://docs.python.org/2/library/argparse.html> for example.


Well, if you plan to make the code explicitly incompatible with 2.6, I'm not thrilled about it - but since there seem to be good enough reasons, I'd say let's go for it.


Is anyone using Python 2.6 for any reason?


Yeah... But my "normal" platforms (i.e. those I have direct control over :) all run 2.7.10 and 3.4. I don't require 2.6 compatibility.

**Comment by webmaster128** [comment]
Right, it is default on CentOS 6.6. CentOS 7 comes with Python 2.7 ([source](http://distrowatch.com/table.php?distribution=centos)). But given that CentOS 6 runs GCC 4.4, that is not a target for Botan.

**Comment by randombit** [comment]
Dropping 2.6 does offer advantages; it is much easier to write Python in the common subset of 2.7 and 3.x than in the common subset of 2.6, 2.7 and 3.x, as 2.7 saw many changes explicitly to be more py3 compatible.

And as of Oct 21 2013 Python 2.6 is retired and not supported anymore upstream https://www.python.org/download/releases/2.6.9/
