### ISSUE TITLE
Features: TLS 1.3

### ISSUE THREAD

**Issue by franziskuskiefer** [randombit/botan#2185]
Add TLS 1.3 support.

I see a couple things related to TLS 1.3, what's the plan for adding TLS 1.3 support?

**Comment by randombit** [comment]
It is on the roadmap but it is a big project and I have only so much free time.

A couple of companies have expressed interest in funding the work but then wandered off :shrug:

If everything goes well it will probably be available sometime next year.

**Comment by pfeatherstone** [comment]
Look forward to this

**Comment by yildizmert1** [comment]
is there any progress about TLS v1.3 ? Do you have a planned release date?

**Comment by randombit** [comment]
It looks like there may be a source of funding for me and also some dev assistance starting early next year. Nothing is certain yet but :crossed_fingers: if all goes well Botan 3.0 will be released early summer 2021 with TLS 1.3 support.

**Comment by pfeatherstone** [comment]
Maybe people will start using botan for their QUIC library rather than using an OpenSSL fork.

**Comment by yildizmert1** [comment]
thank you for your quick reply.

**Comment by pist-eb** [comment]
@randombit: We are strongly interested in having the TLS 1.3 support in Botan.
We are looking forward for further steps and contact with community. Is the LLC discussed in the telco already OK?

**Comment by yildizmert1** [comment]
Any progress on TLS 1.3 ? We look forward to the developments on this subject. Last year, "Botan 3.0 will be released in early summer 2021 with support for TLS 1.3." you said. So do you have any plans to release a new version soon?
We are currently using Botan and we love it. We want to continue to use this library. But we need TLS 1.3 version support. That's why I wanted to ask about this. All the best!

**Comment by reneme** [comment]
Botan 3.0 is now released with support for TLS 1.3: https://github.com/randombit/botan/issues/3209#issuecomment-1503171315
