### ISSUE TITLE
Dose botan support RSA PrivateKey encryption and PublicKey decryption?

### ISSUE THREAD

**Issue by hsllany** [randombit/botan#2214]
OpenSSL supports such methods like RSA_public_decrypt(), RSA_private_encrypt. Dose Botan support similar functions? 
We have some scenarios using this kind of encryption and decryption method.

Thanks very much.

**Comment by randombit** [comment]
Yes. Despite the name, these OpenSSL functions perform a signature operation using either no padding at all (RSA_NO_PADDING) or PKCS v1.5 signature padding but without the usual algorithm identifier that is included in PKCS v1.5.

For no padding, create a `PK_Signer` with padding method "Raw".

For PKCS v1.5 padding without an algorithm identifier, use "EMSA3(Raw)".

**Comment by hsllany** [comment]
We are not using these methods for signature, but just only decrypt(using public key) and encrypt(using private key). 
Does Botan support such lower-level methods to accomplish the goal?

**Comment by randombit** [comment]
Nonetheless, and despite the poorly chosen name, these interfaces are intended to generate signatures. Quoting https://www.openssl.org/docs/man1.1.0/man3/RSA_public_decrypt.html

> RSA_private_encrypt() **signs** the flen bytes at from (usually a message digest with an algorithm identifier) using the private key rsa and stores the **signature** in to.

They are useless for encryption because if you give someone the private key to encrypt a message to you, they can easily also decrypt any message to you. At that point it has the same functionality as a symmetric cipher like AES, except slower.

But in any case you can replicate these operations as described above.

**Comment by hsllany** [comment]
Thanks, randombit. 
You are right. RSA privateKey encryption doesn't make sense. We will change it to AES.
