### ISSUE TITLE
Can we change the behavior of BigInt::random_integer?

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#222]
`BigInt::random_integer(rng, min, max);` returns an integer strictly less than `max`. This is not intuitive and a mathematically precise name for the last parameter should be `strict_upper_bound`.

@983 found that design choise questionable and asked to add the follwing documentation note:

> Generate a random integer that is at least as big as min and strictly less than max

Still, the name `max` is not really helping.

Now I checked how the method is used and it turned out that is most cases, the user wants to set the range [a, b] including the upper bound (see all the `-1`s).

```
src/cmd/factor.cpp-BigInt rho(const BigInt& n, RandomNumberGenerator& rng)
src/cmd/factor.cpp-   {
src/cmd/factor.cpp:   BigInt x = BigInt::random_integer(rng, 0, n-1);
src/cmd/factor.cpp-   BigInt y = x;
src/cmd/factor.cpp-   BigInt d = 0;
--
src/lib/math/numbertheory/numthry.cpp-   for(size_t i = 0; i != test_iterations; ++i)
src/lib/math/numbertheory/numthry.cpp-      {
src/lib/math/numbertheory/numthry.cpp:      const BigInt a = BigInt::random_integer(rng, 2, n_minus_1);
src/lib/math/numbertheory/numthry.cpp-      BigInt y = pow_mod(a);
src/lib/math/numbertheory/numthry.cpp-
--
src/lib/pubkey/dsa/dsa.cpp-
src/lib/pubkey/dsa/dsa.cpp-   if(x == 0)
src/lib/pubkey/dsa/dsa.cpp:      x = BigInt::random_integer(rng, 2, group_q() - 1);
src/lib/pubkey/dsa/dsa.cpp-
src/lib/pubkey/dsa/dsa.cpp-   y = power_mod(group_g(), x, group_p());
--
src/lib/pubkey/ecc_key/ecc_key.cpp-
src/lib/pubkey/ecc_key/ecc_key.cpp-   if(x == 0)
src/lib/pubkey/ecc_key/ecc_key.cpp:      private_key = BigInt::random_integer(rng, 1, domain().get_order());
src/lib/pubkey/ecc_key/ecc_key.cpp-   else
src/lib/pubkey/ecc_key/ecc_key.cpp-      private_key = x;
--
src/lib/pubkey/nr/nr.cpp-
src/lib/pubkey/nr/nr.cpp-   if(x == 0)
src/lib/pubkey/nr/nr.cpp:      x = BigInt::random_integer(rng, 2, group_q() - 1);
src/lib/pubkey/nr/nr.cpp-
src/lib/pubkey/nr/nr.cpp-   y = power_mod(group_g(), x, group_p());
```

std::rand() and Python's  random.randint() also include the upper value. Java's java.util.Random.nextInt does exclude it but calls it `bound`.

Can we break this behaviour in favour of a more intuitive interface?

**Comment by randombit** [comment]
Changing the existing function might be dangerous to callers to are relying on the current (documented, even!) interpretation of maximum. For example in the ECC keygen code above, random_integer returning max would result in a key of zero, even though it is correct now. With the current meaning of maximum I think the callers with -1s are mostly (perhaps all) incorrect.

Clearly the misuse within the library itself suggests this is a confusing API. But `random_integer` has had its current behavior since at least 1.8 (and likely long before that); silently and subtly changing its meaning doesn't feel right; when things break they should break obviously by not compiling anymore. I think it better to define a new interface and define `random_integer` in terms of it, then perhaps also update internal callers of `random_integer`.

**Comment by webmaster128** [comment]
Jap, thats good. Let's define `BigInt::random_int(rnd, min, max)`.

Do you think it is necessary to keep the existing interface with renamed parameters `BigInt::random_integer(rnd, min, bound)`? I'd suggest removing it and deal with some easy to fix compile errors on the user side in favour of a minimal intuitive API.

**Comment by randombit** [comment]
For now let's mark it with a BOTAN_DEPRECATED annotation.

**Comment by webmaster128** [comment]
Kay, I am going to do this after 1.11.19

**Comment by randombit** [comment]
I don't think we want to make any further changes in this space, closing.
