### ISSUE TITLE
Build fails for MIPS-1 VERSION 1

### ISSUE THREAD

**Issue by pfeatherstone** [randombit/botan#2235]
Preface : The only compiler suite you can get for MIPS-1 VERSION 1 is gcc-4.8.5 using uclib. 

Issue 1 : In workfactor.cpp, for some reason, the compiler doesn't like std::log2. Instead i replace #include <cmath> for #include <math.h> and replace std::log2 for log2. 

Issue 2 : I think uclibc doesn't support getauxval. So you have to undefine BOTAN_TARGET_OS_HAS_GETAUXVAL

**Comment by randombit** [comment]
Thanks for the report.

For getauxval you can configure with ``--without-os-features=getauxval`` to disable use without having to hack the source.

Weird about `std::log2`. Maybe that code can be rewritten to use integer math ...

**Comment by randombit** [comment]
It looks like both uses of `log2` in workfactor.cpp can be precomputed instead. Is this the only symbol that causes problems?

I think this is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79017

**Comment by pfeatherstone** [comment]
Yes std::log and std::exp were fine

**Comment by pfeatherstone** [comment]
Though I'm using gcc 4.8.5

**Comment by randombit** [comment]
Now we avoid `std::log2` since it seems like this issue can arise anytime an older GCC is used with a limited libc. For `getauxval` it would be nice to be able to detect support at build time, but there is a clean way to disable use at configure time. So I am considering this resolved. Thanks again for reporting.
