### ISSUE TITLE
Documentation fails to build with Sphinx 3.0, works with doxygen

### ISSUE THREAD

**Issue by kekePower** [randombit/botan#2324]
```
Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/domains/cpp.py", line 7171, in _resolve_xref_inner
    assert parentSymbol  # should be there
AssertionError
The full traceback has been saved in /tmp/sphinx-err-u7eh2ihg.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

Please see [the full build log](https://raw.githubusercontent.com/kekePower/mmbl/6ddfe29086def989b9867c1893548acd716a5939/2020/04/07/20%3A07%3A51/botan2-2.14.0-1.mga8.src.rpm/build.0.20200407175517.log).

**Comment by randombit** [comment]
Confirmed. I don't think this is a problem with our docs and needs to be reported upstream.

**Comment by randombit** [comment]
In https://github.com/sphinx-doc/sphinx/issues/7438 it is noted this only occurs when using parallel builds, and I am seeing the same here. So #2326 disables use of `-j` when invoking sphinx if the version >= 3.0. Once the bug is fixed in a new version of Sphinx, we can enable `-j` again for those versions.

**Comment by randombit** [comment]
Fixed now in master, thanks for reporting this and checking the patch
