### ISSUE TITLE
Signatures created by botan vs openssl

### ISSUE THREAD

**Issue by saiftyfirst** [randombit/botan#2356]
Hello, I would like to use botan to implement a signing feature in my work. Here is what I have so far:
(I am using the botan python interface)

I create a **ecdsa** keypair with params **secp256k1**. Then my idea is to create a signature from a provided message. What I would like to know is the difference between signatures created using botan and openssl with identical parameters. The verification software I am using cannot read the signature I output from botan so I am guessing it might be some encoding issue. In any case, it would be very helpful if I could know what happens or the difference between the following:

1. Signature produced using: botan_pk_op_sign() with hash/padding 'EMSA1(SHA-256)'
2. openssl dgst -sha256 -sign private-key.pem data > sig1

Many thanks. Apologies in advance, if I have made some rookie assumptions and mistakes

**Comment by randombit** [comment]
You're right about the encoding issue I think. ECDSA signatures contain two values r and s, and there are two different ways these values are commonly serialized - in a DER struct, or using an encoding specified in IEEE1363. By default for ECDSA signatures OpenSSL `dgst` produces DER format, while Botan uses IEEE1363.

Normally the fix is easy, as you just have to specify using DER output. However you reference `botan_pk_op_sign` and it turns out the C API doesn't allow specifying DER output! I'm not sure how that got missed.

You can re-encode the IEEE1363 signature by splitting it in half then using an ASN.1 library to form it into

```
ECDSASignature ::= SEQUENCE {
    r   INTEGER,
    s   INTEGER
}
```

https://crypto.stackexchange.com/questions/1795/how-can-i-convert-a-der-ecdsa-signature-to-asn-1 has some hints for doing this without pulling in a whole ASN.1 lib.

I will of course add the ability to produce DER output but that doesn't help much if you are relying on distro-provided packages, etc.

If it's possible to use the C++ API here all you need to do is pass a 4th argument `Botan::DER_SEQUENCE` when constructing `PK_Signer` and it works. We just never plumbed this through to the C (or Python or ...) APIs :/

**Comment by randombit** [comment]
If it's possible for you to just patch then https://github.com/randombit/botan/pull/2357 should do the trick.

**Comment by saiftyfirst** [comment]
Awesome. Worked !!
