### ISSUE TITLE
Is there any reason for tls_record_received data being const?

### ISSUE THREAD

**Issue by GeryEmreis** [randombit/botan#2360]
Hi, would it be possible to modify tls_record_received callback to accept data as non-const parameter? I need to modify received record and it being const forces me to make copy, which is ineffective.

**Comment by randombit** [comment]
Can you explain more about your use case? The data that is passed to `tls_record_received` is a persistent buffer which is reused across records. So even if it is not const, and you modify it, you would still have to copy it if you want to be able to use the data in some way after the callback returns. I just can't think of a case where a) you need to modify the data but b) you don't need that data to live past the current callback invocation.

In the short term it can't be changed to non-const since that would break existing code. It's possible we could make it non-const in a future major release if that makes sense.

**Comment by randombit** [comment]
I guess I should mention that it is safe to `const_cast` the data pointer and modify it, as long as you remember that nothing in the buffer lives after the callback returns.

**Comment by nunojpg** [comment]
I had the exact same requirement. I need to modify the data before passing it somewhere else, and before returning from `tls_record_received`.

While it would be very convenient to me I didn't think it would warrant changing the API, which could also cause implementation limitations in the future.

Don't expect to be able to use 100% upstream, sometimes you need something custom. Part of the job.

**Comment by randombit** [comment]
I don't think we want to document or guarantee that `const_cast` of the record buffer will work in the long run, since it constrains our options and may interplay badly with various 1.3 features. (It should work fine in 2.x releases, however)
