### ISSUE TITLE
Build dynamic library from *.o files

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#237]
As Jack pointed out, when we build a shared library (.so), we are building a static library (.a) first:

> when building a shared library, you also get a static library which actually happens to not work at all.

This might be confusing for the user because he or she might think it is possible to link an application against the static archive. This will not work because linker throws away objects and algorithms will not be registered.

Additionally, I don't know which library a linker would choose if we just give it `-lbotan` and there is `libbotan.a` and `libbotan.so`.

However, I think we can easily build the shared object directly from the compilation objects. I found sample code like that one:

```
$ gcc -shared -Wl,-soname,libctest.so.1 -o libctest.so.1.0   *.o
```

**Comment by mouse07410** [comment]
If you compile with -fPIC, you should be able to build shared just like you described.

Except that on Mac OS X the flags would be different. E.g., -dynamiclib instead of (or in addition to) -shared, .dylib instead of .so, no support for -Wl,-soname, etc.

Sent from my iPad

On Aug 6, 2015, at 02:50, Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:


As Jack pointed out, when we build a shared library (.so), we are building a static library (.a) first:

when building a shared library, you also get a static library which actually happens to not work at all.

This might be confusing for the user because he or she might think it is possible to link an application against the static archive. This will not work because linker throws away objects and algorithms will not be registered.

Additionally, I don't know which library a linker would choose if we just give it -lbotan and there is libbotan.a and libbotan.so.

However, I think we can easily build the shared object directly from the compilation objects. I found sample code like that one:

$ gcc -shared -Wl,-soname,libctest.so.1 -o libctest.so.1.0   *.o

**Comment by randombit** [comment]
This is pretty much what is happening now right?

{{{
g++ -m64 -pthread -fstack-protector -shared -fPIC -Wl,-soname,libbotan-1.11.so.19  build/obj/lib/alloc_locking_allocator.o [....]  -o ./libbotan-1.11.so.19.19
}}}

Maybe the better solution is to define the build as targetting precisely one of static library or shared library, instead of --enable-shared/--disable-shared with the implicit static library, having something like --build-library-type={static,shared}?

**Comment by webmaster128** [comment]
You are right, my fault. I was somehow assuming the .a would be used.

Then we just need to remove this Make target for shared libs:

```
$(STATIC_LIB): $(LIBOBJS)
	$(RM) $(STATIC_LIB)
	$(AR) $(STATIC_LIB) $(LIBOBJS)
	$(RANLIB) $(STATIC_LIB)
```

I think that's an easy job since this is already done on Windows.

The renaming of the configure parameter makes sense. I'll try to come up with something shorter ...

**Comment by mouse07410** [comment]
Well, all the object files have to be compiled with -fPIC flag for this to work.
Which is currently happening: SO_OBJ_FLAGS -> LIB_FLAGS.

My point regarding .so vs .dylib, -shared vs dynamiclib, and -Wl,... not supported stands - but again, the current configuration takes care of that correctly.

So I'm not sure if I want to diverge from what most of the packages are doing now - aka generating both shared and static libraries. It just doesn't make sense to force the config to generate one or the other.

________________________________

**Comment by randombit** [comment]
It could be allowable (and even the default) to build both targets (=static,shared). Enabling building a static library would trigger building via the amalgamation, which is a requirement we are already trying to capture with the current checks (eg on disable-shared).

**Comment by webmaster128** [comment]
At lot of `configure.py`'s code and naming has shifted from "with shared lib" to "shared lib or static lib", which is great to get a simple and maintainable build system. This is also about consistency. On Windows for example it is just not possible to build a DLL and a static lib at the same time because when you build a .dll, you also get a very small .lib, which does contain some kind of index that is used when you link an application against the library. This .lib index file conflicts with the name of a static library on Windows: `botan.lib`.

Thus I'd opt for the either or choice.

> It just doesn't make sense to force the config to generate one or the other.

It does. Please read my initial post. You find the background for Jack's statement in #128.

Ps.: @mouse07410 your comments about different naming of the same stuff on OS X are not helping because all this is handled nicely by `src/build-data/os/*.txt` and `src/build-data/cc/*.txt`.

**Comment by webmaster128** [comment]
This is obsolete given that the current master supports static non-amalgamations.
