### ISSUE TITLE
get AES-256/CBC Key and IV as a variable for share and print

### ISSUE THREAD

**Issue by saeid0034** [randombit/botan#2393]
hi sorry for this question im a new on c++
im use botan on my project to encrypt some string
i need to send encrypted string to my server, also i need send key an IV (random generated) to my server too
but i can get random key and IV
can you show me how can i do that?

thanks for great work

**Comment by randombit** [comment]
If you have a client and a server communicating, and you aren't sure about what you are doing I would heartily recommend using TLS instead of cobbling something together. The library has a lot of very sharp bits (things which seem to have desired result but which have subtle or not so subtle failure modes) because it's intended as a general toolkit to implement any necessary protocol. That's useful in the sense that it is possible with this library to implement any of IPsec or TLS or PGP or Signal protocols with it, but also makes it fairly unsafe unless you do know what you are doing.

Specific examples
 - You mention you are going to send the key to the server. But unless you use public key encryption, anyone who can see the traffic can just take the key off the wire and decrypt your message.
 - CBC mode does not provide message authentication so message modification attacks are possible
 - CBC mode is vulnerable to padding oracle attacks which allow an attacker to decrypt arbitrary messages
 - I'm guessing your first design would fail to account for message reordering attacks, conversation replays, etc

TLS resolves all of these issues and many others besides. Please just use TLS. https://botan.randombit.net/handbook/api_ref/tls.html

But in the interest of giving you enough cryptographic rope to hang yourself (which probably should be the library's motto) - there are several RNG types that can be used (https://botan.randombit.net/handbook/api_ref/rng.html). The simplest is to use the system provided RNG:

```
System_RNG rng;
auto cipher_key = rng.random_vec(32);
auto cipher_iv = rng.random_vec(16);
```

Then you can use the `Cipher_Mode` interface to encrypt (https://botan.randombit.net/handbook/api_ref/cipher_modes.html)

**Comment by saeid0034** [comment]
> If you have a client and a server communicating, and you aren't sure about what you are doing I would heartily recommend using TLS instead of cobbling something together. The library has a lot of very sharp bits (things which seem to have desired result but which have subtle or not so subtle failure modes) because it's intended as a general toolkit to implement any necessary protocol. That's useful in the sense that it is possible with this library to implement any of IPsec or TLS or PGP or Signal protocols with it, but also makes it fairly unsafe unless you do know what you are doing.
> 
> Specific examples
> 
> * You mention you are going to send the key to the server. But unless you use public key encryption, anyone who can see the traffic can just take the key off the wire and decrypt your message.
> * CBC mode does not provide message authentication so message modification attacks are possible
> * CBC mode is vulnerable to padding oracle attacks which allow an attacker to decrypt arbitrary messages
> * I'm guessing your first design would fail to account for message reordering attacks, conversation replays, etc
> 
> TLS resolves all of these issues and many others besides. Please just use TLS. https://botan.randombit.net/handbook/api_ref/tls.html
> 
> But in the interest of giving you enough cryptographic rope to hang yourself (which probably should be the library's motto) - there are several RNG types that can be used (https://botan.randombit.net/handbook/api_ref/rng.html). The simplest is to use the system provided RNG:
> 
> ```
> System_RNG rng;
> auto cipher_key = rng.random_vec(32);
> auto cipher_iv = rng.random_vec(16);
> ```
> 
> Then you can use the `Cipher_Mode` interface to encrypt (https://botan.randombit.net/handbook/api_ref/cipher_modes.html)

thanks for fast reply and good information
can you please provide some example from using TLS?
also i use `Botan::AutoSeeded_RNG rng;` for rng

**Comment by saeid0034** [comment]
this is the code i use
`Botan::AutoSeeded_RNG rng;
Botan::SymmetricKey key("7A24432505094A404E635266556A586E3272357538782F4125442A472D4B6150");
Botan::InitializationVector IV("E3272357536060F4125442A472D4B615");
Botan::SymmetricKey key_rnd(rng,32);
Botan::InitializationVector IV_rnd(rng,16);
// ----- END Botan Key And IV Gen ----- //

MainWindow2::MainWindow2(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow2)
{
    ui->setupUi(this);
    Botan::InitializationVector init;
}

MainWindow2::~MainWindow2()
{
    delete ui;
}

void MainWindow2::on_pushButton_clicked()
{
    Botan::Pipe pipe(Botan::get_cipher("AES-256/CBC",key_rnd,IV_rnd,Botan::ENCRYPTION),new Botan::Hex_Encoder);
    pipe.process_msg(ui->textEdit_input->toPlainText().toStdString());
    std::string m1=pipe.read_all_as_string(0);
    ui->textEdit_output_E->setText(QString::fromStdString(m1));
    ui->textEdit->setText("key: " + QString::fromStdString(key_rnd.to_string()));
    ui->textEdit->append("IV: " + QString::fromStdString(IV_rnd.to_string()));
}`

**Comment by reneme** [comment]
> can you give me some sample example to use TLS?

Botan on its own is not enough to communicate with a server via TLS. It implements the TLS protocol in a "transport agnostic" way, emitting the data frames to be sent to the server and processing the server's responses. Or vice versa. It's the responsibility of the application to send and receive that data to and from the server.

We created an example application based on Boost ASIO (for the TCP socket) and Boost beast (for the HTTP implementation) to perform a simple HTTP request via TLS (provided by Botan). Please see here:

https://github.com/reneme/botan-tls-example

Though, judging from your example, you are building your application on top of Qt. Depending on your use-case you might want to consider using Qt's [QNetworkAccessManager](https://doc.qt.io/qt-5/qnetworkaccessmanager.html). This also comes with TLS and HTTPS built-in (based on OpenSSL by default) and will probably work more seamlessly in your Qt application.

**Comment by saeid0034** [comment]
i think with all help from you two guys my problem solved
thanks
