### ISSUE TITLE
Feature request : make tls_emit_data pass ownership of data, rather than requiring a copy

### ISSUE THREAD

**Issue by pfeatherstone** [randombit/botan#2398]
In tls_callbacks.h, the class ```Callbacks``` has a pure virtual function ```tls_emit_data```. It would be great if the argument was an rvalue reference to std::vector<uint8_t> instead of the current arguments.
So make the function signiture:
```
virtual void tls_emit_data(std::vector<uint8_t>&& data) = 0;
```
This way, the user can move the data and avoid extra copies. Everyone is happy.

**Comment by randombit** [comment]
If I'm understanding correctly, if we `move` the output buffer in order to pass it to `tls_emit_data`, then we can't use it again, even if the callback doesn't need to take ownership. And IIRC, once any object has been moved from, accessing it is UB. Which is really unfortunate since making a moved-from vector a valid empty vector (all-zero pointer/length/capacity) would have been easy, but so it goes.

So we would need to allocate a new output buffer for each record, because we would not know if the callback had consumed the vector or not. That would seem to add worse overhead, in that the allocation and memcpy becomes mandatory and unavoidable, but is hidden from the application.

A variant which might work? But has somewhat less intuitive API; pass by reference:

```
virtual void tls_emit_data(std::vector<uint8_t>& data) = 0;
```

The callback may either copy the data or if it wishes to take ownership of the memory, then it swaps the passed vector with an empty one. Or it could even swap in some random vector it happened to have around, eg a temporary buffer it doesn't need anymore. Basically upon return the vector would assumed to still be valid (eg not moved-from) but with indeterminate size and contents.

Nothing can change here for 2.x but I'm open to making a change along these lines for 3.0

There some complications here because the internal write buffer is actually a `secure_vector` which is an artifact of a limitation of the AEAD API. Probably the solution is to improve the AEAD API so it could encrypt plain `vector` or raw byte arrays.

**Comment by pfeatherstone** [comment]
Using std::swap is also fine. Either way, less copies.

**Comment by pfeatherstone** [comment]
On the same topic, in ```tls_channel.h```, also have a version of ```send``` taking a forwarding reference to ```vector<uint8_t>```.
So also have a function signiture:
```
void send(std::vector<uint8_t>&& buf);
```
So botan can consume the vector in an efficient manner.

**Comment by pfeatherstone** [comment]
Or again, pass by reference and use std::swap. Either way, have a zero copy ```send```

**Comment by randombit** [comment]
We ended up using `span` instead here instead. I think the move-from or swap semantics would be ok, but more complicated/buggy to implement, and either way it's not really zero copy because we have to allocate a new buffer underneath for each record instead of reusing the buffer.
