### ISSUE TITLE
Mac OS dylibs shouldn't have trailing version numbers

### ISSUE THREAD

**Issue by dunn** [randombit/botan#241]
Building 1.11.19 on Mac OS 10.10.4 creates `libbotan-1.11.dylib.19` and `libbotan-1.11.dylib.19.19`.  They should instead be `libbotan.1.11.19.dylib` and `libbotan.1.11.19.19.dylib`.

Thanks!

**Comment by webmaster128** [comment]
Wow, thanks for bringing Botan to Homebrew. This is great for our community. I'll go for that before the next release!

**Comment by webmaster128** [comment]
Is changing dash to dot in `libbotan-1.11*` -> `libbotan.1.11*` essential?

**Comment by mouse07410** [comment]
I think it is not essential, because "libbotan-1.11.dylib" has been working fine for me for ages. Maybe it is against Mac philosophy - I dint know. But it works.

Sent from my iPad

On Aug 24, 2015, at 05:22, Simon Warta <notifications@github.com<mailto:notifications@github.com>> wrote:


Is changing dash to dot in libbotan-1.11* -> libbotan.1.11* essential?

**Comment by webmaster128** [comment]
@dunn Could you please confirm if #260 or rather https://github.com/webmaster128/botan/tree/soname serves your needs?

**Comment by dunn** [comment]
Oh, changing dash to dot is not essential; that was actually a typo.  I'll try building your branch, but as long as it names the dylibs correctly then :+1:

**Comment by webmaster128** [comment]
I think it does. But build system can be a tricky complex bitch ;)

**Comment by dunn** [comment]
Your patch seems to do the trick, thanks!
