### ISSUE TITLE
DTLS Session Cache/Manager

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#2421]
Hi,

What is a example use of Session cache/Manager when using TLS::Server (I am just using for datagram, don't know if it's a special case)?

**Comment by randombit** [comment]
https://github.com/randombit/botan/blob/master/src/cli/tls_proxy.cpp#L487-L503 is probably a good example. There isn't anything special about DTLS here.

**Comment by nunojpg** [comment]
@randombit sorry, how to use is clear, but what is the use? It reduces the handshake length if a session is already cached? The idea is that the server can be destroyed and recreated and re-use the session?

**Comment by randombit** [comment]
If there is a cache hit then the TLS handshake has fewer round trips, and is also less computationally expensive because most public key operations are avoided.

If the cache is persistent (eg a database like `Session_Manager_SQLite` or something custom implemented in your application) then even after server restarts the session can resume.

If the cache is transient (`Session_Manager_In_Memory`) then if the server restarts it will not be able to resume the session. However it will still be able to resume sessions if the same client connects more than once in the time the server is up.

**Comment by nunojpg** [comment]
Ok thanks.
