### ISSUE TITLE
Have the tag as part of final input

### ISSUE THREAD

**Issue by vgarridosm** [randombit/botan#2423]
I need some help.
I am trying to do a decrypt using AES EAX (AE) but Botan throw an internal error: "Have the tag as part of final input". How can I do the decrypt without validate the tag?

This is my code:

```c++
   std::unique_ptr<Botan::Cipher_Mode> aEncoder = Botan::Cipher_Mode::create("AES-256/EAX", Botan::DECRYPTION);
   aEncoder->set_key( theKey );
   Botan::secure_vector<uint8_t> aIV{theIV.begin(), theIV.end()};
   Botan::secure_vector<uint8_t>aBuffer{theCipherPayload.begin(), theCipherPayload.end()};
   aEncoder->start(aIV);
   aEncoder->finish(aBuffer);
```

**Comment by randombit** [comment]
In EAX mode it is not even possible to decrypt a message without validating the tag, because the value of the tag is used as part of decryption process.

Also, EAX without a tag is equivalent to just using counter mode without an authentication mechanism, which means anyone can bitflip messages without detection.

**Comment by vgarridosm** [comment]
So, Botan only supports AEAD? EAX (AE) mode doesn't have a tag.
