### ISSUE TITLE
ECDSA signing question and feature request

### ISSUE THREAD

**Issue by guidovranken** [randombit/botan#2493]
Question: Is it possible to use a different hash algorithm for RFC6979 nonce generation than for input message hashing? Ideally, I'd like RFC6979 nonce generation to always use SHA256, and specify an arbitrary algorithm for input message hashing.

Feature request: Instead of using RFC6979, having the option to explicitly set the nonce by passing a BigInt. Some other libraries (wolfCrypt, Trezor firmware, libsecp256k1) support this and it would be nice to test Botan as well. It would of course be fine if this is only available in fuzzing mode (eg. when `FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` is defined. OSS-Fuzz automatically sets this in the CXXFLAGS for all projects).

**Comment by randombit** [comment]
Controlling the RFC6979 hash: the answer is, kind of. If you use "Raw" you can provide some pre-hashed input. If you use "Raw(SomeHash)" then that input is taken to be a pre-hashed input generated by SomeHash, in which case SomeHash is also used to generate the 6979 nonce. However we verify that the input is the same length as that of SomeHash, so that only works for testing hashes with the same output length.

For explicitly setting the nonce, this is actually already possible. You must disable RFC6979 support from the build (`--disable-modules=rfc6979`). In that case the nonce is taken from the `RandomNumberGenerator&` which was passed to the `PK_Signer`. This is how we test probabilistic ECDSA, with a RNG that outputs some fixed string:

https://github.com/randombit/botan/blob/master/src/tests/test_rng.h#L101
https://github.com/randombit/botan/blob/master/src/tests/test_ecdsa.cpp#L132
https://github.com/randombit/botan/blob/master/src/tests/data/pubkey/ecdsa_prob.vec#L11

The nonce is always taken first, followed by some bits used for blinding etc which can be random or (for your purposes) just repeats of the nonce bits or all 1s or whatever.

I don't know how convenient it is for you that this is an either/or situation in the build. It seems for ordinary users 6979 is better, unless you have some standards compliance reason to avoid it in which case you never want to use 6979, which is why it is set up this way with no ability to switch at runtime.

**Comment by guidovranken** [comment]
Thanks, this is helpful. I will try your suggestion to use `Raw` to use custom digest algorithms. As for the nonce generation, I will stick to RFC6979.
