### ISSUE TITLE
macOS ARM64 - Amalgamation build support for v1.10.17

### ISSUE THREAD

**Issue by adnan-kamili** [randombit/botan#2562]
We still use v1.10.17 as we need to support some old Linux distros. What should we do to create an amalgamation build for arm64 macOS.

We generated it using following command:

`configure.py --cc=clang --os=darwin --cpu=arm64 --no-autoload --gen-amalgamation --enable-modules=rsa,eme_pkcs,emsa3,emsa4,sha1,auto_rng,cbc,kdf2,asm_engine,pthreads,unix_procs,pbes2,sha2_64,des`

Wanted to confirm if there are any possible issues as this arch was not present when this version was released.

**Comment by randombit** [comment]
That seems fine? There might be some problems because this was not an expected configuration but it's hard to say for sure. In 1.10, Aarch64 is supported in the nominal sense that configure.py recognizes it. However there is no support for ARMv8 instructions (AES/SHA-2/etc). So you'll see much better performance (both due to that, and just general optimizations) if you can move to 2.17.2

**Comment by adnan-kamili** [comment]
Thanks
