### ISSUE TITLE
How to use this library without using socket inside callback?

### ISSUE THREAD

**Issue by jeffRTC** [randombit/botan#2571]
I like this library but one caveat is that I have to re-factor whole code base for HTTPS. I'd like to just use everything inside one function.

Is it possible even?

I've used C callback libraries which provide void* pointer to store data..

**Comment by randombit** [comment]
If I'm understanding correctly you want to implement some funnction like

```
std::string GET_some_https_url(const std::string& url);
```

**Comment by jeffRTC** [comment]
Just to clarify, I meant by one function is the worker function/thread not something else. 

Does your callback pause the calling thread and when it done it return back to current stack of thread? 
Or it's fully async with it own threads?

**Comment by jeffRTC** [comment]
If you look at llhttp parser, they provide void* to save the state on their callbacks so I can access the results within threads

**Comment by pgp** [comment]
@jeffRTC if it may help, I've already developed a minimal https client using botan, which however uses helper threads instead of async logic:
https://github.com/pgp/XFilesRootHelper/blob/master/RootHelper/tls/basic_https_client.h
https://github.com/pgp/XFilesRootHelper/blob/master/RootHelper/cli/cli_parser.h
Be aware that the code is not very clean, though... The main entry entry point for using the https client from the compiled application is the function `downloadFromArgs` in the file cli_parser.h
