### ISSUE TITLE
Total number of executed test cases varies

### ISSUE THREAD

**Issue by TestRunnera123** [randombit/botan#2577]
Hello,

unfortunately the total number of executed test cases varies in a range of +/-5 test cases in each test run. I ran the tests with the test binary on Ubuntu via:
./botan-test --run-long-tests

Botan: 2.12.1

There are no failures or something like this, all tests passed.

Are there any explanations or known issues?

**Comment by randombit** [comment]
Probably the issue is some of the randomized tests for public key encryption. We randomly corrupt a ciphertext and then attempt to decrypt it. This may or may not decrypt depending on what mutation happened and also the padding. Then we test that if it decrypted that it decrypted to a different ciphertext. As a result the total test executions will vary slightly depending on the RNG output.

If you need the test run to be precisely reproducible provide a specific seed for the RNG (with `--drbg-seed=` option)
