### ISSUE TITLE
EC key generation per FIPS 186.4

### ISSUE THREAD

**Issue by RobLinux** [randombit/botan#2609]
Does Botan has a method to create new key pair by testing candidates as per B1.2 of https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.186-4.pdf ?

Seeing the algorithm is not very complicated, how could I implement it correctly (I mean, structure wise, not the algorithm itself) ?

Thanks!

**Comment by randombit** [comment]
ECC secret keys are created by `EC_Group::random_scalar` which calls `BigInt::random_integer(rng, 1, get_order())` and that (https://github.com/randombit/botan/blob/master/src/lib/math/bigint/big_rand.cpp#L45) does rejection sampling as described in B1.2, with the slight difference that instead of doing rejection sampling to get an integer in the range [0,q-2] and then returning c+1, we sample directly from [1,q-1]. But I don't think there is any real difference.

**Comment by RobLinux** [comment]
Thanks this is what I figured out.

However I'm trying to generate EC keys compatible with Apple's corecrypto library and it seems that even if I use the same parameters, they're not the same. I'm using a custom written pbkdf2 seeded random generator so they are somehow generated in a deterministic way. But still different using the same seeds

**Comment by randombit** [comment]
It's possible Apple does something different. FIPS 186-4 also allows a different method where an extra 64 bits are generated and then reduced modulo the order. (section B.4.1)

It might be easier to use your PBKDF to generate an integer and then using that as the private key (basically implementing the logic of FIPS key gen yourself) rather than trying to make two different libraries agree on how they will use their RNG.

**Comment by RobLinux** [comment]
Thank's for the info, I'll try to implement it.
