### ISSUE TITLE
Running hash algorithm

### ISSUE THREAD

**Issue by gaborgsomogyi** [randombit/botan#2645]
I'm using hash algorithms and I need it running w/o reset (for example `SHA-160`).
As I've realized `botan_hash_final` resets it all the time which ruins my use-case.

I've found a workaround but it's not a classic solution because in case of heavy load it's just an unnecessary step and burns CPU.
So here is the workaround:
```
botan_hash_update...
botan_hash_t tmp;
botan_hash_copy_state(&tmp, original); <-- Saving state
botan_hash_final...
botan_hash_copy_state(&original, tmp); <-- Restoring state
```

* Is there a better solution what I've not found?
* If no what is the hard limitation which makes it impossible to implement?

Thanks in advance!

**Comment by randombit** [comment]
This is basically the correct approach to this, except that I don't think you need 2 copy states - you can just `copy_state` to the tmp, then call `botan_hash_final` on that tmp.

Re "hard limitation" I suppose it depends on if rewriting and re-testing all of the hash function buffering logic is hard or not. I am not included to do this because rolling hashes like this are pretty rare in my experience. It's much better to block up the message and hash each one independently, then it becomes possible to use eg threads, SIMD execution, Merkle trees, none of which are an option with a rolling hash design.

I don't think there is that much extra CPU usage involved here given copying the state is just a (small) allocation+copy, your cost will be dominated by the compression function which is unavoidable. [If you have profiling that indicates otherwise I'd certainly be interested in seeing it]

**Comment by gaborgsomogyi** [comment]
Thanks for the answer, your suggested workaround is definitely better.
Since I have no idea about the internals I believe it won't cause unacceptable CPU cost, later I'll do some measurements.
All in all I share your point, a running hash is rare but I'm implementing a Tor client where it's a must :)

Related this: `rewriting and re-testing all of the hash function buffering logic`
This sounds serious, I thought a flag can be added to `botan_hash_init`. Seems like it was wrong guess.

Anyway, it works like charm and only nice to have so closing.

**Comment by randombit** [comment]
One thing we could do here which would be easy to do and possibly more convenient for such uses is to effectively have an operation which performs copy_state + finalize. We'd still be performing an extra allocation but it would be easier to optimize in the future. (With copy_state it's totally fine to continue to update that forked state with another message, so it's harder to optimize).

BTW Tor client is a very interesting application of the library which I would like to be able to support well. If you run into anything where something seems difficult/impossible/confusing please don't hesitate to open issues.

**Comment by gaborgsomogyi** [comment]
Good to hear your interest :)
I think it's close to alpha, most major features are implemented, "only" rendezvous is missing.
Since they've just changed the whole handshake it will definitely take some time to understand/implement it.
Be aware my plan is to create a relatively lightweight client and not a full expert bundle replacement!
The binary is 1.6Mb instead of 12Mb with C++ API. Let's see how it goes on...
