### ISSUE TITLE
update_granularity too small for stream ciphers

### ISSUE THREAD

**Issue by winterland1989** [randombit/botan#2744]
Similiar to #1377, I found that all the stream cipher modes(ChaCha20, CTR_BE, etc) all have a update_granularity = 1, which make the FFI API really slow. We should add optimal chunk size to solve that.

**Comment by randombit** [comment]
Yeah there should be some additional function (for all modes) which basically exposes an optimium chunk size, probably something like:

- If update_granularity is >= 4096 (?), just return update_granularity
- If 4096 % update_granularity == 0, return 4096
- Otherwise return the first value < 4096 that is divisible by update_granularity

Need to make sure we avoid any kind of pathological behavior for weird sizes, eg using a prime-length block with Lion in CBC mode might cause something to go weird here.

**Comment by winterland1989** [comment]
From a security perspective, maybe we shouldn't provide a streaming interface(update/finish) at all for AEAD modes, instead, we should encryption/decryption in one go. 

And for streaming mode, we should add a `botan_stream_cipher_mode_t` and add `seek`, `cipher` and `export_keystream/xor` APIs.

**Comment by randombit** [comment]
This has been addressed now with the addition of `Cipher_Mode::ideal_granularity` and `StreamCipher::buffer_size`
