### ISSUE TITLE
Feature Request: X509_Certificate should have getter for subjectPublicKeyInfo

### ISSUE THREAD

**Issue by ryutei** [randombit/botan#277]
ex. vector<Byte> subjectPublicKeyInfo()
Because it's hash is recommend way for HTTP-pinning (RFC #7469).

**Comment by randombit** [comment]
Does `X509_Certificate::subject_public_key_bits` not do the right thing here?

**Comment by ryutei** [comment]
>Does X509_Certificate::subject_public_key_bits not do the right thing here?
This is not same to subjectPublicKeyInfo. I think subject_public_key_bits strips der SEQUENCE part. OpenSSL command generate some bytes more than subject_public_key_bits.

**Comment by randombit** [comment]
Ah sorry you're right. If the spki was encoded as DER (rather than indefinite length BER whatevers) then using `ASN1::put_in_sequence(cert.subject_public_key_bits())` should recover it identically. The way certs are parsed right now, the sequence header is lost so there is no way to handle oddly formed certs with this method.

**Comment by randombit** [comment]
Sorry about the wait
