### ISSUE TITLE
ECIES and the inclusion of the pubkey in the output

### ISSUE THREAD

**Issue by guidovranken** [randombit/botan#2785]
Botan includes the pubkey in the output of ECIES encryption: https://github.com/randombit/botan/blob/37fe3a2f3b806cbb2d4db4c2bb19eb7f2a673bef/src/lib/pubkey/ecies/ecies.cpp#L306

I can't find where http://www.secg.org/sec1-v2.pdf mandates this (section 3.8 talks about encryption).

Botan [claims](https://github.com/randombit/botan/commit/2a58a43264c7994c19a1f05d807e40ffd95644c2) to be basing its ECIES implementation upon ISO-18033.

I don't have access to this document (paywalled) but I assume it mandates the inclusion of the pubkey in the output.

Unfortunately this makes it impossible for me to compare Botan's ECIES against the only other ECIES implementation supported by my fuzzer, which is wolfCrypt, which does not include the pubkey in the output.

If you would like me to test the Botan ECIES implementation, please make inclusion of the pubkey optional. Otherwise you can close this issue.

**Comment by guidovranken** [comment]
Alternatively I can try to remove the pubkey from the output in my fuzzer..

**Comment by randombit** [comment]
ECIES with the ephemeral public key not included in the packet doesn't really make sense though - the recipient would not be able to decrypt since without the public key you can't compute the shared DH secret that was used to encrypt the message. I'm really wondering what wolfcrypt is doing here, maybe in their API you generate the key and pass it into the ECIES operation, and then they assume you transmit it somehow? [This would allow for static-static ECIES - which might be useful, if also dangerous...]

SEC includes the public key (which it calls R) in the output, see section 5.1.3 step 9:

Output C= (R, EM, D). Optionally, the ciphertext may be output as C=R‖EM‖D.

**Comment by guidovranken** [comment]
Thanks! I'll forward this information to wolfSSL.

**Comment by randombit** [comment]
Follow up as I was curious myself, looks like my guess was right https://github.com/wolfSSL/wolfssl/blob/master/wolfcrypt/src/ecc.c#L11209 the user provides the ephemeral private key as an input to ECIES encrypt and similarly provides the public key alongside the ciphertext to ECIES decrypt.

BTW, if I'm reading the wolfssl code right it does not include the public key in the key derivation. Botan calls that SINGLE_HASH_MODE and it is not the default.
