### ISSUE TITLE
OPAQUE Support

### ISSUE THREAD

**Issue by tibotix** [randombit/botan#2801]
Hey,

i just wanted to ask for any updates on OPAQUE development in botan. I saw your comment in #1922 , and since its a while now i am curious if there are any updates or maybe even current development for OPAQUE in progress. I would like to contribute to OPAQUE support if there are any plans on it.

**Comment by randombit** [comment]
No update or immediate development plans. Hash2curve is implemented now, which is the necessary first step for OPAQUE and/or CPace support.

Partially thing haven't moved because for a long time both hash2curve and OPAQUE specs were changing quite a lot. I know there is still not a final OPAQUE RFC but hopefully after all this time things have settled down, spec wise.

I'd be happy to accept patches adding OPAQUE support.

**Comment by randombit** [comment]
Closing this ticket since it has been idle for a while. OPAQUE support is still desired and planned for. It will probably be added at some point during the Botan3 lifecycle. Patches would be happily accepted.
