### ISSUE TITLE
OpenSSL 3.0 support

### ISSUE THREAD

**Issue by bkircher** [randombit/botan#2842]
Any plans on supporting OpenSSL 3.0.0?

The OpenSSL 3.0 release is going to be a significantly new release with changed ABI however with minimal API changes.

When building against OpenSSL 3.0 I see a bunch of deprecation warnings:
```
src/lib/prov/openssl/openssl_rsa.cpp: In constructor 'Botan::{anonymous}::OpenSSL_RSA_Encryption_Operation::OpenSSL_RSA_Encryption_Operation(const Botan::RSA_PublicKey&, int, std::size_t)':
src/lib/prov/openssl/openssl_rsa.cpp:49:35: warning: 'void RSA_free(RSA*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   49 |          m_openssl_rsa(nullptr, ::RSA_free), m_padding(pad)
      |                                   ^~~~~~~~
In file included from src/lib/prov/openssl/openssl_rsa.cpp:22:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
```

**Comment by randombit** [comment]
The OpenSSL provider is being removed in master (#2827) due to this. The benefit is so marginal that the effort of rewriting everything is not worthwhile. For 2.18.2 we've just removed support for the algorithms that OpenSSL 3.0 moved to the deprecated provider (since as a library we couldn't/shouldn't enable a provider unexpectedly) and accepted the deprecation warnings. If OpenSSL 4.0 comes out within the lifetime of the 2.x releases then we'll remove the OpenSSL provider entirely at that point.

**Comment by bkircher** [comment]
Thanks for clarifying!
