### ISSUE TITLE
Clang compilation error: "decomposition declarations are a C++17 extension"

### ISSUE THREAD

**Issue by mharmer** [randombit/botan#2942]
When cross-compiling Botan 2.19.1 with the Android NDK r23b (which uses Clang 12.0.8) with `-std=c++14` the following compilation error occurs:

```
botan_all.cpp:4657:15: error: decomposition declarations are a C++17 extension [-Werror,-Wc++17-extensions]
    const auto [C0,C1,C2,C3,C4] = xor_CNs(A);
```

Which appears to be from: https://github.com/randombit/botan/blob/f7941149eda43e6183ff4efb434412395c8fb064/src/lib/hash/sha3/sha3_round.h#L55

My understanding is that Botan 2.x supports C++11 as the minimum standard.

Note: We build with `-Wall -Wextra -Werror`, so it's unclear if this warning is enabled through those.

**Comment by reneme** [comment]
This issue is fixed with [this patch](https://github.com/randombit/botan/commit/87166cfd6a2ae15fabca98f06d4fb8d369374c08) which is unfortunately not part of Botan 2.19.1.

If you don't rely on SHA-3, you might be able to work around this issue by disabling the module with `./configure.py --disable-modules=sha3`.
