### ISSUE TITLE
Question: Building botan with MSVC 2013 with zlib, bzip2 and lzma

### ISSUE THREAD

**Issue by matejk** [randombit/botan#295]
There are options to enable compression libraries when building botan 1.11.21 on Windows 7.

I compiled all of the libraries and have them in separate dirs.

I managed to pass include dir with --cc-abi-flags="/I../../lzma/include" (don't know if it is the correct way) but linking still fails.

How do I specify include and library paths to configure script to make the build succeed?

**Comment by webmaster128** [comment]
This is related to #19. At the moment you cannot set those paths at configure time. On UNIX platforms this is not a very big deal because the linker finds the libraries using system default paths which (I guess) do not exist on Windows.

Setting includes as compiler arguments using `--cc-abi-flags` is ugly hacking but definitly your best choice at the moment.

You'll need to modify the generated Makefile in order to get it work. Are you familiar with the Windows build system? Can you make that work? How much time do you have?

**Comment by matejk** [comment]
Thank you your response. I edited generated Makefile in the meantime to make the library compile.

However I was bitten by the problem described in #67. Am I right that botan built as a dll does not work properly and I have to use static version?

My opinion is that it would make sense to replace configure.py with CMake. What do you think?

**Comment by mouse07410** [comment]
Re. Cmake: I think - ABSOLUTELY not.

Because now at least those generated Makefiles can be edited by hand, and it's extremely quick and easy, if a bit annoying. In Cmake, once you step outside of what config designer/package author envisioned you'd need - you're screwed with a capital "S". This is my first-hand experience.

So if my choice is between manually correcting a configure.py-generated Makefile and moving to Cmake - I'd rather manually correct that Makefile till the world ends.

Sent from my iPad

On Oct 12, 2015, at 15:06, Matej Kenda <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you your response. I edited generated Makefile in the meantime to make the library compile.

However I was bitten by the problem described in #67<https://github.com/randombit/botan/issues/67>. Am I right that botan built as a dll does not work properly and I have to use static version?

My opinion is that it would make sense to replace configure.py with CMake. What do you think?

**Comment by webmaster128** [comment]
> However I was bitten by the problem described in #67. Am I right that botan built as a dll does not work properly and I have to use static version?

Which one exactly? The ticket covered a bunch of issues, some of which have been in user's code and some fixed now. I do not know of any issue with building DLLs in 1.11.21.

> My opinion is that it would make sense to replace configure.py with CMake. What do you think?

There is an early version of that in the cmake branch. Currently it is only used for IDE integration during development. I'd love to see your contribution there.

**Comment by matejk** [comment]
> Which one exactly? The ticket covered a bunch of issues, some of which have been in user's code and some fixed now. I do not know of any issue with building DLLs in 1.11.21.

DLL compiles but botan-test and botan hang without any output and have to be killed with task manager. When using analgamation options and linked statically, the tools run normally.

> There is an early version of that in the cmake branch. Currently it is only used for IDE integration during development. I'd love to see your contribution there.

Since we plan to use botan seriously in longer term, I certainly plan to contribute.

**Comment by webmaster128** [comment]
> DLL compiles but botan-test and botan hang without any output and have to be killed with task manager.

Hmm.... I have no trouble doing that on Windows. Could you please add your full configure command?

**Comment by matejk** [comment]
I set up the compiler with 
```
c:\msvc2013\vc\vcvarsall.bat amd64
```
Compiler version:
```
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.31101 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```
Configure script is ran with the following options:
```
python configure.py --cc=msvc --cpu=x86_64
```
Compile with nmake passes fine, but botan or botan-test hang when started without any thing displayed to the console.

After reading the issue #67 I changed configuration parameters to:
```
python configure.py --disable-shared --via-amalgamation --cpu=x64 --cc=msvc
```
The commands worked properly then, however there was no dll, of course.

**Comment by matejk** [comment]
I tried to add linker option "/SUBSYSTEM:CONSOLE" for the tools but it did not help.

**Comment by webmaster128** [comment]
Could you please try 32 bit? Your setup works for me using 32 bit.

**Comment by matejk** [comment]
The same problem with 32-bit binaries.

I am now compiling debug build. I hope that I'll get stack trace where it stops.

**Comment by webmaster128** [comment]
* Update 5 of MSVC 2013 installed?
* Did you use the 32 bit environment for 32 bit build?
* When I last searched, "amd64" was not a documented `vcvarsall.bat` parameter. I used the following ones:

```
C:\Users\me>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
C:\Users\me>cl
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

C:\Users\me>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
C:\Users\me>cl
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```

**Comment by matejk** [comment]
No, Update 5 is not installed. I'll install it.

Yes, I did use 32-bit environment for 32-bit.

amd64 seems to be valid option in VS2013 to enable 64-bit environment as described here: https://msdn.microsoft.com/en-us/library/vstudio/x4d2c09s(v=vs.120).aspx

Output of cl definitely indicated that (see my comment above).

**Comment by matejk** [comment]
Compiling with VS 2013 Update 5 unfortunately doesn't make any difference.
```
python configure.py --cc=msvc --cpu=x86
```

I have no idea what I do differently than you...

**Comment by matejk** [comment]
Can version of python be the cause? I use latest: 3.5.

**Comment by webmaster128** [comment]
> Can version of python be the cause? I use latest: 3.5.

I don't think so because Python does not do anything apart from writing the Makefile. And we're not using any sophisticated syntax.

I guess the best bet is your attempt to run it in a debugger and see how far it gets.

**Comment by matejk** [comment]
I opened a separate issue for the hang not to mix everything together (#297).

**Comment by webmaster128** [comment]
Good idea, thanks. I'll close this one. Feel free to follow-up with more specific issues.
