### ISSUE TITLE
PKCS#11 interaction issue

### ISSUE THREAD

**Issue by lagovsp** [randombit/botan#3001]
Hi, everyone!

I have been given a task to work with `PKCS#11`. My question might be silly, though I have not found any corresponding info on the net.

I cannot figure out how exactly I reach the high-level API. When trying to include any `p11` related header (in accordance with the doc) the IDE claims it is absent (underlined in red). Other botan headers are found and suggested, so I assume the lib is properly installed. Moreover, it seems like the doc is outdated, since it mentions low- (now abolished) and high- (outdated description) level API. I simply miss `p11` files in `/usr/include/botan-2/botan` even after lib reinstalling. I must be misunderstanding something really obvious here...

I would be extremely grateful if someone tells me what headers should I use to get to the API?

Thanks in advance!

**Comment by randombit** [comment]
>  Moreover, it seems like the doc is outdated, since it mentions low- (now abolished) and high- (outdated description) level API. 

It sounds like you are trying to use `master` directly, instead of a release from the stable 2.x series. Don't do that unless you really have to because it's an unsupported work in progress.

The main header to include would be `<botan/p11.h>`

**Comment by lagovsp** [comment]
Oh, sounds awesome! Thanks a lot! I will try that

**Comment by morsiiik** [comment]
The problem is that the library installed using `apt install libbotan-2-dev` (version 2.19.1) does not contain files for working with pkcs11 (p11.h if I understood correctly)
The list of files can be viewed here https://packages.debian.org/bookworm/main/libbotan-2-dev
Might be we missed some other libraries that need to be installed, or do we need to install the lib directly from git?

**Comment by randombit** [comment]
Ugh based on https://metadata.ftp-master.debian.org/changelogs//main/b/botan/botan_2.19.1+dfsg-3_changelog it looks like Debian removed the PKCS11 support due to "unclear licensed PKCS #11 headers" (I assume this means the OASIS standard PKCS11 headers, since everything else is BSD licensed)

This being the case, it appears you will have to compile a release from source.
