### ISSUE TITLE
CI: Add/fix additional build configurations

### ISSUE THREAD

**Issue by reneme** [randombit/botan#3059]
When [overhauling the CI to fully run on GitHub Actions](https://github.com/randombit/botan/pull/3007), a few build matrix configurations needed to be deliberately disabled due to build/test errors. Now, with the CI overhaul being fully merged, we should look into them.

* [x] Argon2id [seems to fail](https://github.com/randombit/botan/runs/7390426222?check_suite_focus=true#logs) on Windows 32 bit builds
* [ ] 32 bit build on windows causes an [unreachable code warning](https://github.com/randombit/botan/runs/7390425958?check_suite_focus=true#step:8:1257)
* [ ] [macOS fails to build](https://github.com/randombit/botan/runs/7390425464?check_suite_focus=true#step:8:105) with gcc (lacking `BOTAN_PARALLEL_SIMD_FOR`)
* [x] [Amalgamation build fails](https://github.com/randombit/botan/runs/7390903061?check_suite_focus=true#step:8:55) on ubuntu (as well as [windows](https://github.com/randombit/botan/runs/7390903878?check_suite_focus=true#step:8:485) and [macOS with clang](https://github.com/randombit/botan/runs/7390903422?check_suite_focus=true#step:8:70)) with clang (abstract class marked `final`)

**Comment by randombit** [comment]
Closing as I believe all of these have been fixed now:

Argon2 issue was due to MSVC seemingly miscompiling the SSSE3 Argon2 code on 32-bit - disabled in e37989c5402747f2d1eb26eb6217a40bfe23307f

Amalgamation build failures were due to some broken/dead XMSS headers (removed in b1b6264e30bddb7344955abd5d13341bea7151da)

The macOS gcc build failure is I think a red herring. When I tried to enable that build, it turns out the mac images have a program named `gcc`, but it's actually Clang underneath. Then we try to use a GCC specific pragma, and fail beacuse Clang doesn't recognize it.

I'm not sure about the unreachable code warning - unfortunately the build log has expired. But at least we are compiling with `/Wx` on Windows 32-bit, so I think everything is resolved with that one as well.
