### ISSUE TITLE
Check Kyber verus the final specification

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3098]
I don't want us to ship something that's incompatible

**Comment by randombit** [comment]
OK my current understanding: R3 is the final spec as far as anyone is currently aware. So the main thing atm to check it that we are compatible with the upstream reference implementation and https://github.com/open-quantum-safe/liboqs since that is what a lot of projects are using. I think we have tests based on the NIST submission but not anything that directly tests against the vectors generated by the reference implementation.

**Comment by securitykernel** [comment]
FWIW From what we know NIST draft specs for Kyber and Dilithium are expected in April/May '23.

**Comment by FAlbertDev** [comment]
I've just compared [botan's test vectors](https://github.com/randombit/botan/tree/master/src/tests/data/pubkey) with the most recent [NIST submission](https://csrc.nist.gov/Projects/post-quantum-cryptography/selected-algorithms-2022) (which is still the 3rd round). In my opinion, if our tests pass all NIST test vectors there is no reason to doubt our implementation. Since there are already 100 test vectors per kyber instance, there should be no reason for generating more ones using a reference implementation...

**Comment by FAlbertDev** [comment]
I've also verified that the [ref implementation](https://github.com/pq-crystals/kyber) still generates the same test vectors, so we should be ok :)

**Comment by randombit** [comment]
Thanks for checking on this. We may have to deal with some changes in the final spec, but it seems there is nothing we can or should change at the moment.
