### ISSUE TITLE
Stablize Supported Platforms for Botan 3.0

### ISSUE THREAD

**Issue by reneme** [randombit/botan#3169]
[Currently supported platforms](https://github.com/randombit/botan/blob/master/doc/support.rst#supported-platforms) are roughly:

* GCC 11+
* Clang 14+
* MSVC 2019+

* latest XCode Clang
* latest NDK

Currently, both XCode and NDK are pushing the breaks on (some) C++20 features. For instance, they are behind with adoption of `<ranges>` and `<concepts>` STL headers. This will likely get better with future versions, as we pledge to only support the latest version of those.

Assuming XCode and NDK caught up, MSVC 2019 is [the most likely culprit to hinder adoption](https://github.com/randombit/botan/pull/3165#issuecomment-1377317013) of new features.

Hence, we might want to put MSVC 2019 on probation and not pledge support for the whole 3.0 life-cycle.

**Comment by randombit** [comment]
We are constrained in multiple directions:

* We can't reasonably require a compiler that's later than what is available in the CI images, since we wouldn't be able to test it.
* We want to support as few old compilers as possible, because they have bugs and limitations that must be worked around.
* Nothing stops us from arbitrarily requiring a new compiler version at any time, when we decide we're tired of doing workarounds. *But* doing so is pretty unfriendly; in my experience toolchain versions tend to be very sticky within a certain project, and when we drop supporting a certain compiler that probably will cut off some number of people from being able to use upgraded versions of the library. And it's also sticky *for us* because we have to finally decide at some point "ok, these hacks really aren't worth it anymore, let's drop 2019 support in the next release"
* In principle we could maintain branches to "backport" security fixes to the final release that supported some certain compiler, in order to prevent anyone from becoming stranded. There is just not the manpower for this.

The options as I see them are:
1) Support VC2019 over the entire release lifetime, which might be many years (currently 2.x has been supported for almost 6 years, with another year of support lifetime already advertised, and we will almost certainly have to extend that)
2) Support VC2019 until we get tired of supporting it
3) Support VC2019 until some specific date (say Jan 1, 2024)
4) Drop support for VC2019 right now, and 3.x never supports 2019. (Since it works right now, the final release 3.0 might well compile even if we dropped support today. But we would no longer test it in CI, and not claim it to be supported.)

I would personally advocate for option 4 because it is overall the most predicable for users and the least work for us:

1) A lot of work over the long haul, and resources are scarce.
2) Unpredictable to users, also places a burden on us in deciding when we've had enough.
3) Extra work over the short term but with an end point. Deciding in advance when to drop support removes the decision burden. Predicable to users - *if* they read the documentation.
4) No surprises to users, and we can immediately stop having to figure out workarounds (for VC2019 at least)

My preference order on policy is 4, 3, 2, 1.

Regarding other compilers:

For NDK and XCode our policy of just supporting the latest version evades the issue. That seems especially fortunate given that the current latest versions seem to have some substantial limitations. 

For Clang, there is nothing we can do since Ubuntu 22.04 doesn't ship Clang 15. The main thing I see for the Clang 15 release notes that would be nice to have is support for `std::source_location`. Based on [this page](https://www.ubuntuupdates.org/package/core/jammy/universe/proposed/clang-15) it seems possible that Clang 15 will shortly be backported to Ubuntu 22.04. If this becomes available soon I would probably advocate requiring Clang 15 instead of 14 so we can use `std::source_location`.

For GCC, we could consider requiring GCC 12 instead, since that *is* available in Ubuntu 22.04. Scanning the [GCC 12 release notes](https://gcc.gnu.org/gcc-12/changes.html) there are a few improvements that would be nice to be have in the long run, especially a Clang compatible `__builtin_shufflevector`, and ability to use `vector` and `variant` in `constexpr` functions.

Action items:
 * Decide on the policy we are applying wrt support for VC2019
 * Decide if requiring GCC 12 is worthwhile, and if so, what policy to apply for GCC 11 support.

**Comment by reneme** [comment]
For us (R&S Cybersecurity) VC2019 is not relevant and a switch straight to **VC2022 is fine**. Regarding GCC 11: Our linux distribution of choice comes with GCC 11.3 at the moment. Hence, **GCC 11 would be preferred**. No strong feelings about the supported clang version.

**Comment by mouse07410** [comment]
I say GCC-11 and Clang-14 would be reasonable..?

**Comment by randombit** [comment]
GCC 11 and Clang 14 are probably fine, the benefits of forcing a higher version (described in my earlier comment) are fairly minor, and having 3.0 be usable out of the box on 22.04 (a very common distro) is a plus.

I'm going to go ahead with dropping VC2019 support asap since I think that one is going to cause a lot of problems in the long run.

**Comment by randombit** [comment]
Holding with GCC 11/Clang 14, so with VC2019 removed I think this can be closed as completed.
