### ISSUE TITLE
DTLS snooping / parallel decoding

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#3274]
Hi Jack et al, after a long break!

I think I will be starting a project where I want one DTLS server to have a active connection and another to just listen on it and be ready to take over, datagram by datagram.

The syncronization of key material is of course beyond Botan and I expect to have to feed the mirror instance with material for every connection and for any renegotiation.

I see that similar use cases are partially supported in Wireshark and WolfSSL. With some limitations.

My question is if this has come up yet as a desired feature with some possible prior discussion, and how you see I could go about to implement it.

Thanks!

**Comment by randombit** [comment]
Hi @nunojpg! Hope all is well.

There was some attempts a while back to serialize the entire state of a TLS connection, the goal being transparent migration of active TLS connections. This was driven by IncludeOS which supported such things. This turned out to be quite difficult and I think the whole thing was abandoned. (Partially because IIRC IncludeOS ran into financial problems themselves and the company folded.) I believe there were some tickets and possibly a draft PR but I can't find anything right at the moment.

I think the DTLS case is a bit simpler because for certain state (eg during an active re-handshake) we can forget it and just pretend that we did not see the packets that created that state. But this is not something I've thought about in some time.

Can you point me to docs about the Wireshark & WolfSSL methods? That might give some ideas.

**Comment by nunojpg** [comment]
In my PoC in wolfSSL, I am using DTLSv1.2 ECDHE-ECDSA-AES256-GCM-SHA384, and calling wolfSSL_dtls_export will give me a serialization of 382 bytes that I can use to then import the session.

After navigating a bit around Botan I think this is incredible complicated to implement. If Botan was using a CRTP approach instead of virtual class then it would be possible just to POD export the entire object. I'm just droping this tought since I don't see it used in Botan and it would have several advantages.

If reflection was available in c++ then this could also be much easier to implement, we would just have to mark the parts that need to be exported.

Maybe something for Botan 4 roadmap :)
