### ISSUE TITLE
c++20/gcc-11 using enum

### ISSUE THREAD

**Issue by nunojpg** [randombit/botan#3390]
f5c4a879d9ae1de231fa50ed6efb3be3595f06bf introduced c++20/gcc-11 using enum

Just before you disable GCC-10 CI builds with the messange "Drop CI builds that are stuck with GCC 10".

I am confused if the objective is for Botan-3 to be C++17 or C++20?

**Comment by randombit** [comment]
The original plan was C++17 but that was predicated on 3.0 being released in ~2020 which would have made adopting C++20 impractical. Since now we are already in 2023, adopting C++17 for the long term for 3.x didn't seem sensible especially as C++20 offered `std::span` which is an important feature for this kind of software.

**Comment by nunojpg** [comment]
@randombit sorry I got the website view of news where it said c++17. I see you have updates news at this repo. 

And of course c++20 is the right choice at this time.
