### ISSUE TITLE
Botan 3 requires at least XCode 13.3

### ISSUE THREAD

**Issue by chenrui333** [randombit/botan#3494]
👋 trying to build botan 3.0.0, but ran into the following build failure

```
  build/include/botan/ec_point.h:36:13: error: expected unqualified-id
        using enum EC_Point_Format;
              ^
```

relates to https://github.com/Homebrew/homebrew-core/pull/128062

**Comment by randombit** [comment]
What compiler is this? Probably the version of XCode is too low.

**Comment by mouse07410** [comment]
On an older Mac with Xcode that's too old, you can build Botan-3 using Macports-installed Clang-15 or Clang-16. Brew probably also offers Clang (and/or GCC) installs.

**Comment by chenrui333** [comment]
> Based on https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3-release-notes we only support XCode 13.3 or higher for Botan 3.

I see, that is helpful.

**Comment by chenrui333** [comment]
@randombit any chance to put the xcode requirement into the docs?

**Comment by randombit** [comment]
@chenrui333 XCode situation is a little tricky since unlike GCC, LLVM Clang, and MSVC, where we have a minimum requirement that we aim to keep as supported for the entire life of 3.x, our minimum supported version of XCode (and also Android NDK) is [floating to the latest version](https://github.com/randombit/botan/blob/master/doc/support.rst?plain=1#L21-L22), because both of those compilers are substantially behind the big 3, and we already have to include various hacks to work around limitations, which we'd like to be able to remove eventually. That wouldn't be possible if we maintained a fixed minimum supported version.

XCode 13.3 seems to work, which is great, but already we are only testing with XCode 14.2, and future changes might accidentally break support for older versions without our noticing.

If at some point XCode is no longer the weak point on our compiler support matrix then we would calcify a specific minimum version and ensure this minimum version was tested in CI.

**Comment by randombit** [comment]
I've added some notes in `doc/support.rst` that call out that we are currently requiring the latest XCode/NDK, and noting that it is known that at least XCode 13.3 is required.
