### ISSUE TITLE
Add support for building using ninja to allow for parallel builds on Windows

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#3495]
We only support *nmake* for building on Windows currently. *nmake* still has the longtime downside that it doesn't support multiprocessor builds. Thus, a build can take up to 15mins, even when you run on a 72 threads Xeon machine. The drop-in replacement [JOM by Qt](https://wiki.qt.io/Jom) works well (same build takes 45 seconds), but JOM seems to be abandoned, the latest release is from December 2018. An alternative I saw is Ninja. Maybe there are also other options on Windows.

**Comment by randombit** [comment]
Ninja seems well suited since, to quote its website, it is "designed to have its input files generated by a higher-level build system" which is exactly the situation we are in. Ninja itself generates its build setup using ... a `configure.py` script.

**Comment by securitykernel** [comment]
I think so, yes. We don't use the cmake support currently and I don't see us using it in the future. We will make more use of Conan, where configure.py is also just fine. @reneme Any thoughts?

**Comment by reneme** [comment]
I agree. CMake doesn't quite make sense as a wrapper around `configure.py`. As far as I know its also (in its current shape) not helping as an abstraction layer for Conan. Properly migrating the build system with all its custom features away from `configure.py` to CMake seems like a _huge_ project as well.

Actually, I really like the idea of switching to Ninja as an output target for `configure.py`. I'm a bit worried about maintaining an additional output target though. Would you expect Ninja to replace Make with (say) Botan 4.0?

**Comment by randombit** [comment]
> I'm a bit worried about maintaining an additional output target though. Would you expect Ninja to replace Make with (say) Botan 4.0?

TBH I expect the impact here to be quite minimal. I wouldn't be surprised if adding ninja support comes down to adding a `ninja.in` template, plus a conditional to process the template if ninja support is requested, and all of the variables and template support we need already exists. Due to needing to support both make on Unix and nmake on Windows, already almost all of our build logic is encapsulated either in the configure.py system or else in the various subscripts (`build_docs.py`, etc) so I don't think there will be too much duplication between the two.

If it turns out that supporting both is way more hassle than I expect, I'd be open to going ninja-only in 4.0. But I'd prefer keeping both since I regularly build on machines that I do not admin (like the GCC compile farm, various machines people give me ssh access to, etc), and all of these already have make installed but almost certainly will not have ninja, so that would be a hassle for me personally.

**Comment by crazydef** [comment]
I was actually going to suggest you consider using premake to generate project files and/or make files.  That way people can choose what they generate according to their current setup.  Premake supports most major build systems out of the box (including ninja) and I think gives you a lot of what you're currently doing manually for free.  (And it's infinitely less annoying than cmake.)

Parallel builds (20 minutes per build is embarrassing) on Windows is one thing - proper Visual Studio project files is another thing entirely.  Xcode project files with proper support for universal builds on MacOS (something I'm currently looking into myself) is something else that is painful in its absence.

**Comment by lieser** [comment]
initial support for ninja was added in #3677. If there are still things we want to improve we should create separate issues for it.
