### ISSUE TITLE
Web site is not working

### ISSUE THREAD

**Issue by Danil49** [randombit/botan#3496]

**Comment by securitykernel** [comment]
Known issue. It is down since yesterday already. The contents are populated from what's inside the doc/ folder in the repository, so you should be able to find everything you need there in the meantime.

May I suggest you don't use swear words in the ticket's title or description. To be honest it does not help getting it fixed any faster.

**Comment by randombit** [comment]
Something is wrong, I cannot ssh into it either, but using the VPS console everything is up and running.

**Comment by randombit** [comment]
IPv4 problem - looks like IPv6 works but inbound IPv4 is being dropped. Opened a ticket with the VPS provider.

**Comment by randombit** [comment]
Back up

**Comment by paultag** [comment]
@randombit Thank you for fixing this so quickly! Out of curiosity, what was the underlying issue? I have some services on vultr, was there an issue with vultr's network here?

**Comment by randombit** [comment]
@paultag Actually no idea what happened, which is less than satisfying. At support's suggestion I rebooted the VM and IPv4 came back. First time this has happened, and I host several other sites (which get a lot more traffic than randombit.net) and have never had a problem like this so (shrug).
