### ISSUE TITLE
OS X clang build fails with boost and amalagamation

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#350]
As seen in the Travis reports, Botan does not compile on OS X when amalgamation is used together with boost.

This configuration has been added to the CI today and it is very unlikly that other recent changes introduced the bug, due to the position in the code.

I can reproduce the error on a local OS X 10.9 machine, where `./configure.py --via-amalgamation && make` and `./configure.py --with-boost && make` works but `./configure.py --via-amalgamation --width-boost && make` doesn't.

**Comment by randombit** [comment]
The Travis build is failing due to this gem from a Darwin header:

/usr/include/sys/termios.h:291:12: note: expanded from macro 'B0'
#define B0      0

I assume this is being pulled in by boost for whatever reason.

**Comment by randombit** [comment]
Apple documents it so they probably can't be convinced it's a really dumb idea to define a macro like that:

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/tcsetattr.3.html

Perhaps boost can be changed to avoid this include? Or lacking that #undef B0 after including the offending boost header, the same we do with min/max for windows.h

**Comment by webmaster128** [comment]
I would avoid playing around with include orders, which will increase complexity a lot, especially in the amalgamation. Also forcing the user to use a cutting edge boost version does not seem right to me.

Couldn't we just rename the variables in `src/lib/block/idea_sse2/idea_sse2.cpp`, e.g. to lower case letters? I could do that easily in Qt Creator.

**Comment by randombit** [comment]
This would seemingly require avoiding `B0` in all parts of the code, wouldn't it? That's used all over the place including in macro definitions and frankly IMO sets a bad precedent; No other termios.h apparently does this and frankly having defines like that 'for convenience' defines a buch of values Bx to be exactly x. https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/tcsetattr.3.html

which is just hideous namespace pollution. Adding minor to support a platform which then requires major changes across the entire codebase including things completely unrelated to that platform (say, the Serpent Sbox table macros) is completely unacceptable'; should we avoid std::min/std::max simply because windows.h has defines for it already? No, we say that is brain damage and route around it, contain it, and do not let its crazy bullshit infect this code. We use the best of the platform and avoid/contain everything else; if its crazy cannot be contained then it's time to break up.

First, which boost library is causing the problem? And why is any boost library we use include termios.h anyway?

**Comment by randombit** [comment]
Perhaps boost should be its own 'ABI' for amalgamation purposes.

**Comment by webmaster128** [comment]
`termios.h` included by
`boost/asio/serial_port_base.hpp` included by
`boost/asio.hpp` included by
`src/lib/utils/http_util/http_util.cpp`

I personally have no clue what asio is and don't need it. If it's only 20 undefs in `http_util.cpp`, than let's go for that. Include positions are only changed for STL headers in amalgamation, right?

**Comment by webmaster128** [comment]
Works, beautiful. Thanks.
