### ISSUE TITLE
Convert `Ed25519_PrivateKey` to `Curve25519_PrivateKey`?

### ISSUE THREAD

**Issue by DisableAsync** [randombit/botan#3547]
Still looking for this "use same key for signature and encryption/key agreement/key encapsulation" thing. (Yes I know it's not recommended. )

Currently looking at Ed25519 and Curve25519. On Wikipedia it says the curve used in Ed25519 is "[birationally equivalent](https://en.wikipedia.org/wiki/Birationally_equivalent)" to Curve25519. Does that mean it is totally legit to convert keys in between these two kinds? Is there a standardized way of doing so? Sorry, I don't know math at all, can't read papers properly myself. 

I tried to pass `Ed25519_PrivateKey`'s private key bits to `Curve25519_PrivateKey`'s constructor, the one that takes an unused `algorithm_identifier` and vice versa. The resulting keys worked fine, and they shared the same private key bits, of course! 

Later I did more Googling and found this [`crypto_sign_ed25519_pk_to_curve25519()`](https://github.com/jedisct1/libsodium/blob/d787d2b1cf13ad2e69c3a7ebc3fb7b68b6430774/src/libsodium/crypto_sign/ed25519/ref10/keypair.c#LL46C31-L46C31) and [`crypto_sign_ed25519_sk_to_curve25519()`](https://github.com/jedisct1/libsodium/blob/d787d2b1cf13ad2e69c3a7ebc3fb7b68b6430774/src/libsodium/crypto_sign/ed25519/ref10/keypair.c#L70) from libsodium. Looks like it's an accepted way of converting Ed25519 keys to X25519 keys. But it's a one way conversion because of the hash thing? And the private keys don't share the same bits. 

Which is the correct or more correct way to convert keys? Or is there better ways?

**Comment by randombit** [comment]
> The resulting keys worked fine, and they shared the same private key bits, of course!

Yeah I suppose that works but I think it is pretty sketchy, cryptographically speaking.

Thanks for pointing to the sodium implementations. I have not checked the math but I'm willing to assume for the time being that someone who did checked this code. These APIs must date to after the sodium compatability layer was added to Botan (oh wow that was already over 4 years ago...).

I've been generally hesitant to support this operation in the past because

1. It's relatively esoteric
2. It's mathematically non-trivial and would require a bit of research on my side to get it right
3. I do not myself have a need to do it

It's availability within the public libsodium API somewhat changes the calculus re (1) and (2)

**Comment by DisableAsync** [comment]
I even saw a saying "Ed25519/X25519 keys are essentially just random bits". Out of curiosity, I tested it and yes, keys loaded from `rng.random_vec(32)` are actually usable! What!

I originally looked into this issue because giving `Botan::Ed25519_PrivateKey` and `Botan::X25519_PrivateKey` same private key bits would still yell different public keys. Thought it had something to do with the way Botan loads key.

Guess it's been algorithm stuff all this time. I don't know what I'm looking for any more :(

Would be going for the "distinct keys for signing and for encryption" path without a doubt?

**Comment by DisableAsync** [comment]
Can't really find a thing about this key conversion thing. There might not be a "standard" way of doing so at all.
