### ISSUE TITLE
STM32 CORTEX M4 ENTROPY GATHERING

### ISSUE THREAD

**Issue by altmond** [randombit/botan#3604]
Is there any solution available for gathering entropy in a STM32 CORTEX M4?

**Comment by randombit** [comment]
There is nothing built in but the idea is you should be able to easily provide it yourself.

The first step would be identifying how you can actually get some entropy on the device. That will depend on the board, some have hardware RNGs that would be suitable. Otherwise you'll probably have to do something relatively horrible, like repeatedly sampling from all available clock sources.

Once you have something that seems to work, you define a new `Entropy_Source`:

```
class STM32_Entropy_Source : public Botan::Entropy_Source {
   void name() const override { return "stm32"; }

   void poll(RandomNumberGenerator& rng) override {
       // use rng.add_entropy or rng.add_entropy_T to write whatever you can find into the RNG state
   }
};

int main() {
  Botan::Entropy_Sources es;
  es.add_source(std::make_unique<STM32_Entropy_Source>());
  Botan::AutoSeeded_RNG rng(es);
  // can now use `rng`
}  
```

**Comment by randombit** [comment]
#3606 has some more worked out examples of how to perform this kind of integration

**Comment by altmond** [comment]
I tryed it , but im having problems with the auto_rng_hmac() function. Any ideas?

**Comment by randombit** [comment]
You would have to be more specific as to what the problem is
