### ISSUE TITLE
Supported Platforms: Should we be more specific about minimal supported GCC?

### ISSUE THREAD

**Issue by lieser** [randombit/botan#3613]
I'm currently working on updating the Conan recipe for Botan (https://github.com/conan-io/conan-center-index/pull/18079).
I noticed that there are compile problems with GCC 11.1 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100862).

The documentation currently claims to be compatible with GCC without specifying a minor GCC version. We should consider being more specific there an mention also a minor version we know works.

**Comment by randombit** [comment]
That's pretty surprising to me since my understanding is that whatever shipped feature-wise in GCC 11.1 would be the same feature set that is available for all 11.x; that GCC minor revisions only include bug fixes. Thus a minor version would not be necessary to specify.

Here it seems that GCC 11.1 shipped `using enum` support, but there were bugs that were fixed in 11.2 that would prevent using it in the way that we use it. So I suppose in this case, yes we should specify 11.2 or higher to avoid confusion.

**Comment by randombit** [comment]
Updated the support doc to indicate we need 11.2
