### ISSUE TITLE
CI breaking because jom download is flaky

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3629]
Occasionally Windows CI fails because `choco` fails to download `jom` due to a timeout.

Not really sure how to fix this atm

**Comment by reneme** [comment]
Its been happening for like one or two weeks now. Initially I was hoping this would just go away.
Another gotcha: `choco` doesn't exit with an error when the timeout happens. Therefore, the build fails at a later stage rather than in the setup stage already.

This could be the universe telling us to go back and finish the work in #3508. 🤡

**Comment by randombit** [comment]
Another obnoxious aspect of `jom` - it seems like even when it succeeds, the download takes a long time. The setup phase for each of the Windows builds is 2-3 minutes. :/

**Comment by randombit** [comment]
#3639 has the CI script fall back to nmake if jom is missing. Not really ideal but beats having CI jobs randomly fail, and has the side benefit of probalistically testing our `nmake` build.

**Comment by securitykernel** [comment]
> This could be the universe telling us to go back and finish the work in #3508. 🤡

Thanks for pinging. I can follow up on this after my holidays next week with setting up a todo list and finishing the work.
