### ISSUE TITLE
Python binding: kdf throws "ctypes.ArgumentError: wrong type".

### ISSUE THREAD

**Issue by YxJannis** [randombit/botan#3633]
When trying to call botan3.kdf using the python binding like:

```python
import botan3

return botan3.kdf(
    algo="Argon2id",
    secret="thisIsMySecret",
    out_len=256,
    salt="someRandomSaltValue",
    label="Key Derivation",
)
```

it throws an Error:

```
Traceback (most recent call last):
[...]
  File "/home/user/Coding/kdf_example.py", line 45, in sample_key_derivation
    return kdf(
  File "/home/user/Coding/pqzip/botan3.py", line 993, in kdf
    _DLL.botan_kdf(_ctype_str(algo), out_buf, out_sz,
ctypes.ArgumentError: argument 4: <class 'TypeError'>: wrong type
```

If I change the secret from `"thisIsMySecret"` to `b"thisIsMySecret"`, the error remains with "argument 8" instead of "argument 4".
Changing the algo parameter also doesn't change anything.
For the salt I have tried passing strings or the output of the botan3.RandomNumberGenerator().get(length).

AEAD encryption and decryption are working in my environment, so the installation should not be the problem.

**Comment by randombit** [comment]
Sorry about not getting to this.

The terminology here is unfortunately quite confusing. There are two different mechanisms here - KDF and PBKDF. The first, KDF, uses as input a whole symmetric key and can be used to derive more symmetric keys. An example of this would be HKDF. These functions are designed to run as efficiently as possible, as the assumption is that the original input secret is already immune to brute force.

The second, PBKDF, use as input instead a password that is hopefully remembered by a human. These are designed to be as expensive as possible. Argon2id being a great example.

Unfortunately :disappointed: the `pbkdf` function in the Python wrapper does not really support Argon2 properly, because it always invokes the function with the appropriate threads and passes parameters as 0.

#3667 adds a proper wrapper for Argon2 to the Python API. In the meantime you can do this by invoking the FFI API directly:

```
def argon2(passphrase, salt, out_len, m, t, p):
        import ctypes
        out_buf = ctypes.create_string_buffer(out_len)
        hash = botan._DLL.botan_pwdhash(
            botan._ctype_str('Argon2id'), m, t, p,
            out_buf, out_len,
            botan._ctype_str(passphrase), len(passphrase),
            botan._ctype_bits(salt), len(salt))
        return out_buf.raw
```

**Comment by YxJannis** [comment]
Thank you for the clarification, the workaround and the fix :)
