### ISSUE TITLE
OpenSSL module question

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#368]
Currently there are three modules for openssl: `openssl`, `openssl_block` and `openssl_hash`. There are two more OpenSSL implementations for rsa and ecdsa but these are not splittet into own modules. 

This seems to be not consistently. Or is this intended?

**Comment by randombit** [comment]
This is not consistent and I've been thinking especially with the likelyhood of adding additional system-specific providers (CryptoAPI, CommonCrypto, etc) in the future it makes sense to move all OpenSSL calls to something like src/lib/prov/openssl (and then prov/cryptoapi and so on). Otherwise it is very hard to audit, say, all uses of any particular system library in one go because they are spread all over the code.

Another obnoxious thing about the current setup is that it creates an empty openssl_rsa.o object file even when OpenSSL is disabled from the build, which is potentially very confusing.

**Comment by neusdan** [comment]
That would be a good change! :+1:

**Comment by randombit** [comment]
Done, closing
