### ISSUE TITLE
CVC tests failing

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#372]
Here is the output:

```
CVC ran 22 tests 1 FAILED
Failure 1: invalid time 2008`02-01 failed to throw expected exception
CVC test 1 ran 1 tests 1 FAILED
Failure 1: Invalid argument Decoding error:  decoding failed
CVC test 11 ran 1 tests 1 FAILED
Failure 1: Invalid argument Decoding error:  decoding failed
CVC test 2 ran 1 tests 1 FAILED
Failure 1: Invalid argument Decoding error:  decoding failed
CVC test 3 ran 1 tests 1 FAILED
Failure 1: Invalid argument Decoding error:  decoding failed
CVC test 4 ran 1 tests 1 FAILED
Failure 1: Invalid argument Decoding error:  decoding failed
CVC test 5 ran 1 tests 1 FAILED
Failure 1: Invalid argument Decoding error:  decoding failed
CVC test 7 ran 1 tests 1 FAILED
Failure 1: Invalid argument Decoding error:  decoding failed
CVC test 8 ran 1 tests 1 FAILED
Failure 1: Invalid argument Decoding error:  decoding failed
Tests complete ran 30 tests 9 tests failed
Error: Test error Test suite failure
```

I think the `cvc` module should be enabled in the CI builds.

**Comment by randombit** [comment]
CVC is kind of a wasteland right now and actually I think there are some parts of the code from InSiTo which never made it into the main tree.

Part of the problem is I haven't been able to find any English docs describing the formats. CVC seems valuable enough in theory that I haven't really considered removing it, but it definitely needs some work before it's viable (thus it being disabled from the build, which of course encourages further bitrot...)

**Comment by webmaster128** [comment]
Duplicate of https://github.com/randombit/botan/issues/150

**Comment by randombit** [comment]
Obviated by removal of CVC in 1.11.30
