### ISSUE TITLE
Storing and loading a private key to/from BER

### ISSUE THREAD

**Issue by cordney** [randombit/botan#379]
Assume the following code:

```
#include <botan/rsa.h>
#include <botan/pkcs8.h>
#include <botan/auto_rng.h>
#include <botan/data_src.h>

int main()
{
   Botan::AutoSeeded_RNG rng;
   Botan::RSA_PrivateKey key( rng, 4096 );

   // 1. save key to PEM, attempt to load it with load_key()
   auto pem = Botan::PKCS8::PEM_encode( key );
   Botan::DataSource_Memory keyData2( pem );
   auto keyReloaded2 = Botan::PKCS8::load_key( keyData2, rng );

   // 2. save key to BER, attempt to load it with load_key()
   auto ber = Botan::PKCS8::BER_encode( key );
   Botan::DataSource_Memory keyData( ber );
   auto keyReloaded = Botan::PKCS8::load_key( keyData, rng );

   return 0;
}
```

The same key is converted to PEM, then loaded again, then converted to BER, then loaded again. Loading from PEM works just fine, while loading from BER fails with exception: `Decoding error: PKCS #8 private key decoding failed: Decoding error: BER: Tag mismatch when decoding got 2/0 expected 16/32`. openssl also fails to parse the BER, but parses the PEM just fine. I wonder why this happens, especially as `PEM_encode` is just `return PEM_Code::encode(PKCS8::BER_encode(key), "PRIVATE KEY");`. The same analogy holds for `PEM_decode`.

**Comment by randombit** [comment]
The problem with reloading is that PKCS8::load_key (contrary to the comment in pkcs8.h about checking if the passphrase is empty) assumes any BER key is encrypted. The tag=2 (INTEGER) object that was unexpectedly encountered is the version code which is the first field of an unencrypted PKCS8 key, but here the decoder was attempting to read a structure (the algid of the PBE scheme, which is the first field in an encrypted key). Your example works if you call the encrypting version of BER_encode instead.

Because the structures are different it would be possible to sniff out if the key is encrypted or not based on if the first field is an integer or a structure. Unfortunately the ASN.1 parser interface wrt DataSource does not allow one to do that very easily though. In any case certainly a bug, even if the resolution is not exactly clear yet.

I was not able to replicate the problem loading the BER keys into OpenSSL (1.0.2e) for RSA keys (or DSA), but did see this when loading an ECDSA key - PEM works, BER does not. For ECDSA, it appears that OpenSSL actually uses a different format for PEM vs BER (?!?), because if I take the PEM key and convert it with `openssl ec -in ecdsa.pem -outform DER`, the resulting ASN.1 structure seems to be different from the input PEM.

**Comment by cordney** [comment]
What about making the encrypted/unencrypted choice explicit on the API by making the password parameter not default to `""` and additionally adding two functions without a password parameter for loading unencrypted keys from `DataSource` and file, as in https://github.com/cordney/botan/commit/50b3cce52d5a02c5c3d039dc792edcc7bb7ee7dc? I added in your commented out test for this issue and have all tests passing now, without needing to change caller code, so I think its even an API compatible change.

**Comment by randombit** [comment]
@cordney 50b3cce looks good on first review, can you open a PR?

**Comment by cordney** [comment]
PR opened.

Regarding the OpenSSL incompatibility: Indeed, I only saw that with ECDSA keys, too.

**Comment by randombit** [comment]
@cordney BTW I realized I had discovered this problem with ECC keys in a slightly different form earlier (and forgotten completely about it); when trying to import an ECC key into OpenSSL using d2i_ECPrivateKey (for gaining OpenSSL as an ECDSA provider) I found that a totally different key format is required, as seen in the function `PKCS8_for_openssl`. I have no idea what standard if any that format comes from, I just reversed it from OpenSSL. So in any case the ECC BER problem is a deeper incompatibility than just with OpenSSL's command line tools.
