### ISSUE TITLE
mgf1_mask() not exported

### ISSUE THREAD

**Issue by cordney** [randombit/botan#380]
Is there any reason why `Botan::mgf1_mask()` from `mgf1.h` is not exported, i.e., `BOTAN_DLL` is missing and the header is not marked as public in `info.txt`? In 1.10, `Botan::MGF1` class was exported and when porting some code from 1.10 to 1.11, I suddenly get a linker error about missing symbol for `mgf1_mask()`.

**Comment by randombit** [comment]
Missing BOTAN_DLL here was purely an oversight, helped by the lack of explicit tests in this area: pk padding is only tested in the context of pubkey operations, so `mgf1_mask` not being directly tested (and so the missing export was never noticed) - despite being in fact designed as a public API. Since MGF1 seems to be reused in a lot of different contexts (for example I ran into it today in the PSEC-KEM spec) it seemed best to make it easy to call.

There didn't seem to be any need for the flexibility that having an MGF base class and virtual indirect offered as 1.10 used; things that use MGF1 (like OAEP) occasionally theoretically can use some other MGF but in practice no one supports any such MGF (nor has any MGF1 alternative even been defined to my knowledge). So it is simpler to hardcode MGF1 with a simple interface and make the calling code a little cleaner.

**Comment by cordney** [comment]
Thanks, 65a35d8bf385683b111312353bb40e944a26274e fixes it.
