### ISSUE TITLE
Vcpkg debug build names output botan-3.dll instead of botand-3.dll

### ISSUE THREAD

**Issue by droidmonkey** [randombit/botan#3813]
I wanted to start a bug report here instead of the vcpkg repo because I do not understand all the ins and outs of how Botan build works. When you build botan using vcpkg (at least on Windows), both the release and debug binaries are named `botan-3.dll`. This creates all sorts of problems when trying to find the correct library using cmake and requires workarounds. We currently work around this for KeePassXC by inverting the search path for debug builds. It would be far better if botan would properly output a binary name of `botand-3.dll` for debug builds.

What are your thoughts?

**Comment by reneme** [comment]
Thanks for reporting this. We're not maintaining the vcpkg package ourselves. Though, [a similar discussion](https://github.com/randombit/botan/issues/3066#issuecomment-1316680966) came up with the maintainers a while ago. I'm more than happy to help improve the situation with this, to make it as easy as possible for package maintainers and consumers. Some guidance or feedback would be much appreciated, though.

Certainly, the vcpkg package could be adapted so that debug libraries have a suffix. Botan's `./configure.py` has a switch for that: `--library-suffix=d` should do the trick. This would result in `botan-3d.dll` rather than `botand-3.dll`, but I guess that doesn't really make a difference.

Also note, that starting with Botan 3.3.0 we'll be [shipping `botan-config.cmake` files](https://github.com/randombit/botan/pull/3722). Though, at the moment they are not "configuration aware", yet. Maybe that would help simplifying (or hopefully eventually obsolete) your `FindBotan.cmake`.

As a side-note: There's an [ongoing effort to get Botan 3.x into conan-center-index](https://github.com/conan-io/conan-center-index/pull/18079). The recipe is ready, pending final approval, and will hopefully be available soon.

**Comment by droidmonkey** [comment]
Looks like vcpkg has a rule about renaming libraries. Would you guys be willing to shift to botand-3.dll for the next mid level release?

https://github.com/microsoft/vcpkg/pull/35287#issuecomment-1824696836

**Comment by dg0yt** [comment]
FTR the vcpkg discussion was not only about "rules".
- There are downsides of changing names: breaking users which rely on the existing name. Sometimes in ways which are not obvious.
- Renaming is not needed for depoying DLLs from vcpkg builds: Debug artifacts are in a different location.

**Comment by droidmonkey** [comment]
@dg0yt libraries get renamed all the time. Botan themselves added a `-3` suffix for their last major version number. You are being a tad aggressive about shooting down my suggestion,  just letting you know. I'll let the maintainers make a decision, that's what open source is all about: proposal, discussion, decision. Thanks.

**Comment by reneme** [comment]
> Would you guys be willing to shift to botand-3.dll/lib for the next mid level release?

Changing the default (i.e. renaming to `botand-3.dll` for the debug library without explicitly adding `--library-suffix=d`) would  have to wait until the next major release (that's likely years in the future). Changing the default in a minor release would be "surprising" for downstream users, for sure. (cc @randombit)

However, I would hope that the recently added CMake integration files could come in handy with this. I currently see two major limitations that would need to be addressed:

1. They currently don't support multi-config installations (debug vs. release binaries), as our build system doesn't support multi-config builds out of the box.
2. They assume a vanilla installation directory structure (as generated by `make install`).

I reckon that vcpkg, but also other package managers, want to change the installation directory structure at their discretion. E.g. to put debug libraries in a different subdirectory. That would currently render the botan-config.cmake files broken and useless. I.e. this needs work anyway.

Investing into the CMake integration files could be done now, rather than waiting until the next major release. Do you think that could be helpful to you, @droidmonkey?

**Comment by droidmonkey** [comment]
Hello, we will certainly give your cmake files a spin when they are ready. I am going to invest some time in our own cmake files to ensure they are operating correctly. I think we have a lot of duplicative path additions (legacy cruft) that don't play well with vcpkg.

**Comment by dg0yt** [comment]
@droidmonkey In particular the find modules in keypassxc lack `NAMES_PER_DIR` when doing `find_libary` with multiple `NAMES`. That's why you don't get a hit from the prefix with highest priority but from the name with highest priority.

**Comment by droidmonkey** [comment]
Oooh that's sneaky, its called out at the top of the docs for find_library but not defined until near the bottom of it.

> When more than one value is given to the NAMES option this command by default will consider one name at a time and search every directory for it. The NAMES_PER_DIR option tells this command to consider one directory at a time and search for all names in it.

**Comment by crazydef** [comment]
Having previously [reported errors](https://github.com/randombit/botan/issues/3510) with the `--library-suffix` option, I would strongly request you do not change the format to `<name><suffix>-3.lib`.  Simply because then the `suffix` isn't a suffix.

In all honesty, putting the version number in the name isn't really standard on any platform, is it?  On Linux and MacOS the version number is usually appended after the file extension.  On Windows, I don't know if anyone (else) actually includes the version number anywhere, do they?  Most package manages I've used version things at the directory level.
