### ISSUE TITLE
Possible variable-time division when decapsulating in Kyber

### ISSUE THREAD

**Issue by xvzcf** [randombit/botan#3844]
This bit of code is used in compressing a polynomial ring element into a (secret) message: https://github.com/randombit/botan/blob/3dcf8af5a77e9e7643cc58cd5498d3950c1470ef/src/lib/pubkey/kyber/kyber_common/kyber.cpp#L389-L390

To do so, it performs a division by Q that might not necessarily compile to a multiplication instruction: looking at the output of some C compilers using https://godbolt.org/z/sKn3TKKGq and https://godbolt.org/z/8GqKoTfYh for example, a division instruction is emitted even when -O3 is specified. Should a division instruction be emitted, its execution time would likely be variable and leak information about its secret input.

We reported a similar issue in the CRYSTALS-Kyber reference implementation; you may want to use their fix: https://github.com/pq-crystals/kyber/commit/dda29cc63af721981ee2c831cf00822e69be3220

**Comment by reneme** [comment]
Nice! Thanks for pointing this out. We'll look into it.

**Comment by reneme** [comment]
Thanks again for reporting. We decided not to roll an official patch release for this, since the next minor release of the library is expected in the beginning of January.

Nevertheless: [the patch](https://github.com/randombit/botan/commit/5cfd8953f672f8ec4aaac2657fcd42cb70bc20fd) applies without issues onto the 3.2.0 code and can be used if users need it before that.
