### ISSUE TITLE
Need support for module deprecation

### ISSUE THREAD

**Issue by randombit** [randombit/botan#3853]
A bit of discussion at the end of #3807 about this.

One question is how a deprecated module behaves. My take

* If a deprecated module is being built, we warn about it
* It continues to be included by default, you can explicitly request it if you want, etc. Basically its status as deprecated does not affect module selection.
* There is a new option (`--disable-deprecated-features`?) that disables them, and which possibly also sets a macro that can be used to selectively disable other deprecated features (eg 64 bit GCM tags).

**Comment by reneme** [comment]
This is probably useful, especially when paired with the `--disable-deprecated-features` flag. Otherwise, I'm not exactly convinced whether a warning during configuration is prominent enough for downstream users to actually notice.

While we're discussing to introduce a notion of "lifecycle" for modules: let me bring up [this idea from last year](https://github.com/randombit/botan/discussions/3110). I.e. flagging modules as "experimental". The behaviour of "experimental" modules would likely be similar to "deprecated" modules. Except that they might not be enabled by default and hence require an `--enable-experimental-features` flag.

**Comment by randombit** [comment]
It would be easy to introduce both of these at the same time.
