### ISSUE TITLE
Is Botan vulnerable to SLOTH attacks?

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#397]
A new attack has been published on protocols such as TLS, IKE, and SSH in case weak hash functions are used.

[Here](http://www.mitls.org/downloads/transcript-collisions.pdf) is the paper.

If i am right Botan is not vulnerable in default configuration because in `tls_policy.cpp` in `Policy::allowed_signature_hashes()` MD5 is not offered as a allowed signature hash.

So as long as someone does not overload this function and enables MD5 this should be save?!

**Comment by randombit** [comment]
Having not read the paper completely: I believe having MD5 (and also SHA-1) disabled in the default policy should prevent the most severe of their attacks. There is not much to be done about the (not quite practical) downgrade attack against TLS v1.0/v1.1 since the MD5|SHA-1 concatenation is hardcoded into those protocol versions.

It would probably be reasonable to completely remove support for MD5 for TLS v1.2 signatures since it's obviously broken at this point. (SHA-1 might deserve the same treatment here; hopefully all TLS v1.2 stacks do support SHA-2 signatures, but I haven't checked this).

In reviewing this code I did notice what is probably a bug in the extension handling; even if the policy disables a hash in the client hello, if the server sends that hash anyway I think it will be accepted as they are not cross checked. This does not seem relevant to SLOTH though.

**Comment by neusdan** [comment]
Regarding the bug you have noticed. This seems to be similar to what in GnuTLS was fixed. 

From  [here](http://www.mitls.org/pages/attacks/SLOTH):

> GnuTLS clients and servers up to version 3.3.14 accept RSA-MD5 signatures even if the client or server disables them (using the priority string, for example).

**Comment by randombit** [comment]
Yeah there was a FIXME in the code going back to 1.11.0 for this :/

Just pushed a fix on a branch, plan to land on master shortlyish and do a release in the next day or so.

https://github.com/randombit/botan/commit/29faef22d242d43dc9ae7aac884ef10ce45e591d

**Comment by cordney** [comment]
It seems 29faef22d242d43dc9ae7aac884ef10ce45e591d never landed on master, or do I miss something?

**Comment by neusdan** [comment]
here is the fix:
2f7225c

**Comment by cordney** [comment]
IC, so it's in 1.11.27 and we can close here.

**Comment by neusdan** [comment]
it's not yet released. Landed today on master

**Comment by cordney** [comment]
Ok, was confused by the commit date (7 Jan).

**Comment by randombit** [comment]
Yeah my bad, wrote the patch but forgot to land it :/

**Comment by randombit** [comment]
Failure to check server sigs against policy fixed in 1.11.29
