### ISSUE TITLE
Use of noreturn keyword

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#402]
Currently `noreturn` is not used to mark functions that do no return to the caller. Is there any reason for this?

I don't know if `[[noreturn]]` is already supported by clang and gcc but in any case MSVC does not support it. So something like this is needed:

```
#if !defined(BOTAN_NORETURN)
#  if defined(_MSC_VER)
#    define BOTAN_NORETURN __declspec(noreturn)
#  elif defined(__GNUC__)
#    define BOTAN_NORETURN __attribute__ ((__noreturn__))
#  else
#    define _NO_NORETURN
#    define BOTAN_NORETURN
#  endif
#endif
```

I came up to this because clang-analyzer warns for example about null pointer dereferencing at some places although there is a BOTAN_ASSERT check to prevent this.

Adding the noreturn property to the assertion_failure() function in assert.cpp probably would help.

**Comment by neusdan** [comment]
The compiler will also be happy because more/better optimizations are possible.

**Comment by randombit** [comment]
No reason, just hadn't been done. It might help to do a pass using GCC's -Wsuggest-attribute=noreturn

Somewhat similarly (for GCC and Clang at least) it's possible to mark functions with attribute 'pure' or 'const' (distinct from the C++ const keyword) which can allow better optimization (at the risk of causing bad codegen if a function is incorrectly annotated). It may allow better codegen at the calling site, in cases where the function body isn't visible, since the compiler can know eg with a 'const' function that the call can be safely reordered with a write to a global variable, because a 'const' function promises to neither read nor write anything but its arguments. I haven't checked if in practice with a modern compiler version either attribute provides any actual improvements however. 

There is also C++11 `final` which is not used in the source currently (again purely due to, I haven't done it yet), but I would guess 90% of the classes should be marked as final, which would both make it clear which classes are actually intended for derivation and likely help out the optimizer wrt devirtualization.

**Comment by randombit** [comment]
All set here I think
