### ISSUE TITLE
Keccak_1600 output does not match NIST SHA3 test vectors.

### ISSUE THREAD

**Issue by BouncyCCPP** [randombit/botan#412]
Hi,
Is Keccak_1600 implementation in Botan v 1.11.26 based on the final approved SHA-3 algorithm?  I wrote a little test program to get  a 256 bit digest.  The program is run on a Window 7.  My code is as   following:
secure_vector<byte> sha3v2(vector<byte> input, size_t output_bits) {
  Keccak_1600 sha3(output_bits);
  sha3.update(input);
  return (sha3.final());
}
...
cout << "SHA3v2-256: " + Botan::hex_encode(sha3v2(data, 256)) << "\n";

Where the data is "abc".

Botan returns: 
SHA3v2-256: 4E03657AEA45A94FC7D47BA826C8D667C0D1E6E33A64A036EC44F58FA12D6C45
while NIST vector (http://www.di-mgt.com.au/sha_testvectors.html) for the same input is:
SHA-3-256    3a985da74fe225b2045c172d6bd390bd855f086e3e9d525b46bfe24511431532

Is it my test routine or is it that Keccak_16000 is not based on the approved SHA-3 algorithm?  If it is the second case, then will Botan be updated to support the final version?  If yes, is there some time frame?

Thanks

**Comment by randombit** [comment]
The Keccak version implemented is the round 3 version from the NIST hash competition. I believe NIST made some changes to the algorithm for the final SHA-3, as well as defining various alternative modes like SHAKE.

The final SHA-3 will doubtless be supported eventually (likely with a rename of Keccak, since it will be an incompatible change of the algorithm), but the timeline would be either when someone does the research and submits the appropriate patch or whenever I decide SHA-3 support is relevant to some other goal and do it. Since SHA-3 is slower than SHA-512 and not widely deployed yet, it has not been a priority for me personally.

**Comment by mouse07410** [comment]
My preference would be to keep both the original Keccak, *and* the modified algorithm renamed as SHA-3.

**Comment by randombit** [comment]
That's true it should be easy to continue supporting the current version of Keccak which has been available in the library now for some time (since 2010 or so) in addition to adding SHA-3 support. No idea if anyone is using Keccak but there is no point in breaking their usage, as the currently implemented version remains secure.

**Comment by mouse07410** [comment]
> No idea if anyone is using Keccak...

Keccak offers stronger security guarantees at the cost of slower performance. Leaving along the argument of whether that extra security matters, I'd say for some people it could justify using the original Keccak over the standardized SHA-3.

Somewhat similar situation with AES: Rijndael supports not only keys up to 256 bits, but also the block size. NIST removed the variable block size capability. Yet some people (myself included) need that wider block size version for their block cipher-based cryptographic constructs.

**Comment by neusdan** [comment]
Can this be closed since now SHA-3 and Keccak are available?

**Comment by randombit** [comment]
Yes nothing else we need to do here afaict. Closing. Thank you for the original report @BouncyCCPP SHA-3 will be available in the next release coming shortly.
