### ISSUE TITLE
Variable shadowing in src\lib\pubkey\mce\polyn_gf2m.cpp

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#420]
Something is wrong with this code. The local variable `m_deg` shadows the member var `m_deg`

```C++
polyn_gf2m::polyn_gf2m(int t, Botan::RandomNumberGenerator& rng, std::shared_ptr<GF2m_Field> sp_field)
   :m_deg(t),
    coeff(t+1),
    msp_field(sp_field)
   {
   int i;
   (*this).set_coef( t, 1);
   i = 0;
   int m_deg;
   do
      {
      for (i = 0; i < t; ++i)
         {
         (*this).set_coef( i, random_code_element(sp_field->get_cardinality(), rng));
         }
      polyn_gf2m::degppf(*this, &m_deg);
      }
   while (m_deg < t);
   }
```

**Comment by randombit** [comment]
The McEliece code is adapted from a C implementation and has a rather different style, and polyn_gf2m is particularly opaque.

I believe this is correct, because here we are requiring a m_deg of exactly `t` which is set in the constructor. Then the m_deg declared is used to degppf which is the degree of the random polynomial we produced in the loop above equal to t. But this should be fixed. A lot of the McEliece code would benefit from more readable names.
