### ISSUE TITLE
Code style template

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#424]
It would be really really nice to have a clang-format style (#284) and of course one that is more optimized for readability than the current one.

Until then i've found a solution to format the code with the current style with [Astyle](http://astyle.sourceforge.net/astyle.html)

`--style=whitesmith --indent=spaces=3 --align-pointer=type --align-reference=type --max-code-length=120 --attach-namespaces --indent-preproc-block --indent-preproc-define --unpad-paren --keep-one-line-blocks --keep-one-line-statements --mode=c`

**Comment by randombit** [comment]
Re the reformat, I'm waiting for a quiet release where ideally the reformat can be the only major change. I'm also planning to use clang-tidys fixit mode to add braces around all single-statement blocks at the same time. clang-tidy can insert {} but does not try to match any particular indentation style so needs a format tool to help out.

I was kind of frustrated that clang-format insists on mangling closing namespace brackets (this seems to not be controllable via any clang-format toggle I could find). But then I decided it does not matter that much :P

**Comment by al45tair** [comment]
Have you considered e.g.

```c++
#define BEGIN_BOTAN_NS namespace Botan {
#define END_BOTAN_NS   }
```

Has the added benefit of making many editors' auto indent work the way you'd hope...

**Comment by ksanderon** [comment]
sorry, that I'm  necormancer - with clang-format is not possible (in 99%) to have whitesmith style even "strict allman" is sometimes hard - mostly regarding lambda functions. For more I not recommend it because of major changes in format style between versions - if rules are more complex than just:
```
BasedOnStyle: XYZ
Standard: C++XY
IndentWidth: cde
ColumnLimit: fgh
```

However it work well with complex templates ;)

From other hand astyle should do the job in botan and not break to much in macros and templates, because botan simply don't have them too much / complicated.

Maybe after succesful "code reformat" it will be worth to add to CI job which will run something like this during PR:
```
find * -iname '*.h' -o -iname '*.cpp' | xargs clang-format -i -style=file
git status --porcelain > ../status.log
git diff
test ! -s ../status.log
```
just to keep code style.

**Comment by webmaster128** [comment]
> Maybe after succesful "code reformat" it will be worth to add to CI job which will run something like this during PR:

Something like that could nicely be added to the "lint" job (see Travis matrix) as it does not require compilation

**Comment by randombit** [comment]
As of #3502 `clang-format` is now in use for Botan3
