### ISSUE TITLE
Branching on uninitialized memory in Botan::PCurve::PCurveInstance

### ISSUE THREAD

**Issue by guidovranken** [randombit/botan#4265]
Did you see the OSS-Fuzz reports?

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70745
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70737
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=70746

Looks like it could be a new bug. Don't have time to write a reproducer right now but I can do that later if necessary.

**Comment by randombit** [comment]
I hadn't seen this

**Comment by randombit** [comment]
In all three the error occurs while creating the `PrecomputedBaseMulTable` which is completely deterministic (we could even do it at compile time except that the compilers choke on it). And in all three the final error is in `CT::value_barrier`.

Based on the [regression range](https://github.com/randombit/botan/compare/2a5a9306e1e97420d2629aad89130d61b43db3dc...44897ad6067f7978507235a5b5abcea0cb709799) from OSS-Fuzz I think the change that triggered this is

```
      if(const auto id = PCurve::PrimeOrderCurveId::from_oid(m_oid)) {
         m_pcurve = PCurve::PrimeOrderCurve::from_id(*id);
      }
```

Ie that we create these precomputed tables for any supported curves as a byproduct of using the public EC interfaces.

Valgrind is happy with all of this so I'm suspecting the issue is that the inline asm used in `value_barrier` is confusing MSan, I recall we've had problems like this in the past.

**Comment by guidovranken** [comment]
Yes, MSAN does not work with inline assembly. Instrinsics are fine, though. What do you propose to solve this issue:

- Change Botan to use intrinsics instead of inline assembly.
- Use a command line option to disable inline assembly (if it exists. which one)
- Disable Botan MSAN build on OSS-Fuzz

**Comment by randombit** [comment]
In this case there is no usable intrinsic (though it would be nice if there was); the inline asm is just cycling a value through an inline asm block to prevent compilers (mostly Clang) from performing value range analysis and converting (would-be) constant time code into something using conditional jumps.

```
      asm("" : "+r"(x) : /* no input */);
      return x;
```

We could just disable using this when MSan is on; I don't think we can guarantee anything about constant time behavior with sanitizers on in any case.

What I don't understand is

* We use the constant time utilities in many other parts of the code (integer math, PKCSv1 decoding, etc) - including spots that I would think Cryptofuzz would already hit.
* We've been using the inline asm in `value_barrier` since c4fb4d6a9f in early June.
* OpenSSL and BoringSSL among others use the exact same trick and do not afaict gate the behavior on MSan.

But I guess the easy way to check is to disable it on MSan and see if the issues resolve.

**Comment by randombit** [comment]
I've merged #4267 so I guess we'll see if this resolves the issue next build cycle. In the meantime I'll see if we can add MSan to CI to catch things like this before they break on OSS-Fuzz.

**Comment by guidovranken** [comment]
`value_barrier` is not the source of the uninitialized memory, that is only where it is used for a branch. According to the MSAN traces (assuming they are correct), these are the sources:

https://oss-fuzz.com/testcase-detail/6721559926996992

```
  Uninitialized value was created by an allocation of 'r.i1' in the stack frame of function '_ZN5BotanmiERKNS_6IntModINS_6PCurve12_GLOBAL__N_19sm2p256v112Sm2p256v1RepINS_13EllipticCurveINS3_6ParamsES4_E11FieldParamsEEEEESC_'
    #0 0x203b610 in Botan::operator-(Botan::IntMod<Botan::PCurve::(anonymous namespace)::sm2p256v1::Sm2p256v1Rep<Botan::EllipticCurve<Botan::PCurve::(anonymous namespace)::sm2p256v1::Params, Botan::PCurve::(anonymous namespace)::sm2p256v1::Sm2p256v1Rep>::FieldParams> > const&, Botan::IntMod<Botan::PCurve::(anonymous namespace)::sm2p256v1::Sm2p256v1Rep<Botan::EllipticCurve<Botan::PCurve::(anonymous namespace)::sm2p256v1::Params, Botan::PCurve::(anonymous namespace)::sm2p256v1::Sm2p256v1Rep>::FieldParams> > const&) botan/build/include/internal/botan/internal/pcurves_impl.h:137
```

https://oss-fuzz.com/testcase-detail/5187614846550016

```
	  Uninitialized value was created by an allocation of 'r.i.i' in the stack frame of function '_ZNK5Botan20ProjectiveCurvePointINS_6IntModINS_6PCurve12_GLOBAL__N_19secp256k112Secp256k1RepINS_13EllipticCurveINS4_6ParamsES5_E11FieldParamsEEEEES7_E3dblEv'
    #0 0x24a2300 in Botan::ProjectiveCurvePoint<Botan::IntMod<Botan::PCurve::(anonymous namespace)::secp256k1::Secp256k1Rep<Botan::EllipticCurve<Botan::PCurve::(anonymous namespace)::secp256k1::Params, Botan::PCurve::(anonymous namespace)::secp256k1::Secp256k1Rep>::FieldParams> >, Botan::PCurve::(anonymous namespace)::secp256k1::Params>::dbl() const botan/build/include/internal/botan/internal/pcurves_impl.h:789
```

https://oss-fuzz.com/testcase-detail/4697449281683456

```
  Uninitialized value was created by an allocation of 'z2' in the stack frame of function '_ZNK5Botan20ProjectiveCurvePointINS_6IntModINS_6PCurve12_GLOBAL__N_19secp521r17P521RepINS_13EllipticCurveINS4_6ParamsES5_E11FieldParamsEEEEES7_E3dblEv'
    #0 0x254b910 in Botan::ProjectiveCurvePoint<Botan::IntMod<Botan::PCurve::(anonymous namespace)::secp521r1::P521Rep<Botan::EllipticCurve<Botan::PCurve::(anonymous namespace)::secp521r1::Params, Botan::PCurve::(anonymous namespace)::secp521r1::P521Rep>::FieldParams> >, Botan::PCurve::(anonymous namespace)::secp521r1::Params>::dbl() const botan/build/include/internal/botan/internal/pcurves_impl.h:789
```

OpenSSL and BoringSSL are compiled with `no-asm` on MSAN OSS-Fuzz builds so I assume that circumvents any inline assembly getting compiled.

**Comment by guidovranken** [comment]
Though if it is indeed due to inline assembly somewhere in the code base, these MSAN reports are not necessarily reliable with regards to the provenance of the uninitialized memory.

**Comment by randombit** [comment]
>value_barrier is not the source of the uninitialized memory, that is only where it is used for a branch.

Right, but `value_barrier` *does not branch*. So I strongly suspect this is a MSan bad iteraction and #4267 will resolve it.

> Though if it is indeed due to inline assembly somewhere in the code base

Quite a bit of inline asm is in use, we're just careful to make it so that MSan is aware that the value is initialized (mostly by initializing values outside of the `asm` blocks)

**Comment by randombit** [comment]
OK #4267 apparently did not resolve. One possible issue there is that https://github.com/google/oss-fuzz/blob/master/projects/cryptofuzz/build.sh#L401 does not set `--enable-sanitizers=memory` so we don't set the build macro.

#4273 adds `--disable-asm` option which seems to be the conventional fix for this so ...

**Comment by guidovranken** [comment]
Tried to build this in a OSS-Fuzz container using

```
./configure.py  --disable-asm --cc-bin=$CXX --cc-abi-flags="$CXXFLAGS" --disable-shared --disable-modules=locking_allocator --build-targets=static --without-documentation
```

and I get

```
src/lib/rng/processor_rng/processor_rng.cpp:62:9: error: no matching function for call to '_rdrand64_step'
   62 |    cf = _rdrand64_step(&output);
      |         ^~~~~~~~~~~~~~
/usr/local/lib/clang/18/include/immintrin.h:347:1: note: candidate function not viable: no known conversion from 'hwrng_output *' (aka 'unsigned long *') to 'unsigned long long *' for 1st argument
  347 | _rdrand64_step(unsigned long long *__p)
      | ^              ~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Makefile:1135: build/obj/lib/rng_processor_rng.o] Error 1
make: *** Waiting for unfinished jobs....
src/lib/utils/cpuid/cpuid_x86.cpp:39:8: warning: #warning is a C++23 extension [-Wpedantic]
   39 |       #warning "No way of calling x86 cpuid instruction for this compiler"
      |        ^
src/lib/utils/cpuid/cpuid_x86.cpp:39:8: warning: "No way of calling x86 cpuid instruction for this compiler" [-W#warnings]
src/lib/utils/cpuid/cpuid_x86.cpp:29:28: warning: unused parameter 'type' [-Wunused-parameter]
   29 | void invoke_cpuid(uint32_t type, uint32_t out[4]) {
      |                            ^
src/lib/utils/cpuid/cpuid_x86.cpp:53:8: warning: #warning is a C++23 extension [-Wpedantic]
   53 |       #warning "No way of calling x86 cpuid instruction for this compiler"
      |        ^
src/lib/utils/cpuid/cpuid_x86.cpp:53:8: warning: "No way of calling x86 cpuid instruction for this compiler" [-W#warnings]
src/lib/utils/cpuid/cpuid_x86.cpp:43:37: warning: unused parameter 'type' [-Wunused-parameter]
   43 | void invoke_cpuid_sublevel(uint32_t type, uint32_t level, uint32_t out[4]) {
      |                                     ^
src/lib/utils/cpuid/cpuid_x86.cpp:43:52: warning: unused parameter 'level' [-Wunused-parameter]
   43 | void invoke_cpuid_sublevel(uint32_t type, uint32_t level, uint32_t out[4]) {
      |                                                    ^
7 warnings generated.

```
