### ISSUE TITLE
Ubuntu 22.04 build botan 3.5.0 will send shutdown singal

### ISSUE THREAD

**Issue by hks2002** [randombit/botan#4321]

**Comment by reneme** [comment]
Would you mind to add some more details about your problem? For instance:

* Do you have trouble during configuring the library or during the build?
* What is you `configure.py` command invocation?
* Are you building the library from a repository checkout or via a package manager (for instance via Conan)?
* What happens exactly, vs. what is your expected behavior?

Thanks a lot.

**Comment by hks2002** [comment]
Just run 
```
./configure.py
make -j
```
It seems the root cause is point to 8G mem not enough, and this will let we can't build it in github workflow actions.
If one project want to use botan 3 in ubuntu, ubuntu currently provide botan2, this will be a problem.

**Comment by reneme** [comment]
Can you provide a log from your failing GitHub Actions job?

Our CI is also building the library on GitHub Actions in various configurations and even running tests under valgrind without problems.

**Comment by hks2002** [comment]
please refer it here:
https://github.com/hks2002/trantor/actions/runs/10467627020/job/28986791213
and in my VMware Ubuntu, download source, run configure.py then build, also have this problem.

**Comment by randombit** [comment]
> make -j

This will try to build every single file in the tree at once! GH actions images only have 4 cores, there is no purpose to running more than 4 or 5 jobs simultaneously.

**Comment by hks2002** [comment]
Thanks.

**Comment by reneme** [comment]
If you were to use `./configure.py --build-tool=ninja` and then just use `ninja` instead of `make`, this will automatically run a parallel build with a reasonable default.
