### ISSUE TITLE
Enabled optimizations in debug builds

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#433]
Optimizations are enabled (/O2) if i use configure.py with `--debug-mode` at least on Windows.

**Comment by randombit** [comment]
Intentional. Not sure about how VC behaves with this but very often during development I want optimizations + debug symbols in the same binary (for valgrind, fuzzing, ...) and simply because without any optimizations things can get pretty slow.

--debug-mode is currently an alias for --with-debug-info, maybe it would be better used as a synonym for the option pair `--with-debug-info` + `--no-optimizations`. But certainly I view with/without debug symbols and with/without optimizations as orthogonal considerations and want the ability to toggle either one on or off independently.

**Comment by webmaster128** [comment]
CMake differentiates the build modes Release, RelWithDebInfo and Debug to target those use cases. For us this three modes turned out to be useful in practice. Maybe it would help to align with those namings.

When debugging I often needed no optimization to access the value of variables which otherwise are optimized out.

**Comment by neusdan** [comment]
I think the most tools use debug mode as a configuration where debug info is generated and optimizations are turned off. So changing `--debug-mode` to `--with-debug-info` + `--no-optimizations` should match what most people expect to be happen.
