### ISSUE TITLE
Question: Custom X509 Extensions

### ISSUE THREAD

**Issue by ChrisBFX** [randombit/botan#435]
Hi,
i'm currently trying to read some custom extensions from a certificate. It gets parsed correctly and I also know the oids of the extensions, but I can't find a way to get them with `X509_Certificate`. Do I have to parse the certificate myself? The only thing which looked promising was `X509_DN::get_attributes()` which returns a map of oid->string.

Thanks
Chris

**Comment by randombit** [comment]
Sorry, no. If you check Extensions::decode_from (x509_ext.cpp) you'll see that if the extension type is unknown then the value is discarded. But it absolutely does make sense to support this. Probably the fix is capture and make retrievable all of the binary values of extensions (known or unknown) to allow any needed interpretation by applications. This could be stored as an additional map from OIDs to byte vectors in the Extensions type which is then copied out to the X509_Certificate during decoding (in `force_decode`). I'd take a patch to do this, if you were interested in trying. Either way, thanks for asking and pointing out this deficiency.
