### ISSUE TITLE
Compile Error for Amalgamation build in Linux: In file src/cli/entropy.cpp: include file not found

### ISSUE THREAD

**Issue by CBtiger** [randombit/botan#4352]
I was trying to build an amalgamation build of the current stable release 3.5.0 under Linux gcc 11.3.0 and found that the code would not compile.
* version: https://botan.randombit.net/releases/Botan-3.5.0.tar.xz, released on 2024-07-08.

Reproduce with
```
  ./configure --amalgamation 
  make
```
The resutling error is
```
src/cli/entropy.cpp:7:109: fatal error: ../tests/test_rng.h: No such fule or directory
     7 | #include "../tests/test_rng.h"  // FIXME
```
Cause: 
* The // Fixme postfix prevented the compiler to include this line. 

Workaround:
* I removed the "//FIXME", then it did compile.  Its that the recommended fix?
* when removing the #include line itself, the build failed since the class member _Entropy::go()_  in entropy.cpp line 41 uses a RNG  class from "Botan_Tests" namespace. 
* It seems that the file _src/cli/speed.cpp_ has the same problem

**Comment by randombit** [comment]
Something is strange here since that comment has been in place a long time and has never caused problems in either C++11 or C++20 modes. I also can't find anything that indicates that comments after an include statement aren't fully standard, and I cannot replicate it on godbolt either (https://godbolt.org/z/eeWx6c4cP). Not to mention there are similar comments in `types.h`....

Does the godbolt snippet compile for you? Are you sure your versions of the compiler and `cpp` are consistent?

**Comment by CBtiger** [comment]
Thanks for looking at that. Compiling your snippet indeed worked with no issues, I admit I did not think very much when the code compiled without the comment, so my assessment was clearly rubbish. 
I am going to try to reproduce it on another computer running the same OS and get back.

**Comment by CBtiger** [comment]
OK, False alarm. On the other computer it compiled fine. I guess I had messed up something up before the build I had been trying different build settings before, maybe abusing configure - I don't know. 

Sorry for the fuss. Is there a way to delete an issue?

**Comment by randombit** [comment]
No need to delete, we can just close, glad things are working now
