### ISSUE TITLE
ASN1_String::decode_from wrong handling of different charsets

### ISSUE THREAD

**Issue by ChrisBFX** [randombit/botan#438]
Hi,
it seems like the arguments of Charset::transcode regarding the charset should be swapped
to.
`Charset::transcode(ASN1::to_string(obj), LOCAL_CHARSET, charset_is)`

**Comment by randombit** [comment]
You're right. As you might guess from a bug like this, certs with anything past plain ASCII are not really tested/supported right now. `ASN1_String` is very old code, and converts all strings internally to Latin-1 instead of UTF-8 which mangles many codepoints. It probably needs to be upgraded to use `std::codecvt` for the UTF-8/UCS-2 conversion, and store UTF-8.

I'm not sure if support for Latin-1 (aka T61_STRING) is even needed anymore. Probably most certs have switched to UTF-8 long ago.
