### ISSUE TITLE
The --enable-module=“jitter_rng” parameter

### ISSUE THREAD

**Issue by wendig0x** [randombit/botan#4426]
The --enable-module=“jitter_rng” parameter is missing from the configure.py script

**Comment by reneme** [comment]
I guess you're referring to [the documentation](https://botan.randombit.net/handbook/api_ref/rng.html#jitter-rng), stating that `jitter_rng` needs a specific module to be activated.

This is a typo, it should say `--enable-modules=jitter_rng`. In plural, because this takes a comma-separated list of modules to be enabled.

Thanks for reporting!
