### ISSUE TITLE
Generating Seeds from RDRAND

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#447]
Section 4.2.6 from [here](https://software.intel.com/en-us/articles/intel-digital-random-number-generator-drng-software-implementation-guide)

I think it makes sense to implement this for CPUs where Rdseed is not available. What do you think?

Another question:

> The application should be prepared to give up on RDSEED after a small number of retries, where "small" is somewhere between 1 and 100, depending on the application's sensitivity to delays. As with synchronous applications, it is recommended that a PAUSE instruction be inserted into the retry loop.

So should we place a sleep in the RdRand/RdSeed retry loops?

**Comment by drbo** [comment]
Note that RDSEED and RDRAND are considered [possibly backdoored by the NSA][1] and should not be used except in combination with other entropy sources.  OS X and *BSD kernels use RdRand in this way, but Linux uses it incorrectly.

[1]: https://en.wikipedia.org/wiki/RdRand

**Comment by randombit** [comment]
In the default configuration such RNGs are not trusted at a all (https://github.com/randombit/botan/blob/master/src/build-data/buildh.in#L163)
because of this. That is they are used and their outputs are incorporated into the seed, but are assumed to contribute 0 entropy to the result, so normal software polling proceeds as usual. This relies heavily on the assumption that urandom is not itself just passing through RDRAND, though even then a few other values (timestamp, /proc contents) are also incorporated into the seed.

It has been theorized (by DJB I think?) that RDRAND/RDSEED might not just have a NOBUS backdoor but might actually analyze the current software RNG state and actively output values to manipulate the resulting state. In which case even calling it might be a risk. But I think this is rather less likely, and the RNG used in Botan should be safe even if it were (in that it is designed to accept seed inputs even from such an adaptive attacker and remain secure, as long as some unknown to the attacker inputs are eventually used).

**Comment by noloader** [comment]
> So should we place a sleep in the RdRand/RdSeed retry loops?

`RDRAND` is designed to never underflow. If it fails, then its an exceptional problem. Also DJ's comments at http://lists.randombit.net/pipermail/cryptography/2016-June/007702.html.

`RDSEED` will underflow on occasion and its expected. Empirical testing shows it fails fewer than 64 times in a tight loop for a request of 10,000 bytes.

I have never needed to call to `sleep` or `usleep` for `RDSEED`. If it fails, then immediately retry the operation.

**Comment by randombit** [comment]
@neusdan Is there anything else we need to do here?

**Comment by neusdan** [comment]
This is about generating a seed from RdRand for systems where RdSeed is not available.

> RDSEED is intended for seeding a software PRNG of arbitrary width. RDRAND is intended for applications that merely require high-quality random numbers.

The link in the first post describes a way to do this.

> Processors that do not support the RDSEED instruction can leverage the reseeding guarantee of the DRBG to generate random seeds from values obtained via RDRAND.

So in my understanding it's better to use this technique to seed the HMAC_DRBG than to use RdRand directly. But I haven't looked in the code from Intel yet.

**Comment by randombit** [comment]
OK, maybe an argument for decoupling behavior of RDRAND-as-RNG (RDRAND_RNG) from RDRAND-as-seed-material-source (RDRAND entropy source). Will try to take a look at this further sometime this week.
