### ISSUE TITLE
X509_Certificate class constructor should not check for unknown critical extensions

### ISSUE THREAD

**Issue by caschulz88** [randombit/botan#449]
Hi,

we are currently working on switching to botan from GnuTLS in one of our products. We are now facing an issue with botan because of the way how botan checks certificates when this check is done. The real issue here is that the cerificate verification is done here (at least the check for unknown critical extensions) while loading the certificate from an std::vector<byte> into a X509_Certificate. We support external CAs, that might specify some certificate extensions as critical, in our product and when these checks are done while creating an instance of X509_Certificate it is not possible to create this instance since the OID might not be known (for example for the OID  2.16.840.1.113730.1.1, which is the OID for Netscape certificate type). As our customer might also use other custom OIDs we need to change the way how botan works here in a general way instad of simply adding all OIDs to the known OIDs of botan.

As we only load the certificate in order to get the public key from it or in order to store it in some other way we don't actual run a real verification of the certificate, but we cannot even load it as X509_Certificate.

RFC 5280 says that exactly this step should be done while executing the certificate verification and not on loading time: 6.1.4. (i) (o): 'Recognize and process any other critical extension present in the certificate.  Process any other recognized non-critical extension present in the certificate that is relevant to path processing.'

Cheers

/cc @neusdan @cordney

**Comment by randombit** [comment]
Allowing loading/inspection of a cert even with unrecognized critical extensions seems a reasonable goal. For the case you mention of a customer provided CA with an unknown extension, I think the CA should still not be usable for verification which limits its usefulness. But if applications could also provide support for their own custom X.509 extensions then your app could first inspect the cert and add handlers for whichever critical OIDs were not already in place.

If the extension changes path processing things get more complicated. Perhaps this could work by allowing each Extension* on each certificate to have a chance to inspect the path during validation. This would make path validation more complex in some ways but simplify it in others (for example no reason for explicit path length checks for basicConstraints would appear in path validation itself). Unknown critical extensions then become decoded as a `Unknown_Critical_Extension` type which always adds a failure status to the result.

Right now the Extension types are actually thrown away after dumping some data into the `Data_Store` type; that's already been identified as a problem (see also #437) and it would be better for `X509_Certificate` to hold the DN and extensions directly. So that would have to change, at least for the approach I'm outlining here.

**Comment by cordney** [comment]
To add some more context: We have a certificate store that generates keys and stores them with the corresponding certificate chain and provides some lookup methods to retrieve them. The store does not interpret these certificates, nor does it do any path validation. The keys and certificates are given to other applications, where they are actually used, e.g., to strongswan for VPN peer authentication. It is up to the application to interpret the certificates and apply any path validation.

We are using the fingerprint of the peer certificate's subject public key in each chain as the key in the certificate store. That's where we currently have a problem with the `X509_Certificate`'s constructor, as it throws on any unknown critical extension and we won't have a chance to ever get the public key fingerprint on any such certificate, e.g., one that uses the Netscape cert type.

We will try to implement the solution you outlined above.

**Comment by randombit** [comment]
With the merge of #469 can this issue be closed?

**Comment by caschulz88** [comment]
Yes, this can be closed! With the merge of #469 this issue is now fixed and everything works for us. Thanks!
