### ISSUE TITLE
How to build for windows

### ISSUE THREAD

**Issue by naushadck** [randombit/botan#4495]
Hello,
What are the steps to build the library for windows. 
Thank you..

**Comment by randombit** [comment]
https://github.com/randombit/botan/blob/master/doc/building.rst#on-windows

**Comment by naushadck** [comment]
Thanks...  Can i know, if there is a build for VC++. 
OR documentation exists for the usage of code in our library.

**Comment by reneme** [comment]
Extensive documentation can be found here: https://botan.randombit.net/handbook/api_ref/contents.html

Are you using some dependency manager in your project? vcpkg, or conan? There are packages of Botan for both of them.

Otherwise, the link posted above should get you started. Or did you have some concrete obstacle?

**Comment by naushadck** [comment]
Hello Sir,

Thank you for your support with links and details. 
No dependency in my project. I am trying to build the botan(static/dynamics library) for C++ in windows using cmake. 
I could not find any option to build using cmake.  
Can i know, if there is a facility to build using cmake ?.
