### ISSUE TITLE
Undefined behavior in curve_gfp

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#453]
Tried already 2 hours to find the issue without success.

```
build/include/botan/curve_gfp.h:91:44: runtime error: member call on address 0x611000009640 which does not point to an object of type 'Botan::CurveGFp_Repr'
0x611000009640: note: object is of type 'Botan::(anonymous namespace)::CurveGFp_Montgomery'
 06 00 80 4b  90 88 9f d7 23 7f 00 00  40 e4 f5 d8 23 7f 00 00  80 e4 f5 d8 23 7f 00 00  80 e4 f5 d8
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'Botan::(anonymous namespace)::CurveGFp_Montgomery'
    #0 0xbe740f in Botan::CurveGFp::get_p() const /home/neusdan/botan/build/include/botan/curve_gfp.h:91:44
    #1 0x7f23d5d47eed in Botan::PointGFp::PointGFp(Botan::CurveGFp const&, Botan::BigInt const&, Botan::BigInt const&) /home/neusdan/botan/src/lib/math/ec_gfp/point_gfp.cpp:35:22
    #2 0x7f23d5d7639f in Botan::OS2ECP(unsigned char const*, unsigned long, Botan::CurveGFp const&) /home/neusdan/botan/src/lib/math/ec_gfp/point_gfp.cpp:632:13
    #3 0x7f23d63b7806 in Botan::PointGFp Botan::OS2ECP<std::allocator<unsigned char> >(std::vector<unsigned char, std::allocator<unsigned char> > const&, Botan::CurveGFp const&) /home/neusdan/botan/build/include/botan/point_gfp.h:284:13
    #4 0x7f23d63adcc3 in Botan::EC_Group::EC_Group(std::vector<unsigned char, std::allocator<unsigned char> > const&) /home/neusdan/botan/src/lib/pubkey/ec_group/ec_group.cpp:84:22
    #5 0x7f23d63a6732 in Botan::EC_Group::EC_Group(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/neusdan/botan/src/lib/pubkey/ec_group/ec_group.cpp:39:15
    #6 0x7f23d63a46e6 in Botan::EC_Group::EC_Group(Botan::OID const&) /home/neusdan/botan/src/lib/pubkey/ec_group/ec_group.cpp:25:12
    #7 0x7f23d63a7356 in Botan::EC_Group::EC_Group(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/neusdan/botan/src/lib/pubkey/ec_group/ec_group.cpp:43:15
    #8 0xb40687 in Botan_Tests::(anonymous namespace)::ECC_Randomized_Tests::run() /home/neusdan/botan/src/tests/unit_ecc.cpp:137:23
    #9 0xa7a8ba in Botan_Tests::Test::run_test(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/neusdan/botan/src/tests/tests.cpp:395:51
    #10 0x70a499 in (anonymous namespace)::Test_Runner::run_tests(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::ostream&, unsigned long) /home/neusdan/botan/src/tests/main.cpp:192:37
    #11 0x708714 in (anonymous namespace)::Test_Runner::go() /home/neusdan/botan/src/tests/main.cpp:142:32
    #12 0x74ec35 in Botan_CLI::Command::run(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /home/neusdan/botan/src/tests/../cli/cli.h:226:13
    #13 0x6f8e0d in main /home/neusdan/botan/src/tests/main.cpp:271:11
    #14 0x7f23d204e70f in __libc_start_main (/usr/lib/libc.so.6+0x2070f)
    #15 0x4e6bb8 in _start (/home/neusdan/botan/botan-test+0x4e6bb8)

SUMMARY: AddressSanitizer: undefined-behavior build/include/botan/curve_gfp.h:91:44 in 
```

**Comment by randombit** [comment]
WTF ASan? This makes no sense to me...

`class CurveGFp_Montgomery final : public CurveGFp_Repr`

But that said, I can replicate it with Clang.

Interesting that the CI ASan build (GCC 4.8) is not having any problems.

**Comment by neusdan** [comment]
yeah, big WTF. 

I think this comes from UBsan and not Asan. The CI build is only using ASan right?

On my system both GCC and Clang emit this error.

**Comment by randombit** [comment]
Right, no UBSan in GCC 4.8

**Comment by randombit** [comment]
Just tried with GCC 5.3, see it there also.

I only even enabled ASan+UBSan for Clang quite recently in 20e7a430 and I'm pretty sure  it worked at that point. And since that time there have been very few changes to `ec_gfp`.

What I find especially odd - I have a ASan+UBSan Clang build set up for fuzzing and have run various ECC fuzzers against it with no problems. But if I take that same build and run the test suite against it, blam.

**Comment by randombit** [comment]
Looking at Clang's UBSan list the only check that seems to have anything to do with this failure is

-fsanitize=vptr: Use of an object whose vptr indicates that it is of the wrong dynamic type, or that its lifetime has not begun or has ended.

Perhaps this is actually a lifetime problem rather than the type error the ASan error is suggesting, say calling get_p on CurveGFp before the constructor completes. But I don't see any such issues along these lines either.

**Comment by neusdan** [comment]
I've found something out:

`configure.py --with-debug-info --no-optimizations --cc gcc --with-sanitizers`

==> error

`configure.py --with-debug-info --cc gcc --with-sanitizers``

==> no error

Whatever this means?!

**Comment by neusdan** [comment]
As far as I know UBSAN explicitly says that it's a lifetime issue if it is one.

**Comment by randombit** [comment]
Need to see if this still happens.

**Comment by noloader** [comment]
This issue is not present on Fedora 25, x86_64, GCC 6.3.1, Botan 2.0.1 (unreleased, revision git:e7e130c3d56eead0).

**Comment by randombit** [comment]
Checked again, was still seeing this with Clang 4.0.1. And again WTF.

Turned out, the problem is because `CurveGFp_Repr` is not exported by the DLL but was being invoked via an inline in `CurveGFp`. Exporting _Repr from the shared object, problem goes away. Hurah.

I realized the difference with the fuzzers is they are built against a static library so the symbol visibility stuff didn't come into play.
