### ISSUE TITLE
Issue when trying to cross-compile botan (yocto)

### ISSUE THREAD

**Issue by adegroote** [randombit/botan#455]
The generated Makefile by configure.py looks like:

```
AR               = ar crs

...

$(STATIC_LIB): $(LIBOBJS)
    $(RM) $(STATIC_LIB)
    $(AR) $(STATIC_LIB) $(LIBOBJS)
    $(RANLIB) $(STATIC_LIB)
```

But when using in a cross-compilation context (yocto here), passing an explicit AR variable to the Makefile, the compilation fails miserably (because it gets no flags). It would be better to generate something like

```
AR = ar

$(STATIC_LIB): $(LIBOBJS)
    $(RM) $(STATIC_LIB)
    $(AR) crs $(STATIC_LIB) $(LIBOBJS)
    $(RANLIB) $(STATIC_LIB)
```

I dig into the configure.py, but I don't really get where is generated the STATIC_LIB stuff. Thanks in advance for your help.

**Comment by randombit** [comment]
Yeah, makes sense.

Some of the reasoning behind this is historical - the `crs`  flags are not just embedded in the STATIC_LIB rule because old versions of Darwin did not have the `s` flag and required using ranlib instead. So the ar flags are taken from an OS specific build file, though OS X is the only exception. But it looks like from http://www.manpages.info/macosx/ar.1.html that modern OS X's ar supports the `s` flag now, so all of this could be removed and the makefile would end up looking more or less as you suggest.
