### ISSUE TITLE
Labels in KDF API 

### ISSUE THREAD

**Issue by flanfly** [randombit/botan#476]
Various KDFs allow/require the use of label and context values. For example NIST SP800-56c expects a label describing the purpose of the derived key and a context value that includes the scheme for which it is used. Some with the RFC 5869 HKDF that allows an optional string to be included into the expansion step.

Currently, the KDF API in Botan only accepts a single salt value. What's the best way to pass the label and context values to the implementation?

**Comment by randombit** [comment]
I think the appropriate course here is to add label parameters to `KDF::kdf`, and then add optional parameters to the various convenience functions defined on `KDF`.

I can't remember if IEEE 1363 says anything about labels for KDF1/KDF2; if it allows them then they can be extended to support it, or otherwise they can just reject a non-empty label. The TLS PRF does effectively support labels (the strings "master secret" and "extended master secret") but TLS key generation just appends the label and salt in the correct order and passes it as the salt param to the KDF, to work around the lack of explicit support for labels. So supporting this directly in the KDF API would be a bit cleaner.
