### ISSUE TITLE
Unable to build cli with tls support

### ISSUE THREAD

**Issue by kirillv** [randombit/botan#490]
Hi.
Im building botan on windows with VS. Configuration and building is ok (except a lot of warnings). 
But in cli i dont see tls_\* commands. As i can see there is no BOTAN_TARGET_OS_HAS_SOCKETS option in build.h, thats why code is not build and BOTAN_REGISTER_COMMAND not set. The question is - how to enable tls_\* commands with build system?
And people... your build system is crazy (maybe it is better to use Cmake and not to invent wheels in 2016?)... Dont want to hurt anybody).
Anyway - project is great! Thanks

**Comment by randombit** [comment]
The TLS client and server applications use BSD sockets to talk to the network and won't (IIRC) compile with Winsock, which is why they are gated by this macro check. They are not doing anything complicated so probably it wouldn't take much to port them to Winsock API. But I don't even have a Windows dev VM around anymore, so someone else would have to write this patch.

**Comment by kirillv** [comment]
Thanks for answer.
Where BOTAN_TARGET_OS_HAS_SOCKETS is set/detected in python script? I will try to add winsock.

**Comment by randombit** [comment]
These BOTAN_TARGET_HAS_OS_ macros are derived the <target_features> block in the OS info files (`src/build-data/os`). So add winsock to that block in src/build-data/os/windows.txt (and `mingw.txt' also?).

In an older branch there is code for handling WinSock which may be helpful 
https://github.com/randombit/botan/blob/release-1_10/doc/examples/socket.h

The TLS client and server CLIs were rewritten since then (due to a completely new TLS implementation in 1.11) and for whatever reason the support for WinSock was dropped along the way, perhaps just due to inability of testing it at the time.

**Comment by randombit** [comment]
Closing. The TLS command line utils should be available on Windows in recent releases.
