### ISSUE TITLE
Please avoid std::bind where performance may matter

### ISSUE THREAD

**Issue by DanielTBrown** [randombit/botan#493]
The run time overhead for a call through an `std::bind` function pointer involves many tens of machine instructions. A simple virtual function call, only a few machine instructions, is greatly to be preferred.

When `std::bind` generates a function pointer, it calls `new` to allocate a descriptor, so a line of code with `auto fx = std::bind ...` may generate a memory allocation exception. This can be a surprise.

The attached file is a simple example using `std::bind` to show how it operates. When the `std::bind` call itself is executed, the generated code calls `new` to allocate a descriptor. When a call is made through the `std::bind` function pointer, the generated code walks through the descriptor, building the parameter block for the called function. Use a debugger to step through the execution of one of the function calls, and you will see what is involved.

A virtual function call is much smaller and executes much faster. Writing `virtual f(...)` does not call `new` and cannot generate an exception. I find virtual function calls easier to read, and I find any associated C++ compiler error messages much easier to understand.

[BindTest.zip](https://github.com/randombit/botan/files/259859/BindTest.zip)

**Comment by DanielTBrown** [comment]
The overhead in practice is not as bad as I thought: in a program compiled for 'release', it appears that an std::bind call takes several times as long as a virtual function call (call takes two parameters, returns a value).

**Comment by randombit** [comment]
PR #576 (an update on #457) changes the TLS callbacks to use an interface class with vtables, instead of `std::function` based callbacks. It would be great to get your review there before the PR lands on master.

There are still a few uses of `std::bind` after this PR though, including one that invokes `std::bind` once per TLS record in tls_channel.cpp. Since one of my goals with the TLS stack is no memory allocations during normal application record processing [*], removing that one is probably worthwhile.

[*] This is a goal but there are no tests of this behavior and it may well have regressed in the last years.

**Comment by randombit** [comment]
At this point there are a few uses of `std::bind` and none in hot paths. Closing.
