### ISSUE TITLE
bigint_divop is slow

### ISSUE THREAD

**Issue by jamespic** [randombit/botan#494]
The algorithm used by `bigint_divop` is relatively slow, when compared to other BigInt libraries (notably OpenJDK). In profiling, I've found that `bigint_divop` is using the vast majority of the CPU time when running `fe1_encrypt` and `fe1_decrypt`. In my testing, I've found Botan's implementation of FE1 is an order of magnitude slower than its Java port, because of this.

**Comment by randombit** [comment]
Probably `bigint_divop` could be faster. I can't remember where the algorithm came from but I'm sure it's a very basic hardware approach for Patterson & Henessy or the like. I just tried replacing `bigint_divop` with a dword/word division operation. That will typically result in a call to the compilers runtime implementation (`udivdi3` and company). With GCC 6.1 on x86-64, using that instead of the current code slow down FE1 significantly.

It seems like this report is really about FE1 performance. When I profiled FE1 I see 70+% of the runtime is in `factor` which factors the modulus into two as close to equal as possible values `a` and `b`. These values could be cached for a particular modulus. A typical FPE application would only use a small number of different modulus sizes (different powers of 10).

**Comment by jamespic** [comment]
`dword/word` division sounds like a good option - it's the method OpenJDK's `BigInteger` class uses, and performs well.

Caching factorisations for FE1 would also be a good option.

**Comment by randombit** [comment]
So I retried and it seems I must have made some mistake originally when I stated that implementing `bigint_divop` as a dword/word division was slower - when I tried with now (with GCC 7.1) it resulted in fe1 being about 5x faster.

I'm sure we can do better here but I'm calling it good enough for now and closing this issue.
