### ISSUE TITLE
Mapping of botan signature/hash and other algorithm names to names used in OPC UA.

### ISSUE THREAD

**Issue by RavilN** [randombit/botan#519]
Hi, 
I have hard time trying to figure out what values to pass to botan PK_Signer, PK_Encryptor and other classes' emsa or padding arguments in order to have algorithms required by OPC UA standard. 
Example of such algorithm for OPC UA security policy Basic256  can be found here: http://opcfoundation-onlineapplications.org/ProfileReporting/ModifyProfile.aspx?ProfileID=57c0f86d-400a-4146-a919-cb65679aea97
Somehow encryption seems working if I use "EME1(SHA-1)" as a padding for PK_Encryptor. Although max_input_size is only 26 bytes, while key is 256 bytes, as a result message size is more than 5 times larger than non-encrypted. Given that asymmetric encryption happens only when connection is established, and I have message decrypted correctly on other end, this is not big problem, so  encryption feature is OK to use for OPC UA.

When it comes to signature, cannot make it working. Tried values for emsa argument in PK_Signer constructor as  "EMSA4(SHA-1)", "EMSA3(SHA-1)"; "EMSA2(SHA-1)" or "EMSA-PKCS1-v1_5(SHA-1)" - no luck, other side says that "signature could not be verified". 
The certificate and private keys were generated using botan, I tried to use them with other OPC UA client with the same security policy -  that application can establish secured connection using this certificate. So certificate and private key are fine.
I suspect something wrong in how signature is created. I tried to verify signature in my side using PK_Verifier, the result is true (verified).

Any idea what can be wrong?

**Comment by randombit** [comment]
Hi,
The only statement I can find on that site about the signature schemes was not too helpful, just

AsymmetricSignatureAlgorithm – RsaSha1 – (http://www.w3.org/2000/09/xmldsig#rsa-sha1).

The link points to the xmldsig's schema. I know absolutely nothing about xmldsig, but https://www.w3.org/TR/xmldsig-core/#sec-SignatureAlg seems to indicate it uses PKCS #1 padding for RSA signatures (that's the "EMSA-PKCS1-v1_5(SHA-1)" you already tried)

Having already tried  "EMSA4(SHA-1)", "EMSA3(SHA-1)"; "EMSA2(SHA-1)" and "EMSA-PKCS1-v1_5(SHA-1)"  you have almost exhausted your options but you may also want to try "EMSA1(SHA-1)" padding also, just in case. You might also try SHA-256 (with all schemes), just in case the receiver has SHA-1 turned off? From the Basic256 profile "Both Sha1 and Sha256 shall be supported. However, it is recommended to use Sha256 since Sha1 is considered not secure anymore."

Beyond trying these, one possibility that comes to mind is you are misinterpreting what is and is not signed in the message. Say, some header not being part of the signature, or whatever. You can correctly sign and verify, because your verification code has the same wrong assumption as your signature generation code. This would be easy to check for, if there are published samples of what these messages are supposed to look like. Then, you can be assured your verification routine works correctly. 

Re OAEP (EME1) plaintext size limits; for a 2048 bit RSA key, OAEP padding should take up 2*20+1 bytes, and so plaintexts up to 215 bytes should be allowed. But for a fresh 2048 bit RSA key I see the same result (26) as you; this is a bug. Thanks for mentioning this problem.

**Comment by RavilN** [comment]
Hi, 
Thank you for suggestion to check headers! I have found my mistake: total message size in header was being set after the message is signed and encrypted, so I was actually altering the signed message. Instead the final size should be calculated ahead and set before signing. 
Now I have both sign and encryption working, after completion it with different OPC UA security policies I will put here all the mappings.
So far using of botan is very convenient, much easier than openssl, I like it!

**Comment by randombit** [comment]
Bug in max_input_size fixed long ago. Don't think we need to do anything else - closing.
