### ISSUE TITLE
Undefined soname_patterns not handled properly by configure.py

### ISSUE THREAD

**Issue by lanurmi** [randombit/botan#521]
`src/build-data/os/*.txt` defines `soname_pattern`s for some platforms but not others (such as OpenBSD). When the three `soname_pattern`s are undefined, the generated Makefile contains

```
# Link Commands
SONAME_PATCH =
SONAME_ABI =
SONAME_BASE =
```

Empty values lead into unexpected commands being run, such as:
`ln -fs   ./`
`g++ ... -fPIC -Wl,-soname,  ... -o ./`
`rm -f`
`rm -f ./libbotan-1.11.a ./ ./botan ./botan-test`

I'm not quite sure what is supposed to happen when `soname_pattern`s are not defined, but I guess the current behavior is not intentional, even though it doesn't seem to cause harm. Also wondering whether `soname_pattern`s should actually be defined for all *nix, as I suspect they all support shared libraries.

**Comment by webmaster128** [comment]
When I added soname patterns in #260, I only added support for systems I know about and have access to a testing machine. Other systems are likely to fail until someone comes and fixes it. So feel free to add support for any system you use.

**Comment by randombit** [comment]
Thanks for raising this issue. I think this was fixed as part of 309f91538 (included in 2.0.0), for Unix systems we set a default soname unless there is a system specific override. Sorry forgot to reference the issue in the commit message.

I know 2.0.0 builds shared libs correctly on at least Linux, FreeBSD, and AIX

Closing this issue because I think the issue described is resolved. If you run into further problems with Botan on any BSD or other Unix please do open a new ticket, as we cannot fix bugs we do not know about ;)
