### ISSUE TITLE
Cannot get_cipher() for some DES modes

### ISSUE THREAD

**Issue by bellgrim** [randombit/botan#54]
Trying to use get_cipher() for ”DES/OFB/NoPadding” and ”DES/CFB/NoPadding” with Botan 1.11.14, but getting the following errors:
* Could not find any algorithm named "DES/OFB/NoPadding”
* Creating 'CFB_Encryption(DES,NoPadding)' failed: Could not read 'NoPadding' as decimal string

**Comment by randombit** [comment]
The final /NoPadding should not be used here (in any version). There is no padding option allowed in the SCAN convention for OFB or CFB modes, nor is any implemented in the library, nor does any pad ever make sense to specify for these modes. The bug was that it was allowed in the names in first place (and not explicitly, but simply due to lack of checking). You should update callers.

**Comment by bellgrim** [comment]
Thanks, working better now.
