### ISSUE TITLE
EMSA1 verification

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#550]
I'm trying to understand what's happening inside the `EMSA1::verify` function:
https://github.com/randombit/botan/blob/master/src/lib/pk_pad/emsa1/emsa1.cpp#L67-L96

``` c++
bool EMSA1::verify(const secure_vector<byte>& coded,
                   const secure_vector<byte>& raw, size_t key_bits)
   {
   try {
      if(raw.size() != m_hash->output_length())
         throw Encoding_Error("EMSA1::encoding_of: Invalid size for input");

      secure_vector<byte> our_coding = emsa1_encoding(raw, key_bits);

      if(our_coding == coded) return true;
      if(our_coding.empty() || our_coding[0] != 0) return false;
      if(our_coding.size() <= coded.size()) return false;

      size_t offset = 0;
      while(offset < our_coding.size() && our_coding[offset] == 0)
         ++offset;
      if(our_coding.size() - offset != coded.size())
         return false;

      for(size_t j = 0; j != coded.size(); ++j)
         if(coded[j] != our_coding[j+offset])
            return false;

      return true;
      }
   catch(Invalid_Argument)
      {
      return false;
      }
   }
```

In IEEE 1363-2000 the verification operation is described as:
1. Use the Encoding Operation of EMSA1 to compute a message representative g, a non-negative
   integer. If the encoding operation outputs “error,” output “invalid” and stop.
2. If f = g, output “valid”; otherwise, output “invalid.”

So in my understanding following code should be sufficient:

``` c++
bool EMSA1::verify(const secure_vector<byte>& coded,
                   const secure_vector<byte>& raw, size_t key_bits)
   {
   try
      {
      return coded == emsa1_encoding(raw, key_bits);
      }
   catch(Encoding_Error)
      {
      return false;
      }
   }
```

I could only find one test case that's not working with my changed code. It's the first testcase from Nyberg-Rueppel where the message is `FCABA2CF434AC8DCFCEC`.

The SHA-1 hash of this message is `0000000069113490a6b0793f802c7810bb16e943`. These leading zeros are not returned from NR_Verification_Operation::verify_mr() and i think that's the bug here.

**Comment by randombit** [comment]
I was initially surprised by this because if you had asked me I would have guessed EMSA1::verify would look exactly as you propose (and the PKCS v1.5 verify does exactly this recompute-and-compare logic), but checking source history, the current logic in EMSA1 has been there since at least 2006. It is definitely to handle missing leading zeros in the message representatives coming from the low level PK operations.

RSA and ElGamal also used to have this problem of leading zeros being stripped, which was fixed in b8966d0f8

Re the NR failure - it's possible DSA and/or ECDSA have a similar issue also, but are simply missing a test which produces a hash with leading zero bytes.

I agree the current logic is bogus and leading zeros should be returned to the caller from the pk ops.

**Comment by randombit** [comment]
With #591 merged can we change this logic in EMSA1?

**Comment by neusdan** [comment]
Unfortunately not: #607

**Comment by randombit** [comment]
Is there anything left to be done here?

**Comment by neusdan** [comment]
I try to look at it again in the next few days.

**Comment by neusdan** [comment]
Should be fine now.
