### ISSUE TITLE
TLS server certificate verification broken

### ISSUE THREAD

**Issue by cordney** [randombit/botan#611]
Playing around a bit with `TLS_Client` and the matching cli tool, I recognized that the current master does not verify against public WWW servers such as google.com, apple.com, ... anymore, while 1.11.30 works just fine. I assume we broke this with #591.

Looking at `X509_Certificate::allowed_usage(Usage_Type = TLS_SERVER_AUTH)` matching the key usage with the extended key usage bits seems to be the problem.

```
case Usage_Type::TLS_SERVER_AUTH:
    return allowed_usage(Key_Constraints(DATA_ENCIPHERMENT | KEY_ENCIPHERMENT | DIGITAL_SIGNATURE)) 
           && allowed_extended_usage("PKIX.ServerAuth");
```

 While for TLS server RFC 5280 says:

```
id-kp-serverAuth             OBJECT IDENTIFIER ::= { id-kp 1 }
   -- TLS WWW server authentication
   -- Key usage bits that may be consistent: digitalSignature,
   -- keyEncipherment or keyAgreement
```

So having data encipherment here seems wrong and indeed, if I remove this bit then apple.com, paypal.com and the like verify fine again. While google.de also works fine, google.com still is broken. Printing the two certs gives:

**google.com (broken)**:
```
Constraints:
   Digital Signature
Extended Constraints:
   PKIX.ServerAuth
   PKIX.ClientAuth
```

**google.de (ok)**:
```
Constraints:
 None
Extended Constraints:
   PKIX.ServerAuth
   PKIX.ClientAuth
```

We changed the logic implicitly in #591's `allowed_usage(Key_Constraints)`, so shouldn't the line above now instead be like:

```
case Usage_Type::TLS_SERVER_AUTH:
    return (allowed_usage(KEY_ENCIPHERMENT)
           || allowed_usage(DIGITAL_SIGNATURE) || allowed_usage(KEY_AGREEMENT)) 
           && allowed_extended_usage("PKIX.ServerAuth");
```

**Comment by cordney** [comment]
OpenSSL implements a similar logic, see https://github.com/openssl/openssl/blob/master/crypto/x509v3/v3_purp.c#L590.

IMHO it's a blocker for the 1.11.30 release (#604).

**Comment by randombit** [comment]
Blocker for sure. I may have time to look at this tonight.

**Comment by randombit** [comment]
There should be tests using a corpus of real-world certificate chains from the net, to catch problems like this.

Many end certs are short lived these days and the chains would have to be replaced regularly. It would be better to be able to specify when performing a cert validation the time validation should be performed against, instead of assuming the current local time. I think this could be done just by changing the API `x509_path_validate` to take the time and letting it default to the system clock, instead of calling the system clock directly.

Then the tests can just perform the validation in comparison to the specified reference time (when the chain was collected), and we never have to replace values in the corpus.

Being able to insert OCSP responses in the appropriate place as part of the validation would be a nice bonus goal. But currently OCSP is hardcoded to spawn a thread and connect to the network...

**Comment by randombit** [comment]
This validation code was assuming the previous `allowed_usage` semantics of `allowed(A | B)` meaning A or B, instead of A and B. Reading at the call site really is not obvious which is the intent, so it would be better in all cases to call it with only a single value in the way you suggest. I think the other callers of `allowed_usage` (within the library) that are passing multiple values to `allowed_usage` should be changed to multiple calls in the same way.

**Comment by mouse07410** [comment]
Another possibility is to set the current date for those certificates validation back to their period of validity.

**Comment by randombit** [comment]
Fixed for me in a09d2df (tested google.com, google.de, twitter.com)

One problem I noticed while testing the fix - cert chain for baidu.cn fails to verify (Signature Error). OpenSSL seems to accept it. This is unlikely to be related to this issue or #591

**Comment by cordney** [comment]
Works for me, too. I would change `allowed_usage(DATA_ENCIPHERMENT)` to `allowed_usage(DATA_ENCIPHERMENT)` for `TLS_SERVER_AUTH` and `allowed_usage(NON_REPUDIATION)` to `allowed_usage(KEY_AGREEMENT)` for `TLS_CLIENT_AUTH`, as RFC 5280 demands it. OpenSSL also implements it that way.

**Comment by randombit** [comment]
Thanks for following up on that, taking expected usage bits from RFC 5280 seems right. Fixed in master.

**Comment by cordney** [comment]
Looks good, thx.

> There should be tests using a corpus of real-world certificate chains from the net, to catch problems like this.

Can we add this to TODO?

**Comment by randombit** [comment]
For the record this was eventually added, via the Limbo test suite which includes among other things the live cert chains for various major services.
