### ISSUE TITLE
auto_rng.h in pubkey\blinding.cpp

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#615]
With Botan 1.11.31 and

> configure.py --no-autoload --enable-modules=tls

on Windows, I get the error:

> src\lib\pubkey\blinding.cpp(14): fatal error C1083: Cannot open include file: 'botan/auto_rng.h': No such file or directory

Full log: https://gist.github.com/webmaster128/63c9691ce9b1cbc3ca4d85965bebddea

**Comment by randombit** [comment]
auto_rng is now a separate module, so it is possible to configure a build for example that can only access the system RNG and never a userspace PRNG. Here both system_rng and auto_rng are not enabled (since minimal), and Blinder currently requires one or the other. 

It is an unfortunate diagnositc message for sure (an `#error` explaining the problem would be better, in the case neither RNG was available). In any case for 1.11.31 you will have to explicitly enable _either_ auto_rng or system_rng modules in order to build. Looking forward I expect Blinder will change to take a RNG& that was provided by the application and this issue will be avoided entirely.

**Comment by webmaster128** [comment]
Okay, thanks

Could this be handled by the or-syntax for requirements in the info.txt (similar to `sha1_sse2|sha1`)?

**Comment by webmaster128** [comment]
If this statement should remain true, shoudn't the module "base" depend on "auto_rng"?

> AutoSeeded_RNG is part of the base library now and cannot be compiled out.

(from #520)

**Comment by cordney** [comment]
This should be fixed with #625, as a `RandomNumberGenerator&` is now passed to `Blinder`. @webmaster128 can you confirm this is fixed for you?

**Comment by webmaster128** [comment]
I can reproduce the issue with 1.11.31 and 1.11.32. Fixed on current master. Thanks all :heart:
