### ISSUE TITLE
system_rng on iOS

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#620]
Currently there is no separate "ios" os in the botan build system and "darwin" is used for iOS builds. Thus for iOS configurations, there system_rng is marked as available, because darwin is

> Any system with /dev/random or CryptGenRandom

But there is no access to /dev/random or /dev/urandom on iOS, forcing us to use SecRandomCopyBytes.

Now the question is, how to get this into the build system? Create a separate "ios" os with no system_rng or add a 3rd system_rng implementation (duplicating the darwin_secrandom code)?

**Comment by randombit** [comment]
iOS really is a completely different OS/platform from OS X/Darwin, it should be treated as such in the build.

**Comment by webmaster128** [comment]
Thanks for the feedback. I'll prepare a PR accordingly.

With ios being a separate os: do you think it's worth adding a third system_rng implementation using SecRandomCopyBytes? Or do we just use AutoSeeded_RNG with the default enropy sources (including SecRandomCopyBytes)?

**Comment by randombit** [comment]
I think either approach is fine. I think in practice for iOS, the only active entropy source is `SecureRandomCopyBytes` anyway.

If you want to add `SecRandomCopyBytes` for `System_RNG`, that would allow direct use of the type by apps on iOS. Since `SRCB` has no state it should be an easy to do. Just change all the `#else`s to `#elif defined(BOTAN_TARGET_OS_TYPE_IS_UNIX)` and add the call to SRCB in `System_RNG_Impl::randomize` in new iOS specific block.

I can't remember if SRCB can return short reads or is guaranteed to return the requested amount. The logic may have to be adjusted slightly, compared to the entropy source.
