### ISSUE TITLE
Negotiating custom EC curves in TLS

### ISSUE THREAD

**Issue by cordney** [randombit/botan#636]
We must be able to use custom (prime) curves in the ECDHE key exchange in TLS. Additionally, the points must be transferred in compressed format.

From looking into [RFC 4492](https://tools.ietf.org/html/rfc4492), it seems we must implement two things:

1) `arbitrary_explicit_prime_curves` in the [Supported Elliptic Curves Extension](https://tools.ietf.org/html/rfc4492#page-12)
2) [Supported Point Formats Extension](https://tools.ietf.org/html/rfc4492#page-13)

After looking into the code, I would propose the following changes:

On (1), I would change `TLS_Policy::allowed_ecc_curves()` to return a `std::vector<EC_Group>` instead of a `std::vector<std::string>`. `EC_Group` has a `std::string` constructor, so it would have the same semantics as before. `TLS::Supported_Elliptic_Curves` class would then match `EC_Group` to the named curve id if the OID is known, otherwise it would send the `arbitrary_explicit_prime_curves` id. On the server side, in `Server_Key_Exchange::Server_Key_Exchange()`, `TLS_Policy::choose_curve()` would also return an `EC_Group` instead of an `std::string`. If the `EC_Group` can not be looked up using the OID, additional code would encode an `ECParameters` struct for `case explicit_prime:`.

On (2), the Supported Point Formats Extension must be implemented. `PointGFp` already supports compressed and uncompressed points. `EC_Group` by default always encodes points uncompressed, so maybe there should be an overload specifying the point compression type. I am not sure how to get the uncompressed/compressed decision to the user. Maybe `TLS_Policy::allowed_ecc_curves()` should return an `std::vector<std::pair<PointGFp::Compression_Type, EC_Group>>`?

**Comment by randombit** [comment]
> We must be able to use custom (prime) curves in the ECDHE key exchange in TLS.

I'll admit I can see a certain logic, for some very specialized applications, in using a randomly generated 'in-house' curve. But:

> 1) arbitrary_explicit_prime_curves in the Supported Elliptic Curves Extension

Strong NAK on this. Arbitrary curves are not supported by any other implementation that I know of, and there is a reason for that. Smart protocol stacks don't accept arbitrary ECC curves from strangers. The situation with TLS 1.2 DH in that regard is bad enough.

One solution I might accept would be adding a way for someone building Botan to add their (singlar!) 'house' curve (via PEM file input), which would include a name, OID, and optionally a value in the private use range (0xFE00-FEFF) of `NamedCurve`. Then your in-house curve could be negotiated in TLS via the normal mechanism simply by setting `ecc_curves` policy to include that curve name. Roughly:

```
./configure.py --funky-house-curve=curve.pem,funky311,1.2.3.4.5,FEE7

which adds to build.h

#define BOTAN_HOUSE_ECC_CURVE_NAME "funky311"
#define BOTAN_HOUSE_ECC_CURVE_OID ...
#define BOTAN_HOUSE_ECC_CURVE_PEM ...
#define BOTAN_HOUSE_ECC_CURVE_TLS_ID ...
```

Plus a few checks for these values being defined in the relevant ECC group lookup + TLS code to make them available. Feel free to use a different name if you can think of it,  'house'/'in house' idiom  seems potentially  confusing for a non-native speaker.

This same mechanism would provide an escape hatch for some application out there using P-192 or the like,  after these weaker curves are removed from the library itself, by allowing it to be effectively added back after the fact.

> 2) Supported Point Formats Extension

No problem with this. IMO controlling compression on a per-curve level is over the top though. A simple all or nothing toggle `bool TLS_Policy::use_ecc_point_compression()` seems sufficient. It's likely we're already accepting compressed points, since OS2ECP accepts either form. TLS needs to explicitly check the first byte to see if the point was compressed in order to enforce this policy.

**Comment by cordney** [comment]
> I'll admit I can see a certain logic, for some very specialized applications, in using a randomly generated 'in-house' curve.

Yes, I should have mentioned that. It's nothing we will make use of regularly, but only in very specialized applications.

> Strong NAK on this. Arbitrary curves are not supported by any other implementation that I know of, and there is a reason for that. Smart protocol stacks don't accept arbitrary ECC curves from strangers. The situation with TLS 1.2 DH in that regard is bad enough.

You're right and I had doubts already on using `arbitrary_explicit_prime_curves`, which I should have expressed in the description. The approach you outlined seems sufficient to me.

> No problem with this. IMO controlling compression on a per-curve level is over the top though. A simple all or nothing toggle bool TLS_Policy::use_ecc_point_compression() seems sufficient. It's likely we're already accepting compressed points, since OS2ECP accepts either form. TLS needs to explicitly check the first byte to see if the point was compressed in order to enforce this policy.

Thanks for the feedback, I'll give it a try.

**Comment by cordney** [comment]
I am half-way through implementing the Supported Point Formats Extension and for both the client hello and server hello extensions the following holds:

> If the Supported Point Formats Extension is indeed sent, it MUST contain the value 0 (uncompressed) as one of the items in the list of point formats.

(I am intentionally omitting compressed binary curves, as we don't support them anyway.)
So the client can send [compressed, uncompressed] or [uncompressed, compressed] or [uncompressed], but not [compressed].

The server enumerates the point formats that it can parse, so it would either send [compressed, uncompressed] or [uncompressed, compressed].

Both sides have to respect the preference of the other side when sending their points to the other side. To sum it up, we can't really force the server using compressed points. He can still send uncompressed points if he doesn't support compressed points. In the light of this, should we rename `TLS_Policy::use_ecc_point_compression()` to `TLS_Policy::prefer_ecc_point_compression()` and send the following:

| Party/prefer_ecc_point_compression() | true | false |
| --- | --- | --- |
| Client | [compressed, uncompressed(+)] | [uncompressed, compressed(?)] |
| Server | [compressed, uncompressed(+)] | [uncompressed, compressed] |

(+) mandated
(?) shall we send compressed here, too?

**Comment by randombit** [comment]
Some users may have IP concerns about point compression being enabled. Likely any patent that would actually apply to prime curve point compression has long expired, but certain companies have gone to a lot of trouble to raise ECC patent fears and some other companies have paranoid lawyers.

I think if the policy toggle is false, both sides should send only `[uncompressed]` (or just omit the extension entirely, which is saying the same thing but with fewer bytes... [x]), and point compression is only used if 1) the peer supports it and 2) compression is enabled in the local policy.

[x] Actually not quite identical at the protocol level, since if we send an uncompressed only extension, the server can still reply with compressed,uncompressed - but with the restriction given on also only sending compressed points if the local policy OKs it, they are identical.

If so that would simplify extension encoding, since the extension would be either not sent at all, or sent as exactly `[compressed,uncompressed]`.

TLS really should be checking the OS2ECP inputs, also - in fact enforcing uncompressed points (which is implicitly being negotiated currently due to lack of the extension) would have shielded TLS from the ressol infinite loop (CVE-2016-2194) which was reachable from OS2ECP (and thus the TLS key exchange), but only when parsing compressed points.

**Comment by cordney** [comment]
So when a client or server has `TLS_Policy::use_ecc_point_compression()` set to `true` and the other party sends an uncompressed point, will we hang up?

**Comment by randombit** [comment]
No, that doesn't seem like a good idea since not all implementations support compressed points. I hope nothing I wrote previously seemed to imply doing so, if so perhaps I was insufficiently precise.

**Comment by cordney** [comment]
No, i was just thinking out loud. :)

**Comment by randombit** [comment]
Has this been completed with #645 and #710 merged?

**Comment by cordney** [comment]
Ah yes, forgot to close that one.
