### ISSUE TITLE
Is entropy source selection for win32 correct?

### ISSUE THREAD

**Issue by phraemer** [randombit/botan#644]
https://github.com/randombit/botan/blob/c64d66d355c4e3daf04a79697b7f9271d087e495/src/lib/entropy/entropy_srcs.cpp#L102

```cpp
   if(name == "dev_random")
      {
#if defined(BOTAN_HAS_ENTROPY_SRC_DEV_RANDOM)
      return std::unique_ptr<Entropy_Source>(new Device_EntropySource(BOTAN_SYSTEM_RNG_POLL_DEVICES));
      }

   if(name == "win32_cryptoapi")
      {
#elif defined(BOTAN_HAS_ENTROPY_SRC_CAPI)
      return std::unique_ptr<Entropy_Source>(new Win32_CAPI_EntropySource);
#endif
      }
```

Here you can see that it won't test for `win32_cryptoapi` if `BOTAN_HAS_ENTROPY_SRC_DEV_RANDOM` is not defined. So `win32_cryptoapi` requires that both  `BOTAN_HAS_ENTROPY_SRC_DEV_RANDOM` and `BOTAN_HAS_ENTROPY_SRC_CAPI` must be defined.

Is that correct?

Follow up question: Shouldn't `win32_cryptoapi` be available if configured with `--os=windows` ?

**Comment by randombit** [comment]
Definitely a bug but not quite with the effects you mention. Instead, on Windows what happens is "dev_random" returns a CryptoAPI RNG and "win32_cryptoapi" returns nothing. Since `BOTAN_ENTROPY_DEFAULT_SOURCES` includes "dev_random" on all platforms everything happens to more or less work out (though of course entirely by luck).

Would be great if we had a test that could have caught this, not even sure what that would look like unfortunately.

**Comment by randombit** [comment]
Fixed now in master, thank you for the report.
