### ISSUE TITLE
ECKCDSA verification problem

### ISSUE THREAD

**Issue by randombit** [randombit/botan#701]
With #700 merged, a corrupted signature is accepted once in a while. This can be replicated with `./botan-test eckcdsa_sign --drbg-seed=1482C97A196A6281`

Originally noticed in CI https://circleci.com/gh/randombit/botan/1315 and easy to replicate more instances with

`for i in $(seq 1 100); do ./botan-test eckcdsa_sign ; done`

@neverhub any idea what's happening with this?

**Comment by neverhub** [comment]
Huh. Well that was unintentional. But good that the CI noticed the problem. Compute a valid signature (r,s) and append garbage to s. In this case, the garbage is cut during the construction of the BigInt s and the signature is falsely accepted.

The length check should be
```
if(sig_len != size_r+m_order.bytes())
      {
      return false;
      }
```
instead of
```
if(sig_len < size_r+m_order.bytes())
      {
      return false;
      }
```
Sorry for the trouble. Everything should be fine now.
