### ISSUE TITLE
Timeline for dropping MSVC 2013 support

### ISSUE THREAD

**Issue by randombit** [randombit/botan#703]
I've recently come into two reasons to want to use `constexpr`, which MSVC 2013
does not support at all, though AIUI a 2013 CTP adds it. With 2015 already out
and "15" (which even has full C++14 constexpr) in preview I wanted to poll on
dropping support for 2013 or at least 2013 RTM. I see basically three options:

- Drop 2013 RTM, continue to support/test with 2013 CTP with constexpr. It seems
  like AppVeyor supports installing the CTP on their test images
  (https://github.com/appveyor/ci/issues/807)

- Drop support for 2013 entirely. This allows focusing testing/CI on 2015 (and
  later also "15"). We have a number of hacks in place specifically to work
  around bugs in 2013 which can go away.

- Continue to support 2013 RTM for some further amount of time (but how long?)
  Obviously 2013 cannot be supported idefinitely, it is just a question of
  dropping support now (allowing use of more or less all of C++11) or in a year
  or two during a transition to C++14 or C++17.

I'm personally in favor of dropping 2013 support entirely in relatively short
order (say next release, or the one after), because at this point it is the
least featured compiler we support. In addition to constexpr, MSVC 2015 catches
up with our minimum versions of GCC and Clang in adding alignment support,
inheriting constructors, user defined literals, and noexcept all of which are or
would be used.

But I am not a Windows developer, so I inquire what the situation is with
users. Are people building with 2013? Is 2013 CTP support worth the bother?  If
2013 support needs to stay for longer, what kind of timeline is required to
remove support without causing problems?

As to the reasons for `constexpr`:

Someone recently reported an integer overflow bug (details forthcoming), and
suggested adding a guarded integer type to help protect against other such bugs
in the future. Some examples of such code are SafeInt
(https://safeint.codeplex.com/releases/view/125522) and in CapnProto
(https://capnproto.org/news/2015-03-02-security-advisory-and-integer-overflow-protection.html)
Such a type would be especially useful in the BER decoder and the TLS stack.
Being able to use `constexpr` is not completely essential but ensures there is
no excess runtime overhead. That fact (that it is guaranteed by the compiler to
be 'free' at runtime) would also make it more likely to be used liberally within
the source.

Secondly, I'm midway on a project to remove the OID global lock by making the
OID table read-only at runtime. However initializing a giant constant
`std::{unordered_}map` results in large object sizes, in one case I tried it was
the single largest object in the entire library (by a factor of 2!). What I want
to do instead is a compile time string switch like this:
https://gist.github.com/randombit/1a85dcb32ab4b3f369d2848c784bc759

That results in very compact and fast lookups, and since the input set is a
compile time constant any possible collisions are detected at compile time (by
duplicate case statement). This requires at least C++11 constexpr. Actually this
is not strictly true; the script that generates the switch can also just
precompute the hash values, instead of having the compiler do it. But this is
kind of ugly, and requires two versions of the hash function, one in Python and the other
in C++.

**Comment by neusdan** [comment]
I can totally understand that you want to drop MSVC 2013 support. But at least we are compiling our code  still with VS 2013 and i think we are not the only ones. We'll probably upgrade to 2015 in the first half of 2017.

VS 2015 was released in July 2015. That's not that long ago. Especially for companies that have many products and libraries it's a lot of work to upgrade the toolchain. They have to test everything thoroughly, adjust the code eventually and they also need the money to buy new licences. I can image that many of them will even wait for the first 2 or 3 updates before they even think about upgrading to a new version. Yeah, these updates are released in the meantime.

Regarding the CTP: We definitely don't want to install a technology preview and compile our code with it.

So i hope that you consider supporting VS 2013 for some more time. 

That doesn't mean that you can't use the new C++ features. Yeah, you will need some #ifdefs and workarounds and it's ugly, but it's the best suggestion i can give at this time.

**Comment by randombit** [comment]
Well boo for you making a reasonable argument why I shouldn't do the thing I'd like to do. :) It is true that MSVC 2013 has been supported ok for a while now. And I have worked at a few places where toolchains lagged latest releases by many years even.

OK what I will do instead is define `BOTAN_CONSTEXPR` keyword standin as was already done with `BOTAN_NOEXCEPT`. Then MSVC 2013 can go do whatever it's going to do, and conforming compilers will check that the functions are actually constexpr.

I'm still out of luck on the switch case since those function evaluations actually must be at compile time. But I realized my approach didn't work anyway, because even though there are no collisions in our defined OID set, there would be collisions with arbitrary OIDs/strings, with unfortunate results. So must-be-at-compile-time evaluation is not required by any use case I see at hand and `BOTAN_CONSTEXPR` could be treated as an optimizer hint for now.

**Comment by skaller** [comment]
Using macros to control use of language feature is a completely stupid idea! If you need the feature use it, if the feature helps but isn't essential, you have two sane choices: tell those that can't have the feature to nick off, or accept that those that do have the feature can't have the benefit of it.

Using macros to REPRESENT the feature is saner but should be reserved for absolutely essential cases such as significant optimisations. Do not go down the track followed by Boost. Boost had no choice since it wanted to experiment with upgrades to C++ language, and at the same type make its libraries available to those that didn't even have C++98 support. But if you're doing Boost, you're NOT writing C++.

Its OK to use macros INSIDE your library. But its extremely evil for them to be needed by the user USING your library. This doesn't mean the macros aren't in the interface, it means that the user can call the library without knowing about them.

This is an ideal. In practice you might have SOME macros the user has to use but they should be kept to a minimum. See also my next comment.

**Comment by skaller** [comment]
OK, so the real choice is: C++11 or not, perhaps with only selected features to enable some "almost C++11" compilers to work. Such as some g++ -std=gnu11 compilers which are almost C++11 compliant but not quite.

Be aware a SERIOUS problem exists in C++11 support with gcc. Because of changes to the requirements for C++ string type, object code built by older compilers is completely incompatible with code for newer compilers. This change occurred with g++ version 5.1 I think. Note some people still using gcc 4.7. Some people using later g++ but older third party libraries.

What GCC did to fix this was support BOTH the old and new string types. So the gcc standard C++ library "std::string" is the C++98 string, and "std::__11::string" or something similar is the new C++11 compliant string type. The two types are incompatible, but you can have object code using one and also object code using another and link them against the gnu library and it will link. There is a switch to change the default for g++5.2 or above from the new string type to the old string type.

Clang appears to use a similar scheme.

However it is WORSE. Some Linux OS have misconfigured gcc packages. For example ALL the backports for Ubuntu 12.14 are wrong. This means, in particular, that even gcc 6.x on Travis continuous integration server generates WRONG BINARY CODE and I have given up trying to figure out how to fix it.

So the problem isn't just C++ standards version of the compiler, it depends on the OS as well. Roughly the backports of the new compilers on at least Ubuntu are all broken: you cannot actually generate code that links to the new C++11 library. 

So at least in the gcc and Ubuntu world C++11 support is a complete mess. Its bad enough that using two compilers like Clang and gcc doesn't work for C++ even though it does for C, because although the C ABI is the same for both, the C++ libraries depend on the types of data structures and Clang and gcc use different libraries.

Whilst this doesn't directly impact Botan, it makes distributing pre-built binary tarballs virtually impossible, because of the combinatorial explosion of binaries required.

For my system I say "C++11 with the new string type" and bugger any old code, but then I find I can no longer make a binary on Travis to distribute. I have to mandate C++11 because my systems uses some of the new thread stuff (atomics, etc) which allowed throwing out the hand made versions of the same thing for each OS.

So roughly: people which are using C++ for commercial reasons with large code bases and possibly third party binary libraries are going to take a LONG time to migrate, in fact some of them will NEVER migrate. Its like USA still using feet an inches. Large financial institutions still have COBOL programs running. And its possible they will never migrate because .. well what would you migrate TO?

**Comment by randombit** [comment]
> tell those that can't have the feature to nick off, or accept that those that do have the feature can't have the benefit of it.

I'm pretty sure we're taking the nick off option here - MSVC 2013 won't know about constexpr, cannot optimize on it, and of course applications can't expect to evaluate such functions at compile time. But outside of this, and any missed optimizations as a result it will still see/compile the rest of the library.

> But its extremely evil for them to be needed by the user USING your library. This doesn't mean the macros aren't in the interface, it means that the user can call the library without knowing about them.

If constexpr changed the semantics of the function in some way, I would agree. But it does not (AFAIK). It only restricts the language we may use in the function, and informs the compiler that it can/should perform the computation at compile time if possible. Then we just have to avoid actually (within the library) *requiring* compile time evaluation of any `constexpr` expression since in MSVC 2013 it is not `constexpr` because VC.

As to the C++11 ABI issues of GCC or any other vendor, that is completely out of our control and the choice of C++98 vs C++11 in the library was made a long time ago. From prior experience I have found when distributing C++ binaries for Unix systems it is best to just statically link libstdc++  which avoids many problems.

**Comment by Steppenwolfe65** [comment]
My 2 cents..
 2 years after a release of VS is fine, particularly given that the IDE is free. 
Using newer C++ features, (so long as they add significant value), is also the right track; code becomes obsolescent quickly, better to keep up with the standards, rather than be constantly constrained by late adopters. Trying to be everything to everyone creates clutter, introduces unnecessary complexity, and is enabling use of older, often less flexible/featured compilation software.

Speaking of MSVC support.. is there a visual studio solution I can get a hold of? It would be very useful to debug some of these codes (without having to go through the agony of creating my own solution for the project).

**Comment by randombit** [comment]
It is not so easy to time these moves with VC, whereas with GCC/Clang it seems pretty straightforward - when the stable distros like Ubuntu LTS and RHEL move past GCC 4.8 we can consider moving accordingly.

Cruft avoidance is definitely the big motivator here. Moving to C++11 allowed dropping support for many old buggy compilers (being able to forever stop worrying about what Visual C++ 6 would do was so nice), and portability cruft in fact has the potential to damage or kill a project (witness OpenSSL). That is one reason I also only have interest in supporting OSes which are supported by their vendors, to minimize the number of weird corner cases and `#ifdef` mazes.

@Steppenwolfe65 There is recently integrated support for bakefiles (http://bakefile.org/) which can generate Visual Studio 2013 projects. I do not do any Botan development on Windows or using Visual Studio (these are the kinds of obnoxious things I only do when someone is paying me to do them), so I don't have much else to offer in this regard.

**Comment by neusdan** [comment]
@steppenwolfe65 you have to execute configure.py with --with-bakefile to generate the Bakefile

**Comment by webmaster128** [comment]
Just FYI: We successfully migrated to MSVS 2015, which came with the nice effect that RSA key generation is now ~ 33% faster for 32 bit software due to a better optimizer.

**Comment by Bulat-Ziganshin** [comment]
>2 years after a release of VS is fine, particularly given that the IDE is free.

Let's imagine a project started a year ago, with CUDA and botan. It was using msvc2013 since CUDA suport for MSVC2015 was added only in Sep 2016, with release of CUDA8. If Botan will drop MSVC2013 support now, this project will lose support of botan upgrades, including security fixes.

Overall, i feel that list of supported compilers should be stabilized more or less when a new major botan version is started, exactly to deal with situations like one i described. Otherwise, it seems that noone can start a project using current botan version since he may lose even security updates at any moment, and instead should select a stable botan version line.

I understand that MSVC2013 support require additional efforts, so the price will be less amount of features implemented. Taking into account that botan now became one of major cryptolibs, and probably used by a large number of projects, i think that it will be preferable to have it more "solid" rather than "feature-full".

And btw, what about using [Semantic Versioning](http://semver.org/) for tagging botan versions?

**Comment by randombit** [comment]
I think for 2.0 we are sticking with 2013 support, changing up things now just before the stable release would be unfortunate for everyone who has been developing so far for 1.11 but is still stuck with VC2013 for whatever reason. Likely instead both 2013 and 2015 will be dropped (due to requiring full C++14 constexpr support) in a future development branch. But this will not affect users on the stable 2.0 branch, and 2.2 will not be released for another ~ 18-36 months.

I have thought about semantic versioning but TBH it does not seem like a good fit for the project because we need relatively long lived stable branches (or at least that is how the software is currently developed and has been for a long time, one stable release branch that avoids breaking things plus an anything-goes master). I would be open to a change and have considered alternatives myself but nothing has come to me that seems like it would work better than current system in practice.

Closing since the timeline for dropping VC2013 support is, it seems to me, now clear: not now, not in 2.0, but almost certainly in 2.1 at some point. Likely, early in active 2.1 development the target compilers/versions will be identified and we'll go from there.

**Comment by noloader** [comment]
@randombit,

One thing to consider in the bigger security engineering picture... Companies like Apple and Microsoft have moved to the abandon-ware model, where the move on in in a year or two and stop supporting the previous Christmas' sale. I've got more unpatched Android phones, tablets, Apple iPhones, Tablets, Macs, Microsoft phones and Microsoft tablets than I have patched/up to date ones.

Folks like me depend on an up to date library and compatibility because the platform is not up to date. That is, if my app is built using the latest library, then I can remediate many of the residual threats from an abandoned platform and the infrastructure. For example, my iPads suffer Apple's GOTO bug in SecureTransport, while my app is up to date because of up to date libraries like Botan and OpenSSL.

I'm guessing the abandon-ware model model helps drive futures sales. Maybe not-so-surprising, while Microsoft and Apple abandon the platform, they make sure their programs like iTunes stay up to date and compatible so people can keep buying things. Its sucks to be a consumer at times.
