### ISSUE TITLE
Using PKCS#11 with TLS

### ISSUE THREAD

**Issue by securitykernel** [randombit/botan#730]
This is a follow-up of #725, where @mouse07410 asked about using PKCS#11 objects with TLS. Correct me if I'm wrong, but from my understanding it should already be possible to have a TLS server with the server's long-term key stored in a PKCS#11 device, now as the PK ops are tied to the `Private_Key` and `Public_Key` objects (which was introduced in #625). All you have to do is to create a PKCS11 key, e.g., a `PKCS11_RSA_PrivateKey`, and return it from `Credentials_Manager::private_key_for()`. `TLS_Server` will forward it to `PK_Signer`, which will select and sign with the PK signature op returned by `PKCS11_RSA_PrivateKey::create_signature_op()`.

If you want more control over the handshake, e.g., you want do the ECDH key exchange ops in a PKCS#11 device, there is currently no way to do it. We are currently thinking about a new interface, let it be named TLS Adapter for now, for doing these operations in hardware. We will have to do these operations in a non-PKCS#11 compliant HSM, but we want to make it generic enough that PKCS#11 devices can be supported easily.

We will come up with a proposal for this use case probably in the next few weeks.

*Update: Removed the chain validation part, of course it's already possible by overriding `Credentials_Manager::verify_certificate_chain()`.*

**Comment by randombit** [comment]
> All you have to do is to create a PKCS11 key, e.g., a PKCS11_RSA_PrivateKey, and return it from Credentials_Manager::private_key_for(). TLS_Server will forward it to PK_Signer

That is how it should work but in fact the server currently `dynamic_cast`s its key to a `RSA_PrivateKey` when processing the client key exchange msg, so it would reject a PKCS11 key. It should probably just check `algo_name` matches instead.

**Comment by cordney** [comment]
Thanks for the hint. I am currently implementing this with a `TPM_PrivateKey` type that uses our custom TSS for a TPM key. I will fix whatever is necessary.

**Comment by mouse07410** [comment]
1. Yes, it would be great to have the TLS server (and the client!) fixed, so they can accept a PKCS11 key.

2. Yes it would be great if ECDH would become supported.

Thanks!

**Comment by cordney** [comment]
Going forward with the `TPM_PrivateKey` class in our own library (outside of botan), I can not use this custom key type with a custom `PK_Ops::Signature` op, as `pk_ops.h` is now internal. That only allows having custom key types inside botan while preventing them to be handled outside botan, which I think is a valid use case. Do we need to make it public again or is there another solution?

**Comment by mouse07410** [comment]
Request For Clarification (RFC :).

Where are we now wrt. being able to use PKCS11 keys (on a hardware token) with/by TLS client (and maybe/hopefully server)?

Also:
> the server currently `dynamic_cast`s its key to a `RSA_PrivateKey` when processing the client key exchange msg, so it would reject a PKCS11 key

This doesn't sound good not only for PKCS11, but also for ECC keys. Or am I missing something here?

> It should probably just check `algo_name` matches instead.

I'd say - yes, for sure.

**Comment by randombit** [comment]
> This doesn't sound good not only for PKCS11, but also for ECC keys. 

That statement only applies for RSA ciphersuites.

**Comment by mouse07410** [comment]
OK, thanks. Any comments on the main question - how far are we from being able to use PKCS11 keys with TLS code?

**Comment by cordney** [comment]
A few PRs down the road fixing things in Botan i can now use my custom TPM RSA key type to sign a cert. Now working on connecting this with a TLS client cert. If that works out, I'll take on the PKCS11 part, but I can not commit on a specific timeline.

**Comment by mouse07410** [comment]
@cordney understand, and thank you for your work! Hope to hear the good news rather sooner than later! :-)

Let me know if (minor :) help is needed.

**Comment by reneme** [comment]
Since this issue is a bit dated already, I'd like to know what the state of affairs is right now.
Are there still major show stoppers to use PKCS#11 along with Botan's TLS implementation? For our use case I'd be particularly interested in using a smart card via PKCS#11 for RSA client auth via TLS.

**Comment by randombit** [comment]
I'm not sure that everything works here. But it sounds like from the report in #1663 the existing callbacks are sufficient, or at least it worked for them. Just override `Callbacks::tls_sign_message` and invoke your smartcard.

**Comment by securitykernel** [comment]
We successfully use a TPM 1.2 key for client TLS. Until now, we did not try with a PKCS#11 key. If others can try and report, that would be helpful.

**Comment by reneme** [comment]
Turns out: It works rather smoothly! The API to combine those components is actually quite neat.

Though, here comes the "but": we needed to work around [the signature algorithm selection in the PKCS#11 code](https://github.com/randombit/botan/blob/e07a6819d537e2a2a398a35420596b0f15c7de42/src/lib/prov/pkcs11/p11_mechanism.cpp#L185) by overriding `TLS::Callbacks::tls_sign_message()` like so:

```C++
std::vector<uint8_t>
tls_sign_message(const Botan::Private_Key &    key,
                 Botan::RandomNumberGenerator &rng,
                 const std::string &           emsa,
                 Botan::Signature_Format       format,
                 const std::vector<uint8_t> &  msg) override
{
    // work-around: figure out the correct EMSA padding name by re-using the
    //              EMSA selection code in `emsa.cpp : get_emsa()`
    Botan::EMSA *emsaObject = Botan::get_emsa(emsa);
    const auto   name       = emsaObject->name();
    delete emsaObject;

    // up-call the standard implementation with the adapted EMSA identifer
    return Botan::TLS::Callbacks::tls_sign_message(key, rng, name, format,
                                                   msg);
}
```

Apparently the TLS client requests the EMSA as 'EMSA_PKCS1(SHA-512)' but the [`std::map` in the PKCS#11 code](https://github.com/randombit/botan/blob/e07a6819d537e2a2a398a35420596b0f15c7de42/src/lib/prov/pkcs11/p11_mechanism.cpp#L74) does not recognize this scheme. In my understanding we just abused `Botan::get_emsa()` to "normalize" the string-identifier to something that the PKCS#11 implementation recognizes.

This works for now, but does not seem very elegant. It both forces me to unnecessarily override `tls_sign_message()` and perform a memory allocation just to "lookup" the "normalized" EMSA identifier. Is there a better way?

Obviously we could extend the `std::map<>` in `p11_mechanisms.cpp`, but I fear that the other `std::map<>`s in that file might suffer from similar issues. Furthermore it feels like duplicating a lot of implicit knowledge of these identifiers.

What would you suggest?

**Comment by randombit** [comment]
Glad everything works. You are right though, that does seem really messy. A few things that would probably help

- Change (in TLS) use of `EMSA_PKCS1` to `EMSA3` (this is coming from `TLS::padding_string_for_scheme`). `PKCS1` makes it clearer what is happening but for historical reasons the rest of the code (like PKCS11) uses `EMSA3` here. It is probably better to consistently use the "worse" (less descriptive) name rather than using two different names in different parts of the codebase. Unfortunately this will probably break existing code that is hardcoded to look for `EMSA_PKCS1` here. Downside of string arguments for this. :(
- Provide an alternate callback that receives `TLS::Signature_Scheme` enum (the default version of this would just convert the enum to a string then call the existing `tls_sign_message` so existing code continued to work), which can be handled in a more unambiguous way.
- Extend the PKCS11 map to handle name variants (it also doesn't understand eg PSS padding strings instead using "EMSA4"), which is probably good from a general usability perspective anyway.

**Comment by hrantzsch** [comment]
I opened a pull request that addresses the issue according to your third suggestion, i.e. extending the map to handle the name variants produced by `padding_string_for_scheme(Signature_Scheme)`.

This is a very easy fix, but in fact we would have preferred to go with the additional `tls_sign_message` overload, which gives us more type safety. Unfortunately we hit some blockers, which is why we will probably come back with another pull request tomorrow and ask for your advice.

**Comment by hrantzsch** [comment]
We spend some more time to investigate the variant of another `tls_sign_message` overload, but couldn't come up with a really consistent implementation. Most of all, we didn't find a good way to convert from the naming scheme used by the TLS client to the format the PKCS11 implementation understands, without using the `EMSA` helper object. (`get_emsa` has a lot of logic to figure out the `EMSA` subclass it wants to instantiate, but the appropriate name of the padding scheme is "hardcoded" in the subclasses' `name()` functions.)
We also tried to use the `Signature_Scheme` enum throughout the code instead of the string parameters, so we could do the scheme translation on a lower level. But this touches a lot of places and forces us to offer both variants everywhere in order not to break the API.

We did come up with a way that might better encapsulate the workaround suggested by @reneme though: instead of creating the `EMSA` instance in the TLS callbacks, we could provide the helper object to the [PKCS11 signature operation](https://github.com/randombit/botan/blob/master/src/lib/prov/pkcs11/p11_rsa.cpp#L205) like this:

```c++
class PKCS11_RSA_Signature_Operation final : public PK_Ops::Signature
    {
    public:

      PKCS11_RSA_Signature_Operation(const PKCS11_RSA_PrivateKey& key, const std::string& padding) :
          m_key(key),
          m_emsa(get_emsa(padding)),
          m_mechanism(MechanismWrapper::create_rsa_sign_mechanism(m_emsa->name())) {}
```

Of course, `PKCS11_RSA_Signature_Operation` still doesn't really have a need for `m_emsa` except for this conversion, as it will call to the smartcard module for this functionality.

In your opinion, which is the better option? Extending the `RSA_SignMechanisms`-map or the workaround with the `EMSA` object?

**Comment by jhaws1982** [comment]
I am interested in doing exactly this - using my PKCS11 device to manage my keys and certificates for TLS.  I'm trying to wrap my head around what all I need to handle (I'm new to the security/crypto space).

Based on my reading here it sounds like I just need my application class to override the tls_sign_message() callback along with the typical overrides?  If I have a function that signs the message with PKCS11 - then I just return the signature?  Is that all I have to do?  Would I need to setup a PKCS11_Certificate_Store if I wanted to store certs in my device?

Being new to this space I don't want to make a naive mistake that is compromising...

Thanks for the direction!

**Comment by hrantzsch** [comment]
I created a short script that illustrates how to load keys from a PKCS11 device. Maybe it helps: https://gist.github.com/hrantzsch/c2ed4d32af350b470e67fb07fb5fd7b1

**Comment by jhaws1982** [comment]
So I was able to import the private key from a file using this code.  Does this look viable?  The static_cast<> just didn't feel right...

```
    // Set the private key properties
    PKCS11_RNG rng(session);
    Botan::RSA_PrivateKey *pkey = static_cast<Botan::RSA_PrivateKey *>(
        Botan::PKCS8::load_key(kpath, rng));
    Botan::PKCS11::RSA_PrivateKeyImportProperties priv_import_props(
        pkey->get_n(), pkey->get_d());

    priv_import_props.set_pub_exponent(pkey->get_e());
    priv_import_props.set_prime_1(pkey->get_p());
    priv_import_props.set_prime_2(pkey->get_q());
    priv_import_props.set_coefficient(pkey->get_c());
    priv_import_props.set_exponent_1(pkey->get_d1());
    priv_import_props.set_exponent_2(pkey->get_d2());

    priv_import_props.set_label(label + "_key");
    priv_import_props.set_token(true);
    priv_import_props.set_private(true);
    priv_import_props.set_decrypt(true);
    priv_import_props.set_sign(true);

    // Import the key
    Botan::PKCS11::PKCS11_RSA_PrivateKey priv_key(session, priv_import_props);
```

Now I'm working to get private_key_for working but I believe I am running into issues with my key object going out of scope before whoever is calling private_key_for can use it.  When they finally do I get segfaults.

Here is my private_key_for:
```
     WtPKCS11 &pkcs11 = WtPKCS11::getInstance(); // this is a singleton class that initializes my slot/token
      if (pkcs11.getCertificateKey(context, m_key))
      {
       printf(" ** FOUND KEY FOR %s -- %p", context.c_str(), m_key.get());
      }
    return m_key.get();
```

Here is getCertificateKey():
```
bool WtPKCS11::getCertificateKey(const std::string &label,
                                 std::unique_ptr<Botan::PKCS11::PKCS11_RSA_PrivateKey> &key)
{
  std::lock_guard<std::mutex> lk(m_lock);
  bool valid = false;

  try
  {
    // Create the session
    Session session(*m_slot, false);  // read/write session, destroyed on exit
    session.login(UserType::User, m_pinUser);

    auto keys = findObject<PKCS11_RSA_PrivateKey>(label + "_key", session);
    if (keys.size() > 0)
    {
      key = std::make_unique<Botan::PKCS11::PKCS11_RSA_PrivateKey>(session, keys[0].handle());
      std::cout << " ** FOUND KEY: " << (void*)&keys[0] << " -- " << (void*)key.get() << std::endl;
      valid = true;
    }
  }
  catch (PKCS11_ReturnError &ex)
  {
    printf(" !! Botan Exception: %s", ex.what());
  }

  return valid;
}
```

Note that I keep track of my module and slot in my WtPKCS11 class.  Each time I call a function I open a new session, do my work, then return.  Is that typical for PKCS11 devices?  Or does your application just keep a session open all the time?

I feel like I am missing something obvious to someone who is experienced in security/crypto. Any help/guidance is appreciated!

**Comment by securitykernel** [comment]
@reneme No objections to closing here. We were ultimately able to offload ECDH to a HSM using the callbacks added in #1332.
