### ISSUE TITLE
The test suite doesn't work with a subset of the modules

### ISSUE THREAD

**Issue by BMBurstein** [randombit/botan#743]
I configured with --minimized-build --enable-modules=aes,gcm and the resulting botan-test.exe would not run (something about no PRNG). Is this expected behavior, or is the test suite supposed to only include things that are part of the build?

**Comment by neverhub** [comment]
It is expected behavior.
The test suite does only run tests for algorithms, which are part of the build.
However, the test suite requires a RNG for the test setup. This means you will have to either build with system_rng or hmac_drbg (with sha2_64) for the test suite to work.

`./configure.py --minimized-build --enable-modules=aes,gcm,hmac_drbg,sha2_64`
or
`./configure.py --minimized-build --enable-modules=aes,gcm,system_rng`

**Comment by randombit** [comment]
The fix is as @neverhub suggests. It is unfortunate that you don't get any useful warning that this totally reasonable build scenario is not going to have working tests, though.

It is the case that even the GCM tests require an RNG of some kind, because part of the tests involve doing random mutations to the data and ensuring we do not accept any variations.
