### ISSUE TITLE
VS2013::Multi-threaded DEBUG DLL problem

### ISSUE THREAD

**Issue by sebastiandev** [randombit/botan#75]
I found that when trying to link as /MDd, application crashes with error:
"memory access violation occurred at address 0x00298000, while attempting to  read inaccessible data"

I've built botan with --enable-debug option and see that the flag /MDd is added in the makefile, but for some reason applications crashes.

I can only run the app if linked with /MD. Thats weird and wrong, since I expect the library to be linked to with /MDd. 

Any ideas?

**Comment by webmaster128** [comment]
Jap, an idea: Botan is known to crash when the Microsoft debug standard library is used because in this case bounds-check is enabled for operator[] on a lot of STL types.

An example from the Botan code looks like this
```
void someMethod(std::vector<Byte> foo)
{
    auto beginningOfFoo = &foo[0];
}
```
`&` gives a pointer to the first element `foo[0]`. The code works nicely when bounds-checks are disabled, even if `foo` has zero elements.

Now bounds-checks ensure that `pos < length(foo)` in `foo[pos]`. But if `foo` is empty and `pos = 0`, we have `pos == length(foo)` and an assertion crashes the program.

In the C++ standard it is stated that `operator[]` don't do bounds-checks (in contrast to the [at()](http://www.cplusplus.com/reference/vector/vector/at/) function). MS decided to activate them anyway in their debug library.

The solution is to access the beginning (or end) of a vector using `foo.data()` instead of `&foo[0]`. This is [massive work](https://github.com/randombit/botan/pull/49/files?diff=unified) but we're going to tackle those problems after the release of 1.11.17.

Can you check in a debugger at which point the code crashes?

**Comment by webmaster128** [comment]
@sebastiandev Can you test it again using the current master?

**Comment by webmaster128** [comment]
@sebastiandev Can you test it again using the current release 1.11.18?

**Comment by sebastiandev** [comment]
hey! i will, but probably do it on wednesday. thanks!

**Comment by sebastiandev** [comment]
i couldnt say if its working or not because app hangs forever like mentioned on issue #67

**Comment by webmaster128** [comment]
Is this issue still valid in 1.11.20?

**Comment by sebastiandev** [comment]
i think you can close it :)
