### ISSUE TITLE
llvm fuzzer: possible undefined behavior?

### ISSUE THREAD

**Issue by neverhub** [randombit/botan#751]
The address sanitizer complains about the following issue in the asn1 decoder.

Jack, can you tell me if this is a real problem or a false positive? 

```
bin/llvm_fuzz_crl -max_len=140 -artifact_prefix=output/crl/llvm/outputs/ output/crl/llvm/queue corpus/crl 
INFO: Seed: 2747357045
INFO: Loaded 0 modules (0 guards): 
Loading corpus dir: output/crl/llvm/queue
Loading corpus dir: corpus/crl
#0	READ units: 1155
../../../src/lib/asn1/ber_dec.cpp:125:10: runtime error: load of value 268435328, which is not a valid value for type 'Botan::ASN1_Tag'
SUMMARY: AddressSanitizer: undefined-behavior ../../../src/lib/asn1/ber_dec.cpp:125:10 in 
MS: 0 ; base unit: bebebebebebebebebebebebebebebebebebebebe
0x30,0x80,0x30,0x80,0x2,0x19,0x80,0x30,0x30,0x30,0x30,0x0,0x0,0x0,0x0,0x0,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0x0,0x0,0x0,0x0,0x19,0x80,
0\x800\x80\x02\x19\x800000\x00\x00\x00\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x19\x80
artifact_prefix='output/crl/llvm/outputs/'; Test unit written to output/crl/llvm/outputs/crash-caef864993dd5fcb23573fb95230afa258239550
Base64: MIAwgAIZgDAwMDAAAAAAAP////////////////////////8AAAAAGYA=
```

**Comment by randombit** [comment]
This is a real problem I think. AIUI, assigning a value to an enum which is within the range of the enumeration size but not assigned as a value within the enum results in undefined behavior. Presumably that's to allow compilers to assume that all values are known in advance in order to allow better optimizations of code like `switch(enum_value)`.

This is kind of pervasive in the ASN.1 code as we store bitmasks in enum values in areas - this seems to be undefined behavior. We also at point load integer values and then cast them to enums while decoding - this also seems to be undefined and with attacker-controlled inputs (if that matters). I am not sure if there are actual implications with modern compilers as a result.

I have a general rewrite of ASN.1 planned for next year. I wrote the current version well over 10 years ago, and it is showing its limits. Certainly this would be removed part of that.

Possible short term patch for right now: replace all enum values in ASN.1 with u32bit? holding the flags. Then when an enum is needed, call a function which extracts the appropriate bits and then returns enum values directly, without any (data) conversion between the underlying data and the enum type.

**Comment by neverhub** [comment]
This could also be achieved with c++11 "strong enums", but this takes more effort. I think for a temporary solution your approach is sufficient.

**Comment by randombit** [comment]
I realized my interpretation of this error is wrong. Actually it is fine to have an `enum` take on a value outside of those specifically listed (consider for example the common use of enums as bit flags, where multiple values can be combined). It is actually that `ASN1_Tag` is sized to 16 bits (because 16 bits is sufficient to hold all named members) but in the BER decoder we are willing to read a tag that is up to 32 bits long. So all that is needed is to explicitly size the enum. I'll do that shortly.

**Comment by randombit** [comment]
Fixed
