### ISSUE TITLE
Using semantic versioning

### ISSUE THREAD

**Issue by cordney** [randombit/botan#766]
This is about using [semantic versioning](https://semver.org) for Botan. I actually assumed that we would start using semantic versioning with the release of 2.0 later this month and was surprised to find out that it is planned to keep the current, custom scheme with even and uneven minor numbers signalling stable and unstable branches, as discussed by @Bulat-Ziganshin and @randombit in #703.

I would really favor semantic versioning for Botan starting with 2.0.0. We have lots of experience with this scheme in our enterprise internal libraries and I have not seen a use case which semantic versioning was not able to solve. I have been on both sides for a few years now and I think it's a good compromise for both library developers and library users. Developers can still make breaking changes, by increasing the major version number, and library users are assured that as long as they stay on a major version number, they won't have to change their code and still get fixes by upgrading to a new patch release and new features by upgrading to a new minor version number.

**Comment by randombit** [comment]
I wrote out a very long reply outlining all the problems this would entail and in doing so, convinced myself everything is fine and we should use SemVer. 

To be concrete, the development workflow I'm thinking would become

When ready, master is branched to release-2
fiddle with the readmes and such slightly
release-2 HEAD is tagged as 2.0.0
The distribution tgz is created and distributed, beers are opened
We declare release-2 is a supported branch, until X

Linux distributions and others can take from the latest 2.x release without being concerned about API issues with existing code and knowing there will be patches until X. We increment the minor number on 2.x with abandon. This requires removing the minor number from the soname, which is a nice simplification anyway. The important thing in the soname is the ABI version, since we will need to continue to make ABI incompatible changes in 2.x, even when not making API incompatible changes.

[An aside on ABI issues: I was convinced to try for long term ABI compatibility in 1.10 by the Debian maintainers. But, maintaining ABI compat in a large C++ API is very taxing in scarce developer time and not something we can reliably support especially over the long haul (eg, adding a single virtual function anywhere changes a vtable size). And, it turns out, Debian doesn't even consume Botan releases directly, but instead just backports cherrypicked commits (this seems to be their standard procedure for handling security issues in all packages). And I think every other distro? has mechanism for rebuilding dependencies when required. Certainly Gentoo and Arch handle this fine. For those needing strict ABI compatibility, the FFI interface (intends to) offer exactly that, using an API that has minimal ABI complications.]

After creating the branch, all development work continues on master in a free-for-all manner. Any relevant changes are backported to any release-N branch which is still supported. Things eventually reach the point of saying, what is on master now is interesting and potentially of value to release for broader experimentation. So we create a development release branch

branch again to release-3
We declare that release-3 is a development snapshot, and it has only a short support lifetime (say 3-6 months, with the possibility of being extended later).

We later discover that an API we added is release-3 is incorrect in some way and we must break API. The 3.x branch is abandoned, and we move to release-4, also with a short release lifetime (no longer any even/odd associations). Then we perhaps realize, we are happy with 4.x API, and then extend the support lifetime (and update the readme and such accordingly), and distros and such start picking up 4.x at 4.5.0 or whatever. And so on.

The friction associated with making a new API incompatible release branch is probably a really good thing - it will cause us to carefully consider API incompatible changes before plunging in. At this point there is a substantial codebase built on what will be the 2.x API and it would be nice to minimize and fully understand API breakages before making them.

Maybe there is some better way to do ^ and I'm happy to take any & all suggestions. I'd just feel more comfortable having a fully sketched out plan for what the development workflow looks like before making a change.

**Comment by randombit** [comment]
It may be confusing to users if there is a situation where (say) both Botan 2.x and Botan 5.x are actively supported versions, but then 3.x and 4.x are not supported at all. That seemingly could happen, if releases go as I described in previous comment. To help minimize this confusion, we can at least clearly document the initial release dates and EOL dates for each major version in the docs and website.

**Comment by webmaster128** [comment]
> It may be confusing to users if there is a situation where (say) both Botan 2.x and Botan 5.x are actively supported versions, but then 3.x and 4.x are not supported at all.

I don't think this is an issue as you're targeting professional users who are used to exactly this scenario from everything with Long-term support (Ubuntu, Qt, Python). A good overview will cover that.

**Comment by Bulat-Ziganshin** [comment]
The answer that i planned to wrote before i've read this thread :)  Very close to your own vision.

Unexpected API/algorithm set changes may hurt in the same way as compiler support dropping. When you drop some API, user need to modify his program to support new API style. When you drop some algo like RC6, user has a choice between staying with old version (no security updates!) or add this support himself in some way. So i propose to release current code as 2.0 and continue to evolve is as 2.x, with an explicit guarantees of particular compiler/API/ABI/algorithms supported. You can add to 2.x new supported things, though, and even declare some of them as guaranteed supported starting from some 2.x version.

When at some moment you will decide that you need to drop something guaranteed supported in 2.x, start a beta version, probably as a 3.x branch. While in beta, you don't provide strict guarantees, but this means that beta branch may be used only for short-lived, very-well-supported, or non-serious projects. And this means that you may drop SemVer support in 3.x. Once you have decided, you start a 4.x branch on top of 3.xб with SemVer and expliciitly stated set of supported things. This support may be conditional, though, like "we will not drop RC6 support prior to Dec2016", or "we will support MSVC2013 at least 1.5 years after MSVC2015 release". But with such explicit gurantees projects can better plan their own future.

This means that stages with fast backward-incompatible progress (revolution) will be interspersed with stages of backward-compatible progress (evolution). If you have some revolutionary idea, you just need to delay it until beta stage. And vice versa, for some degree.

> After creating the branch, all development work continues on master in a free-for-all manner. Any relevant changes are backported to any release-N branch which is still supported. Things eventually reach the point of saying, what is on master now is interesting and potentially of value to release for broader experimentation. So we create a development release branch
> branch again to release-3
> We declare that release-3 is a development snapshot, and it has only a short support lifetime (say 3-6 months, with the possibility of being extended later).

A small comment. When in this "beta" stage, you still need some version numbers, so i think that it should use 3.x numbers. And 4.x for stable thingy. Idea of using even version numbers for stable versions and odd ones for betas isn't new.

Alternatively, you may use some other system, f.e. beta-2.999.x.y for beta, and 3.x for stable.

**Comment by cordney** [comment]
@randombit The plan you outlined is just fine. And I agree in that this process somehow forces us to get an API right in the first place, which is a good thing IMHO.

**Comment by randombit** [comment]
Closing, we're doing it

**Comment by Bulat-Ziganshin** [comment]
Great! For me in particular - i want to switch to Botan, but need to know what compilers/APIs will be supported and how long. I see you released 2.0, but docs doesn't include (yet?) any formal promises. Can you explicitly state which compilers/APIs will be supported in this branch, and how long? I know that sucg things are really hard to plan, but for Botan users it's even harder to plan their projects if Botan can suddenly drop their compilers support. In other words, if you call this version 2.0, you need to promise that it will support some compilers/APIs for a long time, otherwise it's better to call it just 1.11.35

If this branch will follow Semver, please also mention that explicitly.

I'm sorry if you just doing these edits now :)

**Comment by cordney** [comment]
The information you requested is already mentioned in the docs. Botan 2.x will be supported until 2020-12-31, that is 4 years from now on, as mentioned in [Support Information](https://botan.randombit.net/manual/support.html). Supported platforms and compiler versions are listed in [Supported Platforms](https://botan.randombit.net/manual/platforms.html). The fact the we are using semantic versioning now is mentioned in [Versioning](https://botan.randombit.net/manual/versions.html).
