### ISSUE TITLE
Usability of TLS::Callbacks::tls_inspect_handshake_msg()

### ISSUE THREAD

**Issue by cordney** [randombit/botan#782]
`TLS::Callbacks::tls_inspect_handshake_msg(const Botan::TLS::Handshake_Message& message)` was added recently to support inspecting handshake message from applications. However, it's currently unusable, as there is no way to cast `message` to one of the `Handshake_Message` message derived classes, e.g., `Server_Hello`. This is because `tls_messages.h` is still an internal header and not publically exported. Just a bug or intention?

**Comment by randombit** [comment]
On bug or intentional, hard to say? Part of the plan is that  `Handshake_Message` API could be extended to be more useful for applications (eg with a to_string method for easier debugging), also I did not want to commit to application developers on the TLS message type API until really forced into it. But at this point things are pretty stable API wise, at least for 2.x (very likely adding TLS 1.3 is going to shake things up quite a bit) so the tls_messages.h header should be exposed for applications that really do want to inspect the messages.

**Comment by cordney** [comment]
Ok, thanks. So I'll be preparing a PR exposing tls_messages.h as a public header.

**Comment by randombit** [comment]
OK to close?

**Comment by cordney** [comment]
Sure. I am used to GitLab where referenced issues are closed automatically, sorry.
