### ISSUE TITLE
OS X 10.5, PowerMac and "ERROR: Unknown or unidentifiable processor "powermacintosh""

### ISSUE THREAD

**Issue by noloader** [randombit/botan#799]
Testing on old PowerMac; its circa 2005 or 2006. It has a 2.0 GHz PowerPC cpu, OS X 10.5.8, and MacPorts with updated gear. I keep it around for big-endian testing. It still runs faster than Core2 Duos, ARM gadgets and even Celerons.

Running `configure.py` produces the following.

```
PowerMac:botan$ /opt/local/bin/python2.7 ./configure.py --cc=clang --cc-bin=/opt/local/bin/clang++-mp-3.4 
   INFO: ./configure.py invoked with options "--cc=clang --cc-bin=/opt/local/bin/clang++-mp-3.4"
   INFO: Platform: OS="Darwin" machine="Power Macintosh" proc="powerpc"
   INFO: Guessing target OS is darwin (use --os to set)
  ERROR: Unknown or unidentifiable processor "powermacintosh"
```

This may be of interest:

```
PowerMac:botan$ uname -a
Darwin PowerMac.local 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:57:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_PPC Power Macintosh
PowerMac:botan$ uname -m
Power Macintosh
```

My apologies if this is unsupported. I saw there was some inline ASM code in the entropy gatherer to read a PowerPC's timestamp registers, so I thought it was game on.

**Comment by noloader** [comment]
It looks like this can be worked around by adding `--os=darwin --cpu=ppc64`. However, it looks line a variant of [Issue 528](https://github.com/randombit/botan/issues/528) resurfaced:

```
$ make
...
/opt/local/bin/clang++-mp-3.4  -m64 -pthread -stdlib=libc++ -fPIC -fvisibility=hidden -std=c++11 -D_REENTRANT -fstack-protector -O3 -Wall -Wextra -Wpedantic -Wshadow -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wunreachable-code -Ibuild/include -c ./src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp -o build/obj/lib/entropy_darwin_secrandom.o
./src/lib/entropy/darwin_secrandom/darwin_secrandom.cpp:10:10: fatal error: 
      'Security/SecRandom.h' file not found
#include <Security/SecRandom.h>
         ^
1 error generated.
make: *** [build/obj/lib/entropy_darwin_secrandom.o] Error 1
```

**Comment by randombit** [comment]
OS X with PowerPC should work. For the CPU detection we are currently relying on Python's platform module. Looks like the problem is machine="Power Macintosh" is unknown, and configure doesn't try to fall back to processor="powerpc" - which is still wrong in this instance if this is a G5. I will fix it so configure at least makes it to powerpc. I will probably extend configure to sniff /proc/cpuinfo and uname when either is available (not before 2.0.0 release, but eventually...).

Thanks for the uname output, is there anything in here that allows distinguishing 32 vs 64 bit?

As to the include path, I'm not sure what to do on our side. Shouldn't your local compiler pick up the correct paths for system headers by default? You can just disable the secrandom module with --disable-modules=darwin_secrandom, it is not really necessary for OS X since we can read /dev/urandom just fine (unlike on iOS where this call is critical since there is AIUU no random device).

**Comment by noloader** [comment]
Thanks @randombit.

I performed a `git merge a0330350f7f43bddb4a41e2db87ed0b8e2c955b3` on Master, which picked up this commit. Then:

```
$ /opt/local/bin/python2.7 ./configure.py --cc=clang --cc-bin=/opt/local/bin/clang++-mp-3.4
   INFO: ./configure.py invoked with options "--cc=clang --cc-bin=/opt/local/bin/clang++-mp-3.4"
   INFO: Platform: OS="Darwin" machine="Power Macintosh" proc="powerpc"
   INFO: Guessing target OS is darwin (use --os to set)
  ERROR: [Errno 2] No such file or directory: '/proc/cpuinfo'
```

On a Modern Darwin system, like OS X 10.8 or 10.9, the place to look is (from an older Core2 Duo MacBook):

```
$ sysctl machdep.cpu.features 2>&1 | cut -f 2 -d ':'
 FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH
 DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 DTES64 MON DSCPL VMX SMX EST TM2
 SSSE3 CX16 TPR PDCM SSE4.1
```

However, on this older PowerMac G5 with OS X 10.5:

```
$ sysctl machdep.cpu.features 2>&1 | cut -f 2 -d ':'
 class is not implemented
```

I'm not really sure what to do with the older PowerMac.

-----

> As to the include path, I'm not sure what to do on our side. Shouldn't your local compiler pick up the correct paths for system headers by default?

I'm thinking its a little more than compiler paths. In this case, think its a lot like Windows 2000 and `CryptGenRandom` or Windows 8 and `BCryptGenRandom`, where earlier versions of Windows did not have it.

In this case, I think Xcode 3 lacks it, and Xcode 4 (and above) have it. I'll do some more digging later tonight or tomorrow.

**Comment by noloader** [comment]
@randombit,

I asked about [availability of `<Secure/SecRandom.h>`](http://stackoverflow.com/q/41489830) on Stack Overflow. According to Sulthan, its declared as:

```
__OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_2_0);
```

Maybe `configure.py` can check for OS X 10.7 or iOS 2.0, and include the `darwin_secrandom` module if the OS meets the minimum requirements.

**Comment by randombit** [comment]
Reopening since #805 did nothing about SecRandom.h header being missing on old OS X.

I am thinking about some options for better feature detection in 2.1, leaving this open to make sure this problem is addressed as part of that change, but not doing anything further here for 2.0. Also (from my brief searching) it seems Apple is no longer supporting even 10.9 for security patches anymore. Since Botan's general policy is to only support OSes supported by their upstream vendors, supporting even 10.9 isn't a particularly high concern. But in this case, handling it well should be mostly 'for free' given other planned work.

**Comment by randombit** [comment]
Closing. Even 10.7 is far out of Apple support now. Someone attempting to build on older versions will just have to disable features, which can be done cleanly now with `--disable-os-features` configure flag.
