### ISSUE TITLE
Cygwin 6.3 and "ERROR: global name 'self' is not defined"

### ISSUE THREAD

**Issue by noloader** [randombit/botan#821]
I'm working on a Cygwin 6.3 x86_64 machine hosted by Windows 8.1.

```
$ ./configure.py
   INFO: ./configure.py invoked with options ""
   INFO: Platform: OS="CYGWIN_NT-6.3" machine="x86_64" proc=""
   INFO: Guessing target OS is cygwin (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Guessing target processor is a x86_64/x86_64 (use --cpu to set)
   INFO: Target is gcc-cygwin-x86_64-x86_64
  ERROR: global name 'self' is not defined
```

And:

```
$ python --version
Python 2.7.12
```

It also shows up on Cygwin i686, which is probably not surprising:

```
$ ./configure.py
   INFO: ./configure.py invoked with options ""
   INFO: Platform: OS="CYGWIN_NT-6.3-WOW" machine="i686" proc=""
   INFO: Guessing target OS is cygwin (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Guessing target processor is a x86_32/i686 (use --cpu to set)
   INFO: Target is gcc-cygwin-x86_32-i686
  ERROR: global name 'self' is not defined
```

**Comment by randombit** [comment]
Hm, interesting one. Can you re-run with `--verbose` (should produce a backtrace for the exception)

**Comment by noloader** [comment]
@randombit,

```
  DEBUG: Matched 'x86_64' to processor '('x86_64', 'x86_64')'
   INFO: Guessing target processor is a x86_64/x86_64 (use --cpu to set)
   INFO: Target is gcc-cygwin-x86_64-x86_64
  DEBUG: Program sphinx-build not found
  DEBUG: Traceback (most recent call last):
  File "./configure.py", line 2395, in <module>
    main()
  File "./configure.py", line 2261, in main
    logging.warning('Shared libs not supported on %s, disabling shared lib support' % (self.infofile))
NameError: global name 'self' is not defined

  ERROR: global name 'self' is not defined
```

**Comment by randombit** [comment]
Thanks, fixed in master, will be merged to release branch before next release. Seems like a straightforward fix so I'm closing, reopen if c46692e fails to resolve the issue.

You can workaround by adding `--disable-shared` to the command line. There is no change in functionality from that flag for cygwin, in fact this error is happening while trying to format a log line to warn that shared libs are not supported (at least by us, at the moment) on Cygwin.

**Comment by noloader** [comment]
@randombit,

Fix confirmed, thanks.

**Comment by webmaster128** [comment]
pylint would have found this automatically: [E:2261,91: Undefined variable 'self' (undefined-variable)](https://gist.github.com/webmaster128/cd1e4900ad1deba65b104f2092b7b94b).

If you are willing to maintain a pylint compliment configure.py, I'd be happy to create an initial pylint setup including CI testing.

I have a lot of experience with the tool from [clcache](https://github.com/frerich/clcache) and I am sure it already saved me a lot of hours debugging errors in Python code.

**Comment by randombit** [comment]
I have never used pylint but if it can help us catch bugs in the configure script before users run into them that is great.

Currently cant install pylint due to some Arch dependency issue (looks like I tried upgrading right in the middle of the Python 3.5->3.6 transition, fun!) but will try it soon.

**Comment by randombit** [comment]
Sorry I missed at first that you were linking to a pylint report for configure.py and not just pylint documentation. Report looks good. As soon as I can run pylint locally I'll fix the current set of warnings.
