### ISSUE TITLE
Amalgamation build for C89 interface

### ISSUE THREAD

**Issue by reitzig** [randombit/botan#862]
For using (a custom, small build of) Botan in a Swift package, I want to use the C interface mentioned in the documentation. I have several questions.

 1. Is there any documentation of the C interface?
 2. Where does `make` create the C headers, in particular with `--amalgamation`?
 3. Do we get C source files or only C headers against the compilate?

**Comment by reitzig** [comment]
Related resp. follow-up question: when [building for iOS](https://botan.randombit.net/manual/building.html#for-ios-using-xcode), how do I create a universal library for the C89 interface?

**Comment by cordney** [comment]
Regarding 1), the [handbook page](https://botan.randombit.net/manual/ffi.html) is currently incomplete. We track this issue in https://github.com/randombit/botan/issues/838 and I hope I'm finished with it by the end of the week.

**Comment by randombit** [comment]
The C API is entirely contained in the header botan/ffi.h (`src/lib/ffi/ffi.h` in git). There are some comments on usage in that file that would be worth reading. There is no preprocessing step that affects this header. So you would take both the amalgamation files to include in your build (`botan_all*`, these must be compiled by a C++ compiler, there is no translation step to C), and also copy `src/lib/ffi/ffi.h` as your C header.

Re iOS with FFI, there is a snag. The FFI module has a hard dependency on having System_RNG and currently iOS doesn't support that due to lacking `/dev/urandom`. So it is actually not possible currently to build a libbotan for iOS that contains ffi module. Right now if you run `./configure.py --os=ios --minimized --enable-module=ffi` the output will have a quiet `INFO: Skipping, dependency failure - ffi`.

Probably this should be fixed on both sides: FFI can remove the hard dependency and just fail at runtime if application requests system rng and it is not available. I will fix this in FFI shortly. And System_RNG for iOS should be added using SecRandomCopyBytes, since that is AIUI the correct way to access the system PRNG on iOS. I don't use or test on iOS so someone else would have to do that.

(Also configure.py should error out if an explicitly requested module could not be loaded.)

**Comment by randombit** [comment]
Fixing FFI turns out to be a bit more complicated than I thought, because initializing a public key operation in Botan requires an RNG reference, but this change to Botan's API came after the FFI API was created, so no RNG is passed by the callers. The FFI code just always uses the system RNG when creating the object.

To fix this seems to require adding new versions of  all `botan_pk_op_*_create` functions (`_create2`) taking also a RNG reference. Then the `_create` calls (without an RNG arg) would fail at runtime on systems without a RNG, and `_create2` could be used on systems with or without a system RNG.

**Comment by reitzig** [comment]
@randombit Thanks, sounds good so far!

Should this ticket be split? It seems to touch multiple somewhat unrelate issues.

**Comment by randombit** [comment]
I believe this can be closed now. Since 2.3.0 `System_RNG` class has been available on iOS through use of the `arc4random` API. So FFI should just work. @reitzig feel free to open up issues if you are seeing any problems with this in 2.3 or 2.4
