### ISSUE TITLE
Default padding for RSA signatures in X.509 certs

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#871]
Can we change the default padding mechanism for RSA signatures to EMSA4/PSS ?

As you can see [here](https://github.com/randombit/botan/blob/master/src/lib/x509/x509_ca.cpp#L240) currently EMSA3/PKCS#1 v1.5 is used.

PSS should be used for new applications.

**Comment by randombit** [comment]
TBH I'm not sure that RSS-PSS certs even work in Botan right now, so at the least some testing would have to happen before changing that.

Also I'm not sure how many other implementations support PSS certs, so changing the default might make certs generated by Botan unreadable by other implementations; but we could certainly make it possible for the application to select generating PSS certs (once it's been tested) instead of hardcoding PKCSv1.5

**Comment by neusdan** [comment]
Yeah, doesn't seem to work right now. Did a quick test and hardcoded it to EMSA4/PSS, but failed because  the OID is missing in oids.cpp.

**Comment by randombit** [comment]
There is more to it than that, one must extract the salt and MGF parameters from the AlgorithmIdentifier, so some special PSS codepaths must be added for signing and verifying X509 objects. The most recent spec seems to be RFC 4055 https://tools.ietf.org/html/rfc4055 updated by RFC 5756 https://tools.ietf.org/html/rfc5756

If RSA-PSS is going to be supported on certificates, it should also be supported by CRLs and OCSP. I think most of the codepaths for all 3 are already shared, but if not it could be taken as a sign to refactor the code so that adding another signature scheme for certificates in the future (like XMSS) is as easy as possible.

Seems Firefox does not support RSA-PSS (https://bugzilla.mozilla.org/show_bug.cgi?id=1088140) but based on comments in that bug Chrome and IE do.

**Comment by randombit** [comment]
RSA-PSS works!

I don't think we want to change the default yet. Maybe in a couple of years...
