### ISSUE TITLE
AppVeyor is green while test fails; AppVeyor link target incorrect

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#88]
The AppVeyor build badge on the Github README is green while the build fails.

Build status (from [build 1.0.5](https://ci.appveyor.com/project/randombit/botan/build/1.0.5))

```
ECDH 3 tests all ok
PK keygen 34 tests all ok
X509 all ok
I/O error: DataSource: Failure opening file 
TLS 3 tests all ok
Tests 1 FAILs
Command exited with code 1
```

Image (green by the time of build 1.0.5):

![AppVeyor badge](https://ci.appveyor.com/api/projects/status/5t1osr48aq000yri?svg=true)

    https://ci.appveyor.com/api/projects/status/5t1osr48aq000yri?svg=true

Is the secure project code `5t1osr48aq000yri` configured correctly?

## Link target

While `https://ci.appveyor.com/project/randombit/botan/` points to the latest project build, e.g. some wild broken PR, the following link represents the current project status and should be used as the badge link target: `https://ci.appveyor.com/project/randombit/botan/branch/net.randombit.botan`

**Comment by cdesjardins** [comment]
This looks great, just what we need, but I can't help to notice that the windows build just does 

    --via-amalgamation --cpu=x86_32 --cc=msvc --cc-abi-flags="/bigobj"

but the travis build does two runs, one with no flags, and one with:

    --via-amalgamation --disable-shared

I think it is basically a requirement at this point to run amalgamation builds as static otherwise this issue can/will occur: https://github.com/randombit/botan/issues/52

I think it would be best to do what the travis build does, and have two configurations (one shared, and one static amalgamation), but if it takes too long, then maybe consider just doing static amalgamation. Of course I only suggest static amalgamation because it is what I use for my development, and it causes me frequent issues, but I think testing shared amalgamation is basically pointless.

**Comment by webmaster128** [comment]
Thanks @cdesjardins for your valuable insight. I think it would be much more noticed and valued as a separate issue since it is going to disappear when this trivial issue posted by me is resolved.

**Comment by webmaster128** [comment]
Badge looks good now, thanks. Could you change the link target to:

    https://ci.appveyor.com/project/randombit/botan/branch/net.randombit.botan

to avoid visitors seeing some irrelevant PR build results?

**Comment by randombit** [comment]
Link updated, thanks!
