### ISSUE TITLE
OS::run_cpu_instruction_probe does not compile on MSVC

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#920]
I tried to fix #914 and changed the `BOTAN_TARGET_COMPILER_IS_MSVC` in `os_utils.cpp` to `BOTAN_BUILD_COMPILER_IS_MSVC`. 

Two compiler errors emitted here:

C2712: 
> __cannot use __try in functions that require object unwinding

C2713:
> only one form of exception handling permitted per function

**Comment by randombit** [comment]
Blerg. I thought the code was already tested but due to the macro typo it was not.

Currently `run_cpu_instruction_probe` is defined to catch any C++ exceptions as well as illegal instruction execution coming from the probe fn. Given this Windows SEH restriction I think the best resolution is to require the probe function not throw, and remove the `try`/`catch(...)` blocks. Really there is no practical reason for such a function to throw, this try/catch was just for completeness, and if we cannot implement it on all platforms better to just forbid it entirely.

There is a test in `test_os_utils.cpp` for a throwing probe function that will have to be removed.

**Comment by randombit** [comment]
Fixed now
