### ISSUE TITLE
Errors when running tests

### ISSUE THREAD

**Issue by ruipacheco** [randombit/botan#922]
I've downloaded Botan 2.0.1 and configured with the following parameters: 

`python configure.py --minimized-build --enable-modules=zlib,md5,sha1,tls --single-amalgamation-file`

Upon running `./botan-test` a number of tests failed with the following message: `'Test error No usable RNG in build, and this test requires an RNG'`

At the end of the test suit I found this message:

```
RSA/EMSA_PKCS1(SHA-256) verify invalid signature ran 141 tests in 12.81 msec all ok
tls ran 1 tests 1 FAILED
Failure 1: Test error No usable RNG in build, and this test requires an RNG
alert parsing ran 9 tests in 0.08 msec all ok
cert_status parsing ran 8 tests in 0.13 msec all ok
cert_verify parsing ran 8 tests in 0.24 msec all ok
client_hello parsing ran 18 tests in 0.21 msec all ok
hello_request parsing ran 2 tests in 0.02 msec all ok
hello_verify parsing ran 5 tests in 0.04 msec all ok
hello_verify_request construction ran 1 tests all ok
new_session_ticket parsing ran 5 tests in 0.04 msec all ok
server_hello parsing ran 12 tests in 0.11 msec all ok
tls_policy ran 1 tests 1 FAILED
Failure 1: Test error No usable RNG in build, and this test requires an RNG
Date parsing ran 71 tests in 0.13 msec all ok
calendar_point::to_string ran 1 tests all ok
X509v3 Name Constraints: Invalid_DN_Name_Constraint.crt ran 1 tests all ok
X509v3 Name Constraints: Invalid_Email_Name_Constraint.crt ran 1 tests all ok
X509v3 Name Constraints: Invalid_IP_Name_Constraint.crt ran 1 tests all ok
X509v3 Name Constraints: Valid_DNS_Name_Constraint.crt ran 1 tests all ok
X509v3 Name Constraints: Valid_DN_Name_Constraint.crt ran 1 tests all ok
X509v3 Name Constraints: Valid_IP_Name_Constraint.crt ran 1 tests all ok
NIST path validation ran 71 tests in 802.10 msec all ok
X509test path validation ran 37 tests in 125.18 msec all ok
x509_unit ran 1 tests 1 FAILED
Failure 1: Test error No usable RNG in build, and this test requires an RNG
Tests complete ran 9977 tests in 4.04 sec 2269 tests failed
Error: Test error Test suite failure
```

TLS is the main reason why I'm using Botan. Can anyone provide information on this?

I'm doing this on the latest OSX.

**Comment by webmaster128** [comment]
Confirming this error on latest master using a slightly simpler configuration: `python configure.py --minimized-build --enable-modules=zlib,md5,sha1,tls`

**Comment by ruipacheco** [comment]
Just so I can plan, how long do you think it will take for this to be fixed?

**Comment by webmaster128** [comment]
You can get this running by manually adding the modules that are required by the tests:

> python configure.py --minimized-build --enable-modules=zlib,md5,sha1,tls,**system_rng,emsa1,sha2_64**

**Comment by ruipacheco** [comment]
So the code works, the tests just don't take into account the fact that some modules can be removed?

**Comment by webmaster128** [comment]
There is the general goal that this should work. But the module system is very complex and especially in cases where the tests do require modules that the configured build does not require, this is just not always perfect.

Feel free to make the tests work without the additional modules, e.g. disable SHA-512 tests when sha2_64 is not available and submit a pull request.

Regarding system_rng: I don't know how the dependencies must be set up here because system_rng is not available on all operating systems and I don't know if we can implement a *either module A or module B is present* rule in the current Botan dependency system. I guess your original build with TLS and without any RNG cannot work anyway.

**Comment by ruipacheco** [comment]
I understand. Thanks!

**Comment by cordney** [comment]
Thanks for the report. Actually, emsa1 is part of the build, it's sha2 which is missing. We use SHA-256 in the TLS tests when creating certificates. Disabling the test code that uses SHA-256 there would largely disable TLS tests.

Regarding the missing RNG, I think we should probably finally add a built-in RNG to the test suite that works on all platforms and not depend on any RNG being part of the library build. Configuring the library without any RNG seems to be a valid use case. RNG handling in the test suite was changed many times, 2.0.1 behaviour is even to error out early if no RNG is part of the library build. Only after 2.0.1 all tests are executed and only the individual tests that try to access an RNG would fail.

@ruipacheco: Just curious, do you want to use TLS with your own RNG? Because you have to provide one when you instantiate `TLS_Server` or `TLS_Client`.

**Comment by ruipacheco** [comment]
I didn't know I needed one, I thought Botan came with all batteries included. Some quick googling led me to [this](https://stackoverflow.com/questions/922358/consistent-pseudo-random-numbers-across-platforms) although my research is very much on the early phase right now.

**Comment by randombit** [comment]
It comes with all the batteries, but you can choose which ones you want included at build time. For example, it is possible to build a version of Botan that just included `RDRAND_RNG`, or just `PKCS11_RNG`, or no built in RNG types at all for the (probably quite rare) application that wants to supply their own and does not want any of the builtin versions. `--minimized-build` really means minimized, with the expectation that the specific things the target application needs will be enabled.

A fallback RNG for the tests would be a good idea. But, also this configuration (minimized build without an RNG type) is only useful in very specific scenarios - most apps are going to want `system_rng` and/or `auto_rng`. So some build-time warning and/or better guidance in the docs would be helpful.

**Comment by ruipacheco** [comment]
I think better documentation would be the answer.

**Comment by ruipacheco** [comment]
`python configure.py --minimized-build --enable-modules=md5,sha1,system_rng,sha2_64,tls --single-amalgamation-file` fixes my problem. I guess I can close the ticket, or do you want to keep it around because of the points you made?

**Comment by ruipacheco** [comment]
Closing ticket.
