### ISSUE TITLE
CTR-BE should allow seeking()

### ISSUE THREAD

**Issue by reneme** [randombit/botan#999]
We are planning to use Botan to encrypt large files before uploading them into cloud storage. Since we need to deal with flaky networks, a possibility for resuming half-way through is desired.

Hence, we would like to use `CTR-BE(AES-256)` for its `StreamCipher` behaviour. Unfortunately, the `CTR_BE` implementation does not allow to use `::seek()`. It just throws a `Not_Implemented` exception.

Are there plans to implement `CTR_BE::seek()` or is there an inherent problem that prevents an implementation?

**Comment by randombit** [comment]
No inherit problem, just hasn't been implemented (same goes for `Salsa20::seek`).

Supporting seeking will require a few changes to `CTR_BE`. Currently the class maintains two buffers, `m_counter` and `m_pad` the first keeps track of the current counter, and is encrypted by the underlying block cipher to produce `m_pad` which is XORed with the plaintext. The counter is initialized using the IV, though normally its actually 2-8 blocks wide and stores (IV+0,IV+1,IV+2,IV+3,...), and the pad is correspondingly also several blocks wide. This allows parallel or bitsliced implementations of the block cipher. (See `CTR_BE::increment_counter`)

This arrangement doesn't work well with `seek` because at the point `seek` is called, `CTR_BE` does not know how many times it has incremented the counter or where it is within the cipher stream, all it knows is the current value of the counter (which is derived from the original IV + # of bytes processed).

Fix is probably to save the original IV in a new member variable. Then if/when `seek` is called, recompute `m_counter` using the original IV plus the seek offset, then encrypt it to produce the new `m_pad` and set `m_pad_pos` to the desired byte within that block.

Thanks for pointing out this problem, would be happy to take a patch and might fix it myself eventually but I have other things I must do right now.

**Comment by reneme** [comment]
Pull request GH #1000 is ready from my point of view.

**Comment by randombit** [comment]
With #1000 merged, closing. Thanks for the contribution
